### ISSUE TITLE
[Dialog]1.16.x 版本 Mask demo 样式不对

### ISSUE THREAD

**Issue by mark-ck** [alibaba-fusion/next#1008]
### Component 
Dialog

### Reproduction link 
[https://fusion.design/design/utility/mask](https://fusion.design/design/utility/mask)

### Steps to reproduce
1.16.x 版本 Mask demo 样式不对

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/N25irJQJlQUM.png)

**Comment by youluna** [comment]
dialog相关 关注https://github.com/alibaba-fusion/next/issues/1016
