### ISSUE TITLE
[Pagination]异步操作里使用event引起warning

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#1009]
### Component 
Pagination

### Steps to reproduce
react 16.9 warning
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/bIZugs2EZ39L.png)

可能是setState这里
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/b0H2BuMXy46I.png)

**Comment by myronliu347** [comment]
fixed
