### ISSUE TITLE
[NumberPicker]NumberPicker 如果添加了 hasClear 会导致样式错位

### ISSUE THREAD

**Issue by huarse** [alibaba-fusion/next#1011]
### Component 
NumberPicker

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/e32f37d2](https://riddle.alibaba-inc.com/riddles/e32f37d2)

### Steps to reproduce
NumberPicker 继承了 Input ，会将 hasClear 传递到 Input 上，导致渲染的时候有一个 x ，会将 上下箭头挤下去

**Comment by bindoon** [comment]
NumberPicker 没设计 clear 按钮，我直接去掉这个属性？

**Comment by huarse** [comment]
> NumberPicker 没设计 clear 按钮，我直接去掉这个属性？

我觉得应该去掉
