### ISSUE TITLE
[All]更新生命周期方法

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#1012]
### Component 
All
#### Question
- componentWillMount, componentWillReceiveProps, componentWillUpdate will be deleted in react@17.0
- you can also see warnings in console when using 16.9
#### Solution
using react-lifecycles-compat
参考Tag
https://github.com/alibaba-fusion/next/blob/master/src/tag/selectable.jsx

https://github.com/alibaba-fusion/next/blob/24fe9ac3131bc8c03046758b0d62d75b9c51009e/src/tag/selectable.jsx#L4
https://github.com/alibaba-fusion/next/blob/24fe9ac3131bc8c03046758b0d62d75b9c51009e/src/tag/selectable.jsx#L55-L63
https://github.com/alibaba-fusion/next/blob/24fe9ac3131bc8c03046758b0d62d75b9c51009e/src/tag/selectable.jsx#L111

**Comment by monkindey** [comment]
hi，这个有计划了么？升级 React 16.9 就有这些 `warning`

![image](https://user-images.githubusercontent.com/6913898/63142903-69e9e980-c01e-11e9-8b33-b26169164c74.png)

**Comment by youluna** [comment]
@monkindey 可以先通过`npx react-codemod rename-unsafe-lifecycles` 自动替换生命周期名称解决。

升级可能是个较长过程，我们会从简单组件到复杂组件升级代码，另外由于组件库需要考虑React 16.0-16.2的支持，因此无法从组件层面上直接更换生命周期名称。

**Comment by youluna** [comment]
10.31 需要完成的简单组件，完成后直接评论到issue
@lianmin 
Loading
Collapse
Tag
Progress

@youluna 
Badge
Animate
ConfigProvider
Icon
Drawer
Shell

@xuhong 
Switch
Range

@mark-ck 
Rating
Typography
Timeline
Affix

@myronliu347 
Button
BreadCrumb
Message
Notification
TimePicker

@bindoon 
Input
Grid
Search
Number-picker

**Comment by youluna** [comment]
计划
- [ ] Badge
- [ ] Animate
- [ ] ConfigProvider
- [ ] Icon
- [ ] Drawer
- [ ] Shell

**Comment by myronliu347** [comment]
* [X] Button 无需改动
* [ ] BreadCrumb
* [ ] Message
* [X] Notification 无需改动
* [ ] TimePicker

**Comment by bindoon** [comment]
- [x] Grid 无须改动

**Comment by lianmin** [comment]
- [ ] Loading ( 无需改动 )
- [ ] Collapse  ( 无需改动 )
- [ ] Tag ( 无需改动 )
- [ ] Progress  ( 无需改动 )
- [ ] Dialog ( 无需改动 )

**Comment by xuhong** [comment]
[ ] Range https://github.com/alibaba-fusion/next/pull/1272
[ ] Switch https://github.com/alibaba-fusion/next/pull/1251

**Comment by mark-ck** [comment]
- [ ] Rating https://github.com/alibaba-fusion/next/pull/1277
- [ ] Affix https://github.com/alibaba-fusion/next/pull/1274
- [ ] Timeline https://github.com/alibaba-fusion/next/pull/1276
- [ x] Typography 无须改动

**Comment by youluna** [comment]
Cascader
CascaderSelect
TreeSelect
Tree

**Comment by youluna** [comment]
1.20.0 done
