### ISSUE TITLE
[Overlay]Content Height not full size

### ISSUE THREAD

**Issue by jdkahn** [alibaba-fusion/next#1016]
### Component 
Overlay

### Reproduction link 
[https://fusion.alibaba-inc.com/25727/design/utility/mask?type=theme&themeid=145](https://fusion.alibaba-inc.com/25727/design/utility/mask?type=theme&themeid=145)

### Steps to reproduce
Overlay does not show full size and has no mask
- add `height: 100%` to overlay-wrapper and it works fine

![Screen Shot 2019-08-15 at 11 47 25 AM](https://user-images.githubusercontent.com/12548603/63071595-7bfe5600-bf52-11e9-83b5-af83d2c3a545.png)

**Comment by youluna** [comment]
we can't simply add `height: 100%` to overlay-wrapper, or there will be a invisible mask all the time. Try the demo, you can't click other buttons when any message is on
https://codepen.io/aboutblank/pen/MWgypOp?editors=0110
