### ISSUE TITLE
🌈 Fusion 团队招人啦，前端 (web/node) 同学看过来

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#1020]
## 中后台系统的未来在哪里？
- 2015年，大部分中后台系统项目还在jQuery时代，大家都说要用组件化来解决效率问题，antd 率先扛起大旗，用react完成了中后台组件体系的建设。
- 2016年，那个时候设计前端之间的关系还是“亲密”，经常设计师端一把小凳子做在前端身边，一坐就是一下午，聊着像素之间的微妙关系。Fusion的出现打破了这种关系，把组件的UI定制能力搬上了平台，让前端从组件UI重构中解放出来了。同时sketch端工具FusionCool逐渐的成为了设计的好帮手，页面拖拖拽拽从未如此轻松。
- 2017年，感受到组件带来的便利，大家都开始完整业务组件，Fusion团队产出Fusion Market组件市场平台上线一年就沉淀了2000+来自集团各BU的业务组件。看着仓库塞得满满的组件，感觉特别充实！
- 2018年，Fusion 已经成为阿里集团大多BU的官方组件，累计覆盖30+BU，大大小小部门200+。集团覆盖度挺高的，但是感觉大家的活依然不少。仔细看看，发现从组件变成页面前端依然要写很多代码，设计师画稿子依然要慢慢拼凑。面对业务的不断迭代，业务组件扩展了一个又一个api口子，感觉日子快过不下去了。
业务组件那一套的玩法越来越多显得无力。我们尝试突破页面布局层面的理论，让设计和前端更少的关注布局细节，把精力更多的放在自己的逻辑层面，我们引入了区块模板，在两个业务中去试点，效果明显。设计师可以基于现成稿子上面修修改改，开发者可以直接下载现成的代码片段添加自己的业务逻辑。
- 2019年，不知道什么时候区块突然成了热门的词，大家都在玩。区块到底能带来多少能力的提升，应该看区块在某一个业务线复用的程度。飞猪作为Fusion第一批落的用户，建立了自己的物料体系，似乎在这个领域已经玩转的不错了。那这种能力能够复制到其他业务吗？能让其他业务线尽量少的花时间在建立上面，而专注于使用吗？物料通用了可能什么业务线都差一点能力，过于业务的又不具备流通性。能否基于一个通用的蓝本快速修改呢。今年我们想做两件事情，1. 实现一套相对通用的中后台领域模板，并产出ProCode和LowCode的两套体系，去分别看他们的流通程度。2. 尝试一条彻底提效的新方案，切小二后台这一条领域，是否可以先实现在新零售范围内的开箱即用方案尝试全链路的解决问题。
- 再往后：Fusion 已经在设计前端协同这条路上的探索已经到了一个相对成熟的阶段了，但是前后端协作的提效才刚刚开始。未来能解前后端协同提效的问题，也可能是工程体系的串联，也有可能是低代码编辑器的普及。表现形式有多种，但是不变的是通用业务能力的抽象和复用。Fusion 已经承载了集团的物料中心，后面我们需要的是让物料能够真正的被利用和流通起来。可能两年后在物料之上可以长出小二后台商业能力、商家后台商业能力...，我坚信不远了

我们期待你的加入，一起造梦！！

#### 联系方式：
游鹿
youlu.zgy@alibaba-inc.com

我们部门的几个开源作品：
- Fusion Design : 一个中后台解决方案
  - 主站 https://fusion.design 
  - github https://github.com/alibaba-fusion/next 
- beidou: 一个 react SSR 框架
  - github: https://github.com/alibaba/beidou
- bizCharts: 一个 react 的图表组件库
  - github：https://github.com/alibaba/bizcharts 

### 团队介绍
阿里巴巴全面启动集团中台战略，构建符合DT时代的更创新灵活的“大中台、小前台”组织机制和业务机制。 业务平台事业部，是搭建阿里电商大中台的产品技术基石，坐拥交易、商品、会员、店铺、推荐、营销、数据、汇金等多个核心业务平台，在阿里电商体系形成真正的大闭环进程中承担着不可或缺的核心地位，力争搭建起一个世界级的电商SAAS平台。业务平台前端团队，负责核心业务平台的UI域开发，提供端到端的电商中台解决方案，降低成本提高效率，支撑阿里所有业务快速构建UI域，为亿万消费者提供优质的产品体验。

### 岗位描述
业务架构挑战：我们以平台方式支撑阿里生态各业务发展，不仅仅是淘宝天猫，还包括飞猪，菜鸟，阿里云，钉钉，数字娱乐，盒马，1688，icbu，lazada等业务。在这里你不是做纯业务研发，更多的是利用你对业务的理解和多年的专业经验，打造出一个支撑多业务场景的端侧中台。

线下新零售业务的挑战： 除了线上零售，我们还面临包括盒马，饿了么等线下新零售业务的挑战， 将会面对多种设备的端侧适配，稳定性等问题，以及有别于传统网站的体验优化的各种挑战。

国际化开发的挑战： 我们目前支撑aliexpress，lazada，icbu等国际化业务的发展，未来将会通过平台能力，帮助更多业务出海。这里你将面临多语言站点开发，跨区域部署，全球性优化等挑战。在这里你也有机会参与制定阿里国际化技术标准，打造开箱即用的国际化解决方案。

全行业的业务挑战：业务平台不直接归属任何业务，但我们以中台SaaS服务的方式支持了阿里所有的业务，因此做为业务中台的研发，你必须拥有全中国最领先的前瞻性和最广阔的业务视野、技术视野。

### 工作地点
杭州、深圳

### 在招职位
阿里集团 - 资深前端、 Nodejs 开发工程师

### 工作年限
二年以上

### 岗位职责
关注用户体验，不断改进服务的易用性；
持续的性能优化，实现极致的Web加载、执行和渲染优化；
参与前端框架建设，并服务多个BU；
改进协作流程，创建技术标准和规范；

### 岗位要求
大学本科学历，2年以上开发经验，能熟练使用常见类库或框架，编写高质量的前端代码；
熟练掌握React、Redux及相关框架和技术，有单页面应用开发经验；
精通ES6，gulp，webpack等规范和技术；
熟悉NodeJS，有NodeJS开发经验，熟悉Express\koa等框架；
善于 Web 性能优化与前端效果的实现；
良好的团队合作精神和积极主动的沟通意识，具有很强的学习能力和对新技术的追求精神，乐于分享；
有大型网站开发经验者优先；
良好的中英文读写能力，英语口语流利者优先。

### 其他注意事项
大家提交简历的时候期望能够在邮件内用300字以内描述下你的在业务上解决的重要问题、印象最重要的事情！

**Comment by bindoon** [comment]
厉害了，大佬求推荐呀！

**Comment by imsobear** [comment]
简历已投，期待~~

**Comment by chenbin92** [comment]
简历已投，期待~~

**Comment by shaojun427** [comment]
上面几位大佬还要投简历的吗。

**Comment by huarse** [comment]
> 厉害了，大佬求推荐呀！

来我们团队吧

**Comment by imsobear** [comment]
搭车招人，楼主优先~~飞冰团队的“寻人启事” https://github.com/alibaba/ice/issues/2738

**Comment by maquannene** [comment]
简历已投，期待

**Comment by ruanima** [comment]
简历已投，期待（逃

**Comment by zowiegong** [comment]
Mark

养肥了再投

**Comment by Yancy1028** [comment]
TreeSelect 中如果使用了treeloadData 后，设置默认值后无法显示已经选中项的名字，这个没有考虑过的么。
