### ISSUE TITLE
[Field]Field的BUG

### ISSUE THREAD

**Issue by sd-yang** [alibaba-fusion/next#1023]
### Component 
Field

### Steps to reproduce
rules中required为false时，还是会进行验证？？？

**Comment by youluna** [comment]
不想进行验证可以删掉required这个参数  

@bindoon 评估下required为false时不进行验证有什么风险么

**Comment by youluna** [comment]
1.18中改掉，参考 https://github.com/alibaba-fusion/next/issues/1102
