### ISSUE TITLE
Icon size 排序优化

### ISSUE THREAD

**Issue by yujiangshui** [alibaba-fusion/next#1024]
### Reproduction link 
[https://fusion.design/62210/design/component/tag?type=theme&themeid=5286](https://fusion.design/62210/design/component/tag?type=theme&themeid=5286)

### Steps to reproduce
打开 Tab 组件配置面板，可以看到这里的排序是按照字母排序的，实际上 xxl 应该比 l 更上面。

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/lFZnflM1dJOx.png)

**Comment by nianxiongdi** [comment]
已解决，按照icon的大小进行排序
![image](https://user-images.githubusercontent.com/41629087/63254298-14c00900-c2a6-11e9-8dff-d7d97fb0467f.png)

**Comment by youluna** [comment]
fixed
