### ISSUE TITLE
[MenuButton]should recompute position while children length changed

### ISSUE THREAD

**Issue by bindoon** [alibaba-fusion/next#1025]
### Component 
MenuButton

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/9dd6034b](https://riddle.alibaba-inc.com/riddles/9dd6034b)

### Steps to reproduce
1. menu-button at the bottom of page
2. click button and get menus by ajax

![image](https://user-images.githubusercontent.com/5189853/63236895-343d3e80-c272-11e9-9d02-03cc2c21385d.png)
should be
![image](https://user-images.githubusercontent.com/5189853/63236899-3c957980-c272-11e9-9191-db00a97ccdc4.png)

**Comment by eternalsky** [comment]
已经解决
