### ISSUE TITLE
[Message]Message 组件快捷调用优化

### ISSUE THREAD

**Issue by myronliu347** [alibaba-fusion/next#1027]
### Component 
Message
### Feature Description
目前Message 只提供了toast的弹出方式，需要在使用方式上做出优化
1. 增加 notification 组件，右侧通知带行动点模式，
2. 新增config 方法，用于设置多个 message 的叠加方式，可选值 `override`, `queue`

**Comment by youluna** [comment]
1. 新增Notification组件，支持消息队列模式
2. Message新增config方法，建议通过maxCount来约束是单例模式还是队列模式。
    - maxCount = 1 的情况下，表现与现在一致；
    - maxCount > 1 的情况下，出现动画改为由下向上弹起

**Comment by myronliu347** [comment]
Fixed, 增加Notification
