### ISSUE TITLE
[Tree]支持叶子节点平铺

### ISSUE THREAD

**Issue by wwsun** [alibaba-fusion/next#1031]
### Component 
Tree
### Feature Description
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/VFzdL1msuTwt.png)

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/zT9OIAyqaIk7.png)

**Comment by jerryyxu** [comment]
已经实现https://fusion.design/pc/component/basic/tree#%E5%B9%B3%E9%93%BA%E5%8F%B6%E5%AD%90%E8%8A%82%E7%82%B9
