### ISSUE TITLE
[Search]Search filter default 属性失效

### ISSUE THREAD

**Issue by sml782** [alibaba-fusion/next#1034]
### Component 
Search

### Reproduction link 
[https://codepen.io/pen/?&editable=true&editors=0010](https://codepen.io/pen/?&editable=true&editors=0010)

### Steps to reproduce
期望filter默认选择default

**Comment by nianxiongdi** [comment]
codepen为啥没有内容？

**Comment by sml782** [comment]
抱歉，那个链接是之前的，这个是
https://codepen.io/sml782/pen/aboBPrp

**Comment by bindoon** [comment]
可以用这个api，defaultFilterValue

**Comment by bindoon** [comment]
文档里面那个default是copy时候的误写，并没有实现那个功能！
