### ISSUE TITLE
[Nav]菜单收起之后的默认宽度样式直接在标签里面，后面无法根据需要修改其样式

### ISSUE THREAD

**Issue by caizhen229** [alibaba-fusion/next#1046]
### Component 
Nav

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/SSMFV3PoGUhs.png)

**Comment by youluna** [comment]
icon要用如下方式添加，这么加会默认调整icon大小与宽度
```
<Nav iconOnly >
  <Item icon="account">Navigation One</Item>
</Nav>
```
