### ISSUE TITLE
[Form]BREACK CHANGE for TypeScript

### ISSUE THREAD

**Issue by justnewbee** [alibaba-fusion/next#1060]
### Component 
Form

### Steps to reproduce
actually it is a bug for all components

for typescript it is best practice to export props interface, however, newer versions 1.16 (maybe) removed props from index.d.ts export which breaks my ts build

version 1.13 has props exported from lib, now they are only in types...

**Comment by bindoon** [comment]
we still have https://unpkg.com/browse/@alifd/next@1.16.6/lib/affix/index.d.ts

**Comment by youluna** [comment]
xxxProps is exported in 1.16.8, check https://unpkg.com/browse/@alifd/next@1.16.8/lib/affix/index.d.ts
