### ISSUE TITLE
[Field]不能对传入的数据做改动

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#1062]
### Component 
Field

https://github.com/alibaba-fusion/next/blob/master/src/field/index.js#L35
![image](https://user-images.githubusercontent.com/10049465/63851563-00c48780-c9c9-11e9-9006-074098cdc711.png)

**Comment by youluna** [comment]
check https://github.com/alibaba-fusion/field

**Comment by bindoon** [comment]
测试下来浅拷贝就够了
