### ISSUE TITLE
[Input]SSR失败，顶层语句强依赖于浏览器环境

### ISSUE THREAD

**Issue by csr632** [alibaba-fusion/next#1071]
### Component 
Input

### Steps to reproduce
在开启SSR的项目中使用textarea就会出现问题。
比如gatsbyjs做SSR的时候，遇到这一行就会报错：https://github.com/alibaba-fusion/next/blob/b66fd93290fd17964614512ad19437546302153f/src/input/textarea.jsx#L24

报错：ReferenceError: navigator is not defined
目前好像只有这条语句是破坏SSR的，我手动改掉这条语句以后就成功SSR了。

请在这种【依赖浏览器环境的】【顶层语句】前面加一下判断吧：`typeof window !== 'undefined' && 其他语句'`

**Comment by youluna** [comment]
请问使用的组件版本是多少，这个问题在1.15.11+修复过

https://github.com/alibaba-fusion/next/blob/b66fd93290fd17964614512ad19437546302153f/src/input/textarea.jsx#L25

**Comment by csr632** [comment]
我用的是1.14.8，看来需要升级版本了。感谢修复
