### ISSUE TITLE
[Table]table组件，使用fixedHeader和lock时报错

### ISSUE THREAD

**Issue by baixc1** [alibaba-fusion/next#1090]
### Component 
Table

### Reproduction link 
[http://ice.work/component/table#锁列](http://ice.work/component/table#锁列)

### Steps to reproduce
官方示例：http://ice.work/component/table#锁列（示例导航-锁列），打开在线预览，上下滑动列表，报错：Unable to preventDefault inside passive event listener due to target being treated as passive。使用全局样式（* { touch-action: pan-y; } ）无法解决问题。

**Comment by youluna** [comment]
duplicated https://github.com/alibaba-fusion/next/issues/644
