### ISSUE TITLE
[Icon]基础组件增加icon

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#1114]
### Component 
Icon
### Feature Description
有几个在中后台系统中非常通用的icon需要再基础库里面补充下：

![image](https://user-images.githubusercontent.com/10049465/64678733-c10f9c80-d4ac-11e9-8fc1-640d7a7bc345.png)

toggle去掉，添加menu-collapse menu-expand
![image](https://user-images.githubusercontent.com/10049465/65211722-44934400-dad2-11e9-9183-8cc1ffa0cefb.png)

copy 复制       
lock 锁  
exit 退出 
chart  图表 
eye
eye-closed
menu-collapse
menu-expand

### 工作量：
1. 基础库 next 新增icon
2. 默认iconfont 地址修改
3. 配置平台 订正数据（用户自定义的icon可能会同名）

**Comment by myronliu347** [comment]
我们应该提供组件库引入 iconfont项目的能力，让用户导入自己需要的 icon

**Comment by youluna** [comment]
提供能力是另一回事哈，这个issue里期望增加icon的主要目的是
1. 丰富基础组件库的icon，让用户不需要额外添加就能满足80%的需求 
2. 组件的一些新功能依赖新的icon 比如input的输入密码功能，shell侧边栏的展开收起功能

**Comment by bindoon** [comment]
我期望的是覆盖，不过要看几个数据。
- 重名的icon到底有多少，都长什么样子，是否可直接覆盖？
- 如果不多，而且可控的话，是否可以针对这几个重复的人肉特殊处理

**Comment by bindoon** [comment]
## copy

![image](https://user-images.githubusercontent.com/5189853/65210065-7f927900-dacc-11e9-946b-e37fd508d7cd.png)
![image](https://user-images.githubusercontent.com/5189853/65210077-8f11c200-dacc-11e9-8f86-7673e45df5cc.png)
![image](https://user-images.githubusercontent.com/5189853/65210105-a781dc80-dacc-11e9-9688-5c1da5fac726.png)
![image](https://user-images.githubusercontent.com/5189853/65210116-b5376200-dacc-11e9-8e73-5794facb7899.png)
![image](https://user-images.githubusercontent.com/5189853/65210201-00517500-dacd-11e9-9ee4-5787833d0d2a.png)

**Comment by youluna** [comment]
结论：
1. 1.18.0新增10个icon如下图
2. 新增icon为基础icon，若用户有自定义icon与之重名，则拿用户的自定义icon替换基础icon内容
![image](https://user-images.githubusercontent.com/10049465/65405608-2fd6e900-de0f-11e9-8e6b-c7e3d342ecc3.png)
