### ISSUE TITLE
[Calendar]希望提供 RangeCalendar

### ISSUE THREAD

**Issue by yibn2008** [alibaba-fusion/next#1122]
### Component 
Calendar
### Feature Description
目前盒马正在做 next 0.x 至 1.x 的迁移, 目前盒马的 DatePicker 是基于 Calendar 的 highlightDates 属性做范围展示的,  现在 next 1.x 把 highlightDates 属性移除了, 希望 next 1.x 能对外暴露 RangeCalendar, 这样我们可以基于这个基础组件做二次开发.

不直接使用 next 1.x 的 DatePicker 是交互无法满足我们当前诉求.

**Comment by myronliu347** [comment]
fixed 1.19.0+
