### ISSUE TITLE
P0 - 主题包 variables.js 文件中的阴影变量无效

### ISSUE THREAD

**Issue by wwsun** [alibaba-fusion/next#1125]
### Type 
Platform

### Feature Description
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/F8fU57BK54es.png)

**Comment by wwsun** [comment]
这种写法是非法的

**Comment by bindoon** [comment]
另外 http://unpkg.com/@alifd/theme-2@0.0.31/variables.scss  里面变量似乎是缺了？https://unpkg.com/@alifd/theme-2@0.0.31/variables.js 里面是有的

![image](https://user-images.githubusercontent.com/5189853/64954572-a24c4400-d8b8-11e9-88e3-396e12c93007.png)
#000000 需要转下值，目前应该只有scss认识

**Comment by youluna** [comment]
![image](https://user-images.githubusercontent.com/10049465/65007150-d31f8e00-d937-11e9-9016-ac0ff6950d87.png)
@mark-ck tokens字段里存储的shadow是不合法的值，得转换下

**Comment by mark-ck** [comment]
这个 issue 已经处理好发布了，你们看看呢

**Comment by youluna** [comment]
fixed
