### ISSUE TITLE
[Input]P0 - 输入框组合样式有问题

### ISSUE THREAD

**Issue by wwsun** [alibaba-fusion/next#1127]
### Component 
Input

### Reproduction link 
[https://fusion.alibaba-inc.com/component/basic/input#%E8%BE%93%E5%85%A5%E6%A1%86%E7%BB%84%E5%90%88](https://fusion.alibaba-inc.com/component/basic/input#%E8%BE%93%E5%85%A5%E6%A1%86%E7%BB%84%E5%90%88)

### Steps to reproduce
应该去掉输入框两边的圆角的

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/tXdQSW0g45D2.png)

**Comment by nianxiongdi** [comment]
修改后的效果为：
![image](https://user-images.githubusercontent.com/41629087/65096712-7f28ae00-d9f8-11e9-97a6-133f0566cf04.png)
此issue与[#1068](https://github.com/alibaba-fusion/next/issues/1068)属于同一个问题，已提交pr.
