### ISSUE TITLE
[Select]Select 组件设置defaultValue后不会触发onChange事件

### ISSUE THREAD

**Issue by chinull** [alibaba-fusion/next#1143]
### Component 
Select
### Feature Description
<Select defaultValue="..." ......../>
当defaultValue命中Option选项时，需要触发一个onChange事件，来响应设置的值对应的变更。

或者从实践上，提供初始化完成相关的事件来处理？
或者defaultValue属性进行事件触发？

**Comment by bindoon** [comment]
设值不应该触发 onChange，onChange 应该由用户选择来触发！
