### ISSUE TITLE
[Select]select选择框

### ISSUE THREAD

**Issue by SearChen** [alibaba-fusion/next#1144]
### Component 
Select

### Reproduction link 
[https://jiejing.cainiao.test/demand/packetChangeDemand?demand_status=create&projectId=29](https://jiejing.cainiao.test/demand/packetChangeDemand?demand_status=create&projectId=29)

### Steps to reproduce
打开链接，选择配方案，选择cp，进入报文关联页中，新增行选择关联cp可复现问题；
1、多了空了，可以优化成不换行嘛
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/cqBBmIkB68c0.png)
2、select选择框，选择面板未关闭情况下，点击右上角下一步，选择面板依然存在，可一起帮忙修复调，是什么引起的
3、鼠标悬停当前选择面板上某一行时，会出现提示，能否把这个提示也同样放在选择后select选择框上，提示出选择了哪些数据
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/pyy4p8Iq7T7m.png)

**Comment by SearChen** [comment]
![Uploading image.png…]()

**Comment by SearChen** [comment]
![image](https://user-images.githubusercontent.com/8577108/65208436-a9956c80-dac7-11e9-86d3-c530574465bd.png)
2中的图片

**Comment by SearChen** [comment]
![image](https://user-images.githubusercontent.com/8577108/65208452-bade7900-dac7-11e9-955f-4f7bee0cc4bd.png)

**Comment by youluna** [comment]
1. 有API  tagInline  
3. 提示是系统行为，添加了title的html标签都会出，跟鼠标位置相关。

=========
2. 在riddle上复现下吧，看下是不是受控模式没关掉之类的
