### ISSUE TITLE
[NumberPicker]NumberPicker style error when use Form size="small"

### ISSUE THREAD

**Issue by bianchengde** [alibaba-fusion/next#1147]
### Component 
NumberPicker

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/cab8fdd9](https://riddle.alibaba-inc.com/riddles/cab8fdd9)

### Steps to reproduce
<Form.Item
  size="small"
>
   <NumberPicker/>
</Form.Item>

NumberPicker arrow style error,when use size="small"

**Comment by youluna** [comment]
![image](https://user-images.githubusercontent.com/10049465/66362178-51f66c80-e9b4-11e9-923a-44af63946481.png)

number-picker目前只有large medium两种状态，经设计师评估可以添加small状态与表单元素保持一致

**Comment by CaoYi-Ali** [comment]
https://udemo.alibaba-inc.com/preview#/preview/1359240/latest/specialStatus

**Comment by youluna** [comment]
from 设计师：
![image](https://user-images.githubusercontent.com/10049465/66562830-0c41cb80-eb8f-11e9-911d-a71a988a0424.png)
左右按钮宽度20，高20，icon尺寸12，中间数字输入框高20，宽24

上下模式下，input宽度改成68
