### ISSUE TITLE
[Table]锁列情况下，左右滚动在移动端有卡顿

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#1152]
### Component 
Table
### Feature Description
监听scroll，通过js同步header的左右offset的方式有性能问题，在移动端更加明显

**Comment by youluna** [comment]
1.21.1版本 通过<Table.StickyLock /> 解决，这个版本更改了实现方式，采用css  position: sticky来解决。

**Comment by xmsz** [comment]
这个问题现在有什么方案可以优化吗 现在即使用Table.StickyLock依旧卡出翔 而且没有弹性滚动的效果
