### ISSUE TITLE
内部版的主题基线没有 1.17.x 选项

### ISSUE THREAD

**Issue by huarse** [alibaba-fusion/next#1156]
如题，内部版的基线现在无法升级到 1.17，但是外部版可以

---- PS: 为什么不迁移至外部版？

- 字体变量不能自定义，只能从 Select 里面选
- 图标添加的体验太差了，导入一个有 100 多个图标的库，要一个一个地拖……

**Comment by mark-ck** [comment]
@huarse  老 fusion 平台我们已经没有精力维护了，最好迁移到新 fusion 平台，新 fusion 平台你提的两个问题我们可以在群里聊一聊，看看能不能尽快支持下
