### ISSUE TITLE
[NumberPicker]NumberPicker组件受控态自动修改问题

### ISSUE THREAD

**Issue by soulwu** [alibaba-fusion/next#1163]
### Component 
NumberPicker

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/red-sound-9ok3r)

### Steps to reproduce
连续多次输入0，第二次开始不会被自动纠正，并且上下操作按钮失效

**Comment by bindoon** [comment]
初始数据是空，不符合规范呀，应该是个整数

**Comment by bindoon** [comment]
原因是，订正的时候修改了显示value，onBlur 的时候应该再修改为 props.value
