### ISSUE TITLE
[Form]希望支持表单组件的呈现态

### ISSUE THREAD

**Issue by janryWang** [alibaba-fusion/next#1164]
### Component 
Form
### Feature Description
考虑到现在的表单页面，大多需要从编辑态切换到呈现态，比如Input切换为呈现态就是一个纯文本展示，类似的还有，Select/NumberPicker/DatePicker等，现在都是用户手动控制的，但是对于一些核心属性的转换还得手工处理，比如Input的innerAfter/addonAfter之类的，所以最好还是官方支持一下比较合适

比如`<Input editable={false}/>`

**Comment by youluna** [comment]
- [ ] Input
- [ ] NumberPicker
- [ ] Select
- [ ] DatePicker
- [ ] TimePicker

**Comment by janryWang** [comment]
Select需要考虑的地方有点多，需要着重关注一下：
1. 多选场景
2. 分组场景
3. 前后缀场景
4. itemRender场景
5. useDetailValue场景

**Comment by janryWang** [comment]
呈现态要考虑支持size="large" | "small" | "middle"的文本化展示场景

**Comment by youluna** [comment]
1. value为数组，preview状态下默认用逗号分隔
2. Select OptionGroup 展示分组信息
3. 默认展示前后缀
4/5. itemRender，useDetailValue情况下，跟select input区域展示的内容保持一致

**Comment by youluna** [comment]
done
