### ISSUE TITLE
[Input]Input.Group下多个input时双border的问题

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#1167]
### Component 
Input

### Reproduction link 
[https://codepen.io/aboutblank/pen/LYPqzMM?&editable=true&editors=0010](https://codepen.io/aboutblank/pen/LYPqzMM?&editable=true&editors=0010)

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/L0c2czHDPnwi.png)

**Comment by bindoon** [comment]
下一个y位发布  
.next-input-group .next-input + .next-input {
margin-left: -$input-border-width;
}

**Comment by bindoon** [comment]
fixed
