### ISSUE TITLE
`<Table useVirtual scrollToRow={n}>` scrollToRow 更新的时候滚动条当前位置没有受控

### ISSUE THREAD

**Issue by Leannechn** [alibaba-fusion/next#117]
**Describe the bug**
`<Table useVirtual scrollToRow={n}>` scrollToRow 更新的时候滚动条当前位置没有受控。

**Version of the Next Components**
1.11.5

**Reproduce URL**
http://riddle.alibaba-inc.com/riddles/638ceda5

受控scrollToRow， onBodyScroll打印的不是当前位置，几个版本的表现都不大一致。总而言之，打印出来的不是当前位置。

**Comment by myronliu347** [comment]
issues 的复现的地址尽量用外网地址吧，其他用户也可以看，
https://jsfiddle.net/
https://codepen.io/

**Comment by youluna** [comment]
riddle的用法不正确，正确用法参考 https://fusion.design/component/table  `虚拟滚动`

**Comment by Leannechn** [comment]
> issues 的复现的地址尽量用外网地址吧，其他用户也可以看，
> https://jsfiddle.net/
> https://codepen.io/

这边的模版一直写不了，才用的riddle，把模版修复一下吧

**Comment by Leannechn** [comment]
复现地址 https://codepen.io/anon/pen/GPvjgr?editors=0011

**Comment by youluna** [comment]
We fix it in 1.11.7
