### ISSUE TITLE
[Balloon]当第二次触发气泡显示时，进入动画会消失

### ISSUE THREAD

**Issue by lianmin** [alibaba-fusion/next#1171]
### Component 
Balloon

### Reproduction link 
[https://codepen.io/aboutblank/pen/OJLreeQ](https://codepen.io/aboutblank/pen/OJLreeQ)

**Comment by youluna** [comment]
跟Overlay相关，1.16.1及之前是好的，1.16.2出现问题，可能由 https://github.com/alibaba-fusion/next/commit/0a92c73  改动引起， @lianmin 看下

**Comment by youluna** [comment]
1.18.1已修复
