### ISSUE TITLE
[Drawer]背景mask不支持外部注入class，导致无法在某些场景下进行动态控制

### ISSUE THREAD

**Issue by veryStarters** [alibaba-fusion/next#1178]
### Component 
Drawer
### Feature Description
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/K61vFEeq6DPc.png)
箭头位置元素无法通过注入外部样式类进行动态控制

**Comment by youluna** [comment]
1.18.2支持 通过maskClass修改 <Drawer maskClass="myclass">
