### ISSUE TITLE
[Select]Select组件useDetailValue的时候label映射没有从dataSource中取

### ISSUE THREAD

**Issue by janryWang** [alibaba-fusion/next#1183]
### Component 
Select

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/goofy-boyd-eixq8)

### Steps to reproduce
考虑到有些时候后端返回的value并不存在label，或者label是A数据库存的，但是dataSource是B数据库存的，很有可能出现不一致的情况，预期是以dataSource为准

**Comment by bindoon** [comment]
useDetailValue 的目的是传入 object 类型的value，并把 object 作为自带数据源。所以为啥 useDetailValue 不需要数据源。

但是似乎大家依然 value = [ 'string'] 这种方式在用，useDetailValue 的目的只是为了 onChange的第一个参数是 对象。

是否可以学习 date-picker 一样，value 支持多种类型，onChange 的第一个参数是何种格式用api控制？

**Comment by bindoon** [comment]
遇到这种情况直接传value数组就好了，会自动从dataSource去匹配。传对象就是为了不传dataSource也能展示数据
