### ISSUE TITLE
[font]修改字体的教程未能解决问题请更新

### ISSUE THREAD

**Issue by opera443399** [alibaba-fusion/next#1194]
### Type 
Platform

### Feature Description
根据【网站-帮助中心-[修改字体](https://fusion.design/help.html#/font)】的教程来移除cdn的字体时，没有成功，经过自己摸索，找到方法：

1. 修改 `ice.config.js` 来自定义主题和主题的配置(参数等)

2. 重点是上述配置中使用到的这个 plugin: [ice-plugin-fusion](https://github.com/alibaba/ice/blob/master/docs/cli/plugin-list/fusion.md)

3. 修改示例

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/FCHWNR6Wc5Tk.png)

before:
```js
    ['ice-plugin-fusion', {
      themePackage: '@icedesign/theme',
    }],
```
after:
```js
    ['ice-plugin-fusion', {
      themePackage: '@alifd/theme-1',
      themeConfig: {
        'icon-font-path': '"/font/icon-font/font_881652_s3dlxhnu6h"',
        'font-custom-path': '"/font/roboto/"',
      },
    }],
```

4. 对应的字体还是按照原来教程中介绍的下载到本地即可

建议更新一下，否则打击新手小白的积极性啊，，在钉钉群也请教过没人理，，琢磨了一周，一度想放弃

**Comment by youluna** [comment]
感谢反馈
你看的教程是Fusion组件库面向用户的教程，不过你的项目是通过ice创建的项目，需要参考ice-plugin-fusion的[文档](https://ice.alibaba-inc.com/docs/cli/plugin-list/fusion) 我反馈给ice同学哈

**Comment by imsobear** [comment]
https://ice.work/docs/cli/plugin-list/local 用这个方案是不是更简单？ @opera443399

**Comment by opera443399** [comment]
> 感谢反馈
> 你看的教程是Fusion组件库面向用户的教程，不过你的项目是通过ice创建的项目，需要参考ice-plugin-fusion的[文档](https://ice.alibaba-inc.com/docs/cli/plugin-list/fusion) 我反馈给ice同学哈

多谢！@youluna @imsobear 
关注 fusion 是因为一篇去年看到一篇宣传博文，然后也是参考的这个[网站](https://fusion.design/)找到的[帮助中心](https://fusion.design/help.html#/)和[工具](https://fusion.design/tool)，意外惊喜是从@imsobear 这里知道ice有一个独立的网站，再次感谢！

**Comment by Loernl** [comment]
icon-font-path可以配置多个字体文件么
