### ISSUE TITLE
mac sketch 的 fusion 插件上没法登陆，拖拽控件无效

### ISSUE THREAD

**Issue by gooddaddy** [alibaba-fusion/next#1201]
### Steps to reproduce
点击右下角登陆淘宝账号，发现授权页白屏，还有我拖拽控件到工作区，都变成了loading控件，并不我当前拖拽的控件

**Comment by gooddaddy** [comment]
控件都变成loading的问题我知道为什么了，sketch不能开多个窗口，多窗口的模式下自由第一个窗口能拖拽出控件，其他窗口都变成了loading了，但是没法登陆的问题，还是存在

**Comment by zobor** [comment]
我私信你 我们钉钉上看下问题

**Comment by gooddaddy** [comment]
@zobor 我压根没输入账号ID的机会，点击淘宝 他就白屏了哦

**Comment by zobor** [comment]
> @zobor 我压根没输入账号ID的机会，点击淘宝 他就白屏了哦

我加下你的钉钉好友 我联系你看下问题哈

**Comment by miadwang** [comment]
请升级插件到1.8.6，重启sketch，查看登录问题是否已解决~
