### ISSUE TITLE
[Dialog]Dialog show 方法没有将 prefix 正常传入

### ISSUE THREAD

**Issue by xdlrt** [alibaba-fusion/next#1202]
### Component 
Dialog

### Reproduction link 
[https://github.com/alibaba-fusion/next/blob/master/src/dialog/show.jsx#L176](https://github.com/alibaba-fusion/next/blob/master/src/dialog/show.jsx#L176)

### Steps to reproduce
期望实现更换 Dialog 整体的 prefix，现在只修改了外层的一个类名

**Comment by lianmin** [comment]
add reproduce link: https://riddle.alibaba-inc.com/riddles/94e3b917
