### ISSUE TITLE
[Table]fixed header模式下，table body是overflow auto导致弹层显示不全

### ISSUE THREAD

**Issue by dandanba** [alibaba-fusion/next#1217]
### Component 
MenuButton

### Steps to reproduce
场次状态.gif
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/idOGME8sasot.png)

**Comment by youluna** [comment]
check https://github.com/alibaba-fusion/next/issues/1350

**Comment by youluna** [comment]
fixed in 1.19.7
