### ISSUE TITLE
[Select]很多组件的 typescript类型定义不准确

### ISSUE THREAD

**Issue by gooddaddy** [alibaba-fusion/next#1218]
### Component 
Select等等
### Feature Description
很多组件的 typescript类型定义不准确，很多都是any，{ }，能不能声明得更加准确点？

**Comment by youluna** [comment]
感谢反馈哈，不过组件库不是用ts写的，声明文件是手写补充的，因此可能存在部分声明比较宽松的问题

我们也在逐步完善，新版本的组件一定比旧版本的组件更全，如果你遇到了声明不准确的部分，请务必提issue过来（截图就可以） 或者直接pr到 https://github.com/alibaba-fusion/next/tree/master/types
