### ISSUE TITLE
Loading 目前是 display: inline-block, 应该是 display: block 才正确

### ISSUE THREAD

**Issue by yibn2008** [alibaba-fusion/next#124]
**Describe the bug**

Loading 目前是 display: inline-block, 应该是 display: block 才正确

**Version of the Next Components**
latest

**Reproduce URL**

直接看图:

![image](https://user-images.githubusercontent.com/4136679/50503863-c5be2d00-0aa4-11e9-8785-8683af3951f5.png)

**Comment by tao1991123** [comment]
为什么要是block？理由？

**Comment by windyGex** [comment]
不太理解设计为display:inline-block的原因，对于大多数场景而言这种覆盖式的loading基本都是用于块状元素。如果默认设为inline-block会影响到子级元素的一些计算。

**Comment by yibn2008** [comment]
是的，比如一个表单 form，各个组件的宽度是100%，如果加了loading，表单就会按内容宽度计算

**Comment by bindoon** [comment]
block 问题就是会通栏展示对组建的包裹不好

**Comment by windyGex** [comment]
可以加个API吧。默认还是inline-block，可以通过这个属性变更为display: block。现在每次都是通过style的方式或者复写CSS来修改的。

**Comment by tao1991123** [comment]
@jdkahn  this issue reporter want a loading with style: display: block

but loading component default style is "display: inline-block".

Now bindoon provides a solution： add a new props inline and this default value = true, if  inline === false, loading style should be  "display: block"

**Comment by jdkahn** [comment]
@tao1991123 When used right now the loader is `inline-block`. Do I need to go to each of these usages and add `inline: true`?

**Comment by youluna** [comment]
1.11.10 released
