### ISSUE TITLE
[Table]合并行的Table组件使用expandedRowRender属性后显示错位

### ISSUE THREAD

**Issue by smancang** [alibaba-fusion/next#1243]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/7a45eb40](https://riddle.alibaba-inc.com/riddles/7a45eb40)

### Steps to reproduce
Table设置了合并行后，再使用expandedRowRender就会出现错位的问题

**Comment by youluna** [comment]
https://riddle.alibaba-inc.com/riddles/ca947f9
需要开启 expandedIndexSimulate， 并修改 record.title -> record.title.name（object不能直接渲染）
`<Table expandedIndexSimulate  expandedRowRender={(record) => record.title.name}>`
