### ISSUE TITLE
[Button]button组件中的icon垂直居中对齐不精准，位置偏下

### ISSUE THREAD

**Issue by CaoYi-Ali** [alibaba-fusion/next#1249]
### Component 
Button

### Steps to reproduce
button组件中的icon垂直居中对齐不精准，位置偏下，需要进行布局上的修复

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/EMuDUubiFLcw.png)

**Comment by myronliu347** [comment]
fixed
