### ISSUE TITLE
[Progress]Progress的backgroundColor无效

### ISSUE THREAD

**Issue by LanxiangWang** [alibaba-fusion/next#1257]
### Component 
Progress

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-template-z26z8)

### Steps to reproduce
背景色没有被设置

**Comment by lianmin** [comment]
可以通过 `backgroundColor` 属性配置背景颜色

eg:
```js
    <Progress percent={30} shape="" color="#AF5F3C" backgroundColor="#00f"/>
```
