### ISSUE TITLE
neutural 单词拼写错误

### ISSUE THREAD

**Issue by tankxu** [alibaba-fusion/next#1259]
### Reproduction link 
[https://fusion.design/component/tokens](https://fusion.design/component/tokens)

### Steps to reproduce
Design Tokens 页面中 「neutural」 单词拼写错误，正确单词为 「neutral」。

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/0ZuOd5gIk4fv.png)

**Comment by youluna** [comment]
先不改了，改动成本太高，需要刷数据库orz
