### ISSUE TITLE
defaultValue是空字符串时，不会选中

### ISSUE THREAD

**Issue by judithhuang** [alibaba-fusion/next#126]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.11.6

### Component
TreeSelect

### Environment
和环境无关

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/bf30aaf](https://riddle.alibaba-inc.com/riddles/bf30aaf)

### Steps to reproduce
1. dataSource

```
treeData = [{
    label: '值是1',
    value: '1',
}, {
  	label: '值是空字符串',
    value: '',
}]
```

2. defaultValue=""

**Comment by myronliu347** [comment]
fixed in 1.12.0
