### ISSUE TITLE
[Pagination]分页器修改

### ISSUE THREAD

**Issue by fengmumu1** [alibaba-fusion/next#1268]
### Component 
Pagination
### Feature Description

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/nCFf3ZBdIc5J.png)
可以增加一个功能是，分页器中间的数字可以输入，比如有分页器的区域比较小，所以只能选择  shape="no-border" type="simple" ，可是这样子 做跳页就很麻烦，可以添加一个功能，数字可以输入

**Comment by myronliu347** [comment]
这个方案目前正在等待设计师确定

**Comment by fengmumu1** [comment]
。。。。 我来催更拉
