### ISSUE TITLE
[Nav]横向的Nav组件下拉箭头尺寸无法调整，选中的下划线也失效

### ISSUE THREAD

**Issue by CaoYi-Ali** [alibaba-fusion/next#1280]
### Component 
Nav

### Steps to reproduce
横向的Nav组件下拉箭头尺寸无法调整，改动引用组件menu的箭头尺寸后没有联动生效

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/3HLn8BD2REEm.png)

如果配置了选中后显示下划线，在选中某横向导航的二级子菜单项目时，该下划线并不会展示出来

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/dPn2XaAs76HQ.png)

**Comment by youluna** [comment]
1. 目前 nav中，hoz/ver两种模式下，arrow都无法配置
  menu中，ver模式下arrow可配置，hoz模式下arrow不可配置
以上是现状，需要增加 nav的hoz ver arrow可配置能力吗？

2. hoz模式下，popup item选中后，第一层级需要出现下划线这个可以改
