### ISSUE TITLE
[Table]table组件的左侧操作栏对齐参数不精确，无法水平居中

### ISSUE THREAD

**Issue by CaoYi-Ali** [alibaba-fusion/next#1281]
### Component 
Table

### Steps to reproduce
table组件的左侧操作栏对齐参数不精确，无法水平居中。如图所示只有左侧的间距是生效的，右侧的间距并没有生效

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/09HZrDMrfZ67.png)

**Comment by CaoYi-Ali** [comment]
如果实在无法做到精准控制，可以让左侧的操作自动水平居中

**Comment by youluna** [comment]
table的选择框列，宽度是50，可以让cell的padding-lr 配置不影响选择列
