### ISSUE TITLE
[Input]input的clear状态的icon颜色，不要影响select组件的下拉箭头颜色，这两者不需要关联

### ISSUE THREAD

**Issue by CaoYi-Ali** [alibaba-fusion/next#1282]
### Component 
Input

### Steps to reproduce
input的clear状态的icon颜色，不要影响select组件的下拉箭头颜色，这两者不需要关联

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/oKVp3llDR4Vk.png)

现在莫名其妙影响了select组件的下拉箭头颜色

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/pZuwuhzLnStv.png)

**Comment by bindoon** [comment]
input clear和 select 的下拉箭头都应该属于操作按钮，颜色都是一致的

![image](https://user-images.githubusercontent.com/5189853/93744994-5481be80-fc25-11ea-9ada-5736e49442e7.png)
