### ISSUE TITLE
[Dialog]quick形态的dialog，配置内容区左右padding时出现布局bug

### ISSUE THREAD

**Issue by CaoYi-Ali** [alibaba-fusion/next#1286]
### Component 
Dialog

### Steps to reproduce
quick形态的dialog，当配置内容区左右padding数值较大时会出现布局bug，整体布局样式严重错乱

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/Crq5NAqEX5Rg.png)

**Comment by bindoon** [comment]
一般不会设置这么大padding
