### ISSUE TITLE
[Drawer]close icon位置

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#1287]
### Component 
Dialog Drawer  Balloon Notificaiton

### Steps to reproduce
close icon的位置，距离上、右统一都改成12 或都改成16，还是根据所在容器环境的padding？
![image](https://user-images.githubusercontent.com/10049465/67752271-abaafd80-fa6d-11e9-909a-c6f9653b46c5.png)
![image](https://user-images.githubusercontent.com/10049465/67752289-b2397500-fa6d-11e9-964b-fb00d79bb248.png)
![image](https://user-images.githubusercontent.com/10049465/67752301-b6fe2900-fa6d-11e9-857b-2980ab337ef0.png)

**Comment by CaoYi-Ali** [comment]
统一把close的top和right padding改为默认S3，和title在高度上默认对齐

**Comment by youluna** [comment]
结论 dialog drawer 的cloase icon 默认位置改为 s3，其他不改
