### ISSUE TITLE
[Field]file表单布局问题

### ISSUE THREAD

**Issue by fengmumu1** [alibaba-fusion/next#1295]
### Component 
Field

### Reproduction link 
[https://codepen.io/fengmumu1/pen/qBBVNMy?editors=0010](https://codepen.io/fengmumu1/pen/qBBVNMy?editors=0010)

### Steps to reproduce
在Dialog的栅格布局里面，file组件的labe和内容不能在同一行，想要的是这样的结果

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/HNaygL0kSpY2.png)

结果出现的是这个结果

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/LiTl04ncMQ2y.png)

**Comment by bindoon** [comment]
{...formItemLayout}   放到每个 formitem 上面，因为formitem没有贴着 Form，所以透传不过去！
