### ISSUE TITLE
[TreeSelect]TreeSelect 非叶子结点某些情况下无法点击 x 来移除

### ISSUE THREAD

**Issue by liunian** [alibaba-fusion/next#1296]
### Component 
TreeSelect

### Reproduction link 
[https://fusion.design/component/basic/tree-select#%E5%8F%97%E6%8E%A7](https://fusion.design/component/basic/tree-select#%E5%8F%97%E6%8E%A7)

### Steps to reproduce
1. 访问官方文档 https://fusion.design/component/basic/tree-select#%E5%8F%97%E6%8E%A7 中的【受控】示例
2. 点击【Display】的 x 号

期望：
能移除该结点

实际：
无法移除。下拉展开，取消选择 display，然后重新选择后，才能点击 x 号来关闭

**Comment by myronliu347** [comment]
fixed
