### ISSUE TITLE
[Field]useField 没有编写类型声明

### ISSUE THREAD

**Issue by maoxiaoke** [alibaba-fusion/next#1305]
### Component 
Field

### Steps to reproduce
在函数组件中使用 useField，未提供 TypeScript 类型声明。
 
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/5GyUulL5lzg1.png)

**Comment by JeromeYangtao** [comment]
今天的一个MR已经补上，且被merge。请问最近准备什么发一次新的1.18.x版本，希望能够带上 @bindoon

**Comment by JeromeYangtao** [comment]
@maoxiaoke fusion已经发版本修复
