### ISSUE TITLE
[Table]fixedHeader的虚拟滚动条和表格内的select的下拉滚动条同时触发

### ISSUE THREAD

**Issue by shaojun427** [alibaba-fusion/next#1308]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/824de28d](https://riddle.alibaba-inc.com/riddles/824de28d)

### Steps to reproduce
fixedHeader开启的滚动条 lock属性开启，表格内的select下拉如果有滚动条，滚动的时候会带着表格的虚拟滚动一起滚动

**Comment by youluna** [comment]
1.19 fixed
