### ISSUE TITLE
裁剪上传缺少css文件

### ISSUE THREAD

**Issue by tao1991123** [alibaba-fusion/next#131]
https://fusion.design/component/upload 裁剪上传
缺少cropperjs/dist/cropper.css 

![](https://img.alicdn.com/tfs/TB1FGRHy9rqK1RjSZK9XXXyypXa-1928-1370.png)

**Comment by youluna** [comment]
@tao1991123 any progress?

**Comment by youluna** [comment]
![image](https://user-images.githubusercontent.com/10049465/53221090-c76e3080-36a2-11e9-994a-127d3ba46aee.png)
And the close icon doesn't work

**Comment by tao1991123** [comment]
done
