### ISSUE TITLE
[Table]锁列状态下空数据样式

### ISSUE THREAD

**Issue by xiaran030** [alibaba-fusion/next#1311]
### Component 
Table
### Feature Description
锁列模式下，no data状态应该是一个整体,而现在因为fusion默认会在每个锁列区都单独展示一个no data，导致业务层都要为了样式去封装，感觉不是很合理，期望是类似antd的处理
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/sqEy7pvHp4Tl.png)

**Comment by youluna** [comment]
1.19.7 fix

**Comment by youluna** [comment]
https://github.com/alibaba-fusion/next/pull/1492
