### ISSUE TITLE
[Table]table demo

### ISSUE THREAD

**Issue by xiaran030** [alibaba-fusion/next#1312]
### Component 
Table

### Reproduction link 
[https://fusion.design/component/basic/table](https://fusion.design/component/basic/table)

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/5mCr28xkHuLT.png)
官方demo，右上角odd,even点击，无反应

**Comment by youluna** [comment]
这里只是示意，点击之后是`console.log(value)`
