### ISSUE TITLE
[Input]提供 blur 时才 trim 的能力

### ISSUE THREAD

**Issue by liunian** [alibaba-fusion/next#1315]
### Component 
Input
### Feature Description
实际使用中，希望能 trim，但同时希望能保留有输入空格、换行（TextArea 的场景）的能力。

目前开启 trim 后，无法直接换行了。为了用户的使用，需要移除 trim，再搭配 blur 来实现 trim，希望组件能直接内置支持。

**Comment by bindoon** [comment]
直接自己监听onChange更快，两行代码的事情。

```
<Input.TextArea onBlur=(v=> this.setState({value: v.trim()}) value={this.state.value}  onChange/>
```

**Comment by bindoon** [comment]
trim 这个api 感觉比较鸡肋，比如你自己在项目里面提交数据之前、设置数据之前 trim 下有效。
组件不在做处理！
