### ISSUE TITLE
[Timeline]增强配置能力

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#1317]
### Component 
Timeline
### Feature Description
1. 增加能力，配置done / success / fail / process状态下的line模式。
2. 透传lineStyle 属性，让用户可以自定义属于当前节点的line的样式
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/Bbd7Z1zaRWKr.png)

**Comment by mark-ck** [comment]
@youluna 这个功能还需要吗

**Comment by lakerswgq** [comment]
先关了
