### ISSUE TITLE
区块里的预览无法展示

### ISSUE THREAD

**Issue by dcdc90** [alibaba-fusion/next#1321]
### Reproduction link 
[http://alifd.oss-cn-hangzhou.aliyuncs.com/ice-complex-progress-table-block/demo/index.html](http://alifd.oss-cn-hangzhou.aliyuncs.com/ice-complex-progress-table-block/demo/index.html)

### Steps to reproduce
区块里的预览无法展示

**Comment by youluna** [comment]
这个链接所在的页面是什么？ 区块要符合规范构建才能用
