### ISSUE TITLE
[Notification]Notification的d.ts声明有误

### ISSUE THREAD

**Issue by wqj97** [alibaba-fusion/next#1322]
### Component 
Notification

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/pChZuKCCCzTx.png)

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/WXmOqzlcNi7g.png)

和文档使用方式不符

**Comment by wqj97** [comment]
创建了一个MR, 有时间可以看下Review一下
https://github.com/alibaba-fusion/next/pull/1323

**Comment by myronliu347** [comment]
fixed
