### ISSUE TITLE
[Input]Input组件中开启trim能力后搜狗五笔无法输入

### ISSUE THREAD

**Issue by lujun5068** [alibaba-fusion/next#1329]
### Component 
Input

### Reproduction link 
[http://fusion-demo.alibaba-inc.com/demos/next/input](http://fusion-demo.alibaba-inc.com/demos/next/input)

### Steps to reproduce
Input组件中开启trim能力后搜狗五笔输入法无法输入，可在官网示例中直接复现

**Comment by bindoon** [comment]
没试过五笔，搜狗是ok的

**Comment by lujun5068** [comment]
拼音输入都是OK的，就是五笔输入有问题，因为拼音输入时是会有字母作为默认值占位的，而五笔的输入时，input中的默认占位值是空格，导致触发了onChange事件，内部的trim方法直接就把内容给干掉了，导致无法输入

**Comment by bindoon** [comment]
@lujun5068 感觉完全没有思路要怎么修复啊，这个是的判断用的什么输入法吗？

**Comment by lujun5068** [comment]
@bindoon 我本来想借鉴一下Vue中的v-model.trim的实现，但试了其他的五笔输入（Mac自带），是有具体的字符占位的，所以就能正常输入了，这个问题是不同输入法的实现导致的，可以暂时不用管了吧
