### ISSUE TITLE
[CascaderSelect]组件数据变量命名和后端开发规范有冲突

### ISSUE THREAD

**Issue by mytrip** [alibaba-fusion/next#1357]
### Component 
CascaderSelect
### Feature Description

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/5EWhWatDRCCL.png)
后端Java规范规定bool类型变量不能用is开头，否则，rpc框架会有解析错误，希望fusion对变量命名能与后端规范相结合，减少前端因该类原因进行的转换诉求

**Comment by myronliu347** [comment]
好的，我们会评估下

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进重新开启
