### ISSUE TITLE
[Nav]Nav.SubNav组件的label属性问题

### ISSUE THREAD

**Issue by Z3FisherX** [alibaba-fusion/next#1359]
### Component 
Nav

### Steps to reproduce
Nav.SubNav 组件的label属性 ，api中的类型为ReactNode，但是写成function形式会提示warning

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/qaX0FtdY5L6C.png)

**Comment by youluna** [comment]
因为function 不是合法的ReactNode，建议你写成function component
```jsx
const MyComponent = props => {
return 'subLabel'
}
...
<Nav.SubNav label={<MyComponent />} >
```
