### ISSUE TITLE
[TreeSelect]TreeSelect 非叶子结点 disabled 后不能展开收起

### ISSUE THREAD

**Issue by liunian** [alibaba-fusion/next#1363]
### Component 
TreeSelect

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/390c7b00](https://riddle.alibaba-inc.com/riddles/390c7b00)

**Comment by myronliu347** [comment]
disabled 的意义就是禁用功能，这个不能改变，建议这种情况 改用 selectable: false
