### ISSUE TITLE
[Input]getValueLength 文件截断策略未按返回的长度生效

### ISSUE THREAD

**Issue by zzfScarecrow** [alibaba-fusion/next#1365]
### Component 
Input

### Steps to reproduce
使用getValueLength属性自定义字符长度计算方式时，已经返回了一个比maxLength小的数字，文本还是会被截断。

**Comment by youluna** [comment]
可以关闭 cutString，这样不会超出截断 <Input.Textarea cutString={false} />
![image](https://user-images.githubusercontent.com/10049465/69133154-6324b400-0af0-11ea-9df7-71c979ab41f6.png)
