### ISSUE TITLE
[Balloon]trigger 如果是 disabled Button 组件,如果 Button 为 absolute ，则不展示气泡内容

### ISSUE THREAD

**Issue by limerickgds** [alibaba-fusion/next#1373]
### Steps to reproduce
老版本没有这个问题，新版本看了一下是增加了一层 span 。
关键是 span 增加了之后这个span 不能定义和继承disabled button 的 className ，而这个 span 布局又是 inline-block ， 原有的布局会被破坏。

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/l1jYR2JCWmm0.png)

**Comment by youluna** [comment]
https://riddle.alibaba-inc.com/riddles/5da23441

**Comment by eternalsky** [comment]
trigger disabled 之后不展示气泡感觉也是有问题的，有些情况下恰巧需要 disabled 时展示气泡说明禁用原因，两者禁用逻辑分离感觉能更好地被业务控制逻辑。
