### ISSUE TITLE
[Table]table组件，固定表头的情况下，如果使用drawer组件，浮层显示之后下面的table依然会跟追随鼠标滚动

### ISSUE THREAD

**Issue by jndxzqc** [alibaba-fusion/next#1377]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/6cfccf79](https://riddle.alibaba-inc.com/riddles/6cfccf79)

### Steps to reproduce
1、点击”enable lock“按钮
2、点击”open“按钮
3、滚动鼠标，table里面的内容跟着滚动（期望table固定不动）

**Comment by youluna** [comment]
1.19.x
fixed
