### ISSUE TITLE
[Table]table组件设置的情况下，如果某一行比较高，table会跳，无法滚动到当前行

### ISSUE THREAD

**Issue by jndxzqc** [alibaba-fusion/next#1378]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/1fc7cb4c](https://riddle.alibaba-inc.com/riddles/1fc7cb4c)

### Steps to reproduce
滚动table即可

**Comment by youluna** [comment]
开启useVirtual的情况下，需要保证行高是固定的，否则没办法计算 当前可视区域内，可提前加载多少行
