### ISSUE TITLE
[ConfigProvider]componentWillReceiveProps 等方法需要替换

### ISSUE THREAD

**Issue by huarse** [alibaba-fusion/next#1387]
### Component 

ConfigProvider

### Feature Description

不仅仅是 ConfigProvider，整个 fusion 里面大量用到了 `componentWillMount` 和 `componentWillReceiveProps`，现在在比较新的 react 版本里面会有很多 warning

**Comment by youluna** [comment]
在逐步升级，计划330之前完成所有升级，具体可以关注issue https://github.com/alibaba-fusion/next/issues/1012
