### ISSUE TITLE
fusion官网业务组件列表针对特定业务增加二级分类

### ISSUE THREAD

**Issue by veryStarters** [alibaba-fusion/next#1389]
### Type 
Platform

### Feature Description
目前业务组件面板中仅支持Table|Filter|Others等基础分类，但对于像企业这样事业部来说，先按照领域分类（通用、采购、法务等）呈现，再在该领域下呈现基础分类应该是一个比较好的方案，希望能够针对特定业务官网提供二级分类能力。

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/nurNBtsBz5er.png)

**Comment by bindoon** [comment]
初步想法， @mark-ck 这边把tag功能完善，让他们可以在组件上面打业务线的tag。
然后平台这边我提供一个配置，根据配置来展现业务线分类！

**Comment by mark-ck** [comment]
done
