### ISSUE TITLE
[Table] 使用useVirtual，能否不传onBodyScroll, scrollToRow

### ISSUE THREAD

**Issue by cwtuan** [alibaba-fusion/next#1394]
### Component 
Table
### Feature Description
Table用到开启虚拟渲染(useVirtual)，还需要自行实现onBodyScroll, scrollToRow。
这两个参数应该是内部实现用的，我觉得应该隐藏在内部代码，不然使用上特别麻烦。
![image](https://user-images.githubusercontent.com/3455798/69705360-5d525280-1130-11ea-8de6-e96288322f69.png)

**Comment by youluna** [comment]
scrollToRow 这里其实是受控用法，感觉你的需求应该是想要defaultScrollToRow，目前暂不考虑加哈

**Comment by cwtuan** [comment]
了解，其实我只是要非受控的用法。

只是这个例子是在展示useVirtual，又展示了受控用法，让人误以为useVirtual必须使用受控用法
