### ISSUE TITLE
[Table]table使用可展开后，onRowOpen第一个参数和第二个参数一直是undefined，非受控

### ISSUE THREAD

**Issue by cpaiyueyue** [alibaba-fusion/next#1395]
### Component 
Table

### Steps to reproduce
table使用可展开后，onRowOpen第一个参数和第二个参数一直是undefined，非受控,怀疑是不是渲染数据需要什么特殊标示，但是文档中并未体现

**Comment by cpaiyueyue** [comment]
发现了，你们默认数据源必须要有id标示，没的话就会出现这种情况

**Comment by youluna** [comment]
数据源必须要有主键，默认情况下主键名为id
