### ISSUE TITLE
[NumberPicker]inline模式下，宽度配置修改为输入区域的宽度

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#1403]
### Component 
NumberPicker

### 需求
inline模式下，宽度配置修改为输入区域的宽度，而不是包括button在内的整个宽度。
否则可能会出现用户修改s-base后，一些异常
![image](https://user-images.githubusercontent.com/10049465/69839684-8e976380-1293-11ea-9356-7cc70d2331bd.png)

**Comment by bindoon** [comment]
`<NumberPicker style={{width: 200}}/>` 这种写法可以直接调整宽度，因为内部input是跟随外面宽度自动伸展的。所以input宽度不能写死。
这块暂时无法这么修改

**Comment by bindoon** [comment]
准备增加 number-picker 最小宽度
