### ISSUE TITLE
[Table]开启useVirtual时，maxBodyHeight使用vh单位，内容渲染不出来

### ISSUE THREAD

**Issue by cwtuan** [alibaba-fusion/next#1405]
### Component 
Table

### Reproduction link 
https://riddle.alibaba-inc.com/riddles/27940daa

### Steps to reproduce
其实是有数据的，但是总是显示"没有数据"
![image](https://user-images.githubusercontent.com/3455798/69880138-27fe5e00-1304-11ea-8fca-0e4c75c21c7e.png)

**Comment by youluna** [comment]
计算可展示的行时，会用maxBodyHeight / rowHeight ，建议使用number

**Comment by cwtuan** [comment]
number就固定大小了。想要做成自适应

**Comment by xmsz-stu** [comment]
在firefox下使用 calc(100vh - 200px) 好像有问题，没有了滚动条，而chrome下正常
