### ISSUE TITLE
[Table]Table组件在虚拟滚动状态下lock的列高度没有随内容变多而撑高，出现错位

### ISSUE THREAD

**Issue by hehuilin** [alibaba-fusion/next#1408]
### Component 
Table

### Reproduction link 
[https://codepen.io/hehuilin/pen/zYYgEOr?&editable=true&editors=0010](https://codepen.io/hehuilin/pen/zYYgEOr?&editable=true&editors=0010)

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/iW393NmWhc0E.png)

**Comment by 909288037** [comment]
遇到相同问题, 请问你解决了吗?

**Comment by hehuilin** [comment]
> 遇到相同问题, 请问你解决了吗?

试下1.18.14版本，我这边是IE11下还是有问题，没解决，只能先不用lock了

**Comment by 909288037** [comment]
> > 遇到相同问题, 请问你解决了吗?
> 
> 试下1.18.14版本，我这边是IE11下还是有问题，没解决，只能先不用lock了

试了下1.18.14版本, 谷歌下没问题, 非常感谢.

**Comment by youluna** [comment]
1.19+ 已修复
