### ISSUE TITLE
[Transfer]穿梭框可以支持树状结构的数据穿梭么

### ISSUE THREAD

**Issue by zsl-lmm** [alibaba-fusion/next#1414]
### Component 
Transfer
### Feature Description
类似与antd里面的穿梭效果

**Comment by mark-ck** [comment]
1.18.x 版本已支持，用法见文档：
https://fusion.design/component/basic/transfer

![image](https://user-images.githubusercontent.com/44559440/70032888-4f497980-15e9-11ea-8ce0-4e08ee5753ad.png)
