### ISSUE TITLE
[Pagination]分页组件显示不能正常显示

### ISSUE THREAD

**Issue by easyhaloo** [alibaba-fusion/next#1420]
### Component 
Pagination

### Steps to reproduce
nacos上的使用分页组件，但是不能正常显示 option

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/9j1nLRrRCjcc.png)

我现在使用自定义的配置覆盖
.next-pagination-size-selector{
  position: static !important;
}
.next-overlay-inner{
  top:154px !important;
}
可以正常显示

**Comment by hieastz** [comment]
可以试试这样

```
    .next-overlay-wrapper.opened {
      height: 260px;
    }
```
