### ISSUE TITLE
[NumberPicker]NumberPicker，设置hasClear属性后样式错乱

### ISSUE THREAD

**Issue by dian533** [alibaba-fusion/next#1421]
### Component 
NumberPicker

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/6a4ce977](https://riddle.alibaba-inc.com/riddles/6a4ce977)

### Steps to reproduce
NumberPicker，设置hasClear属性后样式错乱

**Comment by bindoon** [comment]
不要用hasClear，后面代码里面会把这个透传去掉
