### ISSUE TITLE
[Select]Select多选后希望能有一键清楚功能

### ISSUE THREAD

**Issue by zixi8581** [alibaba-fusion/next#1422]
### Component 
Select
### Feature Description

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/py0vPNoxSzr0.png)

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/zKZH8TqbHUUb.png)

**Comment by nianxiongdi** [comment]
在Select组件当中修改hasClear属性的代码,已提交pr.
