### ISSUE TITLE
Can I replace prefix of the UI library?

### ISSUE THREAD

**Issue by anyexinglu** [alibaba-fusion/next#143]
Can I replace prefix of the UI library, both in css & js?

![image](https://user-images.githubusercontent.com/8243326/50600427-00342980-0eec-11e9-9528-1b50441ea02f.png)

**Comment by youluna** [comment]
You can use like this:
````jsx
// jsx code
class App extends React.Component {
    render() {
        return (
            <ConfigProvider prefix="my-">
                <div>
                    <Input />
                    <Button>Submit</Button>
                </div>
            </ConfigProvider>
        );
    }
}
````
```css
// css
$css-prefix: "my-";
@import "~@alifd/theme-xxx/index.scss";
```
For more information, see https://fusion.design/component/config-provider

**Comment by anyexinglu** [comment]
So sweet!

**Comment by anyexinglu** [comment]
For one component such as Button, can I set `props.prefixCls="my-button"` for it, then className within the js & scss change the prefixCls together?

It seems that, className within js can change, but within scss cannot?

**Comment by youluna** [comment]
Sorry but no,  we can't change js & scss files together. 

Public props like prefix, locales, rtl... should be set in configProvider, then the children of configProvider share the same public context, so that the children behave in consistent ways.
