### ISSUE TITLE
[Select] 开启followTrigger时，会被Collapse遮挡

### ISSUE THREAD

**Issue by cwtuan** [alibaba-fusion/next#1430]
### Component 
Select

### Reproduction link 
https://riddle.alibaba-inc.com/riddles/98a02ce7

### Steps to reproduce
```jsx
ReactDOM.render(
  <div style={{ marginBottom: 1000 }}>
    <Collapse>
      <Panel title="simple 111">
        <Select
          followTrigger={true}
        >
          <Option value="jack">Jack</Option>
          <Option value="frank">Frank</Option>
          <Option value="hugo">Hugo</Option>
        </Select>
        <div>1111111</div>
      </Panel>

      <Panel title="simple 222">222222</Panel>
    </Collapse>
  </div>,
  mountNode,
);

```
![image](https://user-images.githubusercontent.com/3455798/70376283-3ec73500-1942-11ea-9671-6019af44541d.png)

为了解决Select内容飘移问题，开启followTrigger，但是造成Select内容会被Collapse遮挡问题

**Comment by bindoon** [comment]
暂时先手动去掉 .next-collapse-panel-content 下的  overflow: hidden; 解决

**Comment by cwtuan** [comment]
加上了样式
```
.next-collapse-panel-content {
  overflow: initial; // https://github.com/alibaba-fusion/next/issues/1430
}
```

似乎没有完全解决问题。第三笔数据没显示
![image](https://user-images.githubusercontent.com/3455798/70424975-40603c80-1aab-11ea-8fc2-977b13597adf.png)

**Comment by bindoon** [comment]
为了避免折叠起来的时候，内部的元素还占据高度，折叠的时候可以在  .next-collapse-panel-content  加上 overflow:hidden 来解决
![image](https://user-images.githubusercontent.com/5189853/74311500-9a7ec600-4daa-11ea-8d53-572e024e52b6.png)

**Comment by qiufeihong2018** [comment]
如果和x6结合怎么解决，弹出层被遮挡的问题呢？
