### ISSUE TITLE
[Input]Input 组件 htmlType='number' 时 maxLength 失效

### ISSUE THREAD

**Issue by imsobear** [alibaba-fusion/next#1431]
### Component 
Input

### Reproduction link 
[https://codepen.io/sobear/pen/NeJmOG?editors=0011](https://codepen.io/sobear/pen/NeJmOG?editors=0011)

### Steps to reproduce
Input 组件 htmlType='number' 时 maxLength 失效

**Comment by bindoon** [comment]
maxLength利用了input原生的能力，原生能力就是 只要type=number maxLength 就失效。
