### ISSUE TITLE
[Field] Field的parseName支持解析数组、对象

### ISSUE THREAD

**Issue by cwtuan** [alibaba-fusion/next#1432]
### Component 
Field
### Feature Description
有一些组件会返回多笔数据(如RangePicker)
```jsx
<RangePicker {...init('date'} />
```
保存到后端时，一般后端是接收两个变量，前端需要处理一下：
```js
const [beginDate, endDate] = this.field.getValue('date');
http.post({ beginDate, endDate });
```

回显时也要处理一下：
```js
const {beginDate, endDate} = http.get(...);
const date = [beginDate, endDate]; 
this.field.setValue('date', date);
```

## 建议
目前field的parseName，只能解析 "带.的字符串转换成对象"，
希望能提供更多的解析功能，例如例如：
- 解析数组：`init('[beginDate, endDate]')`
- 解析对象：`init('{beginDate, endDate}')`

这样就不用在写来回转换代码了

**Comment by cwtuan** [comment]
预计 1.21 支持

**Comment by eternalsky** [comment]
已支持结构化数据
