### ISSUE TITLE
[Step]宽度应该顶边儿 

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#1433]
### Component 
Step

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/XKIRDB9Jwt1C.png)

**Comment by mark-ck** [comment]
@youluna 是不是已经修复了😂

**Comment by youluna** [comment]
没有修复，这个跟设计相关，直接改成顶边儿的会有样式上的breakchange，暂时hold吧，最多放到2.x里去考虑
