### ISSUE TITLE
[通用]业务场景的组件文档无法切换next版本

### ISSUE THREAD

**Issue by JulienBrks** [alibaba-fusion/next#1450]
### Component 
Affix
### Feature Description
忽略问题所属组件。

核心问题是组件文档无法像fusion-design.alibaba-inc.com可以切换next版本，似乎现在默认是查看最新的next版本的文档。

以下是业务域的文档：
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/AavPyp04BoHe.png)

以下是fusion-design的文档，注意看红框的区域，可以切换next版本：

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/n2VmIavcut3A.png)

**Comment by mark-ck** [comment]
新版本目前就是这么设计的，你在自己的站点(供货中心)看到的组件文档并不是最新版本的，组件文档的版本跟当前站点的基线保持一致；

这么设计是因为正常情况下，你们项目中会使用你们站点的主题包，那么要查看的组件文档的版本需要跟主题包的基线版本一致。
