### ISSUE TITLE
[Upload]upload.card onChange函数TS类型定义错误

### ISSUE THREAD

**Issue by baoliehua** [alibaba-fusion/next#1456]
### Component 
Upload

### Steps to reproduce
upload.card 继承自upload但是onChange这一类函数的TS定义错误
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/YK9w2sc2yYpO.png)

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/QoV8SirMS5QB.png)

**Comment by baoliehua** [comment]
![image](https://user-images.githubusercontent.com/15277679/71082538-3b4a6e00-21cc-11ea-9e11-e9e98615db1b.png)
这是next@1.18.17的Upload.card的TS定义文件中onChange定义，其他函数TS定义

**Comment by bindoon** [comment]
fixed in 72f00064
