### ISSUE TITLE
[Badge][Badge组件小圆点支持color设计]

### ISSUE THREAD

**Issue by yongyi-999999** [alibaba-fusion/next#1459]
### Component 
Badge
### Feature Description
通过小圆点来代表不同的状态，目前不支持color的自定义，目前的组件方案是设置背景色来达到目的

**Comment by youluna** [comment]
小圆点的背景色和上面的文字颜色都支持自定义，可以看下文档
`<Badge content="hot" style={{backgroundColor: '#FC0E3D', color: '#FFFFFF'}} />`
