### ISSUE TITLE
[Affix]table使用affix说明不详细，且在项目中使用affix貌似没生效

### ISSUE THREAD

**Issue by cpaiyueyue** [alibaba-fusion/next#1461]
### Component 
Affix

### Steps to reproduce
table使用affix说明不详细，且在项目中使用affix貌似没生效，使用其包裹了组件，但触碰到浏览器顶部时并没出现固定

**Comment by mark-ck** [comment]
hello，麻烦提供个 codepen 例子，我们看看你指的是什么场景

**Comment by cpaiyueyue** [comment]
我已经解决了哈------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;mark&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月7日(星期二) 上午10:59
收件人:&nbsp;&quot;alibaba-fusion/next&quot;<next@noreply.github.com&gt;;
抄送:&nbsp;&quot;cpaiyueyue&quot;<471220299@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba-fusion/next] [Affix]table使用affix说明不详细，且在项目中使用affix貌似没生效 (#1461)

**Comment by mark-ck** [comment]
嗯嗯，那太好了了 😀
