### ISSUE TITLE
[Table]table stickyHeader 设置为true之后，表头不会发生吸顶

### ISSUE THREAD

**Issue by cpaiyueyue** [alibaba-fusion/next#1465]
### Component 
Table

### Steps to reproduce
单写一个table渲染到根节点上没问题，但是开发项目中，运用到了组件之后属性值等都设置的完全一样则时效，按f12页面resize之后会出来，但是效果仍是bug，不会返回到原位置，难道这个只能运用于根节点么，下面渲染到根节点就行
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/WZCPzGJn8Isv.png)
![image](https://user-images.githubusercontent.com/45730337/71241714-3eb63480-2347-11ea-9b5d-41ea3b496572.png)

**Comment by youluna** [comment]
给个复现环境，站点上所有demo都可以选择用codepen打开

**Comment by cpaiyueyue** [comment]
这个有点为难，项目不能随便暴露的，我现在这个是在一个子路由里面写的，然后就是挺直白的一个demo，用div在外面包了一层，然后设置了这些属性，因为牵扯到数据量大的原因，所以需要做一个吸顶，发现了这个属性后使用了但是失效，于是我就单独的抽离出来用codepen写了一下，可以实现效果，我考虑是不是监听事件的时候没考虑到多层嵌套的原因

**Comment by youluna** [comment]
确认bug的第一步是复现问题，需要通过codepen给一个最小复现demo来确认异常是由哪里引起的
