### ISSUE TITLE
[Table]组件库中table组件最后一列的lock设置为right，emptyContent属性设置的reactElement中如果有比较大的自定义图片，当表格内无数据时，图片不能全部显示出来，希望图片能居中显示

### ISSUE THREAD

**Issue by bt9396118** [alibaba-fusion/next#1467]
### Component 
Table

### Steps to reproduce
过滤后无数据，table组件emptyContent属性自定义图片后
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/xd5lr37wkuY9.png)

**Comment by youluna** [comment]
https://github.com/alibaba-fusion/next/pull/1492

**Comment by youluna** [comment]
已修复，升级到1.19.7（如果用到主题包也要升级主题包哦）
