### ISSUE TITLE
[Table]表格过滤中，过滤弹层没有随着滚动条而滚动，设置popupContainer无效

### ISSUE THREAD

**Issue by bt9396118** [alibaba-fusion/next#1468]
### Component 
Table
### Feature Description

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/NDNdaF5eVfgV.png)

**Comment by youluna** [comment]
涉及到横向滚动的问题

**Comment by youluna** [comment]
可以通过如下方法解决：
```
<Table  id="test" >
  <Table.Column  filterProps={{container: 'test'}} />
</Table>
```
在会出现筛选器的列上设置filterProps，并指定容器是当前Table可以解决。不过需要注意在没有数据的时候，可能会出现滚动条
