### ISSUE TITLE
[Card] componentDidUpdate 后「更多」按钮的展示不会计算

### ISSUE THREAD

**Issue by Lisuhan** [alibaba-fusion/next#1480]
### Component 
Card

### Steps to reproduce
当 Card 内容是接口获取时，获取数据后渲染 content 高度高于 contentHeight， _setNeedMore 方法不会重新执行，「更多」按钮也不会展示出来

**Comment by eternalsky** [comment]
没有复现 demo，无法确定具体的问题，如需继续跟进请重新提交 issue
