### ISSUE TITLE
[Balloon] triggerType鼠标定位问题

### ISSUE THREAD

**Issue by cwtuan** [alibaba-fusion/next#1482]
### Component 
Balloon

### Reproduction link 
https://riddle.alibaba-inc.com/riddles/654fb86e

### Steps to reproduce
当triggerType="click"，鼠标定位：
1. 在第一个输入框，随便输入值
2. 鼠标点击第二个输入框，鼠标会再被focus到第一个输入框

![image](https://user-images.githubusercontent.com/3455798/71456873-810fc380-27d6-11ea-9210-a9977d34ea3d.png)

这个问题，可以使用triggerType="focus"解决，但是已经deprecated，担心以后会移除
![image](https://user-images.githubusercontent.com/3455798/71457003-127f3580-27d7-11ea-8459-733dfd70abf2.png)

**Comment by youluna** [comment]
解决方法：
1. 可以用focus，不会被废弃，提示我改一下。
2. triggerType 为 click时，可以设置autoFocus={false}

@lianmin 看下这个bug，原因是弹层onLeaved时，没有检测是否已经有新的focus的元素，直接回到了记录list里的最近一个节点上  https://github.com/alibaba-fusion/next/blob/e1174873f6ea5090da48b958d68e633893da9f38/src/overlay/overlay.jsx#L576

**Comment by cwtuan** [comment]
@youluna 
triggerType="focus" 的deprecated警告，麻烦移除下。好像没看到commit

**Comment by youluna** [comment]
https://github.com/alibaba-fusion/next/commit/0299695f588d5b81953759b07aa709198e82cb75
