### ISSUE TITLE
[Slider]页面resize会导致slider回到初始设置的slide上

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#1483]
### Component 
Slider
### Feature Description
共4张slides，走到第3张，resize页面，当前slide变成了第一张

原因是页面resize触发组件重新渲染，回到初始设置的slide上

**Comment by zarazhu** [comment]
可以设置defaultActiveIndex={currentSlider}
用一个currentSlider的State存储
页面可以保持在原来的第三张

**Comment by bindoon** [comment]
duplicated with https://github.com/alibaba-fusion/next/issues/3722
