### ISSUE TITLE
[Table]IE11 下锁列不随内容列高度变化而变化

### ISSUE THREAD

**Issue by lvqq** [alibaba-fusion/next#1484]
### Component 
Table

### Reproduction link 
[https://lvqq.github.io/fusion-design-Table-demo/build/index.html#/dashboard](https://lvqq.github.io/fusion-design-Table-demo/build/index.html#/dashboard)

### Steps to reproduce
IE11下，内容列高度变化后， 锁列高度未跟随变化：
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/uDq9sQiMfqFc.png)

**Comment by youluna** [comment]
@lvqq 更新到最新版，我这边在mac的虚拟机里看IE11下是好的

**Comment by lvqq** [comment]
我这边在windows的IE11下看，当横向滚动条存在时，还是有如上问题
