### ISSUE TITLE
alife/next@1.x 版本，Dropdown 和 Menu 一起使用时，弹出的菜单时，第一个选项默认显示为 hover 状态，且无法恢复，hover 其他选项时，第一个选项仍然是 hover 状态

### ISSUE THREAD

**Issue by judithhuang** [alibaba-fusion/next#149]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
~TreeSelect~  Dropdown

### Environment
和环境无关

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/f2b6a306?mode=jsx](https://riddle.alibaba-inc.com/riddles/f2b6a306?mode=jsx)

### Steps to reproduce
见代码

**Comment by youluna** [comment]
可以通过<Dropdown autoFocus={false}>禁用自动聚焦，这样的话当使用键盘访问dropdown时需要多切一次tab才能到弹层里。

将在下个[Y位版本](https://github.com/alibaba-fusion/next/pull/166)优化这里的逻辑，当通过键盘事件触发children展开时，才默认聚焦到弹层里。

**Comment by youluna** [comment]
1.12.0 fixed
