### ISSUE TITLE
[Checkbox]name 属性丢失

### ISSUE THREAD

**Issue by kookxiang** [alibaba-fusion/next#1495]
### Component 
Checkbox

### Steps to reproduce
https://github.com/alibaba-fusion/next/commit/5beedd8c407e2bebe2e859d3031f7a7a9bbd8b85
更新后 name 属性丢失了，因为加到 propTypes 以后被 pickOthers 踢掉了：
https://github.com/alibaba-fusion/next/blob/5b3a275b6ab7f073b69d2cc79d0e246ded3ce039/src/checkbox/checkbox.jsx#L229

组件文档是有 name 属性的，希望重新加一下

**Comment by youluna** [comment]
欢迎PR ❤️
