### ISSUE TITLE
[DatePicker]RangePicker使用体验优化

### ISSUE THREAD

**Issue by cpaiyueyue** [alibaba-fusion/next#1496]
### Component 
DatePicker
### Feature Description
RangePicker点击过日期后不能像菜鸟平台的日期自动回弹，必须手动点击确定或者失焦，开始结束日期光标自动移动，但不明显，用户使用不容易发现，会造成事件切换异常难受，建议选择完成后可以自动回弹
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/C0eAA9jGtxRB.png)

**Comment by YidanWang** [comment]
这个真的能不能改一下？太难受了。
已经遇到好几次用户来问“诶你们的开始时间为什么不能往后点？”
我都是看过文档和看到这个问题才注意到这个框的高亮的...
简单地 点击设置开始-点击设置结束-点击设置开始-点击设置结束... 不香吗？

**Comment by lakerswgq** [comment]
DatePicker2 已经解决这个问题
