### ISSUE TITLE
[Icon]Icon 显示不出来

### ISSUE THREAD

**Issue by ityao** [alibaba-fusion/next#1498]
### Component 
Icon

### Reproduction link 
[https://ice.work/component/icon](https://ice.work/component/icon)

### Steps to reproduce
你们自己官网就显示不出那几个内置的icon, 包括 copy, eye, eye-close, toggle-left, lock, chart-bar, 相关使用了这些icon的组件都有问题, 例如input的password组件

**Comment by youluna** [comment]
看起来ice站点的主题包需要升级下，@imsobear
