### ISSUE TITLE
[Divider]无法解析模块 divider

### ISSUE THREAD

**Issue by ixre** [alibaba-fusion/next#1499]
### Component 
Divider

### Steps to reproduce
使用的版本号:    1.18.17

在.babelrc中添加了按需导入
```
import { Divider } from '@alifd/next';
```
错误提示:
```
Can't resolve '@alifd/next/lib/divider'
```

**Comment by youluna** [comment]
Divider 是 1.19.x加入的，执行下`npm install @alifd/next@1.19.x`
