### ISSUE TITLE
[Select]showSearch   弹层定制模式下，无法输入空格

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#1502]
### Component 
Select

### Reproduction link 
[https://codepen.io/aboutblank/pen/vYEpZLw?&editable=true&editors=0010](https://codepen.io/aboutblank/pen/vYEpZLw?&editable=true&editors=0010)

**Comment by bindoon** [comment]
popup.js 里面 `triggerClickKeycode: [KEYCODE.SPACE, KEYCODE.ENTER]` 。默认用 SPACE 作为触发展开弹窗功能了。

可以
```
        const popupProps = {
            triggerClickKeycode: [13, 32, 40] // space, enter, down-arrow
        };
```
改成 
```
        const popupProps = {
            triggerClickKeycode: [13, 40] //  enter, down-arrow
        };
```
