### ISSUE TITLE
[Form]支持自动加冒号能力

### ISSUE THREAD

**Issue by janryWang** [alibaba-fusion/next#1507]
### Component 
Form
### Feature Description
因为antd也是支持冒号的，UForm这边，大部分用户对冒号的需求还是蛮大的

https://github.com/alibaba/uform/issues/584

**Comment by cwtuan** [comment]
我们这里是直接加上全局样式 content: '：';

**Comment by bindoon** [comment]
考虑到未来可能需要把 label 作为错误提示的一部分，可能需要label的：去掉，那么这个需求就合理了

#700

**Comment by monkindey** [comment]
@bindoon 有计划吗？
