### ISSUE TITLE
[Search]Search不满足大部分使用场景

### ISSUE THREAD

**Issue by csr632** [alibaba-fusion/next#1517]
### Component 
Search
### Feature Description
https://codepen.io/csr632/pen/mdyxwrQ?editable=true&editors=0010
输入r，然后按下回车，应该搜索r。而不是先帮用户选中第一项。

淘宝首页、google搜索都是这样的逻辑。

**Comment by bindoon** [comment]
可以增加api，不自动focus第一个元素

**Comment by lakerswgq** [comment]
closed via https://github.com/bindoon/next/commit/8511283d804d8866ee11a987ea9f45a4ff79c992
