### ISSUE TITLE
[Card]Card 组件的内容高度不会根据 children 变化更新

### ISSUE THREAD

**Issue by ex90rts** [alibaba-fusion/next#1523]
### Component 
Card

### Steps to reproduce
当卡片设置 contentHeight 后，内容超出会出现 “展开/折叠” 功能，当 centent 的 children 动态变化之后（比如 content 是一个文本，该文本来源于一个 state 的值，这个 state 变化后文本长度相应也改变了），内容区不会重新计算并展示或移除 “展开/折叠” 操作按钮

**Comment by eternalsky** [comment]
目前来看在 Card 组件在重新渲染时会重新调用 _setContentHeight，因此只要 children 的变化会引发 Card 重新渲染那么高度就可以重新计算，如果这个更新是被 children 里的组件内部消化的，这个变化目前 Card 感知不到，因此也不会重新计算，这时可以通过回调到 Card，让 Card 进行重新渲染来解决。
