### ISSUE TITLE
[Range]Range 区段选择搭配 Form.Item 一起使用时横向居中对齐不对

### ISSUE THREAD

**Issue by ex90rts** [alibaba-fusion/next#1524]
### Component 
Range

### Steps to reproduce
Range 区段选择搭配 Form.Item 一起使用时横向居中对齐不对，Control 部分顶部对齐，和 Label 不在一条中线上。效果如下图：
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/BJELgQsoiyJG.png)

**Comment by bindoon** [comment]
range的高度不够，form做下hack处理吧

**Comment by bindoon** [comment]
这里也说明了 Range 的高度不规范问题。作为表单组件应该有统一的高度，至少要做到放在 Form 里面不需要 Form去hack，应该是对齐的。

**Comment by eternalsky** [comment]
可以通过加样式来对齐
```tsx
<FormItem label="Range:" className="center-item">
   <Range defaultValue={30} scales={[0, 100]} />
</FormItem>
```
```css
.center-item .next-form-item-control {
  display: flex;
}
```
