### ISSUE TITLE
[Table]Table组件在锁列时使用Balloon组件有时会出现两个气泡

### ISSUE THREAD

**Issue by dyxweb** [alibaba-fusion/next#1526]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/520309ba](https://riddle.alibaba-inc.com/riddles/520309ba)

### Steps to reproduce
出现锁列时点击内容出现气泡有时会出现两个气泡，情景不是必现，可以尝试拖动Table的横向滚动条之后再次点击出现气泡
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/cet8xpUtq63O.png)

**Comment by youluna** [comment]
关联 https://github.com/alibaba-fusion/next/issues/1728  ，升级到1.21.0-beta.4 通过<Table.StickyLock />解决
