### ISSUE TITLE
[Table]使用stickyHeader+offsetTop属性时，table内容溢出

### ISSUE THREAD

**Issue by dabennn** [alibaba-fusion/next#1527]
### Component 
Table

### Reproduction link 
[https://codepen.io/dabennn/pen/NWPBMxQ?editable=true&editors=0010](https://codepen.io/dabennn/pen/NWPBMxQ?editable=true&editors=0010)

### Steps to reproduce
重现步骤： 上下滚动，stickyHeader生效时继续向下滚动，table内容在header上方溢出
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/CoPRIg6nIqbX.png)

期待结果： header上方内容不溢出

**Comment by youluna** [comment]
这里的表现符合预期，因为设置的offsetTop不是0是20，想实现你要的效果应该在页面上加一个offsetTop为0并且高度为20的Affix元素，这个显然不应该由table处理
