### ISSUE TITLE
[Table]表格的行选择支持当前页模式

### ISSUE THREAD

**Issue by ex90rts** [alibaba-fusion/next#1530]
### Component 
Table
### Feature Description
当前表格的 rowSelection 模式的是跨页选择，即在 id 确定的情况下，在当前页选中了某些记录，翻页后，selectedRowKeys 中依然会保存前一页选择的记录。

希望可以有一个开关来控制，翻页后是否保存之前分页里面选择的数据，默认为跨页，开关打开后变为单页。

**Comment by xmsz** [comment]
这个问题怎么样了

**Comment by eternalsky** [comment]
这里有个问题是 Table 并没有翻页的概念，翻页对于 Table 来说只是数据刷新，但数据刷新还有很多可能性并不一定是翻页，因此这里的关于是单页还是跨页是不成立的，但是 Table 确实在不卸载的情况下是会保留 selectedRowKeys（因为这是一个内部状态）。不过，由于可以通过 rowSelection.selectedRowKeys 受控控制选择项，因此可以在业务自己定义的翻页事件时去清空这个值来达到清空的效果。
