### ISSUE TITLE
[Table]table 的 primaryKey 支持传入Function，通过函数来计算行ID

### ISSUE THREAD

**Issue by csr632** [alibaba-fusion/next#1534]
### Component 
Table
### Feature Description
支持通过函数来计算行ID
primaryKey={(item) => {
    return item.schoolId + item.classId
}}

**Comment by youluna** [comment]
primayKey记录的是，dataSource中哪一个是主键，比如以下 idNumbers 是primaryKey是主键，如果需要由两个字段共同构成一个唯一身份认证，建议处理下dataSource
```jsx
[{ 'name': 'ddd', 
    'age': 12, 
    'idNumber': '123123123'
}, {
   'name: 'da', 
   'age': 12, 
   'idNumber': '33212312'
}]
```
