### ISSUE TITLE
[Dialog]Dialog是否可以增加一个输出纯内容的开关

### ISSUE THREAD

**Issue by fengmumu1** [alibaba-fusion/next#1537]
### Component 
Dialog
### Feature Description
我们的网站上有很多的页面是使用 Dialog 包裹后做成弹窗形式的，现在有的地方需要显示同样的内容，不过不是以弹窗形式展示的，要么我抽离内容，改以前的代码，要么我改现在的交互，
我在想是否提供一个按钮，使 Dialog 失效，类似于 React.Fragment，不过可以把 传递给 dialog 的属性继承，或者让用户配置 继承什么属性

**Comment by fengmumu1** [comment]
如果采纳建议，可以给我一个时间嘛，我好计划我这边项目要怎么写哈

**Comment by fengmumu1** [comment]
我现在是在 结合 Dialog 封装的组件里面 加了一个属性，来控制是否输出被 Dialog 包裹的元素，话说，遇到弹窗里面再套弹窗的时候，可以设置不显示（不注销父级弹窗）父级所有弹窗的功能嘛，比如我 a 弹窗里面 包裹了 b, b有个选择功能是弹窗形式的，这时候就成了弹窗套弹窗了，能否加个功能给其所有父级弹窗 不显示，谨显示当前弹窗，

**Comment by acejerry** [comment]
1. 输出纯内容是什么意思没看懂 是不是只需要弹窗 看下 [overlay组件](https://fusion.design/component/basic/overlay)是否符合需求
2. 弹窗嵌套问题可以通过visible属性来隐藏父弹窗，从组件来说，弹窗嵌套并不是通用场景
