### ISSUE TITLE
[Dialog]Dialog.alert/Dialog.confirm 显示 Message 移动端样式兼容问题

### ISSUE THREAD

**Issue by ex90rts** [alibaba-fusion/next#1539]
### Component 
Dialog

### Steps to reproduce
Dialog.alert/Dialog.confirm 中的 content 是通过 Message 组件渲染的，但是在 Dialog 的样式中有一个 min-width 设置：`min-width: $s-25 * 3;` （结果为 300px）导致在手机上开启 isFullScreen 后，由于屏宽不够，Message 内容无法全部显示而被 overflow 掉。如下图：

Screen Shot 2020-01-20 at 9.47.55 AM.png
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/HMWCw61wgimk.png)

**Comment by bindoon** [comment]
移动端是 meet-react, pc 不需要适配
