### ISSUE TITLE
[TimePicker]timePicker设置了format但返回了date的格式

### ISSUE THREAD

**Issue by jasonzhuang** [alibaba-fusion/next#1547]
### Component 
TimePicker

### Reproduction link 
[非必现](非必现)

### Steps to reproduce

偶现date的格式值
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/wuLTgddLOqoU.png)

期望的值是format格式
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/Iu00wsRLoLqH.png)

**Comment by acejerry** [comment]
意思是设置了format属性，但是在onChange回调中，拿到的value是Moment对象？
