### ISSUE TITLE
[Table]升级 Table 组件中对 ref 的使用方式

### ISSUE THREAD

**Issue by woota** [alibaba-fusion/next#1557]
### Component 
Table

### Reproduction link 
[https://reactjs.org/docs/error-decoder.html/?invariant=290&args%5B%5D=lockLeft](https://reactjs.org/docs/error-decoder.html/?invariant=290&args%5B%5D=lockLeft)

### Steps to reproduce
React 16.3.0 开始，把 string ref 标记为 deprecated，目前 Table 组件中的 lock.jsx 组件仍存在这一废弃用法。

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/CQMLJu05nlUf.png)

这导致其在运行时出错。

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/3uyhv6EInTP2.png)

我按照 react 官方给出的建议自查了 react 重复 install 的情况，发现并无异常。

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/OZckxrdPtCGm.png)

我目前猜测可能是新版 react （16.12.0）存在对废弃 string ref 的隐性 bug ，请帮忙升级到推荐的 ref 用法。

**Comment by youluna** [comment]
建议先降级react版本，ref用法计划跟生命周期升级一起，在1.20版本去掉

**Comment by youluna** [comment]
1.20.0 已发布
