### ISSUE TITLE
[CascaderSelect]内部会对传进去的属性进行修改导致使用immer时报错

### ISSUE THREAD

**Issue by bojoyzhou** [alibaba-fusion/next#1558]
### Component 
CascaderSelect

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/tL1hH53ygv3o.png)
组件不应该改用户传入的值

**Comment by bojoyzhou** [comment]
Demo:
https://codepen.io/bojoyzhou/pen/oNXNYBy?editors=0010

**Comment by julytang** [comment]
Same error. Not fixed yet. Any plan?

**Comment by youluna** [comment]
为了防止用户产生br，增加了新参数immutable，用户开启后接受不可变的数据：详情可以参考文档
https://fusion.alibaba-inc.com/pc/component/cascader?themeid=2

`<Cascader immutable />`
