### ISSUE TITLE
[Checkbox]Form表单中设置size时Checkbox的标签和其他组件的标签样式不一致

### ISSUE THREAD

**Issue by baicoding** [alibaba-fusion/next#1568]
### Component 
Checkbox

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-template-7mnuj)

### Steps to reproduce
在Form组件中使用Size来控制尺寸时，复选框的字体很明显。
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/qIbbyAhCUZ7R.png)

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/f0QGQbvjYU9q.png)

**Comment by eternalsky** [comment]
一个是 label，一个是 content，感觉字体大小不一致也很正常，Form 的 size 主要是改变 Form 本身的大小，以及联动一些同样有 size 的组件，checkbox 没有 size 配置，因此几种 size 下表现一致。如希望有多种 checkbox size 的话，可以在不同size 加不同样式来实现。或者说这里更应该实现的可能是 checkbox 提供多种尺寸。
