### ISSUE TITLE
[Select]多选可清空场景下，脚本报错

### ISSUE THREAD

**Issue by sanwei-alibaba** [alibaba-fusion/next#1588]
### Component 
Select

### Reproduction link 
[https://codepen.io/sanwei-alibaba/pen/dyopbVx?editable=true&editors=0010](https://codepen.io/sanwei-alibaba/pen/dyopbVx?editable=true&editors=0010)

### Steps to reproduce
在Select组件中，多选可删除场景下，defaultValue非数组情况下，点击删除脚本报错

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/LlDt24FLJ9WB.png)

**Comment by bindoon** [comment]
都多选了，为啥不设为数组呢？
