### ISSUE TITLE
[Field]Dialog with Field

### ISSUE THREAD

**Issue by flyinhigh** [alibaba-fusion/next#1596]
### Component 
Field

### Steps to reproduce
when form add field in Dialog
can't input anything
https://riddle.alibaba-inc.com/riddles/5eb1e38d

**Comment by bindoon** [comment]
这种情况暂时无解，因为dialog是挂载在body 上，脱离了 class 的控制的，所以 this.setState 什么的做无法控制 rerender。

这种情况需要把 对 input 的校验包装成一个单独的 class 就可以了
