### ISSUE TITLE
[Nav] Nav 的 triggerType 写成 click 无法弹出下拉

### ISSUE THREAD

**Issue by fanybook** [alibaba-fusion/next#1603]
### Component 
Nav

### Steps to reproduce
环境：
"@alifd/next": "^1.x",

Nav 的 triggerType 写 click 无法弹出下拉（官网例子写的是 hover，在我这是能弹出下拉的，改成 click 后不行了，删掉 triggerType 同样，点击后无法弹出下拉）

重现代码：
仅仅是把官网的例子的 hover 改成了 click
```javascript
      <Nav className="basic-nav" direction="hoz" type="normal" header={header} footer={footer} defaultSelectedKeys={['home']} triggerType="click">
        <Item key="home">Home</Item>
        <SubNav label="Component" selectable>
          <Item key="next">Next</Item>
          <Item key="mext">Mext</Item>
        </SubNav>
        <Item key="document">Document</Item>
      </Nav>
```

### 原因分析
我 F12 看了一下，点击后完全没加 next-opened  next-open 之类的 class，而 hover (triggerType) 是加了的

**Comment by youluna** [comment]
原因是：hover时整个item都是可触发区域，click时只有箭头是可触发区域
具体为什么这么做我看一下
