### ISSUE TITLE
[Balloon]Balloon组件超出可视范围部分截断

### ISSUE THREAD

**Issue by catcatSama** [alibaba-fusion/next#1604]
### Component 
Balloon

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/dd125093](https://riddle.alibaba-inc.com/riddles/dd125093)

### Steps to reproduce
现象：
fusion版本从0.x升级到1.x之后，Balloon组件，当高度足够高，超出可视范围后，位置没有自动调整，出现部分截断。
![image](https://user-images.githubusercontent.com/5189853/75321939-ccb11d00-58ac-11ea-8a37-5faeccda9343.png)

复现方式：
依次点击test1, test2, test3会发现test3的Balloon显示不全。
原因定位：
老版本的Balloon超出可视范围会自动调整定位，不会出现top为负数的情况，所以不会出现部分截断，新版本的定位top会出现负值。
期望结果：
和老版本保持一致

**Comment by catcatSama** [comment]
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/QeBIOK8BqTkH.png)

**Comment by bindoon** [comment]
优先展示内容比较合理，比如antd demo 虽然会乱，但是能展示正常 https://riddle.alibaba-inc.com/riddles/d2d7e915

**Comment by youluna** [comment]
应该跟overlay的变动有关，1.16版本发生的变化
