### ISSUE TITLE
[DatePicker]DatePicker在同时监听onBlur/onFocus的时候切换月份失败

### ISSUE THREAD

**Issue by janryWang** [alibaba-fusion/next#1640]
### Component 
DatePicker

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/young-flower-s11m5)

**Comment by youluna** [comment]
@acejerry 需要再验证下1.20版本，生命周期改过了
