### ISSUE TITLE
[Button]Button 因为 user-select: none; 属性不能选中，特别是在设置 component='a' 后

### ISSUE THREAD

**Issue by xinglinb** [alibaba-fusion/next#1644]
### Component 
Button

### Steps to reproduce
问题：Button 因为 user-select: none; 属性不能选中，特别是在设置 component='a' | text 后
期望：Button 在 text 状态可以选中

**Comment by hongxingshi** [comment]
默认的 button 是不能选中文本的，不建议做这样的修改

但是如果确实需要文本能被选中，可以使用一个 span 标签做包裹：

```
<Button type="normal" text>
  <span style={{ userSelect: 'text' }}>Normal</span>
</Button>
```
