### ISSUE TITLE
[Table]table 在edge浏览器下，锁列发生错位

### ISSUE THREAD

**Issue by DophinL** [alibaba-fusion/next#1645]
### Component 
Table

### Reproduction link 
[无，可见图片](无，可见图片)

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/pd5sFhWFblfw.png)

**Comment by youluna** [comment]
mac 下的虚拟机ie11无异常

**Comment by youluna** [comment]
无法复现
