### ISSUE TITLE
[Modal]Will "Modal" be added into Fusion Design?

### ISSUE THREAD

**Issue by maoqxxmm** [alibaba-fusion/next#1661]
### Component 
Modal
### Feature Description
I believe that Modal Component is commonly used in apps. Why Fusion Design hasn't added it into components?

**Comment by youluna** [comment]
see [Dialog](https://fusion.design/component/basic/dialog)

**Comment by maoqxxmm** [comment]
> see [Dialog](https://fusion.design/component/basic/dialog)

Ok, Dialog can do Modal's job. Thanks for your advise!
