### ISSUE TITLE
[Tab]tabs excessMode bug

### ISSUE THREAD

**Issue by reganan** [alibaba-fusion/next#1674]
### Component 
Tab

### Reproduction link 
[https://codepen.io/reganan/pen/YzXYdLj?editors=0010](https://codepen.io/reganan/pen/YzXYdLj?editors=0010)

### Steps to reproduce
在tab组件里面，添加多个tab的情况下会出现尾部的更多按钮不消失，理论上应该在组件只有一个或者是少于更多的限制的时候 更多按钮应该消失

![image](https://user-images.githubusercontent.com/8327090/76318613-efb1e700-6318-11ea-9a8b-e786ef88b680.png)

**Comment by xuhong** [comment]
可以先通过关闭动画解决问题，animation={false}

**Comment by reganan** [comment]
> 可以先通过关闭动画解决问题，animation={false}

我用了另外一个方式，延时50m， 然后再调用一次，也可以干掉这个问题
