### ISSUE TITLE
[DatePicker]DatePicker增加快捷入口，设置预设值presetDate

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#1675]
### Component 
DatePicker
### Feature Description
https://codepen.io/aboutblank/pen/poJagOg?editors=0010

1.  1.x里增加presetDate API，RangePicker的ranges功能仍旧废弃，提示可以用presetDate替代。
2. presetDate（包括ranges）跟footerRender互斥，在有footerRender的情况下presetDate（包括ranges）不生效
2.  DatePicker / MonthPicker/ YearPicker / RangePicker （type为 month year date）都增加配置，支持快速设置预设范围

![image](https://user-images.githubusercontent.com/10049465/76379906-57ede080-638c-11ea-9921-e865072f9fa0.png)
![image](https://user-images.githubusercontent.com/10049465/76379931-6936ed00-638c-11ea-8d0f-a48abc1655b6.png)
![image](https://user-images.githubusercontent.com/10049465/76380052-c3d04900-638c-11ea-8295-4d3ba1425369.png)

**Comment by acejerry** [comment]
预设日期跟footerRender逻辑上会互斥吗，footerRender还有什么使用场景，如果逻辑上不互斥的话，需要改变一下交互和实现方式

**Comment by lakerswgq** [comment]
DatePicker2 支持 preset
