### ISSUE TITLE
[Table]Table分组表格设置Column宽度无效

### ISSUE THREAD

**Issue by sanwei-alibaba** [alibaba-fusion/next#1678]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/d620311e?mode=css](https://riddle.alibaba-inc.com/riddles/d620311e?mode=css)

### Steps to reproduce
Table分组表格（即使用GroupHeader）后设置Column宽度无效，不能实现左右滚动的效果

**Comment by youluna** [comment]
![image](https://user-images.githubusercontent.com/10049465/86914923-b026ca80-c153-11ea-9c3c-a9e8e9126dd7.png)
demo看起来是可以左右滚动的呀🤔

**Comment by youluna** [comment]
用户反馈已经没问题了
