### ISSUE TITLE
升级 webpack-dev-server 后无法启动 dev

### ISSUE THREAD

**Issue by geekrainy** [alibaba-fusion/next#168]
**Describe the bug**
a0076f69cde9779950f116f761a09984fe31e2d5 更新后无法启动 dev server。
> webpack-dev-server 3.x is only compatible with webpack 4.x, as the peer dependencies already warn you about. -@https://github.com/webpack/webpack-dev-server/issues/1334

**Version of the Next Components**
Check if the issue exists in the latest version.

**Screenshots**
<img width="800" alt="wx20190108-205210 2x" src="https://user-images.githubusercontent.com/7333266/50831875-4e7f7780-1387-11e9-84c5-8bbbb0fdcdf6.png">

**Comment by youluna** [comment]
我们升级下webpack4。你可以先把本地的package.json webpack-dev-server改为2.x版本来启动项目
