### ISSUE TITLE
[Input]输入组件input的trim属性不好用

### ISSUE THREAD

**Issue by sunguangjin** [alibaba-fusion/next#1683]
### Component 
Input
### Feature Description
需求：form表单输入框能输入空格，但是最后自动去除首尾空格。
设计：现有的trim属性是每次onChange的时候去除首尾空格，实际效果是根本输入不了空格（除非用户知道，手动移动光标到中间添加空格），trim属性应该是在失去焦点的时候去除首尾空格。

**Comment by bindoon** [comment]
遇到空格 trim 这个api确实鸡肋，目前想不到更好方法，建议自己直接处理
