### ISSUE TITLE
[Dialog]quick方式弹出对话框，对话框内的input组件无法输入

### ISSUE THREAD

**Issue by jerryyxu** [alibaba-fusion/next#1684]
### Component 
Dialog

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/adoring-mendeleev-vpigd)

**Comment by acejerry** [comment]
https://codesandbox.io/s/lucid-mestorf-1pu6b

定位到：quick模式，Dialog组件内render了另外一个根组件，而这个case中的涉及到从一个根组件修改另外一个根组件的状态，初步判断这种方式的修改并没法触发当前组件的更新。

**Comment by acejerry** [comment]
https://codesandbox.io/s/lively-http-cj4zz
临时的处理方式：将content中组件的状态封装在组件内
