### ISSUE TITLE
[TextArea] 在windows双击文字，多选了空白

### ISSUE THREAD

**Issue by cwtuan** [alibaba-fusion/next#1687]
### Component 
https://fusion.design/component/basic/input

### Steps to reproduce
TextArea文案，双击文字，多选了空白，用户要复制文案有点不方便。
windows 10 + chrome 80可以在官方demo复现。
mac没问题
![image](https://user-images.githubusercontent.com/3455798/76601071-25d2af00-6543-11ea-9019-be31aa053390.png)

**Comment by youluna** [comment]
这个应该是windows的默认行为，原生input里进行选择也会选中后面的空格
![image](https://user-images.githubusercontent.com/10049465/76929820-0c08e180-6920-11ea-8a61-b1054535f843.png)
