### ISSUE TITLE
官网文档貌似有错别字，我【么】遵循大图可压缩小

### ISSUE THREAD

**Issue by VicenLaw** [alibaba-fusion/next#1691]
### Reproduction link 
[https://fusion.design/design/doc/16](https://fusion.design/design/doc/16)

### Steps to reproduce
“但实际场景中，无法为各种屏幕做切图适配，我么遵循大图可压缩小“
应该为
“我【们】遵循大图可压缩小”

**Comment by youluna** [comment]
thanks & fixed 💐
