### ISSUE TITLE
[NumberPicker]NumberPicker 精度bug和数字输入问题

### ISSUE THREAD

**Issue by Tony7lee** [alibaba-fusion/next#1693]
### Component 
NumberPicker

### Steps to reproduce
1.设置精度的情况下，比如设置精度两位，一直输入 1111111111111111111111111111，会出现 1.11，属于bug
2.设置精度的情况下，比如设置精度两位，输入 0.0000000001，会出现科学计数法，不符合精度两位的要求，属于bug

**Comment by galogm** [comment]
close in #2244
