### ISSUE TITLE
[Icon]业务组件动态icon组件看不到

### ISSUE THREAD

**Issue by iamwin** [alibaba-fusion/next#1695]
### Component 
Icon

### Reproduction link 
[https://fusion.design/component/bizcomps/2](https://fusion.design/component/bizcomps/2)

### Steps to reproduce
业务组件动态icon组件页面显示“Cannot find "/build/index.html" in @icedesign/data-binder@0.1.8”

**Comment by youluna** [comment]
官网已修复
