### ISSUE TITLE
[DatePicker]DatePicker  的宽度开放设置

### ISSUE THREAD

**Issue by Zitian770** [alibaba-fusion/next#1709]
### Component 
DatePicker
### Feature Description
目前在默认配置的情况下，基线为 6px 会出现过大的情况。
屏幕快照 2020-03-24 下午4.39.39
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/MD6HrLU0e2DZ.png)

**Comment by jerryyxu** [comment]
见：https://github.com/alibaba-fusion/next/issues/1827
