### ISSUE TITLE
[VirtualList] Select useVirtual + showSearch 时 弹层的高度不正确

### ISSUE THREAD

**Issue by bojoyzhou** [alibaba-fusion/next#1722]
### Component 
Select

### Reproduction link 
[https://codepen.io/bojoyzhou/pen/wvaNvwe?editable=true&editors=0010](https://codepen.io/bojoyzhou/pen/wvaNvwe?editable=true&editors=0010)

### Steps to reproduce
输入70进行搜索，发现弹层的高度不正确

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/2SaIAP7kMyhR.png)

**Comment by bindoon** [comment]
计算的时候应该带上下间距的高度

**Comment by bindoon** [comment]
same with #2139
