### ISSUE TITLE
[Overlay]autoFit属性针对x/y两个方向生效

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#1724]
### Component 
Overlay
### Feature Description
autoFit目前只对x方向生效，对y方向没生效，期望改成两个方向都生效

https://fusion.alibaba-inc.com/component/basic/table#%E5%9B%BA%E5%AE%9A%E8%A1%A8%E5%A4%B4
![image](https://user-images.githubusercontent.com/10049465/77884859-744cb100-7298-11ea-9b70-fea5a3c53866.png)

**Comment by bindoon** [comment]
fixed in overlay 2.x
