### ISSUE TITLE
[Select]单选选择后也可以配置是否隐藏下拉框啊

### ISSUE THREAD

**Issue by fengmumu1** [alibaba-fusion/next#1733]
### Component 
Select
### Feature Description
hiddenSelected	选择后是否立即隐藏菜单 (mode=multiple/tag 模式生效)
这个我们单选会打开一个任务页，无权限会关闭这个任务页，但是这个选择框我们想一直开着。。。
单选为什么不能配置这个啊，你们不能歧视单选啊，说好的雨露均沾呢

**Comment by bindoon** [comment]
visible=true 会一直开着
