### ISSUE TITLE
[Select]select taginline mode will expand the parent container's width

### ISSUE THREAD

**Issue by Jeffery-Young** [alibaba-fusion/next#1734]
### Component 
Select

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/a2e09e38](https://riddle.alibaba-inc.com/riddles/a2e09e38)

### Steps to reproduce

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/Lm27fQQb64hC.png)

**Comment by youluna** [comment]
在Col组件上加个限制：
![image](https://user-images.githubusercontent.com/10049465/78032100-10f57880-7397-11ea-827b-b40cb7f55936.png)
