### ISSUE TITLE
【分页器】跳页器输入多位数后，输入框内只显示了一位

### ISSUE THREAD

**Issue by LumenHou** [alibaba-fusion/next#174]

**Comment by LumenHou** [comment]
![tb1sssia4nak1rjszftxxbc2vxa](https://user-images.githubusercontent.com/20264777/50951255-72f26580-14e7-11e9-9506-40dff58d808f.png)

**Comment by myronliu347** [comment]
这里是input的宽度不太对，目前demo上的宽度是合理的，请查找下是否被其他样式重置了这里的宽度.
