### ISSUE TITLE
[NumberPicker]NumberPicker设置值类型为string时可以回显，但是执行加减操作时会从零开始

### ISSUE THREAD

**Issue by orangeyyy** [alibaba-fusion/next#1741]
### Component 
NumberPicker

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/f58d25d4](https://riddle.alibaba-inc.com/riddles/f58d25d4)

**Comment by bindoon** [comment]
文档要求是 Number 类型，不要传字符串
