### ISSUE TITLE
[Nav]样式优先级受组件打包顺序影响汇总

### ISSUE THREAD

**Issue by veryStarters** [alibaba-fusion/next#1754]
### Component 
Nav

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/oaHLTVvA0v0o.png)

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/v2GzAMmcKQtU.png)

**Comment by veryStarters** [comment]
![image](https://user-images.githubusercontent.com/28616892/79709253-518c4600-82f4-11ea-907a-355fbd89d001.png)

**Comment by eternalsky** [comment]
按照正常的样式引入方式的话，不会存在此问题，如需继续跟踪，请提供复现 demo，并 reopen
