### ISSUE TITLE
Range 组件 UI 显示异常

### ISSUE THREAD

**Issue by simonguo** [alibaba-fusion/next#176]
![image](https://user-images.githubusercontent.com/1203827/50963483-cc6a8c80-1507-11e9-8de7-ee2300656acc.png)

**Comment by guanpu** [comment]
😢 没看出来，能加点具体的描述吗

**Comment by simonguo** [comment]
![image](https://user-images.githubusercontent.com/1203827/51300278-4fd73100-1a66-11e9-892f-8f9b967bab25.png)

**Comment by guanpu** [comment]
Fixed, close this.
