### ISSUE TITLE
[Box]  增加 api fullWidth fullHeight 

### ISSUE THREAD

**Issue by bindoon** [alibaba-fusion/next#1761]
### Component 
Box
### Feature Description
在业务开发中 `<Box style={{width: '100%'}} >` `<Box style={{height: '100%'}} >` `<Box style={{width: 200}} >`用法太多了，代码写起来太长

**Comment by youluna** [comment]
是不是增加width height的api更合适，例如
```
<Box width={ 1 / 2} height="80px" />
<Box width={ 1 / 3} height="80px" />
<Box width={1} height="80px" />
```

**Comment by bindoon** [comment]
pls use @alifd/layout
