### ISSUE TITLE
[DatePicker]日期范围选择组件可以通过双击形式选择同一个日期，但传出来的数据值一模一样

### ISSUE THREAD

**Issue by veryStarters** [alibaba-fusion/next#1766]
### Component 
DatePicker
### Feature Description
日期范围选择组件，点选第一个日期，选中了起始日；再次点击，会将当前日期填入结束日期，最终给出的日期区间是同一天的同一个时间戳。
如果允许选择同一天，至少应该给出的是同一个天的起始时间戳和结束时间戳。

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/2hejsyXqcpGG.png)

**Comment by acejerry** [comment]
https://riddle.alibaba-inc.com/riddles/34565d18

**Comment by jerryyxu** [comment]
如果 用户设置了showtime属性 则显示同一个天的起始时间戳和结束时间戳，否则还是显示同一天日期

**Comment by jerryyxu** [comment]
https://github.com/alibaba-fusion/next/pull/1853
