### ISSUE TITLE
（官方文档>设计页的示例） checkbox 无响应 或连点无响应

### ISSUE THREAD

**Issue by iyh** [alibaba-fusion/next#1768]
### Reproduction link 
[https://fusion.design/design/component/checkbox](https://fusion.design/design/component/checkbox)

### Steps to reproduce
设计分页的好多例子

https://fusion.design/design/component/checkbox
checkbox无响应 或连点无响应

https://fusion.design/design/component/tree 
tree的checkbox 连点无响应

所谓连点无响应是指，单击改变其值后 继续点击就没有响应了，只有移除焦点后再次单击才有响应。

Google Chrome 
版本 81.0.4044.113（正式版本） （64 位）
Microsoft Edge
版本 81.0.416.53 (官方内部版本) (64 位) 
on Windows 10 Pro 1909
上均复现
但https://fusion.design/component/basic/checkbox 的又是正常的 所以认为是文档上的示例代码错误 而不是组件本身的错误。

**Comment by youluna** [comment]
https://fusion.design/design/ 这个tab是为了让设计师看到组件的多种状态，方便配置的，所以在这个tab下固定了一部分属性，这个不是问题哈
