### ISSUE TITLE
[Upload]upload 组件需要支持 itemRender 属性

### ISSUE THREAD

**Issue by weepy3641** [alibaba-fusion/next#1778]
### Component 
Upload
### Feature Description
文件显示上需要加入 预览和下载功能，现在默认是个 a 标签无法满足需求，同时 extraRender 也不能满足需求，a标签的 target blank默认开页面的行为无法替换。

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/em8QatQfneqq.png)

**Comment by weepy3641** [comment]
![image](https://user-images.githubusercontent.com/3838676/79935080-99db6d80-8486-11ea-80d2-94f255674070.png)

**Comment by bindoon** [comment]
a标签的 target blank 可以在点击按钮的时候通过 `onClick={e=> {e.preventDefault()}}` 来解决

**Comment by bindoon** [comment]
will fixed in 1.21.0
