### ISSUE TITLE
[Input] 引用 Input 组件后 IE10 报错

### ISSUE THREAD

**Issue by randyou** [alibaba-fusion/next#1781]
### Component 
Input

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/trusting-maxwell-b8xrn)

### Steps to reproduce
1、yarn build 出生产环境代码
2、部署生产环境代码
3、使用 IE9 、IE10 访问页面
 控制台报错 “对象不支持“getDerivedStateFromProps”属性或方法“

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/Ld33LHb64WEb.png)

**Comment by bindoon** [comment]
fixed in 1.20.0
