### ISSUE TITLE
[Table]树形table的排序图标的位置问题

### ISSUE THREAD

**Issue by dyxweb** [alibaba-fusion/next#1785]
### Component 
Table
### Feature Description
当table使用tree形式并使用排序功能时，排序按钮会从原来的title后面的位置调整为title前面的位置。复现地址  https://riddle.alibaba-inc.com/riddles/6d973472

**Comment by youluna** [comment]
![image](https://user-images.githubusercontent.com/10049465/80074625-04220a00-857c-11ea-97d0-a0ed6e9ad2d8.png)
