### ISSUE TITLE
[Collapse]Collapse 的动画形式

### ISSUE THREAD

**Issue by kele5240** [alibaba-fusion/next#1786]
### Component 
Collapse
### Feature Description
1.gif
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/GXmq3jO8Desg.png)

如图，在Panel展开的时候，内容的宽度是有一个width的变化的。这样会导致内容换行，影响体验。

希望提供多种动画形式自行选择，比如不改变宽度仅想下展开等

**Comment by kele5240** [comment]
![1](https://user-images.githubusercontent.com/344451/80057551-6b7a9280-8559-11ea-917f-173ba8aca800.gif)

**Comment by youluna** [comment]
给个复现吧，没有dom结构很难看这个问题
