### ISSUE TITLE
[All]TS专项治理

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#1789]
可以把ts不对的地方截图贴到评论下，最好简单描述你遇到的场景，比如:

DatePicker的value可以是字符串，而ts报错了，ts上只接受moment对象 
```jsx
<DatePicker value="2020-04-03" />
```

**Comment by fengyfeng** [comment]
Form.Item包裹使用Switch组件时，ts缺少name定义
![image](https://user-images.githubusercontent.com/6700197/80217330-18483300-8672-11ea-8940-63a84f861a5c.png)

**Comment by youluna** [comment]
![image](https://user-images.githubusercontent.com/10049465/80443319-870ee000-8941-11ea-8408-2e1f577722d4.png)
