### ISSUE TITLE
[Input]Input.TextArea 无法使用 useRef

### ISSUE THREAD

**Issue by zhaofinger** [alibaba-fusion/next#1801]
### Component 
Input

### Steps to reproduce

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/5NVAuXkDDaTg.png)

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/ioh1LdSGem8l.png)

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/MbATgdzH75YM.png)

**Comment by bindoon** [comment]
same with #1843
