### ISSUE TITLE
[Select]select tag模式支持选中tag上的文案

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#1809]
### Component 
Select
#### 效果
![image](https://user-images.githubusercontent.com/10049465/80579451-a2aae100-8a3c-11ea-9404-2d8f15db1a7c.png)
#### 方案
新增API，API开启的模式下 tag的内容才能被复制

#### 原因
现在的Select的onFocus onBlur实际上用的是内部Input的 onFocus onBlur， 为了在Input上做了键盘输入的响应包括键盘上下箭选择内容。

如果直接全量做Tag内容可复制，需要焦点发生变化，相关事件的改动很大，可能产生非预期的问题。
1.x里要支持的话可以通过API支持下，在2.x里考虑重构逻辑

**Comment by bindoon** [comment]
选择复制 input 需要离开焦点

**Comment by bindoon** [comment]
和现有实现方式冲突，暂时无法处理
