### ISSUE TITLE
[DatePicker]DatePicker.RangePicker时间回填问题

### ISSUE THREAD

**Issue by zhangbenber** [alibaba-fusion/next#1825]
### Component 
DatePicker

### Reproduction link 
[https://codepen.io/zhangbenber/pen/WNQzoJz?editors=0010](https://codepen.io/zhangbenber/pen/WNQzoJz?editors=0010)

### Steps to reproduce
DatePicker.RangePicker组件，showTime=true时，如果是受控模式下，手动删掉时间输入框中的内容，再从列表中选择时刻的时候，这个时刻的值不会回填到输入框里面，如图：

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/XMAf27mkP3NA.png)

**Comment by jerryyxu** [comment]
https://github.com/alibaba-fusion/next/pull/1853
