### ISSUE TITLE
[Select]Select组件Option中value为空选项前面不能打钩

### ISSUE THREAD

**Issue by catcatSama** [alibaba-fusion/next#1826]
### Component 
Select

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/990c9da1](https://riddle.alibaba-inc.com/riddles/990c9da1)

### Steps to reproduce
描述：Select组件的option，当value为空时，选中状态下没有打钩
期望结果：选中状态下正常打钩
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/WQoN7yqVPrll.png)
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/6Q8zNhWvP50h.png)

**Comment by bindoon** [comment]
不建议用空字符串做选项
