### ISSUE TITLE
[Table]table合并单元格同时锁列，数据更新后table会显示错乱

### ISSUE THREAD

**Issue by BuggMaker** [alibaba-fusion/next#1837]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/45fe7b8e](https://riddle.alibaba-inc.com/riddles/45fe7b8e)

### Steps to reproduce
table合并单元格同时锁列，数据更新后table会显示错乱

**Comment by youluna** [comment]
并且本地开发环境有死循环

**Comment by youluna** [comment]
本issue 提到的问题 仍然存在 https://codesandbox.io/s/fusion-next-async-data-with-colspan-p29c9

**Comment by youluna** [comment]
1.20.6 已修复
