### ISSUE TITLE
[All]组件数据回传规范讨论

### ISSUE THREAD

**Issue by jerryyxu** [alibaba-fusion/next#1846]
Tree，TreeSelect等组件 用户选中item后 目前组件只会回传固定的一些字段 不会回传用户业务相关的字段 需要考虑保留用户原始数据 需要讨论规范：

![image](https://user-images.githubusercontent.com/8581684/82801161-73f31f80-9eaf-11ea-9038-08e6f01f35b4.png)

**Comment by jerryyxu** [comment]
TreeSelect等组件 用户选中item后 希望回传源数据项数据

**Comment by jerryyxu** [comment]
### AntD
没有返回源数据
![image](https://user-images.githubusercontent.com/8581684/81785273-aeb09b80-9530-11ea-821d-3c17fc8838a9.png)
![image](https://user-images.githubusercontent.com/8581684/81785536-00592600-9531-11ea-9d77-a81aacc50ac1.png)

### element-ui
返回选中数据项 不改变源数据
![image](https://user-images.githubusercontent.com/8581684/81784700-d6533400-952f-11ea-841c-3c8d044c1c3c.png)
![image](https://user-images.githubusercontent.com/8581684/81784793-f71b8980-952f-11ea-8e94-7471f524d104.png)
![image](https://user-images.githubusercontent.com/8581684/81788265-d9045800-9534-11ea-9e76-9d581c6ea825.png)

### iView
返回选中数据项 改变源数据
![image](https://user-images.githubusercontent.com/8581684/81786419-30ed8f80-9532-11ea-8b64-e52f324b7fca.png)
![image](https://user-images.githubusercontent.com/8581684/81787242-53cc7380-9533-11ea-8eb5-a8c52da5662f.png)

**Comment by youluna** [comment]
我建议onChange等抛出的数据格式如下：
```
{
    label: string;
    value: string;
    key: string;   // Fusion 增加
    pos: string;  // Fusion 增加
    rawData: any;  // Fusion增加，透传用户传入的数据
}
```
其中把常用的值，例如key pos label value等放到最外层（也与1.x模式保持一致），同时增加rawData这个关键词，它的值为用户传入的原始数据，方便用户获取数据。

唯一需要确认的是，rawData 这个名字是否可以作为规范落下来，其他组件例如table等也使用这个参数。

**Comment by eternalsky** [comment]
目前基本已经形成结论，通过 useDetailValue 来支持简单和复杂两种数据格式的传递。后续将分组件来逐一对这一结论进行实施。
