### ISSUE TITLE
[Upload]Upload.Card 的 isPreview=true 时没有展示成只读状态

### ISSUE THREAD

**Issue by zhangbenber** [alibaba-fusion/next#1847]
### Component 
Upload

### Reproduction link 
[https://codepen.io/zhangbenber/pen/VwvBbzq](https://codepen.io/zhangbenber/pen/VwvBbzq)

### Steps to reproduce
Upload.Card 的 isPreview=true 时没有展示成只读状态，如图
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/ovZDgitsplDJ.png)

**Comment by youluna** [comment]
fixed in 1.20.6
