### ISSUE TITLE
Why fusion supports two usages

### ISSUE THREAD

**Issue by anyexinglu** [alibaba-fusion/next#186]
Thank you for this wonderful work!

Recently, I'm frustrated why fusion supports two usages: 
1. children or options  [select example](https://fusion.design/component/select)
![image](https://user-images.githubusercontent.com/8243326/51113849-7b77d280-183e-11e9-8663-94566d0a1efa.png)

Personally, `options`  is enough.

2. defaultValue or value [date-picker example](https://fusion.design/component/date-picker)
![image](https://user-images.githubusercontent.com/8243326/51114208-926af480-183f-11e9-9d90-0937af8cdf4e.png)

Since defaultValue always works with a form, so it seems that`value`  is enough for these basic ui components.

**Comment by bindoon** [comment]
- defaultValue: only work in the first render
- value: for you to control the component value 

you can see the detail in https://reactjs.org/docs/forms.html#controlled-components

**Comment by youluna** [comment]
1. children v.s. props
 - children for simple use, and it also makes information **more intuitive to a human reader(developer)**
```jsx
<Select>
    <Select.Option value="female">female</Select.Option>
    <Select.Option value="male">male</Select.Option>
    <Select.Option value="secrecy">secrecy</Select.Option>
</Select>;
```
 - props for a **large amount of data sources**, maybe you get the data from a remote server with a considerable length 
```jsx
<Select dataSource={dataSource}/>
```

2. `defaultValue` v.s. `value`
This involves a concept of React [controlled-vs-uncontrolled-components](https://reactjs.org/docs/glossary.html#controlled-vs-uncontrolled-components)
- When you use value, the component is controlled and you have full control over the components.It won't change value unless you set the value explicitly.
- When you use defaultValue only, the components is an uncontrolled component. You don't have to care about the data flow inside component.

`defaultValue` for basic usage and `value` for advanced usage, [see usage demo](https://codesandbox.io/s/5xnjkoq9mp)

**Comment by anyexinglu** [comment]
@bindoon @youluna 

Thank you for your patient replies, to my shame, I didn't make the question clear:

1. children v.s. props
```
<Select>
    <Select.Option value="female">female</Select.Option>
    <Select.Option value="male">male</Select.Option>
    <Select.Option value="secrecy">secrecy</Select.Option>
</Select>
**// Attention: Tab.Item has title**
<Tab>
    <Tab.Item title="Home">Home content</Tab.Item>
    <Tab.Item title="Documentation">Doc content</Tab.Item>
    <Tab.Item title="Help">Help Content</Tab.Item>
</Tab>
```
vs
```
<Select
  dataSource={[
    { label: 'female', value: 'female' },
    { label: 'male', value: 'male' },
    { label: 'secrecy', value: 'secrecy' }
  ]}
/>
**// Tab's dataSource seems same as Select's (with label & value, without title)**
<Tab
  dataSource={[
    { label: 'Home', value: 'Home content' },
    { label: 'Documentation', value: 'Doc content' },
    { label: 'Help', value: 'Help Content' }
  ]}
/>
```
The second one seems easier to remember for developers, and more testable for fusion authors.

Obviously, the first one also has some supporter, whatever, a component library can teach users how to write code, `supports two usages` may increase the maintenance and communication cost, I thought it's not necessary.

2. defaultValue v.s. value
I've modified the [DatePicker example](https://codesandbox.io/s/5yrpok88np)

> `defaultValue` isn't a good design by react?  —— by my leader...


![image](https://user-images.githubusercontent.com/8243326/51227408-27303800-198f-11e9-9e4f-4749e86b198a.png)
