### ISSUE TITLE
[Nav]rollup构建时，treeshaking把`Nav.Item = Item`这样的增强语句删掉了

### ISSUE THREAD

**Issue by csr632** [alibaba-fusion/next#1862]
### Component 
Nav

所有具有这种结构的index.js的组件都会出现这个问题：
```
import Menu from '../menu';
import Nav from './nav';
import Item from './item';
import Group from './group';
import SubNav from './sub-nav';
import PopupItem from './popup-item';

Nav.Item = Item;
Nav.Group = Group;
Nav.SubNav = SubNav;
Nav.PopupItem = PopupItem;
Nav.Divider = Menu.Divider;

export default Nav;  // 直接export其他模块的值，会造成本模块的内容全部被treeshaking，因为`sideEffects`字段指定这个模块“没有副作用”
```
比如`Collapse`组件也有这个问题。

其他大部分组件没有暴露这个问题，是因为其他组件的index.js都是这样的：
```
// ...
export default ConfigProvider.config(Message, {  // export的值是在本模块计算的，因此本模块不会被treeshake
    componentName: 'Message'
});
```

### Reproduction link 
[https://github.com/csr632/rollup-issue/tree/fusion](https://github.com/csr632/rollup-issue/tree/fusion)

### Steps to reproduce
使用rollup构建next，`console.log(Nav.Item)`的结果为undefined。
如果手动到`node_modules/@alifd/next/package.json`删掉sideEffects字段，则恢复正常。

如果使用webpack构建，则始终正常。[webpack与rollup的treeshaking逻辑略有差别](https://github.com/rollup/rollup/issues/3565)。上面的复现repo中有用webpack构建的示例。

**Comment by csr632** [comment]
https://github.com/rollup/rollup/issues/3565
已经提了一个issue给rollup，不过大概率会被打回，因为像这样的模块严格来说是有副作用的：
```
import Menu from "./menu";
import Item from "./item";
Menu.Item = Item;  // 修改了其他模块的对象，而不是自己新建一个对象
export default Menu;
```
fusion的解决办法：
1. sideEffects里面把esm/nav/index.js声明为有副作用，
2. 或者在esm/nav/index.js里面创建好nav对象，而不是修改其他模块的对象
3. 或者通过export default (null, Menu) 的方式，阻止rollup将它当做re-export来tree-shaing

**Comment by youluna** [comment]
rollup的作者已经修复了这个问题，https://github.com/rollup/rollup/issues/3565#issuecomment-631023700
treeshaking是最早来自webpack的功能，目前的导出方式可以在webpack里正常工作，next里不再枚举改引用方式了。
