### ISSUE TITLE
[Search]search用field初始化之后，一旦有输入立刻失焦

### ISSUE THREAD

**Issue by fang-bin** [alibaba-fusion/next#187]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Search

### Environment
macos10.13.6 谷歌浏览器71

### Reproduction link
[http://gitlab.alibaba-inc.com/car-center/workorder-list](http://gitlab.alibaba-inc.com/car-center/workorder-list)

### Steps to reproduce
页面中有两个tab，不尽兴切换tab操作之前，输入正常，切换tab之后，search内容一旦有输入，立刻失焦

**Comment by youluna** [comment]
Can not reach the reproduction link
