### ISSUE TITLE
[Table]Table的maxBodyHeight疑问

### ISSUE THREAD

**Issue by baicoding** [alibaba-fusion/next#1878]
### Component 
Table

### Reproduction link 
[https://codepen.io/baicoding/pen/RwWvmJp](https://codepen.io/baicoding/pen/RwWvmJp)

### Steps to reproduce
1、Table主键能否直接加个Pagination属性，在web应用中大部分情况下Table是需要分页的
2、当Table的高度是随着浏览器高度变化时，如何设置maxBodyHeight，才能使Table充满空余区域

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/o4zIWLUT6Jt8.png)

**Comment by youluna** [comment]
1. Table里不准备加pagination相关的属性哈，可以用 ahooks 帮助管理状态 https://ahooks.js.org/zh-CN/hooks/table/use-fusion-table/
2. maxBodyheight支持string，你可以传入calc(100vh - xxpx) 减的值需要你合理计算，例如：https://codepen.io/aboutblank/pen/KKVRwGB
