### ISSUE TITLE
[Drawer]Drawer如何渲染在当前 dom 里或者指定的dom里

### ISSUE THREAD

**Issue by baicoding** [alibaba-fusion/next#1879]
### Component 
Drawer
### Feature Description
类似antd组件的Drawer组件有个getContainer，可以指定渲染的dom，是否可以支持一下？

**Comment by youluna** [comment]
试一下 `popupContainer()` 或者 `container()`，文档参考`Overlay.Popup`组件

**Comment by baicoding** [comment]
> 试一下 `popupContainer()` 或者 `container()`，文档参考`Overlay.Popup`组件
不起作用，设置了以后next-overlay-wrapper已经在指定的div中了，但是还是显示在最外面的body上
[
https://codepen.io/baicoding/pen/GRpLoyL?editors=0110](url)

**Comment by youluna** [comment]
Drawer采用的是fixed布局，定位是页面级的抽屉弹层，目前不支持作为容器的抽屉
