### ISSUE TITLE
[TreeSelect]TreeSelect checkboxDisabled 逻辑有问题

### ISSUE THREAD

**Issue by tao1991123** [alibaba-fusion/next#1881]
### Component 
TreeSelect

### Steps to reproduce
同一份组件代码 在不同数据源下显示不同。
```
<TreeSelect
        dataSource={ds}
        multiple={true}
        treeCheckable={true}
        autoWidth={false}
        style={{ width: 300 }}
        defaultValue={["12", "13", "14"]}
></TreeSelect>
```

#### 显示正常
12、13、14 三个key被自动聚合成 11 予以显示
```
const ds = [
  {
    label: "11",
    value: "11",
    children: [
      {
        label: "12",
        value: "12",
      },
      {
        label: "13",
        value: "13",
      },
      {
        label: "14",
        value: "14",
      },
    ],
  },]

```
![](https://img.alicdn.com/tfs/TB1W3c0HkT2gK0jSZFkXXcIQFXa-706-436.png)

#### 异常数据源代码1
```
const ds = [
  {
    label: "11",
    value: "11",
    children: [
      {
        label: "12",
        value: "12",
        checkboxDisabled: true,
      },
      {
        label: "13",
        value: "13",
        checkboxDisabled: true,
      },
      {
        label: "14",
        value: "14",
        checkboxDisabled: true,
      },
    ],
  },
];
```
问题一:   12、13、14 未聚合成11
![](https://img.alicdn.com/tfs/TB1Lel_cOcKOu4jSZKbXXc19XXa-800-370.png)

问题二: 
第一次点击  11 所在的checkbox， 12、13、14三个值的checkbox被取消 但是输入框中的tag显示数量错误
![](https://img.alicdn.com/tfs/TB17HIVHkP2gK0jSZPxXXacQpXa-670-420.png)
借着再点击一次 11 所在的checkbox
![](https://img.alicdn.com/tfs/TB17Xg0HkT2gK0jSZPcXXcKkpXa-626-376.png)

#### 异常数据源代码2

```
const ds = [
  {
    label: "11",
    value: "11",
    children: [
      {
        label: "12",
        value: "12",
      },
      {
        label: "13",
        value: "13",
        checkboxDisabled: true,
      },
      {
        label: "14",
        value: "14",
        checkboxDisabled: true,
      },
    ],
  },
];
```

问题: 
第一次点击 12所在的checkbox, 12被取消 显示  13 14 两个disable的的tag。这时候显示是正常的。
![](https://img.alicdn.com/tfs/TB1w_I1HeH2gK0jSZJnXXaT1FXa-444-364.png)

再一次点击 12所在的checkbox，12被选中  但是 13 14两个原本处于选中状态的checkbox被取消
![](https://img.alicdn.com/tfs/TB1dg7ZHkL0gK0jSZFxXXXWHVXa-662-370.png)

**Comment by tao1991123** [comment]
版本 1.22.6

**Comment by eternalsky** [comment]
1.26.x 已不存在此问题
