### ISSUE TITLE
[Affix]配置主题发布时卡住

### ISSUE THREAD

**Issue by gzc605984770** [alibaba-fusion/next#1895]
### Component 
Affix

### Reproduction link 
[https://fusion.design/17173/setting/publish?themeid=14023](https://fusion.design/17173/setting/publish?themeid=14023)

### Steps to reproduce
一直处于发布中的状态，卡在这里两天了

**Comment by mark-ck** [comment]
已中断任务，请重试
![image](https://user-images.githubusercontent.com/44559440/83171222-5d1b2a00-a148-11ea-9613-bd3fff191274.png)
