### ISSUE TITLE
[Upload]Upload文档补充跨域问题解法

### ISSUE THREAD

**Issue by tao1991123** [alibaba-fusion/next#1902]
### Component 
Upload
### Feature Description
这是使用者在 知乎回复的内容  期望能添加到文档中
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/6BqNd4yDC1bA.png)

**Comment by tao1991123** [comment]
或者有没有必要去掉这个 X-Requested-With 

现在应该都没有人用这个请求头了

**Comment by bindoon** [comment]
@tao1991123  下个版本去掉
