### ISSUE TITLE
怎么在react15里强行引入fusion并运行

### ISSUE THREAD

**Issue by qiaomu666** [alibaba-fusion/next#1909]
只考虑编译运行，不考虑效率问题，不考虑项目升级，每个组件都能初始化那种
，目前引入有大量组件不兼容导致不能初始化

**Comment by bindoon** [comment]
有点难，弹层类组件用了 React 16 才有的api，所以一定会挂

如果只用简单的 Button之类的你通过按需加载剥离代码应该没啥问题

**Comment by qiaomu666** [comment]
> 有点难，弹层类组件用了 React 16 才有的api，所以一定会挂
> 
> 如果只用简单的 Button之类的你通过按需加载剥离代码应该没啥问题

尝试在依赖加入fusion库自己的依赖react16，组件返回好像也不会正常

**Comment by youluna** [comment]
一个页面只能有一个react版本，只要这个版本是16就可以。

因为用到了react16的新api，同时动画处理库react-transition-group也要求react版本是大于16的，建议升级到react16
