### ISSUE TITLE
[Shell]文档不全

### ISSUE THREAD

**Issue by fengmumu1** [alibaba-fusion/next#1911]
### Component 
Shell
### Feature Description
Shell.Branding 
Shell.Action
Shell.MultiTask
Shell.ToolDockItem
Shell.AppBar
这几个都没有对应的文档

**Comment by youluna** [comment]
这几个组件用法比较简单，功能单一，没有多的API，目前都只有children传递

**Comment by fengmumu1** [comment]
> 这几个组件用法比较简单，功能单一，没有多的API，目前都只有children传递

建议还是说一下用途，用法可以不举例，总不能让用户一个一个实验一边然后再用吧，嗯我先把这个问题 close掉吧

**Comment by kchjxxgh** [comment]
是啊，竟然还没有用途说明。。。
