### ISSUE TITLE
[Transfer]组件 左侧面板切换数据源 右侧面板计数错误

### ISSUE THREAD

**Issue by coder-hu** [alibaba-fusion/next#1931]
### Component 
Transfer

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/5a82dbdd](https://riddle.alibaba-inc.com/riddles/5a82dbdd)

### Steps to reproduce
复现步骤：选择data穿梭到右侧->切换数据源->选择data2穿梭到右侧 此时右侧有两条数据 计数为1
期望：计数为2
实际：计数为1

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/EWYFOwRFx3Hz.png)

**Comment by kreja** [comment]
![image](https://user-images.githubusercontent.com/7478555/84729060-53594980-afc5-11ea-940b-6fb98fee634a.png)

最后再增加一步操作，全选后只有一条选中，前面的 Data 没有被选中。

**Comment by mark-ck** [comment]
1. 考虑在使用层面解决这个问题，按照 Transfer 的设计逻辑来看，切换 DataSource 左右面板的展示应该要按照新数据源重新渲染，这里由于是用户自定义面板因此出现了原数据源的数据也展示出来了；
2. 如果 Transfer 组件要解决这个问题需要将下标是数量和勾选控制对外开放，这将会增加组件的使用复杂度，作为备选方案

**Comment by mark-ck** [comment]
已和用户沟通，从使用侧避免这种情况出现
