### ISSUE TITLE
[Form]IE9下Form.Item与现代浏览器样式表现不一致

### ISSUE THREAD

**Issue by Mosby192** [alibaba-fusion/next#1946]
### Component 
Form

### Reproduction link 
[https://fusion.design/pc/component/basic/form](https://fusion.design/pc/component/basic/form)

### Steps to reproduce
分别在IE9和谷歌浏览器中打开https://fusion.design/pc/component/basic/form中的第一个Demo，样式表现不一致

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/khShI3AUxIOg.png)

**Comment by bindoon** [comment]
除了字体没看出来哪里不一致

**Comment by Mosby192** [comment]
截图中两个浏览器左边边缘是对齐的，但是从label中能明显看到IE9下(底部那个浏览器)比谷歌(上面那个浏览器)宽度更宽。

**Comment by bindoon** [comment]
ie9 要求是 UI 大致布局正常就行，不再纠结ie9了
