### ISSUE TITLE
[Upload]Upload    listType="image"  上传的文件点击默认操作可自定义

### ISSUE THREAD

**Issue by Suixinlei** [alibaba-fusion/next#1948]
### Component 
Upload
### Feature Description
目前在 listType="image" 情况下，上传的文件，默认操作是跳转新链接下载，希望此动作可以自定义

**Comment by Suixinlei** [comment]
用于配合右侧操作入口自定义，可实现默认点击操作为“预览” 或 “当前页面弹窗下载” 等功能

**Comment by bindoon** [comment]
fixed in #1941

会在 @alifd/next@1.21.0 里实现，通过 actionRender 自定义操作按钮

**Comment by bindoon** [comment]
same with #1778 #910
