### ISSUE TITLE
[Upload]ie10里面拖拽上传的文件被覆盖

### ISSUE THREAD

**Issue by magao1991** [alibaba-fusion/next#195]
Upload里面结合Field进行拖拽上传时，由于onDragOver触发会导致componentWillReceiveProps会不断执行，从而默认value值会覆盖上传的文件value列表，导致上传数据无法展示

**Comment by youluna** [comment]
@tao1991123 any progress?

**Comment by tao1991123** [comment]
未复现成功 暂时关闭
