### ISSUE TITLE
[DatePicker]时间格式为YYYY-MM的日期组件返回时间戳毫秒位没有置0

### ISSUE THREAD

**Issue by qijian-beep** [alibaba-fusion/next#1952]
### Component 
DatePicker

### Steps to reproduce
比如返回的应该是1577808000000，但是返回的是1577808000345
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/wEp3zwJmtJt3.png)

**Comment by lakerswgq** [comment]
目前已修复
