### ISSUE TITLE
[Upload] ie10 1.8.x版本下 input的onChange事件二次执行

### ISSUE THREAD

**Issue by magao1991** [alibaba-fusion/next#196]
Upload里面触发input的选择框是由其他标签的click事件触发input的原生click事件产生的，由于想要达到可以选择相同的文件多次上传，所在input的click事件中他们重置了input的value值为null，这样会导致input的onChange事件二次执行，从而使文件列表数据进行叠加展示，数据异常

**Comment by youluna** [comment]
any progress? @tao1991123

**Comment by tao1991123** [comment]
目前没有解决方案
