### ISSUE TITLE
[CascaderSelect]CascaderSelect 如何选择value 为 "" 的情况

### ISSUE THREAD

**Issue by JeromeYangtao** [alibaba-fusion/next#1961]
### Component 
CascaderSelect

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/802431d8](https://riddle.alibaba-inc.com/riddles/802431d8)

### Steps to reproduce
CascaderSelect 如何选择value 为 "" 的情况，复现Riddle，选择 【不限】
https://riddle.alibaba-inc.com/riddles/802431d8

**Comment by jerryyxu** [comment]
目前组件库一致的处理逻辑都是不允许value为空的情况，建议自定义如‘null’等字符串来代表具有特殊的值
