### ISSUE TITLE
[CascaderSelect]CascaderSelect listStyle 设置 maxWidth 不会自动伸缩，和width等效

### ISSUE THREAD

**Issue by JeromeYangtao** [alibaba-fusion/next#1962]
### Component 
CascaderSelect

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/802431d8](https://riddle.alibaba-inc.com/riddles/802431d8)

### Steps to reproduce
CascaderSelect listStyle 设置 maxWidth 不会自适应，和width等效。

**Comment by eternalsky** [comment]
最新版已修复（1.27.x）
