### ISSUE TITLE
[Button]按钮是否可以增加一个a标签的按钮

### ISSUE THREAD

**Issue by fengmumu1** [alibaba-fusion/next#1974]
### Component 
Button
### Feature Description
页面上经常有需要跳转到其他地方或者本站内的其他地址，设计一般都是直接放button的样式，为了访问性，往往需要用a标签来做，然后就要人工写样式，是否button增加一个a标签的子类，样式和交互和 button一样，但是核心是一个 a 标签

**Comment by hongxingshi** [comment]
https://fusion.design/pc/component/basic/button#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%87%E7%AD%BE%E7%B1%BB%E5%9E%8B

`component` 设置成 `a` 应该能满足需求

**Comment by fengmumu1** [comment]
> https://fusion.design/pc/component/basic/button#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%87%E7%AD%BE%E7%B1%BB%E5%9E%8B
> 
> `component` 设置成 `a` 应该能满足需求

666 不好意思 文档没有看仔细
