### ISSUE TITLE
[Table]Table 的 rowSelection API 设计疑问

### ISSUE THREAD

**Issue by Suixinlei** [alibaba-fusion/next#1976]
### Component 
Table

### Steps to reproduce
 onSelect 的 selected 为 true 或 false，record 都为当前行
onSelectAll 的 selected 为 false 时，records 为空，为 true 时，则会返回全部行（不论是否已被选择）

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/Spy4oQdMVfqK.png)

这个 APi 问题导致目前 Table 无法做跨页选择，因为没法反选全部

**Comment by youluna** [comment]
其实行为是一致的，onSelectAll的最后一个参数，跟onSelect的最后一个参数，都是表示，发生变化后，当前Table选中了哪些Key。

onSelect跟onSelectAll相比，多了一个参数，也就是倒数第二个参数，这个参数的含义是「哪个元素发生了变化」，这个只有onSelect有。
