### ISSUE TITLE
[Table]table行展开渲染内嵌的table不能展示完整的table样式

### ISSUE THREAD

**Issue by lystrive** [alibaba-fusion/next#1990]
### Component 
Table

### Reproduction link 
[https://codepen.io/lyStrive/pen/KKVBLOr?editable=true&editors=0010%3Dhttps%3A%2F%2Ffusion.alibaba-inc.com%2Ffeedback](https://codepen.io/lyStrive/pen/KKVBLOr?editable=true&editors=0010%3Dhttps%3A%2F%2Ffusion.alibaba-inc.com%2Ffeedback)

**Comment by youluna** [comment]
关联 https://github.com/alibaba-fusion/next/issues/2053
