### ISSUE TITLE
[Dialog] ts定义文件不全

### ISSUE THREAD

**Issue by cwtuan** [alibaba-fusion/next#1996]
### Component 
Dialog

### Steps to reproduce
![image](https://user-images.githubusercontent.com/3455798/87619932-e49c1700-c74f-11ea-8843-a98876e15337.png)

定义文件不全：@alife/next/lib/dialog/index.d.ts
![image](https://user-images.githubusercontent.com/3455798/87619986-01d0e580-c750-11ea-8842-c2e3753e2655.png)

**Comment by youluna** [comment]
@richardo2016 帮忙看下呢（可能已经解决了也可能没有orz）

**Comment by richardo2016** [comment]
> @richardo2016 帮忙看下呢（可能已经解决了也可能没有orz）

看起来是老版本 fusion-next 的类型问题，最新版本已经修了
