### ISSUE TITLE
[ConfigProvider]ConfigProvider.getContext()依赖于全局状态，结果难以预知

### ISSUE THREAD

**Issue by csr632** [alibaba-fusion/next#2005]
### Component 
ConfigProvider

Dialog.confirm这种命令式挂载的组件，[使用ConfigProvider.getContext()来获得config](https://github.com/alibaba-fusion/next/blob/7d458d41a7f8fd58b54ba9983a94f815ea7d704c/src/dialog/show.jsx#L215)，但是这个方法读取全局状态，依赖执行顺序，结果难以预知。在页面上有多份fusion的时候则更加难以预料。希望Dialog.confirm能用更好的方式来获得context。

ConfigProvider.getContext()获取的是第一个被挂载的config（接近组件树根部的config），不满足我们的需求，希望提供方式能够定制Dialog.confirm弹层的config。

在我们的场景里面，Dialog.confirm没有拿到我们想要的config，有文案丢失。

### 建议提供新的HOC

withDialog(WrappedComponent)

给WrappedComponent提供一个props：dialog，里面包含命令式api。HOC可以感知到当前的config context，从而弹层内能够获得正确的config。

全局的命令式API很难获取到正确的context，但是如果命令式API由组件提供，挂载在组件树上，就能够获得正确的context。

**Comment by youluna** [comment]
Dialog.show()这种用法获取的locale值，是存在于fusion文件中的，也就是说页面上有多份fusion文件，其实是可以取不同文件的locale值的。

如下的用法才是解决函数式调用中locale值不符合预期的根本解决方案：
```jsx
Dialog.show({
    content: 'dialog content',
    locale: {
        ok: 'ok',
        cancle: 'cancle'
    }
})
```
当然从用户角度期望更简单的用法，我能想到的是自定义函数:
```jsx
const DialogShow = (props) => {
    return Dialog.show({
        locale: {
            ok: 'ok',
            cancle: 'cancle'
        },
        ...props
    })
}
```
这个能解决你的问题吗

**Comment by csr632** [comment]
问题复现和问题解法的示例：

http://gitlab.alibaba-inc.com/sirui.csr/fusion-parcel/tree/with-dialog-demo
