### ISSUE TITLE
[Select]清空、展开全部按钮位置冲突

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#2020]
### Component 
Select

### Steps to reproduce
用户去点击下拉的时候，势必会移动到下拉框处，同时hover到「下拉框」时，全部清除的叉叉遮挡下拉箭头，很容易出现误操作。

建议叉叉可左移，避免遮挡下拉箭头；
![image](https://user-images.githubusercontent.com/10049465/88162529-0a3f8980-cc44-11ea-8936-0f4a7e92700f.png)

**Comment by eternalsky** [comment]
恩确实有误点击的可能，但目前各大组件库在这里的交互基本都是统一成这个风格，暂时这里保持不变吧。
