### ISSUE TITLE
[Icon]拓展图标引用无效问题

### ISSUE THREAD

**Issue by Crayon-ShinChan** [alibaba-fusion/next#2046]
### Component 
Icon

### Steps to reproduce
在 fusion 上上传了拓展图标并且发布了 npm，但是引用新的 npm 之后，icejs 中引用无效，请问是我的用法有问题吗？代码如下
```javascript
<Icon type="share"/>
```
![image](https://user-images.githubusercontent.com/38809606/88634642-3a29d980-d0e9-11ea-8dbc-4ad9797f6ee5.png)

**Comment by youluna** [comment]
`npm update`
