### ISSUE TITLE
[Transfer]无法使用树形数据在 Transfer 组件中做很好的功能扩展

### ISSUE THREAD

**Issue by matrixqc** [alibaba-fusion/next#2056]
### Component 
Transfer
### Feature Description
业务需求左侧右侧穿梭框都有可能是树状数据，点击中间的按钮之后出现下拉菜单，可以选择将数据添加到哪个树节点之中。
目前onChange的逻辑在 [`setValueState`](https://github.com/alibaba-fusion/next/blob/8737a08eac2259993448b5087c644996756f1ad3/src/transfer/view/transfer.jsx#L447) 中
```
        if (Object.keys(st).length) {
            this.setState(st, callback);
        } else {
            // eslint-disable-next-line callback-return
            callback();
        }
```
用户无法在数据修改状态之前挂载逻辑进行拦截或者是扩展新的逻辑。

**Comment by mark-ck** [comment]
@matrixqc 新增了 onSelect 回调，应该能解决你的需求
https://github.com/alibaba-fusion/next/pull/2667
