### ISSUE TITLE
[Select]Select组件highlightKey定位

### ISSUE THREAD

**Issue by Evanhahaha** [alibaba-fusion/next#2063]
### Component 
Select
### Feature Description
希望Select能增加一个借口，配置highlightKey选项的定位是alignToTop还是alignToBottom. 现在是根据列表的滚动位置来进行align，感觉不太实用

**Comment by bindoon** [comment]
暂时参考demo，https://riddle.alibaba-inc.com/riddles/7817e120

**Comment by bindoon** [comment]
根据当前高亮选项自动滚动过去是比较合理的。
