### ISSUE TITLE
[Step]step组件在shape发生改变的时候没有重新计算高度，导致样式bug(搭建场景)

### ISSUE THREAD

**Issue by lynsun** [alibaba-fusion/next#2064]
### Component 
Step

### Reproduction link 
[https://work.aone.alibaba-inc.com/issue/29636610](https://work.aone.alibaba-inc.com/issue/29636610)

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/kv9wPu5PgZ1c.png)

**Comment by youluna** [comment]
验证不是Fusion问题，是使用问题，样式覆盖了
