### ISSUE TITLE
[Input]Input  type=password 组件在Chrome Develop Tool 中显示明文 value

### ISSUE THREAD

**Issue by flyinhigh** [alibaba-fusion/next#2067]
### Component 
Input
### Feature Description
在 Chrome 调试工具中能看到 password 控件的 value 值，希望能隐藏一下，或者用 * 代替。

![](https://img.alicdn.com/tfs/TB18dD9cCslXu8jSZFuXXXg7FXa-2466-640.png)

**Comment by bindoon** [comment]
浏览器的原生能力暂时无法支持
