### ISSUE TITLE
[Tree]为不可变数据添加了key

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#2070]
### Component 
Tree
### Steps to reproduce
用户反馈1.19.x正常 1.20.23异常
![image](https://user-images.githubusercontent.com/10049465/89390340-23aefe00-d739-11ea-990a-051a6be3bcb4.png)
![image](https://user-images.githubusercontent.com/10049465/89390354-29a4df00-d739-11ea-9949-de74bb1d038c.png)

![image](https://user-images.githubusercontent.com/10049465/89393372-4e9b5100-d73d-11ea-9df8-42b40e00108d.png)

**Comment by bindoon** [comment]
用户传入的数据源是 immutable 导致的，为了不导致现有问题的 BR，判断下数据源是否是 immutable， 如果是则clone，否则保持现状。

todo: 2.x 中直接把clone一份数据源，不要修改用户传入的数据
