### ISSUE TITLE
[Select]select组件白屏

### ISSUE THREAD

**Issue by 185172970** [alibaba-fusion/next#2071]
### Component 
Select

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/ae0f8c3d](https://riddle.alibaba-inc.com/riddles/ae0f8c3d)

### Steps to reproduce
select组件传入object作为val直接白屏，建议加强健壮性

**Comment by bindoon** [comment]
你这个demo 里面，对象里面至少也得有 value、label 吧
