### ISSUE TITLE
[Table]vscode里某些组件没有属性提示

### ISSUE THREAD

**Issue by lxzy-yun** [alibaba-fusion/next#2082]
### Component 
Table
### Feature Description

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/WOGeFe49UBOB.png)

**Comment by youluna** [comment]
安装下ts插件，这块ts描述一直有 https://github.com/alibaba-fusion/next/blob/44afe0d26f222a0807a90b35be06982c59bbe2ef/types/table/index.d.ts#L149
