### ISSUE TITLE
[Form]手动修改必填项后，如何提交的时候再重新校验 

### ISSUE THREAD

**Issue by Ljiajia** [alibaba-fusion/next#2087]
### Component 
Form
### Feature Description
默认必填项，若不填写内容，点击保存的时候会提示内容为必填项，input框会变红，通过手动设置为非必填项后，label前面的红色星号去掉了，当前项目为非必填项，但是点击提交的时候，还是显示之前的校验信息，如何再提交的时候重新校验？

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/8CUemQr0da9k.png)

**Comment by Ljiajia** [comment]
如果默认是非必填，直接去提交，不会有错误提示，设置为必填项后，再去提交，会展示错误提示

为什么默认状态可以改变为错误状态，错误状态却不能改变为其他状态？

**Comment by bindoon** [comment]
麻烦贴下代码怎么写的
