### ISSUE TITLE
图标删除不了

### ISSUE THREAD

**Issue by celementj** [alibaba-fusion/next#2093]
### Reproduction link 
[https://fusion.design/50512/design/style/icon?themeid=15686](https://fusion.design/50512/design/style/icon?themeid=15686)

### Steps to reproduce
图标删除之后提交，图标还在，反复几次都删除失败

**Comment by jerryyxu** [comment]
sass不区分 "-" 、"_"

**Comment by youluna** [comment]
sass不区分 `-` 、`_`，所以如果icon名字类似，比如`arrow-right` `arrow_right`，实际上他们是一样的
