### ISSUE TITLE
[Field]filed why not get switch value

### ISSUE THREAD

**Issue by SJ941127** [alibaba-fusion/next#2095]
### Component 
Field

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/9Z6djLoxBq3D.png)
filed的方法getValues无法获取到navtar的值，这个是为什么呢？

**Comment by bindoon** [comment]
init 和 onChange 冲突了，

init('navbar', {props:{onChange}}) 这种用法
