### ISSUE TITLE
[Loading]1.13.x版本loading组件

### ISSUE THREAD

**Issue by xiehaisheng** [alibaba-fusion/next#2098]
### Component 
Loading

### Reproduction link 
[https://fusion-demo.alibaba-inc.com/demos/next/loading#loading-1](https://fusion-demo.alibaba-inc.com/demos/next/loading#loading-1)

### Steps to reproduce
全屏的loading组件，loading转动时会出现跳动位移问题

**Comment by youluna** [comment]
升级版本
