### ISSUE TITLE
[Table]TreeTable 组件需求

### ISSUE THREAD

**Issue by leanhunter** [alibaba-fusion/next#2099]
### Component 
Table
### Feature Description

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/RcQ42o9G7HqC.png)

**Comment by bindoon** [comment]
@youluna 翊晨要支持 Tree 的连线，看看好不好实现

**Comment by youluna** [comment]
实现成本很高，而且兼容性会比较差，比如对于不等高的行来说很不好实现，建议hold
