### ISSUE TITLE
[Table] Divider line not align when virtual-scroll enable / 表格虚拟滚动开启时候,中间部分与两边滚动不同步

### ISSUE THREAD

**Issue by tao1991123** [alibaba-fusion/next#210]
**Describe the bug**
Table: Divider line not align when virtual-scroll enable
表格虚拟滚动，开始滚动时中间快，锁列慢

**Version of the Next Components**
1.11.10
**Reproduce URL**
https://fusion.design/component/table

**Expected behavior**
https://rsuitejs.com/components/table#%E8%99%9A%E6%8B%9F%E5%8C%96%E7%9A%84%E5%A4%A7%E8%A1%A8%E6%A0%BC

**Screenshots**

![](https://user-images.githubusercontent.com/1203827/51439692-df940e00-1cf8-11e9-97b1-b1f0ba387fe6.png)

**Comment by youluna** [comment]
滚动开始后，中间滚动快，两边慢，但最终表格单元是对齐的。不影响功能使用，可作为体验优化

**Comment by youluna** [comment]
虚拟滚动下，锁列两边通过scrollTop保持对齐，改成translateY

**Comment by youluna** [comment]
1.21.x 通过Table.StickyLock解决
