### ISSUE TITLE
[Upload]Upload 支持上传完成后自定义渲染

### ISSUE THREAD

**Issue by leanhunter** [alibaba-fusion/next#2100]
### Component 
Upload
### Feature Description
Upload  card 模式支持组件上传成功以后支持自定义渲染样式

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/qF9MnR35vZFS.png)

**Comment by bindoon** [comment]
![image](https://user-images.githubusercontent.com/5189853/91676194-98772b80-eb71-11ea-9bb3-bec28bd8cca8.png)
从默认的这种UI 到需求里面这种，变化很大。是否能有一种比较通用的render方法呢？
