### ISSUE TITLE
[Progress]Fusion Design 的进度条 能否添加颜色渐变的效果

### ISSUE THREAD

**Issue by rabbit-tian** [alibaba-fusion/next#2103]
### Component 
Progress
### Feature Description
Fusion Design 的进度条 能否添加颜色渐变的效果，目前就算传入的值是 `linear-gradient(to right,red,blue)`，但是渲染用的 background-color, 无法渲染出渐变的颜色

[](
![image](https://user-images.githubusercontent.com/26690191/90477157-7aff9600-e15d-11ea-99e7-f0b3c047841e.png)
)

**Comment by bindoon** [comment]
已经支持可配
