### ISSUE TITLE
[Form]希望form预览态增加配置

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#2107]
### Component 
Form
### Feature Description
优化分类：主题配置

关联组件：Form

功能类型：能力升级

标题：站点中form的readonly态样式配置能力

描述：在form的readonly态，行高/字号/字重/间距这些能作为配置项开放出来，因为不同bu要求也会不一样，可以自助配置出定制化的样式

**Comment by bindoon** [comment]
目前预览态用的不是 readonly 模式，是自己定义的渲染。不明白要开放哪些配置项！
