### ISSUE TITLE
[CascaderSelect]级联选择不能连续搜索问题

### ISSUE THREAD

**Issue by haolic** [alibaba-fusion/next#2112]
### Component 
CascaderSelect

### Reproduction link 
[https://fusion.alibaba-inc.com/pc/component/basic/cascader-select#%E6%90%9C%E7%B4%A2](https://fusion.alibaba-inc.com/pc/component/basic/cascader-select#%E6%90%9C%E7%B4%A2)

### Steps to reproduce
重现链接为官网地址，可以复现。
复现步骤为：
级联选择多选状态，输入关键字搜索后选择一项，无法继续输入了，只能先点击其他空白地方关闭下拉弹层再点击搜索框继续输入。
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/P2WWQx9HtqK2.png)

**Comment by jerryyxu** [comment]
![Kapture 2020-10-23 at 14 20 48](https://user-images.githubusercontent.com/8581684/96963306-0705b380-153b-11eb-9217-136224dc0286.gif)

**Comment by lakerswgq** [comment]
已经修复
