### ISSUE TITLE
[Menu]Menu 组件的onItemClick事件报 Warning

### ISSUE THREAD

**Issue by matrixqc** [alibaba-fusion/next#2114]
### Component 
Menu

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/floral-framework-bfhqw?file=/src/App.js:408-438)

### Steps to reproduce
console Warning
Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `altKey` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.

**Comment by youluna** [comment]
fixed
