### ISSUE TITLE
[Select]The inheritance design pattern, such as 'class Select extends Base' may bring problems in the future?

### ISSUE THREAD

**Issue by anyexinglu** [alibaba-fusion/next#212]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Select

### Feature Description

In the source code, I found that:
![image](https://user-images.githubusercontent.com/8243326/51454240-b6b65c00-1d7e-11e9-98d4-3101fe26a7df.png)

But this is not suggested by react officially?

FYI: 
["Composition vs Inheritance"](https://reactjs.org/docs/composition-vs-inheritance.html#___gatsby)
[Here is a demo shows a "inheritance problem"](https://codesandbox.io/s/7zo3vm1x81), value works wrong

**Comment by bindoon** [comment]
wrong use of  extends.  if you want to use  `Super.render` here, render should be a static function.

![image](https://user-images.githubusercontent.com/5189853/51454375-4bb95500-1d7f-11e9-8c79-05fa4f249f9d.png)

**Comment by anyexinglu** [comment]
Thanks

Excuse me, how about this issue: https://github.com/alibaba-fusion/next/issues/186 ?
