### ISSUE TITLE
[Transfer]穿梭框筛选数据后，“移动全部”移动的是全量数据

### ISSUE THREAD

**Issue by csr632** [alibaba-fusion/next#2123]
### Component 
Transfer

用户期待点击“移动全部”时，移动的是筛选后的数据

### Steps to reproduce

https://fusion.alibaba-inc.com/pc/component/basic/transfer#%E7%AE%80%E5%8D%95%E6%A8%A1%E5%BC%8F
将这个demo加上筛选功能以后，即可复现

**Comment by mark-ck** [comment]
deprecated with #1066
