### ISSUE TITLE
[Box]sketch插件中 组件显示异常，没法使用

### ISSUE THREAD

**Issue by kinoen** [alibaba-fusion/next#2126]
### Component 
Box

### Steps to reproduce
组件无法使用，拖拽到画板时，提示在加载中Bitmap.png
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/dPJDuEPCU1JP.png)

**Comment by youluna** [comment]
这两个组件都是纯功能性组件，没有skecth版本需要去掉的
