### ISSUE TITLE
[NumberPicker]When I use precision for number-picker, it doesn't work for some cases

### ISSUE THREAD

**Issue by dhlolo** [alibaba-fusion/next#2128]
### Component 
NumberPicker

### Steps to reproduce
When I use "precision={3}", it does not work for these cases
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/i3keQSwBaWfq.png)

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/2XFHmgQ8htdA.png)

**Comment by galogm** [comment]
fixed in #2102
