### ISSUE TITLE
[Dialog]Dialog如何禁止快捷键

### ISSUE THREAD

**Issue by threescales** [alibaba-fusion/next#2159]
### Component 
Dialog
### Feature Description
现在我在dialog里用了一个Editor组件，使用tab进行缩进时，会被dialog监听，导致editor的缩进失效

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/EtmW9QEd400s.png)

**Comment by jerryyxu** [comment]
重复issue： https://github.com/alibaba-fusion/next/issues/1986
