### ISSUE TITLE
[Table]Table】首列树形节点开启、关闭事件参数化建议

### ISSUE THREAD

**Issue by MarshalShan** [alibaba-fusion/next#2168]
### Component 
Table
### Feature Description
目前开启Table的tree模式, 接收的数据格式中包含children则渲染成tree table，当前树形展开的事件触发是固定在首列的，是否可以增加一个 props 由组件使用者来控制在Table的哪一列上面来开启和关闭树形。

**Comment by youluna** [comment]
有功能需求截图吗？什么情况下会要求 展开、收起 tree的触发节点不在首列？
