### ISSUE TITLE
[Box]容器组件使用反馈

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#2169]
### Component 
Box
### Feature Description
在使用Box ResponsiveGrid等组件中遇到的问题、让组件变得更好用的建议。（新增api的时候最好讲下原因，你是在什么场景下需要这个API的）

**Comment by libin-code** [comment]
Component

Box

Feature Description

建议 direction 属性 propType 中增加 `space-evenly` 属性，目前属性使用正常，但控制台会报一个 warning 提示类型错误。

该属性值浏览器兼容性等同于 `space-around`。用于均匀排列每个元素且使每个元素之间的间隔相等，文档地址：https://developer.mozilla.org/zh-CN/docs/Web/CSS/justify-content

**Comment by bindoon** [comment]
欢迎使用 @alifd/layout
