### ISSUE TITLE
Select组件在预览模式下，value=null时报异常；Demo见https://riddle.alibaba-inc.com/riddles/4d04f167 项目即将上线，麻烦看下如何快些解决（版本更新到lastest也未解决）

### ISSUE THREAD

**Issue by youka2012** [alibaba-fusion/next#2174]
![image](https://user-images.githubusercontent.com/13498596/93105652-eb102600-f6e1-11ea-8197-76c3d87786a7.png)
![image](https://user-images.githubusercontent.com/13498596/93105733-ffecb980-f6e1-11ea-8fac-23a57bf5eb02.png)
![image](https://user-images.githubusercontent.com/13498596/93105748-04b16d80-f6e2-11ea-8311-5d5f2555c09c.png)

**Comment by youluna** [comment]
已解决
