### ISSUE TITLE
[DatePicker]Datapicker选择同一天会清空结束时间

### ISSUE THREAD

**Issue by sunning-o** [alibaba-fusion/next#2183]
### Component 
DatePicker
### Feature Description
在使用RangePicker的时候 如果选择同一天会先清空EndTime 再次选择的时候才会选中这样例如：用户先选择了2020-9-16 19:18  还想选9-16号 那之前选择的时间就会被清空 并且默认的结束时间也会被清空 我们做的需求跨度是不能超过24小时的 所以选择同一天的可能性还是很高的 想要AntD的Datapicker组件 可以直接选中同一天的 交互效果

**Comment by jerryyxu** [comment]
![Kapture 2020-10-23 at 16 46 56](https://user-images.githubusercontent.com/8581684/96977298-76859e00-154f-11eb-9329-5504cf06cb62.gif)

**Comment by bindoon** [comment]
fixed in DatePicker2
