### ISSUE TITLE
[TimePicker]是否支持替换 Moment.js 

### ISSUE THREAD

**Issue by imsobear** [alibaba-fusion/next#2185]
### Component 
TimePicker
### Feature Description
Moment.js 进入维护阶段，不再增加新功能，并且本身也存在很多问题，fusion 组件是否有替换 Moment.js 的方案？

**Comment by Mavericker-1996** [comment]
+1

**Comment by youluna** [comment]
要做，在规划中。跨端组件也要求支持moment.js可替换，支持day.js（meet的推荐库）

**Comment by bindoon** [comment]
fixed in TimePicker2
