### ISSUE TITLE
[Select]能否支持已经选中项可以再次选中，目前已选就没法再选中了只能点击旁边关闭

### ISSUE THREAD

**Issue by fengmumu1** [alibaba-fusion/next#2186]
### Component 
Select
### Feature Description
期望：增加一个配置可以多次点击同一个选择，当然可以增加一个阀值，做个截流
需求背景：
遇到的场景多是，结果根据选择值发生变化，第一次搜索完成后，用户做了操作觉得不满意。然后想重新用刚才的条件发起搜索或者操作（搜索场景下有搜索的按钮，但是有时候选择的动作是触发搜索的开关），这时候他就没有办法点击现在正在选择的值，只能清空选择或者选择其他的然后再选回来，体验并不是很好

**Comment by bindoon** [comment]
这描述太绕了，没看懂是什么个流程，最好上截图说明

**Comment by fengmumu1** [comment]
就是可以对同一个选项选择多次，现在选择完成后，再选择这个就咩有办法选择了
