### ISSUE TITLE
[Input]Input.Password icon反了 

### ISSUE THREAD

**Issue by cqcmdwym** [alibaba-fusion/next#2193]
### Component 
Input

### Reproduction link 
[Input.Password](Input.Password)

### Steps to reproduce
应该是 .next-icon-eye:before { content: $icon-content-eye-close; }
.next-icon-eye-close:before { content: $icon-content-eye; }

**Comment by bindoon** [comment]
经过内部讨论，觉得两种方式都能体现

目前是表示期望的点击效果，你期望的是目前的状态。

暂时不改变
