### ISSUE TITLE
[Field]field 自定义错误setError,不会被validate捕获和触发

### ISSUE THREAD

**Issue by shifengdiy** [alibaba-fusion/next#2195]
### Component 
Field

### Steps to reproduce
    handleRichTextOverflow = (formKey) => {
      // 富文本输入超出限制
      this.field.setError('product_desc', '字数超出限制');
    }

    onSubmit = () => {
      const errors = this.field.getErrors();
      console.log(errors, '--');
      this.field.validate((error, value) => {
        // error 的值为null，没有错误信息
        if (!error) {
          this.props.onOk && this.props.onOk(value);
        }
      });
    }

当使用field.setError()设置一个自定义错误之后，调用validate校验方法，错误并不出现在回调参数error中，并且会清除这个错误状态
 除非手动调用 this.field.getErrors()，才有这个错误信息

**Comment by bindoon** [comment]
这个是正常逻辑，触发校验就是要根据校验规则重新计算的。

eg: 一上来带着服务端的错误提示，在前端展示错误提示。但是期望前端在提交的时候再次前端校验，根据实际输入情况重新校验。

那么你的场景是什么？

**Comment by shifengdiy** [comment]
感谢答复，首先对于提出的eg，我认为服务端的错误和校验的错误是平等对待，在validate的时候，错误信息应该出现在回调error中

我的场景是一个受控的富文本组件，需要对长度限制，所以我在onChange中计算长度，超出限制之后setError，错误信息在ui上显示，但是在之后的validate方法中，这个error却不存在
