### ISSUE TITLE
[NumberPicker]NumberPicker小数部分除第一位外，无法输入0

### ISSUE THREAD

**Issue by veryStarters** [alibaba-fusion/next#2201]
### Component 
NumberPicker

### Reproduction link 
[https://codepen.io/pen/?&editable=true&editors=0010=https%3A%2F%2Fmc-fusion.alibaba-inc.com%2Fdemos%2Fcomp_groups%2F%40alife%2Fnext%401.20.28%2Fnumber-picker%3Ftheme%3D%40alife%2Ftheme-97%401.12.3%26bgColor%3D%2523ffffff](https://codepen.io/pen/?&editable=true&editors=0010=https%3A%2F%2Fmc-fusion.alibaba-inc.com%2Fdemos%2Fcomp_groups%2F%40alife%2Fnext%401.20.28%2Fnumber-picker%3Ftheme%3D%40alife%2Ftheme-97%401.12.3%26bgColor%3D%2523ffffff)

### Steps to reproduce
另外如果第一位小数输入0，可不受限制输入N位0

**Comment by galogm** [comment]
fixed in #2055
