### ISSUE TITLE
[Dialog]Dialog.alert和confirm的标题图标能否支持自定义

### ISSUE THREAD

**Issue by sxei** [alibaba-fusion/next#2202]
### Component 
Dialog
### Feature Description
Dialog.alert和confirm的标题图标能否支持自定义？真的是太丑了，又没法换掉，每次只能用Dialog.show去自己实现一个最基本的alert框。

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/k1nY9aIgqIwG.png)

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/x1DK97Qnpbor.png)

**Comment by jerryyxu** [comment]
可以通过messageProps属性的iconType字段设置
![image](https://user-images.githubusercontent.com/8581684/93999966-0efdf680-fdc9-11ea-8a12-a06a1eded6bd.png)
![image](https://user-images.githubusercontent.com/8581684/94000044-2ccb5b80-fdc9-11ea-85eb-2ef2d37c9596.png)

**Comment by sxei** [comment]
对Next的UI以及各种默认配置真的是无力……
