### ISSUE TITLE
[Select]The defaultValue property is ineffective in Select Component if changing it after component consturcting

### ISSUE THREAD

**Issue by Empireo** [alibaba-fusion/next#2204]
### Component 
Select

### Reproduction link 
[https://codepen.io/empireo/pen/wvGRmER](https://codepen.io/empireo/pen/wvGRmER)

**Comment by youluna** [comment]
defaultValue只在第一次渲染的时候生效，可以通过先卸载、再载入的方式实现你的诉求

![image](https://user-images.githubusercontent.com/10049465/93979042-698a5900-fdaf-11ea-9799-0d15ddbb7018.png)
