### ISSUE TITLE
[VirtualList]官方DEMO#  设置初始位置 ,将滚动条拉到最下面后，进入无限加载中

### ISSUE THREAD

**Issue by agoni1212** [alibaba-fusion/next#2210]
### Component 
VirtualList

### Reproduction link 
[https://fusion.design/pc/component/basic/virtual-list?themeid=2](https://fusion.design/pc/component/basic/virtual-list?themeid=2)

### Steps to reproduce
 设置初始位置这个DEMO，将滚动条一直拼命拉到最下面，就会出现无限加载

**Comment by YunMeng99** [comment]
官网未复现 先关闭处理 如需继续跟进重新开启
