### ISSUE TITLE
[NumberPicker]数字输入框支持是否打开科学计数法转化

### ISSUE THREAD

**Issue by ssbabysong** [alibaba-fusion/next#2212]
### Component 
NumberPicker
### Feature Description
希望数字输入框能增加一个参数配置是否转化为科学计数法，现在输入0.000000000012会自动转化为1.2e-11，不利于再次编辑
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/u6ieUJOJNQNu.png)

**Comment by galogm** [comment]
NumberPicker不支持科学计数法，会展示是非预期行为，已修复 #2244
