### ISSUE TITLE
[Table]table组件虚拟滚动数据问题

### ISSUE THREAD

**Issue by cpaiyueyue** [alibaba-fusion/next#2217]
### Component 
Table

### Steps to reproduce
使用网站上的静态数据格式可以，但是使用动态数据后虚拟滚动失效，
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/FOCGDwNbRgWb.png)

**Comment by youluna** [comment]
无法复现，请提供demo

https://codepen.io/aboutblank/pen/wvWzxYK

**Comment by eternalsky** [comment]
新版本（1.27）已无此问题
