### ISSUE TITLE
[Select]Safari下Select组件选中元素后，有黑色阴影

### ISSUE THREAD

**Issue by wangxiaojuan** [alibaba-fusion/next#2228]
### Component 
Select

### Steps to reproduce

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/hEIT9uYdktSb.png)

**Comment by bindoon** [comment]
liner-gradient 在safari 下面和 Chrome 表现不一致导致的

**Comment by bindoon** [comment]
比较难修复，总有点问题。解了亮色主题，暗色主题就会有问题。
暂时找不到通用的方法。
