### ISSUE TITLE
[demo]帮助文档中关于在 create-react-app 中使用按需加载的示例代码已经失效

### ISSUE THREAD

**Issue by Terryand** [alibaba-fusion/next#223]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.11.11

### Environment
由于 react-app-rewired 的更新，导致 babel-plugin-import 的引入方式发生变化 

### Reproduction link
[https://github.com/timarney/react-app-rewired](https://github.com/timarney/react-app-rewired)

### Steps to reproduce
建议参考 ant-design 组件库更新 https://ant.design/docs/react/use-with-create-react-app-cn

**Comment by youluna** [comment]
Thank you and fixed https://github.com/alibaba-fusion/examples/tree/master/basic-demo

**Comment by 2012shenghua** [comment]
我的项目还是使用 create-react-app的1.x的版本，想接入的话怎么办呢

**Comment by youluna** [comment]
@2012shenghua 可以参考1.x版本的demo https://github.com/alibaba-fusion/examples/tree/b2fa4a73ed527fac3506ac18aded76ff80405f7b/basic-demo

**Comment by 2012shenghua** [comment]
> @2012shenghua 可以参考1.x版本的demo https://github.com/alibaba-fusion/examples/tree/b2fa4a73ed527fac3506ac18aded76ff80405f7b/basic-demo

我参考了案例，用了还是不管用，项目里之前用了antd，现在加入fusion就失效了吗

**Comment by 2012shenghua** [comment]
现在只能全局引入css，但是这样有点污染，和antd的一些样式冲突了

**Comment by youluna** [comment]
Fusion next的样式前缀都是`next-` 理论上不会有冲突的，有可能冲突的地方是reset样式，你可以通过引入不同的文件去除reset样式
```
// with reset
import '@alifd/next/index.scss';
// without reset
import '@alifd/next/index-noreset.scss';
```
