### ISSUE TITLE
[Balloon]Balloon弹出增加一个限制规则

### ISSUE THREAD

**Issue by fengmumu1** [alibaba-fusion/next#2234]
### Component 
Balloon
### Feature Description
背景：比如我们有一个删除提示，用户鼠标放在操作按钮上，就会告诉用户这个操作可能会删除xx个数据，如果数据数量是 0的话，说明这个操作没有危险就不需要给提示，
需求：有一个开关，这个开关决定是否按照visible来决定显示还是隐藏（这样就可以使用visible 和组件自带的触发方式灵活处理了），貌似传  undefined ，visible也还是会当作false生效。。。

**Comment by youluna** [comment]
从描述看来不需要Balloon新增任何功能，提供个思路做参考：
Balloon 组件上添加判断
```jsx
render() {
  const props= {};
  // 非危险操作，不需要提示
  if (!needTip) {
    props.visible = false;
  }
  return <Balloon {...props} />
}
```
