### ISSUE TITLE
[Table]组件卸载时，未清空columns，导致展示异常

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#2235]
### Component 
Table 

1.21+
### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-columns-rfbzj?file=/src/index.js)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/10049465/95755336-e043b380-0cd6-11eb-9882-bc0324d7b14f.png)

**Comment by eternalsky** [comment]
目前已无此问题
