### ISSUE TITLE
[Balloon]Balloon组件hover展示再移开鼠标后页面会滚动

### ISSUE THREAD

**Issue by andyforever** [alibaba-fusion/next#2237]
### Component 
Balloon
### Feature Description

在Table组件内部使用，如果页面比较长出现滚动条的时候，hover到某一行再移开，页面会滚动

**Comment by youluna** [comment]
文字描述的太抽象了，需要提供截图或者demo辅助说明

**Comment by youluna** [comment]
经排查是tab组件的聚焦问题，关注 https://github.com/alibaba-fusion/next/issues/2259
