### ISSUE TITLE
[CascaderSelect]级联组件datasource异步获取，多选且只能选叶子节点时，新增选项会重复老的

### ISSUE THREAD

**Issue by ritawr** [alibaba-fusion/next#2251]
### Component 
CascaderSelect

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/93565c73](https://riddle.alibaba-inc.com/riddles/93565c73)

### Steps to reproduce
级联组件datasource异步获取，多选且只能选叶子节点时，新增选项会重复老的

**Comment by shifengdiy** [comment]
遇到了同样问题，请问有解决吗

**Comment by suprise** [comment]
一年过去了，还没解决吗？

**Comment by YunMeng99** [comment]
demo未发现这个问题 先关闭处理 如需继续跟进重新开启
