### ISSUE TITLE
业务组件同步不上物料中心，本地文件没问题

### ISSUE THREAD

**Issue by fengxs269** [alibaba-fusion/next#2253]
### Reproduction link 
[https://fusion.alibaba-inc.com/imd/biz/3333](https://fusion.alibaba-inc.com/imd/biz/3333)

### Steps to reproduce
http://gitlab.alibaba-inc.com/iampm/import-material-center/tree/develop  components下的ImcQueryFormTable同步不上物料中心

**Comment by mark-ck** [comment]
![image](https://user-images.githubusercontent.com/44559440/96830554-326e9c80-146e-11eb-8e1e-ce5ebad2f287.png)
看起来已经同步上去了
