### ISSUE TITLE
设计页面，文档编辑，内容会被截掉看不全

### ISSUE THREAD

**Issue by zhangfeishui** [alibaba-fusion/next#2255]
### Reproduction link 
[https://fusion.design/16399/design/style/font?themeid=16575&type=doc](https://fusion.design/16399/design/style/font?themeid=16575&type=doc)

### Steps to reproduce
编辑状态可以写很多
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/QHMiHcNQ9C7J.png)

但是阅览状态可视高度受限会被裁掉内容

**Comment by zhangfeishui** [comment]
![Uploading image.png…]()

**Comment by galogm** [comment]
已修复发布
