### ISSUE TITLE
[Balloon]小三角的阴影建议去掉

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#2257]
### Component 
Balloon

### Steps to reproduce
![image](https://user-images.githubusercontent.com/10049465/96426783-42993880-1230-11eb-8acb-0c4cb8ba0711.png)
![image](https://user-images.githubusercontent.com/10049465/96426933-81c78980-1230-11eb-961f-a18140b3821f.png)

**Comment by zuoqi705** [comment]
when ready?
