### ISSUE TITLE
[Overlay/Balloon/Tooltips] 回到聚焦问题

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#2259]
### Component 
Tab

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/f61d6e40?mode=jsx](https://riddle.alibaba-inc.com/riddles/f61d6e40?mode=jsx)

### Steps to reproduce

1. 滚动到最下面
2. hover到“序号”上
3. 移开鼠标，使弹层消失
4. 发现滚动条滚动到了最上面

可以看出是由这个 pr https://github.com/alibaba-fusion/next/commit/5feb398 引起的

**Comment by bindoon** [comment]
改造计划：
- Overlay 增加 api 支持是否回到焦点
- Balloon/ToolTip 针对 hover 类关闭回到焦点功能

**Comment by bindoon** [comment]
解法：不要在 hover 态的时候开启 autoFocus。 
功能上：保持现状，组件不能因为 hover 在按钮上面，就 focus 到 按钮上面
