### ISSUE TITLE
[Loading]  demo 里面有不正确的 api

### ISSUE THREAD

**Issue by bindoon** [alibaba-fusion/next#2260]
### Component 
Loading

### Steps to reproduce
![image](https://user-images.githubusercontent.com/5189853/96531000-43c37780-12bb-11eb-8bac-0d6f76aa7b32.png)

**Comment by galogm** [comment]
Loading没有特殊处理safeNode

**Comment by galogm** [comment]
Loading并有处理safeNode的机制，safeNode也是不存在的api

**Comment by galogm** [comment]
Loading并没有处理safeNode的机制，safeNode也是不存在的api

**Comment by galogm** [comment]
fixed in #2465
