### ISSUE TITLE
[Table]table resize lock column 

### ISSUE THREAD

**Issue by dorado-lmz** [alibaba-fusion/next#2265]
### Component 
Table

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-table-bug-zxk5z?file=/src/table.js)

### Steps to reproduce
 table组件在浏览器resize时无法自动 show/hide lock column的问题
column "Time"  has attribute `lock="right"`, but "Time" column couldn't trigger 'lock' mode when resizes browser window

**Comment by eternalsky** [comment]
目前可以使用 StickyLock 来解决此问题
