### ISSUE TITLE
fusion 组件支持 SSR 

### ISSUE THREAD

**Issue by luhc228** [alibaba-fusion/next#2269]
现在 Overlay 组件里面的代码会有用到 document，使用 SSR 时会有报错。

**Comment by youluna** [comment]
Fusion是支持ssr的，哪里报错了可以贴一下代码，定点看

**Comment by luhc228** [comment]
Overlay 组件：

![image](https://user-images.githubusercontent.com/44047106/101234954-f8e0b080-36fe-11eb-8b64-26bb00ae860d.png)
