### ISSUE TITLE
[Dialog]react 17,  在dialog上点击无法收起像<select><Dropdown>组件的下拉框.

### ISSUE THREAD

**Issue by j787701730** [alibaba-fusion/next#2273]
### Component 
Dialog

### Steps to reproduce
<Dialog>
<Select id="basic-demo" onChange={onChange} onBlur={onBlur} onToggleHighlightItem={onToggleHighlightItem} defaultValue="jack" aria-label="name is" showSearch hasClear>
    <Option value="jack">Jack</Option>
    <Option value="frank">Frank</Option>
    <Option value="hugo">Hugo</Option>
</Select>
</Dialog>

**Comment by j787701730** [comment]
`<Dialog>
<Select id="basic-demo" onChange={onChange} onBlur={onBlur} onToggleHighlightItem={onToggleHighlightItem} defaultValue="jack" aria-label="name is" showSearch hasClear>
    <Option value="jack">Jack</Option>
    <Option value="frank">Frank</Option>
    <Option value="hugo">Hugo</Option>
</Select>
</Dialog>` 在dialog里面关不掉下拉框,  在黑色遮罩层是正常的.

**Comment by bindoon** [comment]
same with #2417
