### ISSUE TITLE
[Table]MuxTable 当 openRowKeys 的数组元素内包含 0 时，为 0 的行不会被展开

### ISSUE THREAD

**Issue by kooriko** [alibaba-fusion/next#2275]
### Component 
Table

### Steps to reproduce
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/qoFI9gw3aNM2.png)

**Comment by youluna** [comment]
无法复现 https://github.com/alibaba-fusion/next/issues/2275

**Comment by youluna** [comment]
经验证是业务方问题
