### ISSUE TITLE
[Dialog]希望对话框可以支持拖动和调整大小

### ISSUE THREAD

**Issue by 52flutter** [alibaba-fusion/next#231]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Dialog

### Feature Description
希望对话框可以支持拖动和调整大小，这样的应用场景也不少

**Comment by bindoon** [comment]
目前为止反馈这个需求非常少，决定不支持
