### ISSUE TITLE
[Field]使用 functional component 时，CustomInput 再删除后校验仍然存在

### ISSUE THREAD

**Issue by maotlab** [alibaba-fusion/next#2327]
### Component 
Field

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-template-forked-kdbj9?file=/src/ArrayItem/index.js)

### Steps to reproduce
复现步骤：
====CustomInput====
1. 打开 https://codesandbox.io/s/fusion-next-template-forked-kdbj9?file=/src/ArrayItem/index.js
2. 输入框输入内容，并点击添加再输入内容
3. 点击“保存”，此时提示应该是成功
4. 删除第二项记录
5. 点击“保存”，此时提示失败
6. 查看 console 可以看到是刚刚删除的第二条记录为“必填”项的校验失败

======Input=====
7. 修改 /src/LeafRule/index.js 里的 CustomInput为 Input,
8. 再重复 2-4 的步骤，再点击保存，此时提示“成功”

场景描述：
使用 functional component  包裹了 Input 组件，名为 CustomInput，所有属性都透传的情况下，我通过field 的 addArrayValue ，deleteArrayValue做增加再删除后，form 的 validate 仍然会去校验已经删掉的CustomInput。
而如果用Input 组件直接替换 CustomInput，则这个增删操作后，validate 不会再去校验这个组件。

**Comment by bindoon** [comment]
双11后来发布

**Comment by bindoon** [comment]
原因是调用 deleteArrayValue的时候没有删除 fieldMeta 上面的数据

**Comment by youluna** [comment]
发布了吗？
