### ISSUE TITLE
[Table]table 组件的components属性api文档缺失

### ISSUE THREAD

**Issue by cpaiyueyue** [alibaba-fusion/next#2331]
### Component 
Table

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/rQcZA6LGELh9.png)

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/pELvBKa2lD29.png)

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/K4h0UgmnlKmy.png)
第一张和第二张是我这边的实现，发现表头渲染和第三张的demo渲染不一致，希望提供下这个api的说明哈

**Comment by youluna** [comment]
这是个高级用法，不对外进行详细透出。可以把你想要的场景描述出来，给一些代码，我从开发角度给一些建议哈

**Comment by cielyic** [comment]
> 这是个高级用法，不对外进行详细透出。可以把你想要的场景描述出来，给一些代码，我从开发角度给一些建议哈

我们现在要用到拖拽组件
但是我们没有components的属性

一方面就不太敢用
一方面没有类型提示太麻烦了，还报错
