### ISSUE TITLE
[VirtualList]VirtualList  虚拟滚动列表设置初始位置 demo 鬼畜

### ISSUE THREAD

**Issue by zuoqi705** [alibaba-fusion/next#2332]
### Component 
VirtualList

### Reproduction link 
[https://fusion.alibaba-inc.com/pc/component/basic/virtual-list#%E8%AE%BE%E7%BD%AE%E5%88%9D%E5%A7%8B%E4%BD%8D%E7%BD%AE](https://fusion.alibaba-inc.com/pc/component/basic/virtual-list#%E8%AE%BE%E7%BD%AE%E5%88%9D%E5%A7%8B%E4%BD%8D%E7%BD%AE)

### Steps to reproduce
https://fusion.alibaba-inc.com/pc/component/basic/virtual-list#%E8%AE%BE%E7%BD%AE%E5%88%9D%E5%A7%8B%E4%BD%8D%E7%BD%AE

**Comment by YunMeng99** [comment]
官网未复现 先关闭处理 如需继续跟进重新开启
