### ISSUE TITLE
[Select]select tag模式，输入框中的内容是否不应设置为选项

### ISSUE THREAD

**Issue by 1048034876** [alibaba-fusion/next#2341]
### Component 
Select

### Reproduction link 
[https://alifd.alicdn.com/demos-pages/@alifd/next/Select@1.21.8/@alife/theme-blue@1.2.3/index.zh-cn.html#%E6%A0%87%E7%AD%BE](https://alifd.alicdn.com/demos-pages/@alifd/next/Select@1.21.8/@alife/theme-blue@1.2.3/index.zh-cn.html#%E6%A0%87%E7%AD%BE)

### Steps to reproduce
输入框中输入“lu”，选项第一条即为“lu”，可以选中成为一个tag，但用户希望能选中的tag一定都是select datasource中存在的数据，所以“lu”不应该作为一个可点击选项

**Comment by bindoon** [comment]
那就不要用 tag 模式， 多选模式 mode=multiple 不行吗？
