### ISSUE TITLE
[Tree]平铺叶子节点Demo异常，只渲染一层节点

### ISSUE THREAD

**Issue by jerryyxu** [alibaba-fusion/next#2346]
### Component 
Tree

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/7be78984](https://riddle.alibaba-inc.com/riddles/7be78984)

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/JvvpsaK55L8K.png)

**Comment by wdn007** [comment]
这个咋还不解决呢

**Comment by eternalsky** [comment]
从 issue 中看不出需要解决的问题是什么，如需跟进，请重新提起 issue

**Comment by wdn007** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
我已经收到邮件，会尽快给您回复。
