### ISSUE TITLE
[Table]对于可resize的表头，在hover的时候显示辅助线

### ISSUE THREAD

**Issue by csr632** [alibaba-fusion/next#2360]
### Component 
Table
### Feature Description
我们的table都是无border的：
![](https://user-images.githubusercontent.com/18747423/98906551-3c793d80-24f8-11eb-9dcf-a2ea214dd007.png)
对于可resize的表头，在拖拽的时候，没有明显的标识，造成不好的体验。

希望在resize表头的时候，出现辅助线纵向贯穿到表格底部，像这样：
![image](https://user-images.githubusercontent.com/18747423/98906589-4d29b380-24f8-11eb-8e1d-aefc2e40039d.png)

**Comment by xmsz** [comment]
+1

**Comment by eternalsky** [comment]
目前已支持。
