### ISSUE TITLE
[Table]table dataIndex = '[a,b]' 兼容问题

### ISSUE THREAD

**Issue by TaoMiss** [alibaba-fusion/next#2361]
### Component 
Table
### Feature Description
需求：dataIndex = '[a,b]' 获取record的多列数据；
与现有规则冲突，报错

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/U4zSRueu39bi.png)

**Comment by youluna** [comment]
Table支持的dataIndex数据类型为 `dataIndex="name"` `dataIndex="info.name"` `dataIndex="item[0].name"`，不支持dataIndex = '[a,b]'这种数组类型，这是一个非法值不要这么用
