### ISSUE TITLE
[Form]编辑态 预览态的样式调整

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#2364]
### Component 
Form
### Feature Description
![image](https://user-images.githubusercontent.com/10049465/99026401-d814b780-25a5-11eb-81df-82dbf6cc2bc0.png)

![image](https://user-images.githubusercontent.com/10049465/99026425-e1058900-25a5-11eb-8362-cecb8bf79bbd.png)

**Comment by bindoon** [comment]
![image](https://user-images.githubusercontent.com/5189853/99496495-58c12280-29af-11eb-99ef-957d7ff50b55.png)
后续再持续跟进，是否预览态下 label 也有诉求变化？
