### ISSUE TITLE
[TreeSelect]TreeSelect组件  isPreview设置后报错

### ISSUE THREAD

**Issue by hustxuli** [alibaba-fusion/next#2372]
### Component 
TreeSelect

### Steps to reproduce

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/lw0gOGdecRGQ.png)

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/jTtM8rR8UeBa.png)

**Comment by YunMeng99** [comment]
官网未复现 先关闭处理 如需继续跟进重新开启
