### ISSUE TITLE
[All]Fusion 容器组件无法进行 SPM D 位埋点

### ISSUE THREAD

**Issue by zernmal** [alibaba-fusion/next#2376]
### Component 
Tab
### Feature Description
我在页面 head 里声明了：
```
<meta name="aplus-auto-exp" content='[{"logkey":"/abc.auto.exp","cssSelector":".auto-exp","props":[]}]' />
<meta name="aplus-auto-clk" content='[{"logkey":"/abc.auto.clk","cssSelector":".auto-clk","props":[]}]' />
```

在对应元素加上 class="aplus-auto-exp aplus-auto-clk" data-spm="d_xxxx" 后就会自动上报曝光和点击埋点的黄金令箭，在使用 Tab 组件时，现在我想知道每个 tab 按钮的使用转化率，想操作对应的 dom 加一些属性，但是现在完成不了。你们看看怎么处理，对问题有不清楚的地方，可以联系我

**Comment by bindoon** [comment]
手风琴、Nav、Tree、MenuItem 太多了，需要系统梳理透传 data-* 系列属性

**Comment by bindoon** [comment]
组件无法透出，建议每个 Tab 包裹一层 span
