### ISSUE TITLE
[Overlay]Dialog内的Select组件 点击Dialog区域内 Select菜单没法自动收起

### ISSUE THREAD

**Issue by jerryyxu** [alibaba-fusion/next#2396]
### Component 
Overlay

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/af1c8938?mode=jsx](https://riddle.alibaba-inc.com/riddles/af1c8938?mode=jsx)

### Steps to reproduce
如题

**Comment by youluna** [comment]
see https://github.com/alibaba-fusion/next/issues/2417
