### ISSUE TITLE
[Table]StickyLockTable页面窗口变小时锁列错位

### ISSUE THREAD

**Issue by cytle** [alibaba-fusion/next#2399]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/1b750eef](https://riddle.alibaba-inc.com/riddles/1b750eef)

### Steps to reproduce
Table.StickyLock 表格，从无锁列表格到出现锁列状态时，锁列错位，造成露出白底，以及其它列被盖住

![2020-11-18 16-51-33 2020-11-18 16_52_20](https://user-images.githubusercontent.com/5120505/99508556-afcef380-29bf-11eb-8f6a-1983a98296a9.gif)

**Comment by youluna** [comment]
StickyTable没有监听浏览器的resize事件，所以没有自动切换锁列/非锁列的能力。

预计11月底之前支持下

**Comment by cytle** [comment]
@youluna 请问修复了吗？
