### ISSUE TITLE
[Step]circle垂直模式下，宽度异常

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#2415]
### Component 
Step

### Steps to reproduce
https://riddle.alibaba-inc.com/riddles/c30e5f71
![image](https://user-images.githubusercontent.com/10049465/99903982-0b241d00-2d03-11eb-84f2-756be7c0c228.png)

**Comment by weinianyang** [comment]
### step嵌套在弹窗中，你需要设置step的宽度/设置弹窗的宽度。例如：
```
<div>
        {step}
        <Overlay.Popup style={{width: '90%'}} visible>{step}</Overlay.Popup>
</div>
```
