### ISSUE TITLE
[Select]Select popup  cant not close in Dialog with React17

### ISSUE THREAD

**Issue by akecn** [alibaba-fusion/next#2417]
### Component 
Select

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elegant-ardinghelli-q49zz)

### Steps to reproduce
click select open popup and blur, the popup not close in dialog

**Comment by bindoon** [comment]
已经确认是 react@17.0.0 版本引起的，16.13.0 版本没这个问题。

**Comment by youluna** [comment]
参考解决方案
```jsx
<Dialog
  onOk={(e) => {
    e.stopPropagation();
  }}
/>
```

**Comment by youluna** [comment]
fixed in 1.23.15
