### ISSUE TITLE
[Select]在浏览器翻译后的页面上select组件选择后会崩溃

### ISSUE THREAD

**Issue by fengmumu1** [alibaba-fusion/next#2424]
### Component 
Select

### Steps to reproduce
测试页面
https://mc.fusion.design/unpkg/@alifd/fusion-design-pro@0.2.3/build/index.html#/form/group
动图不动了。。。 复现流程，找一个使用了选择器的组件，然后右键使用浏览器翻译页面，然后选择，然后就崩溃了

**Comment by fengmumu1** [comment]
![image](https://user-images.githubusercontent.com/37215225/100192687-5caff000-2f2d-11eb-895a-97402c2b6951.png)

**Comment by bindoon** [comment]
https://github.com/facebook/react/issues/11538#issuecomment-390386520

google translate 翻译的时候会把文字转为 font 标签，dom 结构变化 unmount 的时候找不到元素导致页面 crash

可以在文字上面包裹 span 避免此bug
