### ISSUE TITLE
[Table]Table锁列在Edge上高度异常

### ISSUE THREAD

**Issue by csr632** [alibaba-fusion/next#2437]
### Component 
Table

### Reproduction link 
用Edge打开fusion文档即可复现

### Steps to reproduce
用Edge打开fusion文档即可复现
![image](https://user-images.githubusercontent.com/18747423/100322099-b92f1000-2ffe-11eb-805b-3b03520057f9.png)

Edge版本18.18363

**Comment by flyinhigh** [comment]
求快速修复，急用。

**Comment by youluna** [comment]
我这里试了IE11 复现不出来，最新版本的Edge也表现正常，1个解决思路：升级到1.21.x， 使用Table.StickyLock，这个功能优化了锁列实现方式，不会有锁列与非锁列不等高的问题

**Comment by flyinhigh** [comment]
还有个问题，锁列和表格嵌套一起，会出现嵌套表格被遮挡的问题

![Uploading image.png…](https://img.alicdn.com/tfs/TB1HgC537L0gK0jSZFAXXcA9pXa-2946-544.png)

**Comment by youluna** [comment]
这个也可以通过1.21.x的Table.StickyLock来实现，1.21.0之前是锁table列，1.21.x是锁行的列
https://fusion.design/pc/component/basic/table#%E5%8F%AF%E5%B1%95%E5%BC%80-%E9%94%81%E5%88%97
