### ISSUE TITLE
[Table]使用columns方式渲染的表格，在卸载后重新加载，表格选择会出现Bug

### ISSUE THREAD

**Issue by distums** [alibaba-fusion/next#2472]
### Component 
Table

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inspiring-hill-jensm?file=/readme.md)

### Steps to reproduce
1. 点`打开弹窗`按钮，在表格里随便选择几条数据（此时一切正常）；
2. 然后点`取消/确定`关闭弹窗；
3. 再次点`打开弹窗`按钮，此时表格不能既不能选择新的，也无法取消选择已有；

PS：使用<Table.Column>默认渲染是正常的

**Comment by eternalsky** [comment]
目前（1.27.x） 已无此问题
