### ISSUE TITLE
[Tab]Tab excessMode style problem when has extra

### ISSUE THREAD

**Issue by FrominXu** [alibaba-fusion/next#2482]
### Component 
Tab

### Steps to reproduce
Tab excessMode style problem when has extra

**Comment by bindoon** [comment]
![image](https://user-images.githubusercontent.com/5189853/102360642-3ee62000-3fed-11eb-9469-9b3bc1b04975.png)
需要设计师给出交互规范，extra 和 下拉按钮冲突了

**Comment by eternalsky** [comment]
和此问题相同 https://github.com/alibaba-fusion/next/issues/1891，只保留一个继续跟踪
