### ISSUE TITLE
[Tree]select/tree 等数组类的 组件，编辑回填数据的时候，提示 类型不一致

### ISSUE THREAD

**Issue by ShichengBegonia** [alibaba-fusion/next#2494]
### Component 
Tree
### Feature Description
CascaderSelect/Tree 等数组类的 组件，编辑回填数据的时候，提示 类型不一致；控制台报警告

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/iF2KmVe7fHAU.png)

**Comment by youluna** [comment]
那就按照提示修改类型呀，问题是什么呢，从描述看不到是什么问题

**Comment by YunMeng99** [comment]
问题描述不清楚先关闭处理，如需继续跟进重新开启

**Comment by YunMeng99** [comment]
问题描述不清楚先关闭处理，如需继续跟进重新开启
