### ISSUE TITLE
无法打开 FusionCool 面板

### ISSUE THREAD

**Issue by wmzy** [alibaba-fusion/next#2499]
### Steps to reproduce
最新版 sketch 和最新版 FusionCool ，点击【打开/关闭面板】无响应。
查看日志报错：
```sh
Error: An Obj-C exception occurred.
    at [native code] (/)
    at /Users/zlt/Library/Application Support/com.bohemiancoding.sketch3/Plugins/fusion-cool 3.sketchplugin/Contents/Sketch/index.js:1:78882
    at /Users/zlt/Library/Application Support/com.bohemiancoding.sketch3/Plugins/fusion-cool 3.sketchplugin/Contents/Sketch/index.js:1:1475
  nativeException: Error: An Obj-C exception occurred.

```

**Comment by wmzy** [comment]
@youluna 您好，我是按照你们模板填写的：https://github.com/alibaba-fusion/next/issues/new?title=%E6%97%A0%E6%B3%95%E6%89%93%E5%BC%80%20FusionCool%20%E9%9D%A2%E6%9D%BF&body=%23%23%23%20Steps%20to%20reproduce%0A%E6%9C%80%E6%96%B0%E7%89%88%20sketch%20%E5%92%8C%E6%9C%80%E6%96%B0%E7%89%88%20FusionCool%20%EF%BC%8C%E7%82%B9%E5%87%BB%E3%80%90%E6%89%93%E5%BC%80%2F%E5%85%B3%E9%97%AD%E9%9D%A2%E6%9D%BF%E3%80%91%E6%97%A0%E5%93%8D%E5%BA%94%E3%80%82%0A%E6%9F%A5%E7%9C%8B%E6%97%A5%E5%BF%97%E6%8A%A5%E9%94%99%EF%BC%9A%0A%0AError%3A%20An%20Obj-C%20exception%20occurred.%0A%20%20%20%20at%20%5Bnative%20code%5D%20(%2F)%0A%20%20%20%20at%20%2FUsers%2Fzlt%2FLibrary%2FApplication%20Support%2Fcom.bohemiancoding.sketch3%2FPlugins%2Ffusion-cool%203.sketchplugin%2FContents%2FSketch%2Findex.js%3A1%3A78882%0A%20%20%20%20at%20%2FUsers%2Fzlt%2FLibrary%2FApplication%20Support%2Fcom.bohemiancoding.sketch3%2FPlugins%2Ffusion-cool%203.sketchplugin%2FContents%2FSketch%2Findex.js%3A1%3A1475%0A%20%20nativeException%3A%20Error%3A%20An%20Obj-C%20exception%20occurred.%0A%0A%3C!--%20generated%20by%20alibaba-fusion-issue-helper.%20DO%20NOT%20REMOVE%20--%3E%0A%3C!--%20fusion-cool%20--%3E

**Comment by youluna** [comment]
什么版本的sketch

**Comment by wmzy** [comment]
@youluna 版本 70.2 (109071)

**Comment by wangxiaojuan** [comment]
建议下载新版的插件：https://nhcil-udesign.oss-cn-hangzhou.aliyuncs.com/done_plugin/done_client-latest.zip
