### ISSUE TITLE
[Overlay]弹窗布局，位置计算时机需要优化

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#2500]
### Component 
Overlay

### Reproduction link 
[https://codepen.io/dashdots/pen/yLaJLYR?editors=0010](https://codepen.io/dashdots/pen/yLaJLYR?editors=0010)

### Steps to reproduce
从宽屏，拉动窗口大小切成窄屏，弹窗位置会一直往上飘。此时刷新页面会变好
![image](https://user-images.githubusercontent.com/10049465/101337412-96caab80-38b6-11eb-9c54-57971c425b18.png)

**Comment by bindoon** [comment]
fixed in `@alifd/next@1.25` with api `v2`
