### ISSUE TITLE
[Search]css-var中包含非法样式

### ISSUE THREAD

**Issue by csr632** [alibaba-fusion/next#2505]
### Component 
Search

### Steps to reproduce
https://unpkg.alipay.com/@alife/theme-xconsole-v4@0.4.13/dist/next-noreset.var.css

搜索 " \0" , 能看到 `line-height: 30px \0;`这样的样式

**Comment by bindoon** [comment]
```
   line-height: 34px \0;
      line-height: calc(var(--form-element-large-height, 36px) - var(--input-border-width, 1px)*2) \0;
```
\0 是为了兼容ie9， 我check下
