### ISSUE TITLE
[Table]Table的filter无法展开

### ISSUE THREAD

**Issue by Gamehu** [alibaba-fusion/next#2512]
### Component 
Table

### Reproduction link 
 [demo](https://codesandbox.io/s/dumi-demo-forked-4bchx?file=/demo.tsx)

### Steps to reproduce
 Table.Column的filters为多层时，  设置openKeys后，折叠失效

**Comment by youluna** [comment]
从demo看表现是正常的，可以详细说一下有什么异常么

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进请重提 issue
