### ISSUE TITLE
[Table]Table Column能否替换为CascaderSelect 这类组件

### ISSUE THREAD

**Issue by Gamehu** [alibaba-fusion/next#2513]
### Component 
Table
### Feature Description
现filter是基于Menu组件，当存在多层结构时，易用性很差，希望能提供方式扩展filter组件，比如可用CascaderSelect 替换

**Comment by youluna** [comment]
建议自己定义filter组件，可以通过title写进去，例如 `<Table.Column title={<TitleWithFilter />} />`
