### ISSUE TITLE
文档里面的钉钉2群人满了，加不进去怎么办

### ISSUE THREAD

**Issue by xiaofuliang** [alibaba-fusion/next#2514]
![1](https://user-images.githubusercontent.com/23289722/101854121-d38af100-3b9b-11eb-98c2-b80143a36654.jpg)

**Comment by bindoon** [comment]
可以去社区群 ![](https://img.alicdn.com/tfs/TB1.TVIYHY1gK0jSZTEXXXDQVXa-1125-1485.png)
文档里面地址我更新下
