### ISSUE TITLE
钉钉2群满了，加不进去，有新群吗

### ISSUE THREAD

**Issue by xiaofuliang** [alibaba-fusion/next#2515]
### Type 
Platform

### Feature Description
有开新群吗
![1](https://user-images.githubusercontent.com/23289722/101854241-18af2300-3b9c-11eb-8758-e0032c3156f1.jpg)

**Comment by youluna** [comment]
![image](https://user-images.githubusercontent.com/10049465/102033475-7b036000-3df6-11eb-9e47-03f0c9713510.png)
