### ISSUE TITLE
[NumberPicker]NumberPicker一直输入会出现指数和Infinity

### ISSUE THREAD

**Issue by sxei** [alibaba-fusion/next#2529]
### Component 
NumberPicker

### Steps to reproduce
输入`10000...`一直输入0，会先变成1e 21，继续输然后又变成Infinity

```js
import { NumberPicker } from '@alife/next';

ReactDOM.render(
    <div>
        <NumberPicker/>
     
    </div>,
    mountNode
);
```

**Comment by galogm** [comment]
使用的next版本是哪一个？新版本的已经修复了，例如1.21.13的demo：https://riddle.alibaba-inc.com/riddles/dd2908f8

**Comment by galogm** [comment]
fixed in #2244
