### ISSUE TITLE
[Overlay]当没有给body设置padding时，偶现padding去不掉

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#2533]
### Component 
Overlay

### Steps to reproduce
![image](https://user-images.githubusercontent.com/10049465/102223285-75556980-3f1f-11eb-90df-d1694ffbc354.png)
上图中的`ne()` 就是 `hasScroll()`，它是用来判断当前页面是否有滚动条的，出现dialog等的情况下已经没有滚动条了，这一判断条件可以直接去掉
![image](https://user-images.githubusercontent.com/10049465/102223340-8aca9380-3f1f-11eb-923e-8b1db8378c5a.png)

![image](https://user-images.githubusercontent.com/10049465/102223215-5fe03f80-3f1f-11eb-89f5-3cc295a17cb8.png)

**Comment by bindoon** [comment]
fixed in `@alifd/next@1.25` with api `v2`
