### ISSUE TITLE
[Field] type for validate method's argument ’values‘ may be mistake.

### ISSUE THREAD

**Issue by keepmood** [alibaba-fusion/next#2538]
### Component 
Field

### Steps to reproduce
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/DZ1UEmgElswz.png)

**Comment by julytang** [comment]
Same issue.

**Comment by eternalsky** [comment]
fix in https://github.com/alibaba-fusion/next/pull/4710/files#diff-2ea8b37c5ea4f253b1109cac22b65643cb0bb67ce00fbb45a3054150f916fa66
