### ISSUE TITLE
[CascaderSelect]CascaderSelect 自己封装组件问题

### ISSUE THREAD

**Issue by jacktang** [alibaba-fusion/next#2542]
### Component 
CascaderSelect

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-template-forked-l14jr?file=/src/ThreeColumnForm.jsx)

### Steps to reproduce
项目需要将省市区级联选择进行封装，以便在Form提交过程中可以复用。封装后发现dataSource可以设置进去，但是不能显示出来。具体 Demo: https://codesandbox.io/s/fusion-next-template-forked-l14jr?file=/src/ThreeColumnForm.jsx 请帮忙看下哪里没有理解到位。谢谢

**Comment by jacktang** [comment]
fusion前端组是不是工作都满负荷 没人管这些问题了 @.@

**Comment by youluna** [comment]
@jerryyxu 看下来

**Comment by jerryyxu** [comment]
![image](https://user-images.githubusercontent.com/8581684/102861252-53516f00-446a-11eb-8050-82cdfcbb7591.png)
dataSource拼错了

**Comment by jacktang** [comment]
@jerryyxu demo我更新了，还是有个问题，选定选项值，但是设置不进去是为什么?

**Comment by jacktang** [comment]
在 PCDSelector.jsx中，
```
const { onPCDSelect, error, ...rest } = props;
....
console.log("rest =>", rest);
```
输出
```
rest => {data-meta: "Field", id: "pcd_id", value: undefined, onChange: ƒ (), defaultValue: "2982"…}
```

`value:undefined` 怎么会设置进去的？怎么去掉？

**Comment by jacktang** [comment]
> @jerryyxu demo我更新了，还是有2个问题：
> 1）defaultValue没有起作用
```
{...init("pcd_id", {
              initValue:'2982',
              rules: [{ required: false, message: "必填" }]
            })}
```
这个解决了
> 2）选定选项值，但是设置不进去
> 
> 是自己封装组件需要注意什么吗？文档我都来回看几遍了。。。

**Comment by jacktang** [comment]
https://codesandbox.io/s/fusion-next-template-forked-l14jr?file=/src/ThreeColumnForm.jsx:2345-2363 是fixed的例子
