### ISSUE TITLE
[Shell]Shell.Branding自带的收起侧边栏按钮无法隐藏

### ISSUE THREAD

**Issue by xiaosong120** [alibaba-fusion/next#2550]
### Component 
Shell
### Feature Description
想隐藏掉这个收起按钮 想加载侧边栏上 但是好像没有留这个口子
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/hp3VNRs4TBMP.png)

**Comment by youluna** [comment]
`<Shell.Navigation trigger={null} />` 注意要设置在左侧边栏的navigation上
