### ISSUE TITLE
[Select]加载更多数据时滚动条定位异常

### ISSUE THREAD

**Issue by h1orz** [alibaba-fusion/next#2551]
### Component 
Select

### Reproduction link 
[https://codepen.io/pen/?&editors=0010](https://codepen.io/pen/?&editors=0010)

### Steps to reproduce
复现步骤：
下拉菜单中，选中option0，下拉触发onScroll事件加载更多数据。

期望结果：
加载更多数据，滚动条不会重新定位至option0。

实际结果：
加载更多数据，滚动条重新定位至option0。

**Comment by bindoon** [comment]
same with #2611
