### ISSUE TITLE
[Select]Select组件问题

### ISSUE THREAD

**Issue by izuomeng** [alibaba-fusion/next#2554]
### Component 
Select
### Feature Description
1. 关闭下拉等宽时，希望能够支持下拉选项的宽度最小为选择框的宽度
lALPD0eJxRQT8mXNBQDNCIQ_2180_1280.png
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/WHfHY7ukJfXM.png)

2. 多选模式时，tag会被单行截断，希望可以hover显示完整内容，在tag上添加html的title属性即可

**Comment by bindoon** [comment]
1. same with #2583 
2.目前没看到折行问题，截图看看
