### ISSUE TITLE
[Menu]设置focusabled={false}禁止滚动到focus区域的

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#2565]
### Component 
Menu
### Feature Description
https://riddle.alibaba-inc.com/riddles/bb665fa8

**Comment by youluna** [comment]
有个矛盾点，现在Menu组件在第一次渲染，或数据更新的时候，会把当前focus的项目，默认在第一屏展示出来

Select用到了Menu，而Menu区分不出来是Select打开关闭，还是重新加载了

**Comment by bindoon** [comment]
- 弹窗从关闭到打开，menu自动滚动到高亮的选项
- 弹窗打开状态，刷新dataSource 比如给尾部增加数据，不需要滚动

**Comment by bindoon** [comment]
最终逻辑修改为 Menu 在数据源 update 的时候不再自动滚动
