### ISSUE TITLE
object is not extensible

### ISSUE THREAD

**Issue by Gamehu** [alibaba-fusion/next#2571]
### Version

ice.js :1.9.9

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tablefield-zuiv7?file=/index.js:1013-1216)

### Steps to reproduce
重现链接直接使用原生的useState传递数据时，正常。

但是用ice.js store传递数据时，报错：

Uncaught TypeError: Cannot add property Symbol(@@YOU_CAN_NEVER_REMOVE_ARRAY_UNIQUE_TAG@@), object is not extensible http://localhost:3333/js/index.js 271046 7 TypeError: Cannot add property Symbol(@@YOU_CAN_NEVER_REMOVE_ARRAY_UNIQUE_TAG@@), object is not extensible

当我不用ice pageStore的数据时，则正常。

 ![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/1ljLzQFLNg9T.png)

**Comment by luhc228** [comment]
贴一下你使用报错的代码

**Comment by luhc228** [comment]
可以看下这里的例子是否能解决你上面的问题
https://codesandbox.io/s/tablefield-forked-cgvwx

**Comment by Gamehu** [comment]
如图点击新增按钮，使用reset也无法清空表单数据

![image](https://user-images.githubusercontent.com/10043320/103144940-c873bb80-476c-11eb-969e-49b2668d79f9.png)

https://codesandbox.io/s/tablefield-forked-3lkg8?file=/index2.js

**Comment by Gamehu** [comment]
> 可以看下这里的例子是否能解决你上面的问题
> https://codesandbox.io/s/tablefield-forked-cgvwx

例子是好使的，但是本地还是有问题，因为没法完全模拟ice那一套，我再查查吧，感谢。

**Comment by youluna** [comment]
@luhc228 是ice工程的问题吗？需要组件配合做什么修改吗？
