### ISSUE TITLE
[Dialog]Dialog 快捷方法使用 promise 时存在的问题

### ISSUE THREAD

**Issue by liunian** [alibaba-fusion/next#2576]
### Component 
Dialog

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/ad022bb4](https://riddle.alibaba-inc.com/riddles/ad022bb4)

### Steps to reproduce
使用 dialog 快捷方法来函数式展示 dialog，如第一次使用 confirm，点确定按钮调用 alert 来做二次确认，其中，不想关闭第一个弹层，所以 alert 放在 promise 中来触发。

结果会导致 alert 那个弹层的确定按钮自动展示了 loading 状态，并且不可点击

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/oZpavMYux014.png)

**Comment by bindoon** [comment]
fixed in @alifd/next@1.25
