### ISSUE TITLE
[CascaderSelect]希望CascaderSelect组件查询功能可受控

### ISSUE THREAD

**Issue by Bingzhao** [alibaba-fusion/next#2578]
### Component 
CascaderSelect
### Feature Description
在列表查询场景中，showSearch以后的多选场景输入框与内容展示放到一起不是很友好，我们希望通过header定制一个输入框，

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/FAnuGP7gLvQ9.png)

交互方案
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/TQBFzOPjEiJL.png)

**Comment by eternalsky** [comment]
没太看懂这个可控指的是哪里可控，如需继续跟进，请重开 issue 说明。
