### ISSUE TITLE
动态主题切换

### ISSUE THREAD

**Issue by robin2017** [alibaba-fusion/next#2579]
### Steps to reproduce
我们业务一套代码现在需要支持多主题，fusion能支持吗？
ps，目前我们用了ice的动态主题方案，但支持颜色切换，不支持高度，边角等样式，有什么其他替代方案吗？

**Comment by mark-ck** [comment]
@jerryyxu @youluna 我们的 css variable 主题方案能否支持这个 “动态主题” 的需求吗？

**Comment by bindoon** [comment]
已经支持 css variable
