### ISSUE TITLE
[Select]增加autowidth="growable"来使弹层宽度 >= 输入框宽度

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#2583]
### Component 
Select
### Feature Description
Pagination需要

**Comment by csr632** [comment]
目前的autowidth=false会造成下拉宽度小于输入框宽度，不太美观：

![image](https://user-images.githubusercontent.com/18747423/103336664-d6e70d80-4ab3-11eb-95d0-e8eed08c3f52.png)


因此希望增加一个autowidth="growable"模式，避免出现这种情况。

**Comment by bindoon** [comment]
autoWidth
- true。下拉菜单和选择器同宽。也就是写死了 width
- false。自动跟随内容下拉内容，增加当值小于选择框宽度时会被忽略。这里有变动可能是个 BR
- number。固定宽度，当值小于选择框宽度时会被忽略。
