### ISSUE TITLE
[CascaderSelect]CascaderSelect 如果子节点value一样，会选择不到

### ISSUE THREAD

**Issue by snowrzy** [alibaba-fusion/next#2594]
### Component 
CascaderSelect

### Reproduction link 
[https://codepen.io/jishen/pen/dypmawK?editors=0010](https://codepen.io/jishen/pen/dypmawK?editors=0010)

### Steps to reproduce
背景：国内部分区域存在相同的值，如天津市和平区 和沈阳市和平区
故障描述：这种情况下可能会选择不到指定的值，实例中无法选择到北京和平区

**Comment by youluna** [comment]
省市区value都使用区号或者邮编，没有用中文名字命名的

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进请重提 issue
