### ISSUE TITLE
[Overlay]overlay的事件处理机制在react16 17中的表现不一致

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#2606]
### Component 
Overlay

### Steps to reproduce
![image](https://user-images.githubusercontent.com/10049465/103968441-d5e26a00-519e-11eb-840e-5e32e83be3df.png)

在react17中符合预期：选中开始时间，选中结束时间，点击确定 => balloon不消失，移到balloon后balloon消失
在react16中不符合预期：选中开始时间 => balloon消失

https://riddle.alibaba-inc.com/riddles/ff532985?mode=jsx
https://riddle.alibaba-inc.com/riddles/7d7c5d8b

**Comment by youluna** [comment]
目前只能通过在DatePicker / Select上设置 followTrigger或者popupContainer来解

https://codesandbox.io/s/autumn-forest-908t1?file=/src/App.js

**Comment by youluna** [comment]
参考解决方案
https://github.com/facebook/react/issues/11387#issuecomment-355258340
```jsx
<Dialog
  onOk={(e) => {
    e.stopPropagation();
  }}
/>
```

**Comment by bindoon** [comment]
fixed in `@alifd/next@1.25` with api `v2`
