### ISSUE TITLE
[Select]Select 滚动加载选项数据源的时候滚动条会跳转到选中记录位置

### ISSUE THREAD

**Issue by yczz** [alibaba-fusion/next#2611]
### Component 
Select

### Reproduction link 
[https://fusion.alibaba-inc.com/pc/component/basic/select](https://fusion.alibaba-inc.com/pc/component/basic/select)

### Steps to reproduce
零售云使用SELECT 滚动加载功能实现的商品选择功能，当用户现选中选项后再滚动加载数据，会导致滚动条调到选中记录位置。官方demo中“滚动到底部加载 ”存在同样问题。此问题为飞鹤BUG需要加速修复

**Comment by bindoon** [comment]
same with https://github.com/alibaba-fusion/next/issues/2551

**Comment by bindoon** [comment]
fixed in https://github.com/alibaba-fusion/next/pull/2567
