### ISSUE TITLE
[Table]table expandedRowRender resize

### ISSUE THREAD

**Issue by 185172970** [alibaba-fusion/next#2613]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/ed3eea52](https://riddle.alibaba-inc.com/riddles/ed3eea52)

### Steps to reproduce
先把屏幕拖窄，然后再把屏幕宽度拖宽，resize不会触发tableOuterWidth改变，导致expandedRowRender不会铺满

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/LIqXn3i8hTxD.png)

**Comment by youluna** [comment]
本质上是希望table可以监听屏幕变化，resize的时候，table重新渲染。

要考虑好性能问题哦

**Comment by CastileMan** [comment]
什么时候发布口牙 @youluna

**Comment by youluna** [comment]
1.23.x fix
