### ISSUE TITLE
[Field]弹框表单用this.field.init方法初始化的值在再次唤起弹框时undefined

### ISSUE THREAD

**Issue by LeanWang0428** [alibaba-fusion/next#2617]
### Component 
Field

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-template-forked-7qd8i?file=/src/DialogDemo.js)

**Comment by LeanWang0428** [comment]
再次点击弹框显示时，表单初始化的值为undefined, 见demo的console.log

**Comment by bindoon** [comment]
正常，因为 autoUnmout 默认 true，dialog关闭的时候弹窗内form也销毁了。如果不想销毁设置 `new Field(this,{autoUnmount: false});`
