### ISSUE TITLE
[Nav]Nav组件

### ISSUE THREAD

**Issue by seekhow** [alibaba-fusion/next#2619]
### Component 
Nav
### Feature Description
垂直模式下   当Nav组件外层的容器定高的时候，Nav会滚动，这个时候希望提供一个图标来标识这个菜单还能继续往下滚动。当滚动最下方的时候无法再滚动的时候，图标消失。简而言之，就是一个标识能不能滚动的状态图标

**Comment by youluna** [comment]
用户描述的是：需要一个类似于vscode中，在左侧菜单栏，右键展开的菜单那样的业务组件，可以自动做一些空间识别。

需求比较复杂，评估下来很难做到，hold

![image](https://user-images.githubusercontent.com/10049465/111746495-13fbb880-88c9-11eb-8ff9-7f75b5cf6b34.png)

![image](https://user-images.githubusercontent.com/10049465/111746518-1cec8a00-88c9-11eb-8736-2c50dfa2ecad.png)

**Comment by YSMJ1994** [comment]
Stale
