### ISSUE TITLE
[DatePicker2]颜色没有跟主题色

### ISSUE THREAD

**Issue by bindoon** [alibaba-fusion/next#2620]
### Component 
DatePicker2

### Steps to reproduce
1. 选择色没有跟品牌色走
![image](https://user-images.githubusercontent.com/5189853/104894104-3cd9fd00-59af-11eb-8e2f-634fd391f190.png)
2. DatePicker1 应该抛 warning 丢弃掉

**Comment by jerryyxu** [comment]
已修复
![image](https://user-images.githubusercontent.com/8581684/115356757-8de7d000-a1ee-11eb-8f43-d7e10aadc6e1.png)
