### ISSUE TITLE
[Menu]Menu菜单组件，展开问题

### ISSUE THREAD

**Issue by Tony7lee** [alibaba-fusion/next#2621]
### Component 
Menu
### Feature Description
菜单展开，如果我的key可以确保唯一，可以支持仅配置叶子展开么？

![image](https://user-images.githubusercontent.com/9986631/104898376-8842da00-59b4-11eb-8557-3d819c753b67.png)

**Comment by youluna** [comment]
不支持哦，需要写全['a1', 'a2-1']
