### ISSUE TITLE
[Table]Table行合并错位

### ISSUE THREAD

**Issue by Bingzhao** [alibaba-fusion/next#2623]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/610e409e](https://riddle.alibaba-inc.com/riddles/610e409e)

### Steps to reproduce
primaryKey指定的属性相同的情况下，数据更新的时候行合并错位，由于rowSelection存在的情况下primaryKey正好与展示的id相同导致的。

**Comment by youluna** [comment]
表格数据源中，每行需要有唯一标示该条数据的主键，默认值为id，可通过 primaryKey 更改 e.g.<Table primaryKey='myId'></Table>

错位就是因为多行的主键一致，react渲染出错
