### ISSUE TITLE
[CascaderSelect]CascaderSelect多选问题

### ISSUE THREAD

**Issue by promotion-xu** [alibaba-fusion/next#2625]
### Component 
CascaderSelect

### Reproduction link 
[https://codepen.io/xuzhen/pen/rNMRpXV?editors=0011](https://codepen.io/xuzhen/pen/rNMRpXV?editors=0011)

### Steps to reproduce
1.打开重现链接
2.选择外滩soho楼宇，没有被选中
3.选择外滩soho子楼层F1没有被选中

**Comment by promotion-xu** [comment]
I need help

**Comment by bindoon** [comment]
![image](https://user-images.githubusercontent.com/5189853/105316810-5ae86d00-5bfc-11eb-8e81-d437b69008da.png)
value 不要有重复，第二个1 改掉就好了
