### ISSUE TITLE
[Dialog] 缩放 90% 情况下，对话框显示时报错

### ISSUE THREAD

**Issue by leer168** [alibaba-fusion/next#2626]
### Component 
Dialog

### Reproduction link 
[CDN控制台](CDN控制台)

### Steps to reproduce
显示对话框时报错

"error":"TypeError: Cannot read property 'style' of undefined\n at t.adjustSize (https://g.alicdn.com/aliyun/cdn-next/1.51.0/vendors.js:336:7027)\n at t.adjustPosition (https://g.alicdn.com/aliyun/cdn-next/1.51.0/vendors.js:336:6732)\n at https://g.alicdn.com/aliyun/cdn-next/1.51.0/vendors.js:392:7639\n at t.setPosition (https://g.alicdn.com/aliyun/cdn-next/1.51.0/vendors.js:336:23985)\n at t.componentDidMount (https://g.alicdn.com/aliyun/cdn-next/1.51.0/vendors.js:336:23173)\n at as (https://g.alicdn.com/aliyun/cdn-next/1.51.0/vendors.js:400:83372)

**Comment by youluna** [comment]
直接升级下版本，或者给准确稳定的复现demo

**Comment by Nanchenk** [comment]
相同的问题，无法给出稳定的 demo，版本 1.15.x

**Comment by Nanchenk** [comment]
> 相同的问题，无法给出稳定的 demo，版本 1.15.x

可复现的 demo， https://riddle.alibaba-inc.com/riddles/c079b77d，触发条件为 Chrome 浏览器缩放为 90%

**Comment by bindoon** [comment]
确认，缩放 90% 的情况下 1.22.x 版本也存在同样问题

**Comment by Nanchenk** [comment]
给一个 hack 方案，children 默认放一个 div，适用于此版本的各种弹窗

**Comment by leer168** [comment]
> 给一个 hack 方案，children 默认放一个 div，适用于此版本的各种弹窗

多谢多谢，这个是什么原理啊
