### ISSUE TITLE
[Tab]tab dropdown模式下样式bug

### ISSUE THREAD

**Issue by xiaran030** [alibaba-fusion/next#2634]
### Component 
Tab

### Reproduction link 
[https://fusion.alibaba-inc.com/45196/component/basic/tab#%E8%B6%85%E5%87%BA%E6%97%B6%E6%BB%91%E5%8A%A8](https://fusion.alibaba-inc.com/45196/component/basic/tab#%E8%B6%85%E5%87%BA%E6%97%B6%E6%BB%91%E5%8A%A8)

### Steps to reproduce

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/iPrcABEbSu0G.png)

**Comment by bindoon** [comment]
fixed in latest
