### ISSUE TITLE
[DatePicker2]DatePicker2 不支持Form 组件的 name属性，并且报错

### ISSUE THREAD

**Issue by Jennifer-Liuu** [alibaba-fusion/next#2641]
### Component 
DatePicker2

### Steps to reproduce
DatePicker2 不支持 Form组件的name 属性，并且 报错：

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/dGRmYiyaH7cN.png)

**Comment by YSMJ1994** [comment]
Fixed
