### ISSUE TITLE
[Search]search组件在选中过一次联想后，无法取消取消

### ISSUE THREAD

**Issue by xiaran030** [alibaba-fusion/next#2642]
### Component 
Search

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/d2041045](https://riddle.alibaba-inc.com/riddles/d2041045)

### Steps to reproduce
用上下箭头选中过一次联想，该联想记忆无法取消，用户无法搜索自己想搜索的关键词

**Comment by bindoon** [comment]
search 用户回车的时候其实是期望搜索自己输入的关键字，目前 autocomplete 逻辑有问题 一旦通过上下键 选择后就会记住highlight 选项，导致回车自动补全。

解法：只要有删除那么就应该去除 highlight 高亮

**Comment by bindoon** [comment]
这里应该定一个 highlight 规范：
- 上下键盘的 highlight 和 鼠标hover 应该是同一个状态，鼠标 hover item的时候 highlightKey 也应该跟着一起变化。目前鼠标hover的时候 仅仅是 样式的变化，这块要统一。目前fusion的现状如下
![image](https://user-images.githubusercontent.com/5189853/105935741-78e71f00-608d-11eb-9161-311202a9cf28.png)
- autoHighlightFirstItem： Select 默认为true, AutoComplete 默认为 false。Select和AutoComplete的差别是选择和输入的差别，所以要做此区分。
- 自动高亮：点击展开弹窗的时候应该自动 highlight 到第一个选中的元素，如果没有则没有 highlightKey=null，需要选择或者up/down 触发
