### ISSUE TITLE
[Table]Table 锁列阴影不出现（loading结束以后）

### ISSUE THREAD

**Issue by csr632** [alibaba-fusion/next#2647]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/8a123101](https://riddle.alibaba-inc.com/riddles/8a123101)

期望loading结束以后有这样的阴影：
![image](https://user-images.githubusercontent.com/18747423/105978846-f599ed80-60cd-11eb-948c-bdecfc676b75.png)

实际结果：
![image](https://user-images.githubusercontent.com/18747423/105978911-03e80980-60ce-11eb-841e-2cff25eb9a4a.png)

**Comment by youluna** [comment]
see https://github.com/alibaba-fusion/next/issues/2673

**Comment by youluna** [comment]
see https://github.com/alibaba-fusion/next/issues/2673
