### ISSUE TITLE
[Step]steps组件支持自定义留白宽度

### ISSUE THREAD

**Issue by ensorrow** [alibaba-fusion/next#2651]
### Component 
Step
### Feature Description
现在的实现是用 1/stepItem数量 的宽度作为留白，stepItem 数量越小留白就越大，期望能够自定义留白大小

**Comment by zuoqi705** [comment]
希望可以像 antd 一样两边顶起

**Comment by mark-ck** [comment]
@ensorrow @zuoqi705 新增了一个 API: stretch，如果设为 true 则 step 就拉伸占满整行，你们看看这样可以吗？
至于两面的留白，你们可以在外层再加个容器设置 padding 来控制。

**Comment by ensorrow** [comment]
可以满足需求

**Comment by zuoqi705** [comment]
🉑️
