### ISSUE TITLE
[DatePicker]DatePicker添加了showTime配置后设置预览态没有包括具体时间

### ISSUE THREAD

**Issue by SHERRYWANNA** [alibaba-fusion/next#2655]
### Component 
DatePicker

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/b607afb4 ](https://riddle.alibaba-inc.com/riddles/b607afb4 )

### Steps to reproduce
DatePicker添加了showTime配置后设置预览态没有包括具体时间

**Comment by bindoon** [comment]
这个和你的value有关系，value没有就没有。
