### ISSUE TITLE
[DatePicker2]DatePicker2 受控模式有BUG

### ISSUE THREAD

**Issue by Cyrilszq** [alibaba-fusion/next#2664]
### Component 
DatePicker2

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/140d40f6](https://riddle.alibaba-inc.com/riddles/140d40f6)

### Steps to reproduce
问题demo地址：https://riddle.alibaba-inc.com/riddles/140d40f6
 1. 点击button click按钮，日期组件可以正常展示 2021-02 ～2021-02，此时符合预期；
 2. 点击日期组件，发现值被改成 2021-05 ～ 2021-08了，不符合预期；

**Comment by jerryyxu** [comment]
close on commit https://github.com/alibaba-fusion/next/commit/91d4b70
