### ISSUE TITLE
[Table]Table.StickyLock导致锁列阴影消失

### ISSUE THREAD

**Issue by 185172970** [alibaba-fusion/next#2673]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/453065e8](https://riddle.alibaba-inc.com/riddles/453065e8)

### Steps to reproduce
table使用Table.StickyLock的时候锁列阴影消失，必须滚动之后才展示阴影

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/8VuHpXP24znJ.png)

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/Y6oLnXRbKtRG.png)

**Comment by youluna** [comment]
设置了loading后，第一次渲染没有阴影
