### ISSUE TITLE
[Table]Table.Sticky z-index 穿透问题

### ISSUE THREAD

**Issue by zuoqi705** [alibaba-fusion/next#2674]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/eb6a466f](https://riddle.alibaba-inc.com/riddles/eb6a466f)

### Steps to reproduce
使用 Table.Sticky 当 cell 嵌入包含 z-index 的组件时，会出现穿透。
使用之前的 Table 不会出现，感觉需要给 Table.Sticky 加一个 z-index

**Comment by youluna** [comment]
已修复 1.22.17可用
