### ISSUE TITLE
[NumberPicker]NumberPicker组件 能把device加入NumberPickerProps里面? 编辑器红线看着难受

### ISSUE THREAD

**Issue by j787701730** [alibaba-fusion/next#2676]
### Component 
NumberPicker

### Steps to reproduce
 No overload matches this call.
Overload 1 of 2, '(props: NumberPickerProps | Readonly): NumberPicker', gave the following error.
Type '{ device: string; onChange: (value: number) => void; onKeyDown: (e: KeyboardEvent) => void; style: { display: "inline-block"; width: string; }; precision: number; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes & Readonly & Readonly<...>'.
Property 'device' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes & Readonly & Readonly<...>'.
Overload 2 of 2, '(props: NumberPickerProps, context: any): NumberPicker', gave the following error.
Type '{ device: string; onChange: (value: number) => void; onKeyDown: (e: KeyboardEvent) => void; style: { display: "inline-block"; width: string; }; precision: number; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes & Readonly & Readonly<...>'.
Property 'device' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes & Readonly & Readonly<...>'.

**Comment by galogm** [comment]
fix in #3077
