### ISSUE TITLE
[Tab]组件，当TabItem为动态创建时，excessMode属性传值为dropdown时，样式不生效

### ISSUE THREAD

**Issue by hmjMaggie** [alibaba-fusion/next#2678]
### Component 
Tab

### Steps to reproduce
如果TabItem是动态创建的，excessMode属性传值为dropdown时，样式不生效。必须要重新resize一下窗口，dropdown的样式才会生效。

**Comment by wangchongwei** [comment]
> ### Component
> Tab
> 
> ### Steps to reproduce
> 如果TabItem是动态创建的，excessMode属性传值为dropdown时，样式不生效。必须要重新resize一下窗口，dropdown的样式才会生效。

@hmjMaggie 


我也碰到这个问题，于是来github查看。但是没有看到有啥回复。
经过我多次测试发现，与动态数据无关，与tab的样式有关。
`.homepage {
  display: flex;
  justify-content: center;
  align-items: center;

  :global {
    // .next-tabs-nav {
    //   display: flex;
    //   justify-content: space-between;
    // }
    // .next-tabs-tab {
    //   display: flex;
    //   justify-content: center;
    //   align-items: center;
    //   width: 100%;
    // }
}
`
当我屏蔽掉对tab中的样式重写时，excessMode效果就出来了。
希望对你有帮助。

**Comment by bindoon** [comment]
fixed in latest
