### ISSUE TITLE
[Select]Select wcag

### ISSUE THREAD

**Issue by KerryFu** [alibaba-fusion/next#2687]
### Component 
Select

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/74e686d0](https://riddle.alibaba-inc.com/riddles/74e686d0)

### Steps to reproduce
Select渲染后的combobox，初始缺少required [aria-*]
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/aJhB5FwVK7Gm.png)

Select re-render会增加aria-valuetext，而combobox无aria-valuetext属性
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/zSX7I6XPHYxn.png)

reference:
[www.w3.org](https://www.w3.org/TR/wai-aria/#combobox)

**Comment by bindoon** [comment]
combobox 不需要 valuetext ，因为 combobox 直接有value，展示的是真实数据。而 select 的value和展示的可能不一样(比如value=1,展示的是 选项1，才需要 value-text=选项1）。

**Comment by bindoon** [comment]
如上， combobox 不需要 valuetext。时间太久了关闭issue
