### ISSUE TITLE
[CascaderSelect]CascaderSelect数据取自getModel会报错

### ISSUE THREAD

**Issue by slightc** [alibaba-fusion/next#2688]
### Component 
CascaderSelect

### Steps to reproduce
```js
const [globalState] = store.getModel('global');
const { areaList } = globalState;
<CascaderSelect dataSource={areaList} />
```

在源代码 https://github.com/alibaba-fusion/next/blob/master/src/cascader/cascader.jsx#L27 处将导致报错
TypeError: Cannot assign to read only property 'value' of object '#<Object>'

**Comment by YSMJ1994** [comment]
对于 immutable 数据，需向组件传递 `immutable=true` 来阻止内部改变数据
