### ISSUE TITLE
[Button]loading按钮居左

### ISSUE THREAD

**Issue by sylingd** [alibaba-fusion/next#2690]
### Component 
Button

### Steps to reproduce
按钮使用loading时，图标偏左。期望是和文字一样居中。

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/H5YpGD1NKRaZ.png)

**Comment by YSMJ1994** [comment]
目前官网示例里按照图示设置 style 已经是 icon与文本一起居中了
