### ISSUE TITLE
[Grid]Grid demo 调用废弃浏览器api导致报错

### ISSUE THREAD

**Issue by csr632** [alibaba-fusion/next#2697]
### Component 
Grid

### Reproduction link 
[https://fusion.alibaba-inc.com/pc/component/basic/grid#type-container](https://fusion.alibaba-inc.com/pc/component/basic/grid#type-container)

### Steps to reproduce
window.removeListener 在chrome浏览器中为undefined

**Comment by bindoon** [comment]
use @alifd/layout
