### ISSUE TITLE
next.min.css'version should be introspective

### ISSUE THREAD

**Issue by guanpu** [alibaba-fusion/next#270]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Button

### Feature Description
It's actually not an issue with button, but global feature improve request.
When ever I get a next.min.css file, I should be able to know it's version, like bootstrap.min.css

````
/*!
 * Bootstrap v3.3.7 (http://getbootstrap.com)
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,hgroup,main,menu,nav,section,summary{display:block}audio,canvas,progress,video{display:inline-block;vertical-align:baseline}audio:not([controls]){display:none;

````

**Comment by guanpu** [comment]
And also the license & copyright header is also important.

**Comment by youluna** [comment]
https://unpkg.com/@alifd/next@1.12.4/dist/next.min.js  done
