### ISSUE TITLE
[VirtualList]某些情况下.next-virtual-list-wrapper高度会坍缩

### ISSUE THREAD

**Issue by luhaopeng** [alibaba-fusion/next#2706]
### Component 
VirtualList

### Reproduction link 
[https://codepen.io/luhaopeng/pen/VwmzMez](https://codepen.io/luhaopeng/pen/VwmzMez)

#### 重现

1. https://codepen.io/luhaopeng/pen/VwmzMez

点击链接，这是一个设置了`useVirtual`的Tree组件，#mountNode加上了pink背景色和边框。
点击一个节点进行异步展开，可以发现高度坍缩了，打开F12 Chrome控制台，可以看到".next-virtual-list-wrapper"的节点高度样式被设置成了`height: 56px`。

收起节点后高度恢复正常。

![1](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/HHO7Q5x36fRq.png)

2. https://codepen.io/luhaopeng/pen/mdOMBVX

点击链接，这是一个设置了`useVirtual`的TreeSelect组件。
点击输入框，依次键入'abc'，可以看到候选列表逐渐减少为'Not Found'。然后再依次退格删除输入值，能看到候选列表逐渐增加，然而在输入值由'a'变为''时，候选列表的高度发生了坍缩，打开F12 Chrome控制台，可以看到".next-virtual-list-wrapper"的节点高度样式被设置成了`height: 56px`。

重新键入一次'1'并退格删除后，高度恢复正常。或者取消焦点并重新激活打开下拉框，高度也会恢复正常。

![2](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/1BU26wDNqu96.png)

#### 问题定位

计算高度的代码位于`src/virtual-list/virtual-list.jsx/VirtualList/getSpaceBefore`，怀疑是高度缓存值出了问题，但是具体原因尚未找到。

**Comment by youluna** [comment]
感谢反馈，写的很详细，近期看下

**Comment by YSMJ1994** [comment]
@luhaopeng  already fixed at 1.26.24
