### ISSUE TITLE
[Shell]ConfigProvider或 Shell 在固定顶部和左侧菜单, 右侧内容滚动到顶部或底部会卡住, 鼠标滚动无响应

### ISSUE THREAD

**Issue by j787701730** [alibaba-fusion/next#2707]
### Component 
Shell

### Steps to reproduce
ConfigProvider或 Shell 在固定顶部和左侧菜单, 右侧内容滚动到顶部或底部,鼠标继续同方向滚动, 当鼠标位置不动反方向滚动滚轮时会无响应,页面会卡住不会滚动, 鼠标位置移动后, 再滚动滚轮页面恢复正常滚动.

**Comment by youluna** [comment]
没有复现你说的问题，需要给复现demo
