### ISSUE TITLE
发布后2天了进度始终停留在80%

### ISSUE THREAD

**Issue by salaxiao** [alibaba-fusion/next#2710]
### Reproduction link 
[https://fusion.design/98412/setting/publish?themeid=17844](https://fusion.design/98412/setting/publish?themeid=17844)

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/QA3xvAFOf942.png)

**Comment by bindoon** [comment]
这个故障类的问题可以走答疑群，效率比github会快。
