### ISSUE TITLE
[Select]Select 选择器的，勾 icon 不能配置

### ISSUE THREAD

**Issue by Zitian770** [alibaba-fusion/next#2716]
### Component 
Select

### Steps to reproduce
Select 选择器的，勾 icon 不能配置
截屏2021-02-19 下午4.01.31.png
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/mnarrYDKkri6.png)

**Comment by bindoon** [comment]
要配成啥样的，现在看起来挺好的。
