### ISSUE TITLE
demo提供展开代码按钮

### ISSUE THREAD

**Issue by cwtuan** [alibaba-fusion/next#2719]
### Type 
Platform

### Feature Description
希望提供展开全部代码的功能，方便搜索
![image](https://user-images.githubusercontent.com/3455798/108809473-e2524300-75e3-11eb-84a4-40409adda213.png)

**Comment by galogm** [comment]
新版demo已支持，需要站点基线升级为1.22.x及以上，位置：站点设置 -> 通用设置 -> 基线版本 -> 右侧升级按钮。
PS：项目基线升级指引 https://fusion.alibaba-inc.com/pc/yuque/fusion-design-system/ahvubx/ef7b6a?themeid=2。
