### ISSUE TITLE
[Menu]Pagination无法定制Select的Props

### ISSUE THREAD

**Issue by csr632** [alibaba-fusion/next#2720]
### Component 
Menu
### Feature Description
我们组件库想要定制下拉Menu的isSelectIconRight，Select和Menu都可以通过组件封装来解决，但是Pagination无法定制Select的props。

**Comment by youluna** [comment]
目前可以用<ConfigProvider defaultPropsConfig={}>

https://fusion.alibaba-inc.com/pc/component/basic/config-provider#interactive-container

参考 https://riddle.alibaba-inc.com/riddles/50a75aae
