### ISSUE TITLE
_@alife_next@0.19.81@@alife包出现问题导致我的项目不能启动

### ISSUE THREAD

**Issue by ZPCKJZD** [alibaba-fusion/next#2727]
### Steps to reproduce
in ./node_modules/_@alife_next@0.19.81@@alife/next/lib/_components/@alife/next-feedback/lib/main.scss

Module build failed (from ./node_modules/_mini-css-extract-plugin@1.3.8@mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/_sass-loader@10.1.1@sass-loader/dist/cjs.js):
SassError: expected ";".
     ╷
2402 │             )

**Comment by bindoon** [comment]
项目环境问题，建议自己排查
