### ISSUE TITLE
[Rating]Rating 组件支持 分数值定制显示

### ISSUE THREAD

**Issue by lidahui10** [alibaba-fusion/next#273]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Rating

### Feature Description
1.定制分数的显示，需要跟随鼠标hover移动，动态显示分数值。
2.定制的分数可以显示，类似于 3分 喜欢， 5分 非常喜欢，这种类似的交互

**Comment by youluna** [comment]
@lidahui10 supported in 1.13.1
