### ISSUE TITLE
[CascaderSelect]cascader-select 加 hasClear 后，handleChange 返回的值为空

### ISSUE THREAD

**Issue by tanyafuzhou** [alibaba-fusion/next#2733]
### Component 
CascaderSelect

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/39b44cdc](https://riddle.alibaba-inc.com/riddles/39b44cdc)

**Comment by YSMJ1994** [comment]
所给复现链接已无法复现问题，应该是已解决
