### ISSUE TITLE
[Button]Button组件出现两个loading

### ISSUE THREAD

**Issue by anticcc** [alibaba-fusion/next#2735]
### Component 
Button

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/NG2qYeEtIsDj.png)

code: 

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/NPTd8olrx134.png)

**Comment by hongxingshi** [comment]
看起来是在 Dialog 中，能不能提供较为完整的代码？
