### ISSUE TITLE
[Dialog]ok/cancek button support return promise / ok cancel按钮支持返回promise

### ISSUE THREAD

**Issue by tao1991123** [alibaba-fusion/next#274]
- [x ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Dialog

#### CN 
1. ok/cance按钮 已经支持Promise, 但是文档的钟函数签名错误
2. ok/cance按钮 在返回promise的等待期间, 需要表现了loading状态

#### EN
1. ok/cance buttons have supported returning a Promise but in documents, it's  function signature is wrong and effect TypeScript working.

2. ok/cance buttons is lack of loading state when return a Promise

**Comment by jdkahn** [comment]
@tao1991123 I only see support for promises for the `Show` component. That what you are referring to? I can add such documentation, but to add Promise support for the `Dialog` is more complicated due to the use of the `makeChain` function.

**Comment by tao1991123** [comment]
Now  `ok`  and `cancel` button support  sync returns, true will close window and false will do nothing.

this issue request the promise support， Promise.resolve(true) will close window and  Promise.resolve(false) will do nothing.

**Comment by jdkahn** [comment]
the function returned from `makeChain` does not return a value because it just calls the functions in a for loop.

**Comment by tao1991123** [comment]
> the function returned from `makeChain` does not return a value because it just calls the functions in a for loop.

you can estimate the cost of time.  
we recommand to implement it.
if it is too complicated actually，you may reject this issue

**Comment by jdkahn** [comment]
I was wrong, it is the `quick` dialog components inside `show.jsx` that accept promises because they use a wrapper function instead of `makeChain`. I can update the documentation in `show.jsx`

**Comment by jdkahn** [comment]
For the loading, it is simple to add a loader to buttons using the `loading` property for buttons. I can add this to the `footer.md` demo page to assist developers.

**Comment by jdkahn** [comment]
@tao1991123 I added documentation and examples for how to use promises and have the buttons show loaders, no code change was necessary. Changes made in https://github.com/alibaba-fusion/next/pull/395
