### ISSUE TITLE
[Tab]Should auto scroll to new added tab

### ISSUE THREAD

**Issue by guanpu** [alibaba-fusion/next#275]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Tab

### Feature Description
When new tab is added, if in excess-mode, it should auto activated and scroll into view.

**Comment by youluna** [comment]
any progress? @guanpu

**Comment by guanpu** [comment]
It's a legacy feature request, we can talk on if we should accept it, personally I think this enhencement request is a little bit duplicated with "excess-mode" which we already have. @youluna @bindoon @bojoyzhou

**Comment by hywww** [comment]
我也有同样的诉求，希望在打开多个tab页面的时候可以将当前tab自动滚动到可视区域

**Comment by guanpu** [comment]
I'm going to add this feature in 1.15.0

**Comment by guanpu** [comment]
Turn to 1.16

**Comment by guanpu** [comment]
Released at 1.16.0
