### ISSUE TITLE
[Dialog]希望优化一下Dialog关闭时抖动的问题

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#2750]
### Component 
Dialog
### Feature Description
背景
- 在有滚动条的页面，弹出dialog，然后关闭的时候，内容区域会向左上方抖动一下。看起来很别扭

希望
- 希望优化一下这个问题，例如等动画结束以后再恢复页面滚动条

**Comment by bindoon** [comment]
fixed in v2
will release in @alifd/next@1.25
