### ISSUE TITLE
Done-Client Skecth插件加载不出来

### ISSUE THREAD

**Issue by zevol** [alibaba-fusion/next#2756]
### Steps to reproduce
Done client在skecth上加载不出来，已尝试多次重启，及升级sketch客户端
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/TWn92qK2loEX.png)

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/sDXR7c5QSk9Y.png)

**Comment by bindoon** [comment]
故障类的问题建议通过钉钉群反馈，可以得到快速支持
