### ISSUE TITLE
[Dialog]Dialog组件在resize后的居中问题

### ISSUE THREAD

**Issue by fengxinming** [alibaba-fusion/next#2758]
### Component 
Dialog
### Feature Description
Dialog被设置了isFullScreen，当缩小浏览器窗口大小小于Dialog的大小时，Dialog未居中而是下对齐，查看浏览器控制台初步分析时:before伪类中height:100%导致。 version:1.20.28

**Comment by bindoon** [comment]
v2 版本，通过设定 height 后自动把滚动条展示出来。不再需要 isFullScreen。不设置高度默认就是 isFullScreen。

**Comment by bindoon** [comment]
fixed in #3345 , release in @alifd/next@1.25
