### ISSUE TITLE
[Tag]CSS 透出的样式配置项不足，无法在线进行主题配置 / CSS props is not sufficient for online theme editting

### ISSUE THREAD

**Issue by tao1991123** [alibaba-fusion/next#276]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Tag

#### CN
default
  - line-height (small size)
  - padding (content)

selectable 
   - right (:not(primary):after √的位置)绝对定位
   - bottom (:not(primary):after)绝对定位
   - transform (:not(primary):after medium)

#### EN

default
  - line-height (small size)
  - padding (content)

selectable 
   - right (:not(primary):after √ postion) 'position: absolute'
   - bottom (:not(primary):after) 'position: absolute'
   - transform (:not(primary):after medium)

#### 注意事项 / Notice

这个是 六个月前的Issue 可能已经不存在了

This issue was reported 6 months age and it may not exits now

**Comment by jdkahn** [comment]
@tao1991123 It looks to me like the Tag component is fully customizable with online theme editor. I am confused about what the description means. Do we want to allow for changing placement of the check?

**Comment by jdkahn** [comment]
Closing issue as this seems to be resolved.
