### ISSUE TITLE
[Step]Step组件报错，Received `false` for a non-boolean attribute `stretch`

### ISSUE THREAD

**Issue by yancekang** [alibaba-fusion/next#2765]
### Component 
Step

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/kBsjcsbwAaaN.png)

**Comment by mark-ck** [comment]
这里 stretch 是 bool 类型，你传入的 value.toString() 是字符串吧，你看看是否正确使用了这个 API
