### ISSUE TITLE
[Search]在有popupcontent的情况下无法输入空格 / unable to input a space when using popupcontent 

### ISSUE THREAD

**Issue by tao1991123** [alibaba-fusion/next#277]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.12.3

### Component
Search

### Environment
any

### Reproduction link
[https://fusion.design/component/search](https://fusion.design/component/search)

### Steps to reproduce
https://fusion.design/component/search

Custom popupcontent demo

Fail to input  a space， but other characters are ok

**Comment by youluna** [comment]
any progress ?

**Comment by youluna** [comment]
duplicated issue https://github.com/alibaba-fusion/next/issues/500
