### ISSUE TITLE
[Table]Table.Sticky z-index bug

### ISSUE THREAD

**Issue by zuoqi705** [alibaba-fusion/next#2775]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/eb6a466f](https://riddle.alibaba-inc.com/riddles/eb6a466f)

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/cJ4Kifef1cJO.png)

**Comment by youluna** [comment]
body下的z-index特地去掉了 https://github.com/alibaba-fusion/next/pull/2506/commits/a8681ea6233ec9a2106f425fd4e4b8bda1aae7aa

没有上下文，忘记当时出于什么考虑了。

为解决本issue问题，先加上

**Comment by youluna** [comment]
会出现锁列的列覆盖header的问题
https://riddle.alibaba-inc.com/riddles/1215c0eb
![image](https://user-images.githubusercontent.com/10049465/112276948-37a17300-8cbc-11eb-896c-c434454a606f.png)
