### ISSUE TITLE
[Upload]Upload组件里面的文案修改

### ISSUE THREAD

**Issue by Lucas-Zeng** [alibaba-fusion/next#2783]
### Component 
Upload
### Feature Description
我是国际化场景的，需要改upload组件里面默认的
“上传”、“取消”换成其他语言

**Comment by bindoon** [comment]
https://github.com/alibaba-fusion/next/blob/master/src/locale/zh-cn.js#L110

多语言是直接支持的。可以用 `<Upload locale={} />` 直接替换单个组件，或者使用 ConfigProvider 全局替换
