### ISSUE TITLE
[Table]Table组件设置锁列后，在使用Dialog 蒙版效果时，锁列部分未能被蒙版遮蔽，且依旧能点击锁列中设置的按钮

### ISSUE THREAD

**Issue by SHENLing0628** [alibaba-fusion/next#2785]
### Component 
Table

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/vizWUQ88qP9F.png)

复现步骤
1、创建table，并设置最右侧为操作按钮栏，column属性设置为lock:"right"

2、创建一个Dialog，设置点击其他按钮（如：新建），可以打开该具有蒙版的Dialog

3、发现问题：蒙版只能遮罩锁列以外的屏幕部分，锁列部分未能被遮盖，且锁列中渲染的button等均可照常点击

**Comment by youluna** [comment]
需要给最小复现demo。

光是问题描述是不够的，因为：
1. 问题描述中没有版本号，不知道用的什么版本
2. 没有复现demo就不知道你的代码是怎么写的，Dialog与Table的逻辑关系是什么，什么情况下出现了这种dom结构。
3. 我本地没有复现
