### ISSUE TITLE
[Select]select组件在Dialog组件里面不会自动收起弹层当我鼠标点击外围的时候

### ISSUE THREAD

**Issue by linxiaowu66** [alibaba-fusion/next#2787]
### Component 
Select

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/ccff9a69](https://riddle.alibaba-inc.com/riddles/ccff9a69)

**Comment by yancekang** [comment]
+1

**Comment by crawler-django** [comment]
+1

**Comment by bindoon** [comment]
fixed in 1.22
