### ISSUE TITLE
[DatePicker2]日期选择组件自定义页脚展示不正确

### ISSUE THREAD

**Issue by hzxshark** [alibaba-fusion/next#2789]
### Component 
DatePicker2

### Reproduction link 
[https://codepen.io/hzxshark/pen/poNqeER](https://codepen.io/hzxshark/pen/poNqeER)

### Steps to reproduce
DatePicker2.RangePicker 切换控件mode，自定义页脚展示不正确，只会展示一种mode的自定义页脚。

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/vDjqb0zZR4dD.png)

**Comment by YunMeng99** [comment]
给的demo里面显示是正确的 先关闭处理 如需继续跟进重新开启
