### ISSUE TITLE
[Dialog]基于Fusion Dialog实现了拖拽功能，在用动画的情况下，关闭弹窗，动画会自动回到拖拽前的位置，然后关闭动画

### ISSUE THREAD

**Issue by finleymma** [alibaba-fusion/next#279]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.12.3

### Component
Dialog

### Environment
macOS chrome

### Reproduction link
[无](无)

### Steps to reproduce
基于Fusion Dialog实现了拖拽功能，在用动画的情况下，关闭弹窗，动画会自动回到拖拽前的位置，然后关闭动画

**Comment by jdkahn** [comment]
@finleymma please reproduce this issue so i can better understand it. Use https://riddle.alibaba-inc.com/

**Comment by jdkahn** [comment]
Closing Issue. @finleymma Please reopen with reproduction link if you still have this issue
