### ISSUE TITLE
[Table]findDOMNode is deprecated

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#2790]
### Component 
Table

### Steps to reproduce
在 React Strict 模式下会警告：
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Row which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node

**Comment by youluna** [comment]
关注 https://github.com/alibaba-fusion/next/issues/2803

**Comment by YSMJ1994** [comment]
https://github.com/alibaba-fusion/next/issues/2803

**Comment by YSMJ1994** [comment]
https://github.com/alibaba-fusion/next/issues/2803
