### ISSUE TITLE
[NumberPicker]键盘focus到NumberPicker内部时，应该显现操作按钮

### ISSUE THREAD

**Issue by csr632** [alibaba-fusion/next#2794]
### Component 
NumberPicker

### Reproduction link 
[https://fusion.alibaba-inc.com/79480/component/number-picker?themeid=7491](https://fusion.alibaba-inc.com/79480/component/number-picker?themeid=7491)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/18747423/111427975-db75a680-8731-11eb-8313-93960244c95d.png)

再按一次tab，会focus到操作按钮上，但是操作按钮还是隐藏的。并且，此时NumberPicker的focus态消失（应该使用`:focus-within`来保持focus样式）。

**Comment by bindoon** [comment]
这个是为了支持无障碍吧，无障碍不用上下按钮来操作，而是通过 UP/DOWN 键盘来操作。不需要这两个按钮吧

**Comment by youluna** [comment]
出现按钮的逻辑应该是：当focus之后按钮出现，让人知道这是个numberpicker

**Comment by bindoon** [comment]
之前有人提过不期望展示两个按钮，期望长的像 Input
