### ISSUE TITLE
[Overlay] overlay嵌入input 复制文字鼠标出去松开不希望弹窗消失

### ISSUE THREAD

**Issue by zuoqi705** [alibaba-fusion/next#2797]
### Component 
Overlay

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/c341c787](https://riddle.alibaba-inc.com/riddles/c341c787)

### Steps to reproduce
就是鼠标在弹层内部点击，在外部松开后，不希望弹层消失。 在dialog里面就是好的～

**Comment by bindoon** [comment]
fixed in `@alifd/next@1.25` with api `v2`
