### ISSUE TITLE
[CascaderSelect]级联组件（CascaderSelect）修改了 value 类型

### ISSUE THREAD

**Issue by lianqin7** [alibaba-fusion/next#2808]
### Component 
CascaderSelect

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/faefb6a5](https://riddle.alibaba-inc.com/riddles/faefb6a5)

### Steps to reproduce
1. dataSource 里的 value 是 number 类型
2. onChange 拿到的 value 是 string 类型
3. 【根因】在 CascaderSelect 的下拉框首次 show 的时候，会导致 dataSource  发生了突变，value 类型都变成了 string

**Comment by lianqin7** [comment]
@youluna

**Comment by YSMJ1994** [comment]
可以传递 `immutable=true` 属性来阻止变化 dataSource 的行为
