### ISSUE TITLE
[DatePicker] RangePicker 支持设置自定义去掉icon

### ISSUE THREAD

**Issue by LeeChingYin** [alibaba-fusion/next#2809]
### Component 
DatePicker
### Feature Description
不同部门，不同场景有不同的诉求，对于日期范围组件，能通过配置设置是否显示日历icon。另外日历范围组件的图标设置文档不是太清楚，因为通过手动设置后，发现只能设置开始时间的图标，不能设置结束时间的图标。

**Comment by bindoon** [comment]
没看懂，没截图。
用 DatePicker2 吧

**Comment by YunMeng99** [comment]
问题描述不清楚先关闭处理，如需继续跟进重新开启
