### ISSUE TITLE
[Table]Tree树形表格如何实现懒加载，icon 目前被数据控制

### ISSUE THREAD

**Issue by Suixinlei** [alibaba-fusion/next#2816]
### Component 
Table
### Feature Description
需要 icon 可以被属性控制或者可以默认展现

**Comment by youluna** [comment]
你的需求可以通过ExpandTable实现，expand模式下icon可以通过API `rowExpandable` 控制

参考demo https://fusion.design/pc/component/table?themeid=2#expandedLock-container
