### ISSUE TITLE
[Table]Table.StickyLock

### ISSUE THREAD

**Issue by Bingzhao** [alibaba-fusion/next#2820]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/1215c0eb](https://riddle.alibaba-inc.com/riddles/1215c0eb)

### Steps to reproduce
next出现的版本：1.22.5

Table.StickyLock中stickyHeader的组件，锁定列上下滚动会覆盖表格头

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/xPbknDwxpcBE.png)

**Comment by youluna** [comment]
解决 https://github.com/alibaba-fusion/next/issues/2775 时引起，需要处理下
