### ISSUE TITLE
[ConfigProvider]希望颜色配置时可以支持渐变

### ISSUE THREAD

**Issue by ali-pay** [alibaba-fusion/next#2825]
### Type 
Platform Theme
### Component 
ConfigProvider
### Feature Description
希望配置颜色时可以使用linear-gradient函数来设置渐变色

**Comment by youluna** [comment]
渐变色是以“基础变量颜色”为维度，还是以“组件变量”为维度呢？
比如button primary模式下的背景色颜色是$color-brand1-6， checkbox 选中模式下的背景色也是$color-brand1-6。

如果以“基础变量颜色”为维度，那么$color-brand1-6 值会变成渐变色，它会影响button 和 checkbox
如果以“组件变量”为维度，那么“button primary模式下的背景色颜色”、“ checkbox 选中模式下的背景色” 可以分开搞

**Comment by ali-pay** [comment]
谢谢！我的理解是，在颜色配置的时候是以基础变量定义创建不同的颜色，也就是新增颜色的时候能够创建拥有渐变色的变量，至于组件间的颜色引用可以根据不同的变量名去区分呀。我现在的需求就是根据颜色渐变创建更加立体的按钮，不过目前平台上还只能使用纯色。(●'◡'●)
