### ISSUE TITLE
[Calendar2]Calendar2的年份选择器的下拉菜单没有勾选图标

### ISSUE THREAD

**Issue by csr632** [alibaba-fusion/next#2840]
### Component 
Calendar2

![image](https://user-images.githubusercontent.com/18747423/112957939-89427580-9174-11eb-9a9f-2b581274b949.png)

旁边的月份选择器却有勾选图标：
![image](https://user-images.githubusercontent.com/18747423/112958086-ac6d2500-9174-11eb-8fbf-a910c21f6182.png)

### Steps to reproduce

https://fusion.alibaba-inc.com/pc/component/calendar-2?themeid=2#basic-container

**Comment by youluna** [comment]
已修复
