### ISSUE TITLE
[NumberPicker]NumberPicker删除值后失去焦点期望为空值，而不是0

### ISSUE THREAD

**Issue by cccRaim** [alibaba-fusion/next#2856]
### Component 
NumberPicker

### Steps to reproduce
https://fusion.alibaba-inc.com/pc/component/number-picker?themeid=2  
删除NumberPicker的值，失去焦点，会被重置为0

表单非必填字段，期望是空值，而不是0。这会导致不可预期的数据提交。

**Comment by bindoon** [comment]
全部删除然后再失去焦点，是否返回 undefined ？

**Comment by cccRaim** [comment]
> 全部删除然后再失去焦点，是否返回 undefined ？

原来是不会自动format的，在某次更新后就自动format了。
看看是不是2天前的提交有关系，我看新增了很多判断逻辑。https://github.com/alibaba-fusion/next/commit/603f89715e312b995a0eca87f9ecfa18ec2c0b96

**Comment by cccRaim** [comment]
应该是和https://github.com/alibaba-fusion/next/blame/master/src/number-picker/number-picker.jsx#L301 这一行代码有关系
