### ISSUE TITLE
[ConfigProvider]多个页面使用了ConfigProvider，切换页面后 Dialog.show 无法正常继承 ConfigProvider

### ISSUE THREAD

**Issue by jianfei** [alibaba-fusion/next#286]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.12.3

### Component
ConfigProvider

### Environment
任意

### Reproduction link
[找我要示例代码和演示视频](找我要示例代码和演示视频)

### Steps to reproduce
页面A和B里面都包了 ConfigProvider, 并设置 prefix="foo"
正常情况下，页面A里面用 dialog.show 打开的组件里面前缀改成了"foo"
但是通过react router的push方法跳转到B页面，再跳回到A页面，再调用 dialog.show，打开的组件里面的前缀恢复成了"next"
这个现象只有 dialog.show 这种方式会出现，正常渲染的组件都没问题

**Comment by youluna** [comment]
### 原因
Dialog.show() 是函数式调用，它的context是取的ConfigProvider.getContext()的返回值，即childContextCache.root()，它是多个ConfigProvider实例共用的一份存储。

childContextCache是个map：
- 它在每个ConfigProvider实例的Constructor执行时添加，如果当前状态已经存在root，那么root不变，如果没有root，那么第一个执行constructor的ConfigProvider会设置这个root
- 它在每个ConfigProvider实例的componentWillUnmount生命周期里清除。

单页应用内，页面A 到页面B的切换其实是卸载A组件，加载B组件。从 https://github.com/facebook/react/issues/11106 可以看出，卸载是异步的，也就是从A到B的过程中，B组件的Constructor 会先于 A组件的componentWillUnmount执行，因此切换到B页面之后，childContextCache.root()变成了undefined

![image](https://user-images.githubusercontent.com/10049465/79463210-1dcacb00-802b-11ea-8845-cd496f088625.png)

### 解决方案
改变childContextCache中root值更新的时间
