### ISSUE TITLE
[Upload]upload点击按钮上传,无法重复点击按钮上传 

### ISSUE THREAD

**Issue by 371280604** [alibaba-fusion/next#2865]
### Component 
Upload

### Steps to reproduce
通过选择文件后,点击按钮才上传,场景需要支持用户再次点击按钮,可以继续上传.但是upload组件无法再次发送请求

**Comment by 371280604** [comment]
![image](https://user-images.githubusercontent.com/70129933/114329451-f50fdf80-9b71-11eb-8388-ce74cb58ac0b.png)
官网upload里的提交上传demo选择了一个文件后,多次点击上传按钮,只在第一次点击时发送请求

**Comment by bindoon** [comment]
文件肯定只上传一次呀。

**Comment by 371280604** [comment]
@bindoon 目前业务需求是需要支持重复上传,请问可以做到吗

**Comment by bindoon** [comment]
为啥要重复上传，一个文件要传多次？

**Comment by 371280604** [comment]
@bindoon 点击上传按钮后,会弹出框展示excel数据,如果用户点了取消后,可以再次点击按钮上传直接展示数据,而不需要选择文件再点击上传

**Comment by bindoon** [comment]
你这个功能应该是选择文件后有个预览功能，而不是和上传功能混合在一起。分开吧！
