### ISSUE TITLE
[Table]如果Table外层套了个div, 且div拥有高度和滚动条. 那么Table的stickyHeader失效

### ISSUE THREAD

**Issue by crawler-django** [alibaba-fusion/next#2866]
### Component 
Table
### Feature Description
如果Table外层套了个div, 且div拥有高度和滚动条. 那么Table的stickyHeader失效. 例子: https://codepen.io/crawler-django/pen/dyNZwPY?editors=0010

我目前的解决方法是改写样式来解决: 
.next-table-inner > div:first-child {
            position: sticky;
            z-index: 10;
            top: -10px;
}

Table的stickyHeader是不是不应该受外层div高度和滚动条的影响?

**Comment by youluna** [comment]
你可以通过 affixProps设置滚动的参考container来解决

`<Table affixProps={{ container: () => document.getElementById('container') }} />`

如果不设置，默认container是body，也就是说在触发“页面滚动”的条件下才会固定。
如果设置成你所说的有固定宽高的div，那么table header就参考这个div进行滚动
