### ISSUE TITLE
文档 api 错误

### ISSUE THREAD

**Issue by stickmy** [alibaba-fusion/next#2875]
### Steps to reproduce

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/sgUmGURh3Uvi.png)

**Comment by jerryyxu** [comment]
这个参数是指定面板打开的时候默认展示的月份，是没问题的，参考这个demo：https://fusion.design/pc/component/date-picker?themeid=2#defaultVisibleMonth-container
