### ISSUE TITLE
[Dialog]自定义底部的时候，传入style更改dialog宽高，按钮位置有问题

### ISSUE THREAD

**Issue by xiaran030** [alibaba-fusion/next#288]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Dialog

### Environment
所有版本均可复现

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/2179c65a](https://riddle.alibaba-inc.com/riddles/2179c65a)

### Steps to reproduce
dialog，自定义底部的时候，一旦改变dialog的宽高，底部按钮的位置却没有在底部
      
![image](https://user-images.githubusercontent.com/39256793/52110703-6bccfc00-263c-11e9-91b2-8e94889ddd7f.png)
![image](https://user-images.githubusercontent.com/39256793/52110712-6ff91980-263c-11e9-9ab7-ba67cd41604f.png)

**Comment by jdkahn** [comment]
@xiaran030 It appears you are setting inline styles for the Dialog container and so there is no way for the content to know of this. I suggest you use classes on the inner content and footer to reduce padding

**Comment by jdkahn** [comment]
@xiaran030 Did removing the inline styles not fix this problem?

**Comment by xiaran030** [comment]
As long as I customize the height of the dialog, whether it is using classes or inline-style, the position of the bottom button needs to be controlled by itself?

**Comment by jdkahn** [comment]
If you want to set a fixed height for the component you should add some additional styles for the location of the footer. You could, for example, set `position: absolute`, `bottom: 0`, `right: 0`, and have the buttons always at the bottom.
