### ISSUE TITLE
[Select]select tag模式和filterLocal有冲突

### ISSUE THREAD

**Issue by stormrise** [alibaba-fusion/next#2884]
### Component 
Select

### Reproduction link 
[https://codepen.io/stormrise/pen/qBRYNaj](https://codepen.io/stormrise/pen/qBRYNaj)

### Steps to reproduce
tag模式提供输入的内容可以作为选项，但是参数fliterLocal设置为false的情况下不能把输入的内容选进去

**Comment by bindoon** [comment]
filterLocal=false 说明是根据搜索内容展示的远程数据源；而tag 模式说明数据源里面搜不到了要用当前输入当数据源。

感觉这两者不能同时存在吧，又要用远程的，有要用本地的。

你是什么场景下既要手动输入的本地tag，又要远程tag？
