### ISSUE TITLE
[Nav]nav，mode为popup，iconOnly时收起状态，宽度可配置

### ISSUE THREAD

**Issue by LHgogogo** [alibaba-fusion/next#2888]
### Component 
Nav
### Feature Description
nav组件，mode为popup时，iconOnly为true，收起的导航的宽度，
你们代码里写死了58px，    var newStyle = newIconOnly ? (0, _extends3.default)({}, style, { width: '58px' }) : style;
这个如果不用important覆盖无解了？好像没地方配置。
需要一个参数，可以配置收起nav的宽度样式。

**Comment by youluna** [comment]
![image](https://user-images.githubusercontent.com/10049465/114823001-79be6000-9df5-11eb-8086-936df01e67cb.png)

**Comment by youluna** [comment]
用户需要的还是实例级别的
![image](https://user-images.githubusercontent.com/10049465/114968507-142bab80-9ea9-11eb-892f-f3b8702e0953.png)
![image](https://user-images.githubusercontent.com/10049465/114968511-17269c00-9ea9-11eb-9f68-887aa3d79b38.png)
