### ISSUE TITLE
[Balloon]Trigger希望可以直接传入组件

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#2892]
### Component 
Balloon
### Feature Description
  

```
<Balloon
    trigger={
        <Avatar />
    }
  />
```
上面写法无效，需要下方写法

```
<Balloon
    trigger={
      <div>
        <Avatar />
      </div>
    }
  />
```

希望
- 直接可以包裹组件使用，不需要在封装一层

**Comment by youluna** [comment]
![image](https://user-images.githubusercontent.com/10049465/114983607-68dc2000-9ec3-11eb-908c-dc1c8790f405.png)

Trigger可以不包裹、直接传入组件使用的，issue描述的问题好像不存在。是版本或者环境问题么？需要给个复线demo哦

**Comment by xmsz** [comment]
> ![image](https://user-images.githubusercontent.com/10049465/114983607-68dc2000-9ec3-11eb-908c-dc1c8790f405.png)
> 
> Trigger可以不包裹、直接传入组件使用的，issue描述的问题好像不存在。是版本或者环境问题么？需要给个复线demo哦

https://github.com/xmsz/demo-20210416

我邀请你了

没有具体测试 不只是我的写法还是依赖问题

**Comment by youluna** [comment]
如果trigger是自定义组件，需要给它透传属性例如onMouseEnter onClick等，例如
```jsx
const Avatar = (props) => {
  return (
    <div {...props}>Avatar</div>
  );
};
```
参考demo https://codesandbox.io/s/balloon-avatar-sm4jo

**Comment by xmsz** [comment]
> 如果trigger是自定义组件，需要给它透传属性例如onMouseEnter onClick等，例如
> 
> ```js
> const Avatar = (props) => {
>   return (
>     <div {...props}>Avatar</div>
>   );
> };
> ```
> 
> 参考demo https://codesandbox.io/s/balloon-avatar-sm4jo

好吧 我看到文档了，这太容易忽略了

props的类型属于哪个
