### ISSUE TITLE
[Input]Input.Texterea切换isPreview状态后autoHeight失效

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#2909]
### Component 
Input

### Reproduction link 
[https://codepen.io/xmsz/pen/qBRJwWO](https://codepen.io/xmsz/pen/qBRJwWO)

### Steps to reproduce
1. isPreview默认状态true
2. 切换isPreview状态为false
3. input的autoHeight失效 （具体表现，输入后自动变成了一行）

希望
1. 修复这个问题
2. isPreview这个一直提示没有这个类型，希望补全

**Comment by bindoon** [comment]
这个是和表单 Form 一起使用的，没有单独使用的吧。

**Comment by xmsz** [comment]
> 这个是和表单 Form 一起使用的，没有单独使用的吧。

这个From一起使用有什么关系吗？

**Comment by xmsz** [comment]
![image](https://user-images.githubusercontent.com/5879146/115987981-1fd64b00-a5ea-11eb-8286-39a0b28c30f2.png)
![image](https://user-images.githubusercontent.com/5879146/115987989-25cc2c00-a5ea-11eb-80e6-f394fb941dc7.png)
![image](https://user-images.githubusercontent.com/5879146/115987995-2a90e000-a5ea-11eb-932a-0a8fe76d8485.png)
![image](https://user-images.githubusercontent.com/5879146/115988004-3381b180-a5ea-11eb-8985-5246c4238b3d.png)

**Comment by xmsz** [comment]
@bindoon

**Comment by xmsz** [comment]
@youluna
