### ISSUE TITLE
[Select]select 无限滚动配合本地模糊搜索的样式问题

### ISSUE THREAD

**Issue by hzxshark** [alibaba-fusion/next#2911]
### Component 
Select

### Reproduction link 
[https://codepen.io/hzxshark/pen/BapGBwB?editors=0010](https://codepen.io/hzxshark/pen/BapGBwB?editors=0010)

### Steps to reproduce
当模糊搜索匹配到的结果只有一条或者数量很少的几条时，不能撑开容器高度，样式错乱。
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/SdgMuGgnkXHK.png)

**Comment by bindoon** [comment]
@youluna 似乎是虚拟滚动没有算上 padding-top padding-bottom 的间距
