### ISSUE TITLE
[Balloon]关闭按钮样式细节设计调优

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#2912]
### Component 
Balloon
### Feature Description
Balloon 关闭 Icon 大小和位置优化。
有title、有关闭按钮：
![image](https://user-images.githubusercontent.com/10049465/115645634-44fd5c00-a353-11eb-810b-48ad624e4fa0.png)

无title、有关闭按钮：
![image](https://user-images.githubusercontent.com/10049465/115645698-678f7500-a353-11eb-8d70-9c17abf12e91.png)

无title、无关闭按钮：
content撑满

**Comment by bindoon** [comment]
横线细节，有title的时候横线拉满。目前没拉满感觉略丑。
![image](https://user-images.githubusercontent.com/5189853/117623087-f0a50980-b1a5-11eb-82ce-653cfad26b19.png)
