### ISSUE TITLE
[ConfigProvider]ConfigProvider 在 SSR 的场景下会发生内存泄漏

### ISSUE THREAD

**Issue by Boelroy** [alibaba-fusion/next#2920]
### Component 
ConfigProvider

### Steps to reproduce
在 SSR 服务的压测下，我们发现 ConfigProvider 的内置缓存会发生内存的增长，没办法被 GC 掉

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/sqRqVjI664kt.png)

通过翻阅源码之后发现，虽然 [这里](https://github.com/alibaba-fusion/next/blob/48450accd638661e84747ec013a13b967807c245/src/config-provider/index.jsx#L246) 会在 `componentWillUnmount` 中移除掉这个缓存，但是在 React Issue 里面发现 https://github.com/facebook/react/issues/3714 发现在 SSR 的场景下面并不会执行 `componentWillUnmount` 的生命周期。

所以看看能不能提供出来一个手动清除缓存的 API 或者 其他更好的手段去回收 ConfigProvider 里面的缓存。

**Comment by youluna** [comment]
https://github.com/alibaba-fusion/next/blob/17a0af0ae3825b9018bc47cb5a31c4d72d9814f1/src/config-provider/index.jsx#L172
带来的副作用

**Comment by youluna** [comment]
2个思路来解决：
1. Map 换成 WeakMap
2. 增加静态方法`clearCache`回收全局变量childContextCache

**Comment by Boelroy** [comment]
ConfigProvider 没提供 clearCache 的 types. 还需要修改一下
