### ISSUE TITLE
[Upload]upload组件 js error

### ISSUE THREAD

**Issue by 185172970** [alibaba-fusion/next#2922]
### Component 
Upload

### Reproduction link 
[https://fusion.alibaba-inc.com/pc/component/upload?themeid=2#oss-container](https://fusion.alibaba-inc.com/pc/component/upload?themeid=2#oss-container)

### Steps to reproduce

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/MQVNGtnff93s.png)

upload组件使用oss上传，在上传过程中取消后，控制台报错

**Comment by 185172970** [comment]
![image](https://user-images.githubusercontent.com/21350840/115977930-d61c3f00-a5ae-11eb-965c-45ca02eed234.png)

**Comment by bindoon** [comment]
没有复现
