### ISSUE TITLE
[CascaderSelect]CascaderSelect 宽度100%bug

### ISSUE THREAD

**Issue by 185172970** [alibaba-fusion/next#2926]
### Component 
CascaderSelect

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/e1e4f67b](https://riddle.alibaba-inc.com/riddles/e1e4f67b)

### Steps to reproduce
CascaderSelect 宽度不会自动100%，和select表现不一致
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/xyJ45KQI0KOQ.png)
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/moiVTfyakFTH.png)

**Comment by YSMJ1994** [comment]
级联的交互标准与 Select 是不一样的，这是符合预期的结果
