### ISSUE TITLE
[Table]Table能否支持粘性滚动条?

### ISSUE THREAD

**Issue by crawler-django** [alibaba-fusion/next#2929]
### Component 
Table
### Feature Description

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/179nWevprhfI.png)
像antd可以设置横向的粘性滚动条. 我看了下affixProps好像只作用于header.
antd 粘性api链接: https://ant.design/components/table-cn/#API

**Comment by crawler-django** [comment]
类似demo: https://codesandbox.io/s/xuanzehecaozuo-antd4153-alpha0-forked-ex932?file=/index.js

**Comment by youluna** [comment]
需要固定的底部滚动条，这个功能可以有，PR Welcome 😄

**Comment by YSMJ1994** [comment]
Same as #4210，后续在 #4210 跟踪
