### ISSUE TITLE
[Tree]Tree查询能否支持高亮的同时，并滚动到具体位置?

### ISSUE THREAD

**Issue by crawler-django** [alibaba-fusion/next#2930]
### Component 
Tree
### Feature Description
在数量很多的情况下, Tree查询只高亮和展开了字段, 但是不会滚动到具体位置. 要一直拉下去找才行.
在demo里搜索"我在哪"
示例demo: https://codepen.io/crawler-django/pen/ZELwdvK?editors=0010

**Comment by crawler-django** [comment]
> ### Component
> Tree
> 
> ### Feature Description
> 在数量很多的情况下, Tree查询只高亮和展开了字段, 但是不会滚动到具体位置. 要一直拉下去找才行.
> 在demo里搜索"我是谁".
> 示例demo: https://codepen.io/crawler-django/pen/ZELwdvK?editors=0010

**Comment by eternalsky** [comment]
可以考虑增加功能支持在第一个高亮位置 scrollIntoView
