### ISSUE TITLE
[NumberPicker]数字输入框 props.type 不被尊重

### ISSUE THREAD

**Issue by micate** [alibaba-fusion/next#2931]
### Component 
NumberPicker

### Reproduction link 
[https://github.com/alibaba-fusion/next/blob/master/src/number-picker/number-picker.jsx#L527](https://github.com/alibaba-fusion/next/blob/master/src/number-picker/number-picker.jsx#L527)

### Steps to reproduce
数字输入框在 device 为 phone 时将 type 强制指定为了 inline，这个设计是不是不太符合预期。

当用户没有指定 type 时可以根据设备类型自动适配，但当 props 中指定了之后应该以 props 为准。

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/5Gh8VXxAH8ct.png)

**Comment by youluna** [comment]
这个考虑的是在移动端模式下，numberpicker不需要inline的模式，因为手机端没有hover状态，也很难点到输入框里的上下button
![image](https://user-images.githubusercontent.com/10049465/116065773-eec54b80-a6b9-11eb-849b-4223db262fc2.png)

**Comment by micate** [comment]
我们的页面会跑在钉钉容器内，此时容器的宽度可能会变化，触发了 device 重新计算为 'phone', 'tablet', 'desktop' 等。
此时用户会感知到表单样式发生了变化，但不了解为什么，为了保持一致性，期望能统一显示为 normal。

另外一个方案就是我们强制覆盖业务中使用 NumberPicker 的场景 device 为 desktop，应该也能解决我们的问题。

但作为组件实现层面，强制覆盖 type 总感觉不是很妥当，或许需要在文档中备注下这个逻辑，你们可以考虑下。

**Comment by youluna** [comment]
这里是做了多端适配，当device为phone时，有部分组件单独做了优化处理，numberpicker就是其中一个，我们内部评估下来这个逻辑仍然保留哈，我这边优化下文档
