### ISSUE TITLE
[Input]Disabled 输入框不应该显示清除按钮

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#2933]
### Component 
Input

### Steps to reproduce
对于 Disabled 的输入框等，因为无法交互，所以不应该显示清除按钮。但是现在清除按钮会一直显示：

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/ASRW1k5DJkmE.png)

**Comment by weinianyang** [comment]
您说的情况，已经做了修复，感谢反馈。
