### ISSUE TITLE
[Form]校验时使用 label 替代 name / use label as name for validate

### ISSUE THREAD

**Issue by bindoon** [alibaba-fusion/next#294]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Form

### Feature Description

```
<FormItem label="名称">
    <Input name="username"/>
</FormItem>
```

```
username 是必填字段 
```
to 
```
名称 是必填字段 
```

**Comment by youluna** [comment]
any progress? @bindoon

**Comment by youluna** [comment]
https://github.com/alibaba-fusion/next/issues/345 这两个是关联issue吧

**Comment by bindoon** [comment]
不是同一件事情，这个是校验出错提示的时候希望不用name而是用formitem上的label

**Comment by bindoon** [comment]
是个feature，不过改动会比较大，涉及form field validate 三个组件的修改。先不着急处理！

**Comment by huarse** [comment]
我记得之前提过类似的，但是我希望是提供一个通用的全局设置方法，比如 

```js
Field.setConfig({
  message: {
    required: '请填写 {label}',
    format: '请输入正确的 {label}'
  }
});
```

现在虽然使用 Form.Item 方便了很多，但是一个页面如果有50个字段，每个字段除了写 label，还得写 requiredMessage
