### ISSUE TITLE
[Menu]Menu组件新增业务自定义配置icon

### ISSUE THREAD

**Issue by huguoliang1314** [alibaba-fusion/next#2950]
### Component 
Menu
### Feature Description
业务需求：
   左侧菜单栏的展开收起icon，目前默认写死了空心的icon（type为arrow-down），无法配置。现在希望这块能做成配置点，放在主题包的配置平台进行配置，无须业务开发。

**Comment by youluna** [comment]
![image](https://user-images.githubusercontent.com/10049465/116559308-e4fa4d00-a932-11eb-9562-44c870bb69e7.png)
现在已经支持了，需要改Menu组件
