### ISSUE TITLE
[Select]多个Select框在Dialog下面不会自动收起

### ISSUE THREAD

**Issue by heny** [alibaba-fusion/next#2959]
### Component 
Select

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusionzujianceshi-unkc3?file=/src/DialogForm.js)

**Comment by bindoon** [comment]
确认在 React 17 有问题

**Comment by bindoon** [comment]
fixed in 1.24
