### ISSUE TITLE
[Input]TextArea最大长度限制不起作用

### ISSUE THREAD

**Issue by houseBetter** [alibaba-fusion/next#2963]
### Component 
Input

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/9f96ef06](https://riddle.alibaba-inc.com/riddles/9f96ef06)

### Steps to reproduce
输入最大长度内容后，用中文输入法，输入拼音，但不要把字打出来，
此时拼音下面有下划线，在这种状态下，鼠标点其它的地方，拼音
能输入进去

**Comment by youluna** [comment]
fusion的在超出长度限制后，如果处于拼音输入过程中，点击一下页面空白地方，会出现cutstring特性无效的问题
https://img.alicdn.com/imgextra/i2/O1CN01VUYxSY29uDVI1hkIw_!!6000000008127-1-tps-1790-1096.gif
