### ISSUE TITLE
[Breadcrumb]支持自定义省略号的能力

### ISSUE THREAD

**Issue by luckydrq** [alibaba-fusion/next#2968]
### Component 
Breadcrumb
## 背景
目前组件支持设置`maxNode`指定`Breadcrumb.Item`的最大展示个数，超过部分采用省略号展示，而省略号现在是写死的：https://github.com/alibaba-fusion/next/blob/master/src/breadcrumb/index.jsx#L160 

## 需求
对于一些场景需要省略号有更丰富的交互能力，例如：点击省略号展示被折叠的项，方便用户快速导航。

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/8d6CyHEmhaYO.png)

因此，希望组件能够支持自定义省略号。

### 方案一
`Breadcrumb` 新增 `ellipsisNode` 属性，支持传入`ReactNode`或者`function`，类型为：`ReactNode | (collapseItems: ReactElement[]) => ReactNode`，当传入`function`时，它接收**被折叠的项**作为参数。

### 方案二
组件直接内置*点击省略号展示被折叠项弹层*的交互模式。其中，弹层使用`Dropdown`组件。

## 讨论
方案一更灵活，可自由定制省略号的展示和交互，但成本更大。
方案二大幅减少对于使用成本，前提是*Fusion Design认可这种交互是通用的并且没有其他的定制需求*。

**Comment by youluna** [comment]
面包屑的场景比较固定 @设计师 看下是否可以直接使用方案二
