### ISSUE TITLE
[Table]特定场景下 fixedHeader 无效果

### ISSUE THREAD

**Issue by acrens** [alibaba-fusion/next#2969]
### Component 
Table

### Steps to reproduce
Table 内包含 Table.GroupHeader 时，fixedHeader 无效果

**Comment by youluna** [comment]
在有group header的模式下，建议使用 `<Table fixedHeader stickyHeader />  `

我先加下文档说明Table.GroupHeader 不支持fixedHeader，如果有迫切需求一定需要Table.GroupHeader 支持fixedHeader模式，再沟通哈
