### ISSUE TITLE
[Field]validatePromise返回错误问题

### ISSUE THREAD

**Issue by MosinNg** [alibaba-fusion/next#2976]
### Component 
Field
### Feature Description
           

这个api非常奇怪，返回Promise的错误，为啥不用reject函数返回呢，error first返回错误信息这不是callback风格的用法吗。
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/PJp6qwRRYvhH.png)

**Comment by MosinNg** [comment]
API文档上也没有validatePromise这个API说明 

只有demo上有，这个API是不建议使用吗

**Comment by bindoon** [comment]
async function() {
  const result = await this.field.validatePromise(); 
}
是这么拿到的，目前还没透出！
