### ISSUE TITLE
[Nav]Nav组件点击及鼠标来回滑上滑下时，会有多余线闪动

### ISSUE THREAD

**Issue by CurryChou777** [alibaba-fusion/next#2980]
### Component 
Nav

### Reproduction link 
[https://codepen.io/zhouhuanhuan/pen/YzZwwXg?editors=0010](https://codepen.io/zhouhuanhuan/pen/YzZwwXg?editors=0010)

### Steps to reproduce
**重现步骤**
1、设置为hoz normal模式
2、点击切换菜单，之后在各菜单之间来回滑动，滑入滑出
3、菜单项下面会不时出现多余线段，如图

**期望结果**
期望操作过程中无多余线段出现

**实际结果**
不时出现不明线段

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/AoQqQ01RP7ue.png)

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/TYlY6OJfOtov.png)

**Comment by youluna** [comment]
多次切换选中项，chrome可以复现，safari firefox无法复现。

暂时没有什么思路，有想法的欢迎评论🙏

**Comment by YSMJ1994** [comment]
现在好像复现不了了，麻烦再 check 一下

**Comment by YSMJ1994** [comment]
Stale
