### ISSUE TITLE
[Select]请教：有什么方式可以在input/select的changeEnd执行

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#2983]
### Component 
Select
### Feature Description
背景
- 我有一个需求大概是

```
const [value,setValue] = useState()

const handleSubmit = () => {
   console.log(value); // 这里是旧的值
}

<Select 
  onChange={(val) => {
    setValue(val);
    handleSubmit()
}}
>
</Select>
```

限制条件
- handleSubmit 不可用传参

我想实现
- 在handleSubmit里拿到的值是新的 

如果我使用Search就可以实现，因为我可以

```
<Search
   onSearch={handleSubmit}
   onChange={setValue}
/>

```
这样就不会因为setState异步的问题造成拿到就值

--------

所以我的问题是

- input/select 能否有个类似与onSearch这样的事件回调，例如select，就是选择后再进行触发，但是这个多选的情况可能有问题
- 或者有没有其他办法解决这样的需求

尝试过的方案
- onBlur : 失败，因为选择后不会触发
- onVisibleChange： 失败，因为onVisibleChange比onChange快
- onChange  + useEffect + 是否是onChange状态判断（原理是只处理通过onChange改变值的情况）: 能用，但是复杂且不保险
- onChange + 组件内state + useEffect(原理是只处理通过onChange改变值的情况): 能用，但是逻辑不完善，实现更复杂
- 弹窗选择手动提交按钮：适用于多选，普通的没必要体验不好

**Comment by bindoon** [comment]
可以通过节流的方式吧，比如输入停止后1s才触发请求

**Comment by xmsz** [comment]
> 可以通过节流的方式吧，比如输入停止后1s才触发请求

cool 理论确实可以 利用时间差
