### ISSUE TITLE
[DatePicker]DatePicker的value为什么不能接受null值

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#2987]
### Component 
DatePicker
### Feature Description
背景
- DatePicker的onChange，会有值为[null,null]的时候
- 所以理论上value也应该可以接受null的类型
- 但是现在只能传undefined和number以及dayjs
- 这就导致，我如果想onChange里的值直接付给value类型就会报错，为了解决类型，我还得把null转成undefined

需求
- value支持null[]类型

**Comment by jerryyxu** [comment]
DatePicker.RangePicker 是支持 null[] ，是有报错吗？麻烦提供一下demo。

**Comment by xmsz** [comment]
> DatePicker.RangePicker 是支持 null[] ，是有报错吗？麻烦提供一下demo。

![image](https://user-images.githubusercontent.com/5879146/120982466-52f42880-c7ab-11eb-8da7-d4a29a09c911.png)
![image](https://user-images.githubusercontent.com/5879146/120982510-5e475400-c7ab-11eb-8041-59a8cf5376e9.png)

https://github.com/alibaba-fusion/next/blob/master/types/date-picker2/index.d.ts#L85

会出现类型重载错误

**Comment by lakerswgq** [comment]
是不是开启了 strictNullChecks
