### ISSUE TITLE
[NumberPicker]number-picker输入负数有问题

### ISSUE THREAD

**Issue by mosikoo** [alibaba-fusion/next#2989]
### Component 
NumberPicker

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/10f48a2b](https://riddle.alibaba-inc.com/riddles/10f48a2b)

### Steps to reproduce
尝试在我的demo上输入-0.02，然后发现无法输入

**Comment by youluna** [comment]
输入 -0.02，无法通过移动光标更改成 -1.02
