### ISSUE TITLE
[Select]有没有可以组合MenuSelect和TagSelect

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#2991]
### Component 
Select
### Feature Description
背景
我们想要实现以下效果，类似于Search组件。左边是MenuSelect，右边是TagSelect
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/pQqSgIPyP0Me.png)

希望
- 可以和Search一样有组合在一起

**Comment by bindoon** [comment]
可以用 Input Group 自己包起来 https://fusion.design/pc/component/input?themeid=2#group-container
