### ISSUE TITLE
[Switch]field和switch交互不能联动

### ISSUE THREAD

**Issue by fengmumu1** [alibaba-fusion/next#2997]
### Component 
Switch

### Reproduction link 
[https://codepen.io/fengmumu1/pen/bGqpYwm](https://codepen.io/fengmumu1/pen/bGqpYwm)

### Steps to reproduce
使用filed设置组件的值后，组件值被重置，但是样式没有变过来

**Comment by fengmumu1** [comment]
<Switch { ...init('checked',{valueName: 'checked'})} />
这样就可以了

**Comment by bindoon** [comment]
准备优化下 Field 的文档，写上 checkbox/radio/switch 的valueName='checked'
