### ISSUE TITLE
[Icon]希望提供“一键替换”功能

### ISSUE THREAD

**Issue by luckydrq** [alibaba-fusion/next#3001]
### Type 
Platform Theme
### Component 
Icon
## 背景
想用新的一批icon**替换**老的一批（之前配置的）icon，不希望是仅仅是合并   覆盖。因为老的一批icon里有不少是不再需要的，需删除。目前只能手动一个一个删。

## 建议
希望提供**一键替换**功能，直接使用新的一批icon。

**Comment by bindoon** [comment]
icon 名称相同即可替换
