### ISSUE TITLE
[Slider]meet  SlideView组件 h5 iphone 11 兼容性问题

### ISSUE THREAD

**Issue by zhiqiangx** [alibaba-fusion/next#3002]
### Component 
Slider

### Steps to reproduce
meet  SlideView组件 在iphone 11上只剩背景

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/KqSIBJCmPMW3.png)

**Comment by youluna** [comment]
这里是Fusion Next pc组件库的仓库，关于meet的问题搜内网群“Fusion Mobile 2.0 vip 服务” 反馈哈
