### ISSUE TITLE
[CascaderSelect]CascaderSelect搜索及选择后没有清空结果

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#3008]
### Component 
CascaderSelect
### Feature Description
背景
- 多选加搜索的时候
- 用户已经选中了所有结果项
- 但是还是停留在搜索结果页
- 用户不知道接下去该怎么操作，或者如何返回所有列表页
- 必须要点击弹窗外，重新打开下拉框才能返回
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/NeL7Wv9ERrim.png)

需求
- 能否有个当已选择完所有结果后自动清除搜索结果的机制
- 或则能否有个清除搜索结构的按钮，用户点击这个按钮可以清除当前搜索的字段

**Comment by YSMJ1994** [comment]
同 #3154 ，欢迎 PR
