### ISSUE TITLE
[Overlay] table lock情况下，在lock列的header添加popup，受控模式下展示异常 / Overlay bug when table works in lock column mode

### ISSUE THREAD

**Issue by tao1991123** [alibaba-fusion/next#301]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/64f9c05f](https://riddle.alibaba-inc.com/riddles/64f9c05f)

### Component
Overlay

### Environment
Mac Chrome

### Steps to reproduce
1. Set Table component to column lock mode and controlled mode
2. add popup for  table header
3. it will display not correctly

### More
table lock的原理是将lock的列复制一份使用fix定位渲染到页面上，产生锁列效果。 在table lock 列的header上添加popup，受控模式下，相当于用一份state数据控制了两处popup的展示，popup也分别注册了

table lock is implemented by copy locked colunm and fix it on the screen page.
at table controlled mode， one piece of state data will register two popup. it causes bug.

for more  to ask @youluna 

![](https://img.alicdn.com/tfs/TB17vEOGkvoK1RjSZFwXXciCFXa-1060-827.png)

**Comment by jdkahn** [comment]
@tao1991123 The problem is caused by document click handler for the other paired popup. The `safeNode` properties need to be set to ignore the paired popup trigger and content. See here for an example https://codesandbox.io/s/4z57x1qmyx.
