### ISSUE TITLE
[Upload]upload组件上传图片需要支持重传功能

### ISSUE THREAD

**Issue by bondli** [alibaba-fusion/next#3010]
### Component 
Upload
### Feature Description
目前上传组件默认提供下载和删除，我们的场景不需要下载，也认真思考了下没有什么地方需要下载，我需要能有个重传的功能入口

**Comment by bindoon** [comment]
确认需求OK，设计师这边先产出视觉交互 @Zitian770

**Comment by bindoon** [comment]
设计师设计反馈如下：
![image](https://user-images.githubusercontent.com/5189853/119101890-0dfe9100-ba4c-11eb-9ef1-d409b997e577.png)

上传出错后把下载按钮换成 圆圈 刷新按钮。目前暂时没有更多操作按钮的诉求，暂时不做。

TODO:
需要增加 api 配置控制 1. 是否展示下载按钮 2. 是否展示重新上传按钮
