### ISSUE TITLE
[Overlay]overlay content抖动 / overlay content bounces

### ISSUE THREAD

**Issue by tao1991123** [alibaba-fusion/next#302]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Overlay

### Environment
mac chrome

### Reproduction link
[http://git.cn-hangzhou.oss-cdn.aliyun-inc.com/uploads/next/overlay/2c4a1bae52843eab96acd1313386f10c/QQ20181031-132702-HD.mp4](http://git.cn-hangzhou.oss-cdn.aliyun-inc.com/uploads/next/overlay/2c4a1bae52843eab96acd1313386f10c/QQ20181031-132702-HD.mp4)

### Steps to reproduce
overlay content抖动, 有鼠标的时候 

overlay content bounces

**Comment by jdkahn** [comment]
@tao1991123 It seems this issue has been resolved. Can you confirm https://fusion.design/design/component/message?

**Comment by jdkahn** [comment]
Closing as this seems to be fixed
