### ISSUE TITLE
[Upload]itemRender 不支持删除功能

### ISSUE THREAD

**Issue by bojhkaka** [alibaba-fusion/next#3022]
### Component 
Upload

### Steps to reproduce
upload组件使用itemRender时，缺少删除功能，版本1.22.0
![image](https://user-images.githubusercontent.com/6252290/119342733-1531d300-bcc8-11eb-9880-3f33d9c867b1.png)

**Comment by bindoon** [comment]
fixed in #3034 
will be released in @alifd/next@1.24
