### ISSUE TITLE
[Table]table表格合并后，点击合并后的单元格展开详情，表格样式出问题

### ISSUE THREAD

**Issue by chichi12311111** [alibaba-fusion/next#3026]
### Component 
Table

**Comment by youluna** [comment]
出什么问题呢？

**Comment by chichi12311111** [comment]
两行单元格合并之后，点击合并后的单元格展开列表，默认展开了第一行的数据 导致页面乱掉，不知道这块有没有什么配置能够避免这种场景？
我目前的做法是：通过合并计算得出合并之前的末端行数作为当前行展开，就不会让页面乱掉了。
