### ISSUE TITLE
[Search]高度比同大小的 button 多两个像素

### ISSUE THREAD

**Issue by tao1991123** [alibaba-fusion/next#303]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.5.6

### Component
Search

### Environment
mac

### Reproduction link
[https://img.alicdn.com/tfs/TB1HqEJGb2pK1RjSZFsXXaNlXXa-1590-1528.png](https://img.alicdn.com/tfs/TB1HqEJGb2pK1RjSZFsXXaNlXXa-1590-1528.png)

### Steps to reproduce
![](https://img.alicdn.com/tfs/TB1HqEJGb2pK1RjSZFsXXaNlXXa-1590-1528.png)

**Comment by youluna** [comment]
@tao1991123 这个问题是不是解决了 现在还有么？

**Comment by youluna** [comment]
关注issue https://github.com/alibaba-fusion/next/issues/386
