### ISSUE TITLE
[Select]在弹窗中使用下拉框组件，弹窗出现滚动条时，展开的下拉框位置停滞

### ISSUE THREAD

**Issue by zxzybin** [alibaba-fusion/next#3031]
### Component 
Select

### Steps to reproduce
所有带有下拉框的组件（例如select || datePicker 等等），在弹窗中使用时，当弹窗出现滚动条时，下拉框会固定在当前位置，不会滚动
下拉框位置停滞.png
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/5D7Xw1I51rRh.png)

**Comment by zxzybin** [comment]
麻烦官方小哥哥或者小姐姐及时处理，急急急！！！

**Comment by bindoon** [comment]
增加api followTrigger

**Comment by crawler-django** [comment]
我这边有个比较奇怪的现象.
![image](https://user-images.githubusercontent.com/37062307/119777980-7d1b3000-bef9-11eb-8cd1-a16085c13fde.png)
在这个Dialog里, 点击Dialog里面的空白 DatePicker/Select失焦都不会关闭对应的overlay.
但是点击灰色蒙层的话就可以....
(关键还是我建demo的话重现不了这个问题...)
