### ISSUE TITLE
[Table]表格虚拟滚动交互Bug

### ISSUE THREAD

**Issue by wwyx778** [alibaba-fusion/next#3035]
### Component 
Table

### Reproduction link 
[https://fusion.alibaba-inc.com/pc/component/table#virtual-container](https://fusion.alibaba-inc.com/pc/component/table#virtual-container)

### Steps to reproduce
官方的codepen例子中:
1.滚到底部后再向下滚动整个表格会抖动
2.向上缓慢滚动会有跳行的情况
如图，猜测是没有设置缓冲区的原因。

![tar](https://user-images.githubusercontent.com/28632663/119753604-9dcf8f80-bed1-11eb-9d4c-492b072cc898.gif)

**Comment by youluna** [comment]
分析了下原因，应该是屏幕宽度导致了id列内容折行，行高不同，第一行行高小，第二行行高大。现在table的虚拟滚动不支持行高不同，它计算的时候都是拿第一行的行高来计算，所以一旦有了折行计算就会有偏差。改大id列的width可以绕过这个问题先
