### ISSUE TITLE
[Search]CSS 透出的样式配置项不足，无法在线进行主题配置

### ISSUE THREAD

**Issue by tao1991123** [alibaba-fusion/next#304]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Search

### Feature Description
border (split)
height (input medium)
height (simple 类型 调整整体高度)
padding-left padding-right (btn medium)
width (btn)

**Comment by youluna** [comment]
感觉这类需求优先级不高
