### ISSUE TITLE
[Image] 希望可以新增Image组件

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#3042]
### Component 
Overlay
### Feature Description
背景
- 项目中有点击图片展开预览的需求
- 看到只有sixue-photo-preview这个官方插件，但是发现功能太奇怪了（不能满足需求）
- 然后antDesign本身有https://ant.design/components/image-cn/支持

需求
- 官方图片预览查看，支持全屏、缩放、下载、旋转、多图等基础功能

**Comment by youluna** [comment]
目前没有这样的规划😂

**Comment by xmsz** [comment]
> 目前没有这样的规划😂

那有推荐的插件吗，没找到合适的

**Comment by YSMJ1994** [comment]
Stale
