### ISSUE TITLE
[Upload]上传组件显示跨域

### ISSUE THREAD

**Issue by camellieeee** [alibaba-fusion/next#3047]
### Component 
Upload

### Steps to reproduce
ice.js: 1.0.0
接口已经做了跨域配置，但是请求还是显示跨域
1622375025926.jpg
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/M1iG4CCPeBR1.png)
1622375196380.jpg

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/yfCdQxx6ZKeK.png)
1622375283889.jpg

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/0CzeBlYXv8U4.png)

**Comment by bindoon** [comment]
这个需要你 apistrain.daiping.cc 要支持跨域，和组件没关系！
