### ISSUE TITLE
[Table]table有lock锁列后排序, onsort返回的order一直是desc, 排序后有ajax后台排序, 本地数据排序和没有lock都是正常的.

### ISSUE THREAD

**Issue by j787701730** [alibaba-fusion/next#3053]
### Component 
Table

### Steps to reproduce
table有lock锁列后排序, onsort返回的order一直是desc, 排序后有ajax后台排序, 本地数据排序和没有lock都是正常的. 只有锁列所在的列才有问题, 其他的都正常. (还是jQuery爽. 自己造轮子. )

**Comment by aaronyyan** [comment]
换成 StickyLock 就好了

**Comment by youluna** [comment]
老的锁列实现方式，如果要排序的列是左锁列或右锁列，的确会出现排序样式没有变化的问题，是个已知问题，用 Table.StickyLock 可以解决哈

**Comment by j787701730** [comment]
@youluna , @aaronyyan 谢谢解答
