### ISSUE TITLE
[Form] Form.Item的 requiredTrigger 支持什么值？

### ISSUE THREAD

**Issue by cwtuan** [alibaba-fusion/next#3063]
### Component 
Form
### Feature Description
Form.Item的 requiredTrigger 支持什么值？

https://fusion.design/pc/component/form?themeid=2#Form
文档没看到详细的说明

![image](https://user-images.githubusercontent.com/3455798/120581142-df75b280-c45c-11eb-850d-5b124b92eb37.png)

**Comment by youluna** [comment]
![image](https://user-images.githubusercontent.com/10049465/120581673-c6213600-c45d-11eb-8ea4-a4d446942a3d.png)

Form上的requiredTrigger参数，是 Field组件上 rules的缩写，它表示在什么时机下触发必填校验，值可以是原生事件onBlur onChange等，推荐是onBlur

修改下文档吧，这个用法太隐晦了
