### ISSUE TITLE
[Table]Table 组件横向滚动的时候内容区域会抖动 查看官方例子即可

### ISSUE THREAD

**Issue by aaronyyan** [alibaba-fusion/next#3064]
### Component 
Table

**Comment by youluna** [comment]
可以截图或者视频辅助说明

**Comment by aaronyyan** [comment]
![Kapture 2021-06-03 at 15 42 55-min](https://user-images.githubusercontent.com/39476555/120611007-51162680-c486-11eb-9f5d-24fb0dcb1cbe.gif)
@youluna

**Comment by YSMJ1994** [comment]
目前已无法复现问题，看起来已修复 https://fusion.alibaba-inc.com/dsm/pc/components/detail/table?themeid=2#multipleHeader-container
