### ISSUE TITLE
[Balloon]trigger 如果是 disabled Button 组件，鼠标移出 Button 无法自动消失

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#308]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.12.3

### Component
Balloon

### Environment
chrome

### Steps to reproduce
chrome 的bug 
https://github.com/facebook/react/issues/4251

hack方案可参考：
https://github.com/react-component/tooltip/issues/18#issuecomment-411476678

**Comment by csr632** [comment]
这个问题又重新出现了：https://github.com/alibaba-fusion/next/issues/308

```jsx
import { Button, Balloon, Input } from "@alifd/next";

const App = () => (
  <div style={{ margin: 280 }}>
    <Balloon
      // v2
      trigger={
        <span>
          <button disabled>test</button>
        </span>
      }
      align="t"
      closable={false}
    >
      <div>content content content content content</div>
    </Balloon>
  </div>
);

ReactDOM.render(<App />, mountNode);
```

**Comment by bindoon** [comment]
这个问题暂时还没找到解法，可以在 disabled 的 button 上面加 style={{ pointerEvents: 'none' }} 来避归此问题

```jsx
<Balloon
      trigger={
        <span>
          <button disabled  style={{ pointerEvents: 'none' }}>test</button>
        </span>
      }
      align="t"
      closable={false}
    >
      <div>content content content content content</div>
</Balloon>
```

**Comment by csr632** [comment]
@bindoon 你回复的方法不管用呀，在riddle上试试：https://riddle.alibaba-inc.com/riddles/9dd9c08b

**Comment by bindoon** [comment]
已确认可用
