### ISSUE TITLE
[Tab]移动端的 Tab、Dialog、Drawer 组件是否可以不再依赖 PC 端的 @alifd/next 中的资源？

### ISSUE THREAD

**Issue by air-eienniutau** [alibaba-fusion/next#3080]
### Component 
Tab

### Reproduction link 
[https://github.com/alibaba-fusion/next/blob/build/1.23.4/src/tab/mobile/index.jsx#L2](https://github.com/alibaba-fusion/next/blob/build/1.23.4/src/tab/mobile/index.jsx#L2)

### Steps to reproduce
最新的 @alifd/meet-react 已经存在 Tab、Dialog、Drawer 组件了(http://gitlab.alibaba-inc.com/fusion-mobile/meet/tree/master/src)，当前的 mobile 代码中判断 meet 组件不存在时降级到 PC 端版本的逻辑，会导致打包时额外打包 PC 端 @alifd/next 中资源。是否已经可以移除此降级逻辑了？

https://github.com/alibaba-fusion/next/blob/build/1.23.4/src/tab/mobile/index.jsx#L2
https://github.com/alibaba-fusion/next/blob/build/1.23.4/src/dialog/mobile/index.jsx#L2
https://github.com/alibaba-fusion/next/blob/build/1.23.4/src/drawer/mobile/index.jsx#L2

**Comment by youluna** [comment]
@lianmin 给一下现在的mobile组件列表吧，我把确定有的这些组件去掉对next的依赖

**Comment by youluna** [comment]
1.24里改掉

**Comment by fengsx** [comment]
为什么会把 alibaba-inc 的地址放出来~
