### ISSUE TITLE
[Slider]Slider在scale容器下高度计算有问题

### ISSUE THREAD

**Issue by H5DevHoward** [alibaba-fusion/next#3082]
### Component 
Slider

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-template-forked-d18r0?file=/src/index.js)

### Steps to reproduce
等比缩放实现自适应的场景，给容器设置scale后，slider自动轮播高度计算有问题，部分内容显示不全

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/fe0B2oTJRyNj.png)

**Comment by youluna** [comment]
期望slideToShow不受scale影响：
补充demo：https://codesandbox.io/s/fusion-next-template-forked-nrmh4?file=/src/index.js
![image](https://user-images.githubusercontent.com/10049465/121145337-6c5fa800-c871-11eb-85f2-9e025365bd1e.png)

**Comment by youluna** [comment]
差别在于获取内容高度的方法上，react-slick用的是 `offsetHeight`
 https://github.com/akiran/react-slick/blob/5fb7ac78321f3469118a974af3852742b64fcbd3/src/utils/innerSliderUtils.js#L54-L55

基础组件是先用 `getBoundingClientRect` 再用 `offsetHeight`
https://github.com/alibaba-fusion/next/blob/abcdb0ce0ad33930f32e53bfdf14c342a29b29fa/src/slider/slick/mixins/helpers.js#L63-L69
