### ISSUE TITLE
[Form]Form label 折行行高过大

### ISSUE THREAD

**Issue by zuoqi705** [alibaba-fusion/next#3087]
### Component 
Form

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/7303aadc](https://riddle.alibaba-inc.com/riddles/7303aadc)

### Steps to reproduce
希望可以在折行的时候行高变小，或者超出省略，hover 显示 tooltip

**Comment by youluna** [comment]
![image](https://user-images.githubusercontent.com/10049465/121315528-00e20d00-c93b-11eb-93b2-7ef1ca7547cf.png)
![image](https://user-images.githubusercontent.com/10049465/121316240-b1e8a780-c93b-11eb-9cec-be9c5f62a981.png)

## 现在的问题

1. label超长情况下，行高太高导致空间浪费
2. label文字跟输入框文字垂直不对齐

## 解法
有两个交互方案：
### 1. 文字超长隐藏的交互方案
![image](https://user-images.githubusercontent.com/10049465/121315654-2111cc00-c93b-11eb-84cd-aa204d7c5cb4.png)

参考demo https://riddle.alibaba-inc.com/riddles/67a3bf66

### 2. 文字超长折行、全显示的方案
![image](https://user-images.githubusercontent.com/10049465/121316580-0db33080-c93c-11eb-8eb5-9e9a63cb9da5.png)
修改实现方式，用margin-top实现

其中方案1是现成的，方案2需要组件层面做改造支持。方案2在2.x中应当是默认模式
