### ISSUE TITLE
[Table]Table rowSelection的onChange里的selectedRowKeys和records的数量不一致

### ISSUE THREAD

**Issue by crawler-django** [alibaba-fusion/next#3090]
### Component 
Table

### Reproduction link 
[https://codepen.io/crawler-django/pen/RwpBYMr?editors=0010](https://codepen.io/crawler-django/pen/RwpBYMr?editors=0010)

### Steps to reproduce
重现步骤: 查看console.log()  ---->  先随便勾选两行  ----->  然后删除勾选中其中的一行  ----->  再勾选一行未选中的  ----->  console.log出来的selectedRowKeys 和 records的length不一致,  一个长度为3, 一个为2

**Comment by crawler-django** [comment]
我现在的处理就只能record.map映射出来对应的keys,,

**Comment by crawler-django** [comment]
![image](https://user-images.githubusercontent.com/37062307/121334442-3cd19e00-c94c-11eb-8969-a95ce1687b49.png)

**Comment by youluna** [comment]
![image](https://user-images.githubusercontent.com/10049465/121487520-bf1d9900-ca04-11eb-95d5-786ead11cc00.png)

这里的设计是这样的：records 拿到的数据是 selectedRowKeys ∩ dataSource，组件本身不存历史的recored。

selectedRowKeys 不会做数据删除处理，有些模式比如翻页情况下，是需要保留历史数据的，所以不做数据删除。

========
这里你可以通过受控做处理哈

**Comment by crawler-django** [comment]
好的.... 翻页也要保留 我是没想到的...  一般翻页我就会重置selectedRowKeys了..

**Comment by youluna** [comment]
我们遇到过跨页选择的需求，所以这个能力保留哈
