### ISSUE TITLE
[Calendar2]Calendar2

### ISSUE THREAD

**Issue by hioak** [alibaba-fusion/next#3100]
### Component 
Calendar2

### Steps to reproduce
Calendar2的onVisibleMonthChange好像没实现

**Comment by YSMJ1994** [comment]
`onVisibleMonthChange` 在 Calendar2 组件有新的实现方法，https://fusion.design/pc/component/calendar-2?themeid=2#defaultVisibleMonth-container
文档中多余的 `onVisibleMonthChange` 我们会在近期移除
