### ISSUE TITLE
[Upload]Upload.Dragger设置limit后无法点击也没有提示

### ISSUE THREAD

**Issue by sxei** [alibaba-fusion/next#3107]
### Component 
Upload

### Steps to reproduce
<Upload.Dragger
            listType="image"
            limit={2}
        />
上传2张照片后无法点击，但没有任何提示，让用户认为是bug

**Comment by bindoon** [comment]
是否有设计稿嗯？可以看看你们的交互是什么样？

**Comment by YSMJ1994** [comment]
Stale
