### ISSUE TITLE
[NumberPicker] win10+chrome+微软输入法打开的情况下 输入09 会变成 99

### ISSUE THREAD

**Issue by bindoon** [alibaba-fusion/next#3110]
### Component 
NumberPicker

### Steps to reproduce
https://fusion.design/pc/component/number-picker?themeid=2#basic-container

- win10 / chrome / 微软中文输入法打开
- 输入 09 会变成 99
- 版本 next@1.23

![image](https://user-images.githubusercontent.com/5189853/122225026-437d8980-cee7-11eb-8b20-3602d5007b93.png)

**Comment by bindoon** [comment]
我看原生的 `<input />`  `<input type=number />` 都没问题，需要确认我们组件哪个环节导致的该问题

**Comment by galogm** [comment]
定位为原生input问题，原生input复现条件【即 Fusion number-picker问题原因】：

1）win10 18363.1016 左右版本
2）chrome 86.0.4240.198 左右版本
3）微软输入法 中文模式
4）初始值0
5）原生input的type不为number
6）原生input受控，回填值类型为number

**Comment by bindoon** [comment]
目前 next@1.24 NumberPicker 对数据获取逻辑做了重构，能够做到组件不受控的时候是正常的。但是一旦业务线自己外部受控了，依然会出现此问题。

看看如下方法是否可行：
在 getDriverStateFromProps 里面 判断
if  (foucsed(聚焦)  + 开启了中文输入模式(onCompositionStart 判断中文输入模式启动) + 输入值是 0x 形式 + props.value的值格式化后和0x相等) 
then
不接受props.value 更新。

**Comment by galogm** [comment]
> 目前 next@1.24 NumberPicker 对数据获取逻辑做了重构，能够做到组件不受控的时候是正常的。但是一旦业务线自己外部受控了，依然会出现此问题。
> 
> 看看如下方法是否可行：
> 在 getDriverStateFromProps 里面 判断
> if (foucsed(聚焦) + 开启了中文输入模式(onCompositionStart 判断中文输入模式启动) + 输入值是 0x 形式 + props.value的值格式化后和0x相等)
> then
> 不接受props.value 更新。

1. onCompositionStart 只在输入非latin字符时触发，中文输入法输入数字时不会触发；
2. 1.24版本受控模式的绕过方式改为：在触发onChange前判断是否“输入值是 0x 形式 + onChange回传的值为x”则通过延迟onChange触发时机，先render一次0x展示值，再render用户受控回填的值。

**Comment by galogm** [comment]
fixed in 1.24
