### ISSUE TITLE
[TimePicker2]TimePicker2 style not rendering

### ISSUE THREAD

**Issue by netyro-starduster** [alibaba-fusion/next#3118]
### Component 
TimePicker2

### Steps to reproduce
common usage, no style rendered even at very low depth of entire dom.
"Fusion Design Pro" scaffold from icework.
no errors or warnings on build.
tried upgrade alifd/next to version 1.23.7 still no style on it.

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/RaYvXqMj4X65.png)

**Comment by youluna** [comment]
fixed
