### ISSUE TITLE
您好，为啥新建不了站点

### ISSUE THREAD

**Issue by zmy1235** [alibaba-fusion/next#3130]
### Reproduction link 
[https://fusion.design/sites/new?spm=fusion-design.design-design-fusion.0.0.611d1b1dzCSlvW](https://fusion.design/sites/new?spm=fusion-design.design-design-fusion.0.0.611d1b1dzCSlvW)

### Steps to reproduce
建站不成功，倒是提供个理由吧，一点提示都没有就说失败，到底失败啥愿意呢？这用户体验做的

**Comment by youluna** [comment]
不好意思，今晚已修复，可以再试一下

**Comment by zmy1235** [comment]
好的，谢谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba-fusion/next"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月23日(星期三) 晚上9:39
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [alibaba-fusion/next] 您好，为啥新建不了站点 (#3130)





 
不好意思，今晚已修复，可以再试一下
