### ISSUE TITLE
[Balloon]balloon组件某些场景开启needAdjust属性报错 堆栈溢出

### ISSUE THREAD

**Issue by hzxshark** [alibaba-fusion/next#3135]
### Component 
Balloon

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/f1d78e7b](https://riddle.alibaba-inc.com/riddles/f1d78e7b)

### Steps to reproduce
在某些场景下开启balloon组件的needAdjust属性，会报错导致页面白屏；
应该是某些场景下触发了overlay.position组件无限更新导致的堆栈溢出；
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/Ldp9pxZD3Z55.png)

**Comment by youluna** [comment]
感谢反馈，复现demo给的很准确， @jerryyxu 大哥来看看

**Comment by bindoon** [comment]
fixed in 1.25
