### ISSUE TITLE
[Table]Table组件使用FixHeader属性时表头与表格本体错开

### ISSUE THREAD

**Issue by foxfanfan** [alibaba-fusion/next#3140]
### Component 
Table

### Reproduction link 
[<Table dataSource={data} fixedHeader={true} stickyHeader maxBodyHeight={"60vh"}>](<Table dataSource={data} fixedHeader={true} stickyHeader maxBodyHeight={"60vh"}>)

### Steps to reproduce
使用了fixHeader配置之后产生了问题，Fusion官网关于fixheader的效果图中也有此问题

**Comment by youluna** [comment]
有截图吗？ stickyHeader的情况下，表头会固定在页面上，这个是正常的，你说的异常是什么？

**Comment by foxfanfan** [comment]
![image](https://user-images.githubusercontent.com/61485010/124220232-1f00ee80-db30-11eb-821c-8825529bc39d.png)
这是当时在官方文档中的表头右边被滚动条撑开的状况。

**Comment by crawler-django** [comment]
这个错位问题的话  使用Table.StickyLock代替Table就解决了

**Comment by lakerswgq** [comment]
推荐使用 Table.StickyLock
