### ISSUE TITLE
[Table]异步加载数据后，虚拟滚动失效

### ISSUE THREAD

**Issue by crawler-django** [alibaba-fusion/next#3141]
### Component 
Table

### Reproduction link 
[https://codepen.io/crawler-django/pen/VwbZebR?editors=0010](https://codepen.io/crawler-django/pen/VwbZebR?editors=0010)

### Steps to reproduce
我看见源码和api接口都有rowHeight可以设置, 但是我设置了rowHeight却不起作用.

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/4l0gvvE54eP4.png)

**Comment by youluna** [comment]
文档上没有这个接口哦，这个API设计出来是只给「虚拟滚动」计算行高使用的。

可以说下你遇到了什么问题、想实现什么功能、想实现什么效果

**Comment by crawler-django** [comment]
https://codepen.io/crawler-django/pen/VwbZebR?editors=0010
这个例子我调整了一下, 主要是虚拟滚动失效的问题.

我以为rowHeight 和 onScroll是暴露出来的, 有rowHeight 和 onScroll, 用户就可以自定义实现虚拟滚动了.
题外话:  源码里好多个Table, 有点不太明白这么做的理由..  有没有考虑class组件转函数组件..

**Comment by crawler-django** [comment]
这个步骤使虚拟滚动失效.
![image](https://user-images.githubusercontent.com/37062307/124433228-182ee180-dda5-11eb-8181-d16fd93e6652.png)

**Comment by youluna** [comment]
问题可以换成 异步加载数据后，虚拟滚动失效，是个bug

**Comment by crawler-django** [comment]
基本问题解决了, 但是还有一个问题. 
比如: 我设置的maxBodyHeight如果设置为string, 且大于1屏的高度就不行了. maxBodyHeight={'calc(100vh - 10px)'}
例子: https://codepen.io/crawler-django/pen/VwbZebR?editors=0010

**Comment by YSMJ1994** [comment]
现在看这些复现 demo 已经不能复现问题了，应该是已经都解决了
