### ISSUE TITLE
[Tree]tree虚拟滚动

### ISSUE THREAD

**Issue by fate-zy** [alibaba-fusion/next#3144]
### Component 
Tree

### Steps to reproduce
IntrinsicClassAttributes<Tree> & Readonly<TreeProps> & Readonly<{ children?: ReactNode; }>”。
      类型“IntrinsicAttributes & IntrinsicClassAttributes<Tree> & Readonly<TreeProps> & Readonly<{ children?: ReactNode; }>”上不存在属性“useVirtual”。
  第 2 个重载(共 2 个)，“(props: TreeProps, context?: any): Tree”，出现以下错误。
    不能将类型“{ children: any; useVirtual: true; className: string; style: { maxHeight: string; height: string; width: string; maxWidth: string; }; selectable: false; loadData: any; checkable: true; onCheck: any; checkedKeys: any; }”分配给类型“IntrinsicAttributes & IntrinsicClassAttributes<Tree> & Readonly<TreeProps> & Readonly<{ children?: ReactNode; }>”。
      类型“IntrinsicAttributes & IntrinsicClassAttributes<Tree> & Readonly<TreeProps> & Readonly<{ children?: ReactNode; }>”上不存在属性“useVirtual”。

**Comment by kurisu994** [comment]
> @fate-zy 请提供一个复现的 demo

我也一样 描述文件有问题，没有对应useVirtual参数，虽然能生效。

**Comment by lakerswgq** [comment]
https://github.com/alibaba-fusion/next/pull/3904/files
