### ISSUE TITLE
[Table]Table cell 应该用break-word而不是break-all

### ISSUE THREAD

**Issue by csr632** [alibaba-fusion/next#3148]
### Component 
Table

https://github.com/alibaba-fusion/next/blob/e987b83f621e2a45917ec4b784317bda1bb01367/src/table/main.scss#L104

造成单词意外换行：
![image](https://user-images.githubusercontent.com/18747423/124090217-346e0e00-da87-11eb-91ec-8ed99130291a.png)

手动改为break-word以后：
![image](https://user-images.githubusercontent.com/18747423/124090306-4c459200-da87-11eb-9b29-ae6a606e5671.png)

### Steps to reproduce

https://riddle.alibaba-inc.com/riddles/e2aa6981

**Comment by csr632** [comment]
对比：
break-all：
- 优势：在大部分场景比较美观，能充分利用cell的宽度，不会造成不稳定的首位空白
- 劣势：会截断单词
break-word：
- 优势：不会截断单词
- 劣势：长单词很多、列宽度不够的时候，表格会很丑

因此我觉得默认值可以保持为break-all。但是需要一个列配置项来方便地配置成break-word。否则用户需要自己手动解决单词被截断的问题。

**Comment by youluna** [comment]
可以考虑加API `<Table.Column breakWord={"word | all"} />`  默认是all
