### ISSUE TITLE
[CascaderSelect]Cascadeselectfield 组件支持搜索的结果快速切换到级联

### ISSUE THREAD

**Issue by dongruiyang** [alibaba-fusion/next#3154]
### Component 
CascaderSelect
### Feature Description
1：cascadeselect 组件在开启搜索之后，搜索的列表点击之后直接选中，再次定位到输入框才能出现级联效果，希望能够在搜索的时候点击可以直接到级联的效果；
2：实际想要的效果：输入值出现搜索结果list，点击label，跳转到级联面板

**Comment by YSMJ1994** [comment]
这个是符合设计的，因为也有场景是搜索后要在搜索结果里选中多个的，这个过程就不需要切换到级联面板。
如果有需要，建议新增 api 来控制选中后是否清空 searchValue 的逻辑，目前固定是在 multiple 场景下不清空，欢迎 PR

**Comment by YSMJ1994** [comment]
同 #3008
