### ISSUE TITLE
[Table]Table.Column 的行渲染函数 cell 希望能自动传入 dataIndex

### ISSUE THREAD

**Issue by wwyx778** [alibaba-fusion/next#3155]
### Component 
Table
### Feature Description
Table.Column 的行渲染函数 cell 希望能自动传入 dataIndex 或者传入 context 并且可以取到 dataIndex，使用频率较高，希望能官方支持，不用每次都手动引入。

**Comment by youluna** [comment]
`<Table.Column dataIndex={dataIndex} cell={this.renderCell.bind(this, dataIndex)}>`
不考虑加哦
