### ISSUE TITLE
[Select]列表选项较少时仍随机出现滚动条

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#3156]
### Component 
Select

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-dropdown-scrollbar-joz7m)

### Steps to reproduce
如图，只过滤到两个选项时，仍出现了滚动条，导致用户无法看到完整的选项。屏幕空间是足够的。

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/WqTLQFc7rsiY.png)

**Comment by guoyunhe** [comment]
我测试对比了一下，只有在 useVirtual=true 的情况下才会出现，去掉就好了

**Comment by guoyunhe** [comment]
@bindoon 请问这个问题有跟进吗？

**Comment by youluna** [comment]
@guoyunhe  看 demo 没有出现你截图的现象，还有什么条件吗？我试过设置电脑始终展示滚动条，发现没有什么变化。

但是发现了另外一个问题：虚拟滚动开启时，滚动到第一条和滚动到最后一条，滚动条的比例不对
![image](https://user-images.githubusercontent.com/10049465/134295858-475d17df-e62f-4516-9494-1a029b271f35.png)

![image](https://user-images.githubusercontent.com/10049465/134295839-475a39f2-e5ae-4048-bb18-d4b7ca346e29.png)

**Comment by guoyunhe** [comment]
@youluna  这个例子输入 ch 的时候会出现，有一定概率。

**Comment by bindoon** [comment]
虚拟列表问题，已经控制个数使用

**Comment by guoyunhe** [comment]
@bindoon 在哪个版本修复了？我想测一下，不然业务需求没法处理。
