### ISSUE TITLE
Css doesn't work

### ISSUE THREAD

**Issue by KarovInal** [alibaba-fusion/next#3160]
### Reproduction link 
[https://unpkg.com/@alifd/next/dist/next.css](https://unpkg.com/@alifd/next/dist/next.css)

### Steps to reproduce
This page is not working: https://unpkg.com/@alifd/next/dist/next.css.
It affects our project...

**Comment by KarovInal** [comment]
Currently, it works well. What was the problem? Because a few minutes ago this page did response 302 code (with empty content)

**Comment by mark-ck** [comment]
> unpkg is a fast, global content delivery network for everything on npm. 
> from https://unpkg.com/

@alifd/next is a npm package, so u can get  `@alifd/next/dist/next.css` with url `https://unpkg.com/@alifd/next/dist/next.css`, and u can see there is no `version` in the that url, so unpkg will redirect to the latest version.

so the request of `https://unpkg.com/@alifd/next/dist/next.css` response 302 is correct, the browser will follow redirect and get the right css content.
