### ISSUE TITLE
[Table]表格组件crossline属性的bug

### ISSUE THREAD

**Issue by YSMJ1994** [alibaba-fusion/next#3161]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/5010414d](https://riddle.alibaba-inc.com/riddles/5010414d)

### Steps to reproduce
hover上去有部分单元格没显示背景

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/0QjLwGtdh66d.png)

**Comment by youluna** [comment]
欢迎来排查  ☕

**Comment by YSMJ1994** [comment]
提供的 demo 已不能复现问题，应该是已修复，如有问题可以新提 Issue
