### ISSUE TITLE
[DatePicker]DatePicker2和DatePicker的接口兼容性问题

### ISSUE THREAD

**Issue by monjer** [alibaba-fusion/next#3162]
### Component 
DatePicker
### Feature Description
DatePicker2和DatePicker的接口兼容性问题，onChange和onOk的含义已经完全不同，DatePicker2无法直接无缝替换DatePicker。
### 问题复现Demo
https://codesandbox.io/s/fusion-datepicker-demo-diff-sccbm

**Comment by YSMJ1994** [comment]
两个组件的交互方式有些变化，但执行 `onChange` 和 `onOk` 的时机是符合该 api 含义的， DatePicker2 的设计并不会确保无缝替换，建议以 DatePicker2 为准，2.x 版本将会移除旧的设计，仅保留 DatePicker2
