### ISSUE TITLE
[biz-anchor] index.js 中不应该 import style.js

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#3168]
### Component 
Affix

### Steps to reproduce
node_modules/@alifd/biz-anchor/lib/index.js 
```
require("@alifd/next/es/affix/style");
```

这里直接引用了 style.js 会导致在 jest 环境中出错。我理解 fusion/icejs 体系应该是分开 index.js 和 style.js ，由 icejs 构建插件去自动引入（仅用于构建，不用于 jest 测试环境）。

**Comment by bindoon** [comment]
jest 还不支持在js中引入？

**Comment by guoyunhe** [comment]
这个 @youluna 说会修的啊，怎么 wontfix 了？

**Comment by guoyunhe** [comment]
求帮忙看一下这个问题，现在 ICE 的 Vite 模式运行 dev server 会报错
