### ISSUE TITLE
官网文档经常打不开

### ISSUE THREAD

**Issue by TrumanDu** [alibaba-fusion/next#3171]
### Type 
Platform

### Feature Description
- 页面加载慢
- 经常组件文档崩溃

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/5MLPRghxQV6I.png)

**Comment by bindoon** [comment]
https://alifd.alicdn.com/demos-pages/@alifd/next/Radio@1.23.12/@alifd/theme-2@0.3.1/index.zh-cn.html  你看看这个地址能打开吗？

**Comment by TrumanDu** [comment]
@bindoon 可以打开

**Comment by bindoon** [comment]
点Radio里面嵌套的就是这个 iframe 地址呀，下次打不开的时候麻烦打开下控制台截取下DOM结构，或者网络报错

**Comment by TrumanDu** [comment]
iframe 会不会不能复用缓存？用iframe体验 差，感觉还不如ice那边文档的体验。

**Comment by TrumanDu** [comment]
自从组件文档更换网站后，体验太差了。哎，心累。
