### ISSUE TITLE
[Table]typo

### ISSUE THREAD

**Issue by goodboy1215** [alibaba-fusion/next#3178]
### Component 
Table

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/UTya4yyPCe4V.png)

**Comment by youluna** [comment]
应该是滚动到指定“行”

**Comment by goodboy1215** [comment]
当时一个大数据表格时，例如：30+列，在表头进行筛选/排序操作，rerender后会一直显示在第一列，之前在业务中手动实现了一个scrollToCell，获取滚动表格的父元素，记录滚动后的位置，通过element的scrollLeft属性， rerender后自动滚动到记录的位置，个人感觉不够优雅，不知道fusion师傅有计是否加一个scrollToCell属性吗？

**Comment by goodboy1215** [comment]
> 应该是滚动到指定“行”

当时一个大数据表格时，例如：30+列，在表头进行筛选/排序操作，rerender后会一直显示在第一列，之前在业务中手动实现了一个scrollToCell，获取滚动表格的父元素，记录滚动后的位置，通过element的scrollLeft属性， rerender后自动滚动到记录的位置，个人感觉不够优雅，不知道fusion师傅有计是否加一个scrollToCell属性吗？

**Comment by youluna** [comment]
我之前考虑过，但是因为信息不充分等各种原因放弃了，可以再讨论下。之前主要拿不准的有以下一些点：
1. 是滚动到「Cell」 还是滚动到某一「位置」
     - 虽然现在在虚拟滚动滚动下有scrollToRow的能力，但参考antd等其他库都是滚动到某一位移，不知道用户对这两类移动的偏好如何，而且直观看下来，滚动到某一位移的性能理论上是好过滚动到某一单元格的
2. 在有锁列的情况下，尤其是左锁列的情况下，应该以「可视区域」为参考，还是以物理上的Table位置为参考

@goodboy1215 你可以新开一个issue咱们一起讨论下这个功能吗？需要一些来着使用者的输入 🤔

**Comment by goodboy1215** [comment]
> 我之前考虑过，但是因为信息不充分等各种原因放弃了，可以再讨论下。之前主要拿不准的有以下一些点：
> 
> 1. 是滚动到「Cell」 还是滚动到某一「位置」
>    
>    * 虽然现在在虚拟滚动滚动下有scrollToRow的能力，但参考antd等其他库都是滚动到某一位移，不知道用户对这两类移动的偏好如何，而且直观看下来，滚动到某一位移的性能理论上是好过滚动到某一单元格的
> 2. 在有锁列的情况下，尤其是左锁列的情况下，应该以「可视区域」为参考，还是以物理上的Table位置为参考
> 
> @goodboy1215 你可以新开一个issue咱们一起讨论下这个功能吗？需要一些来着使用者的输入 🤔

好的，issue:https://github.com/alibaba-fusion/next/issues/3188

**Comment by YSMJ1994** [comment]
Stale
