### ISSUE TITLE
[Table]table 使用expandedRowRender时，cell函数中index步长是2

### ISSUE THREAD

**Issue by lou0820** [alibaba-fusion/next#318]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Table

### Environment
开发环境

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/211kzjz16y)

### Steps to reproduce
使用expandedRowRender时，cell函数中的index的步长是2，期望结果是1

**Comment by bindoon** [comment]
cell 里面的 index 一般用于做哪些操作呢？

**Comment by youluna** [comment]
实现这样的功能 https://codepen.io/aboutblank/pen/GzPved?editors=0011
