### ISSUE TITLE
[Select]Select.AutoComplete 不支持 onCompositionStart 和 onCompositionEnd 事件

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#3181]
### Component 
Select
### Feature Description
由于业务需求，我们被要求增加一个“按 Enter 键跳转到下一个输入框”的功能。因此必须要在 Input 和 Select 组件上监听 onKeyDown，同时为了避免输入法模式中 Enter 跳转，还要监听 onCompositionStart 和 onCompositionEnd 事件。

Input 和 Select.AutoComplete 组件只支持 onKeyDown，不支持 onCompositionStart 和 onCompositionEnd。

**Comment by guoyunhe** [comment]
暂时的解决方案是在 Input 和 AutoComplete 外面套一层 div，然后监听 div 上的冒泡事件。

**Comment by bindoon** [comment]
composition 加上这个api呢，中文结束才会抛onChange

**Comment by guoyunhe** [comment]
我们的交互逻辑比较复杂，只能使用原生 onCompositionStart 和 onCompositionEnd 才能实现。
