### ISSUE TITLE
[Timeline]讨论关于timeline支持交替显示的issue

### ISSUE THREAD

**Issue by Summer-andy** [alibaba-fusion/next#3183]
### Component 
Timeline
### Feature Description
我调研了国内外主流的组件库， 发现timeline支持交替显示的组件库不多，所以标准比较难制定，以国内流行度最高的react组件库ant design和国外的material UI为例，如果在轴的左边和右边都有内容，那么timeline是居中显示。因此关于交替的布局方面，我打算整个timeline居中显示，大家觉得呢？
ant design:
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/IjZHnWuHLpMV.png)

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/kq5jAaxVWKNC.png)
material-ui:
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/oKpB2piEDMeG.png)

**Comment by Summer-andy** [comment]
交替显示的话 direction 也不太好搞，就是有的特殊语言是rtl。 现在有人用 direction 为 rtl么？

**Comment by Summer-andy** [comment]
目前代码里面感觉处理direction的方式不太严谨，代码里面面就简单设置了**text-align**属性，不是应该结合css direction属性一起么，除此之外timeline还支持自定义的节点dot,那是不是还得考虑一下图标或者图片这种的翻转，感觉这玩意儿不太好弄呀

**Comment by Summer-andy** [comment]
我找到一篇关于页面布局双向性的设计规范的文章[https://material.io/design/usability/bidirectionality.html#mirroring-layout](https://material.io/design/usability/bidirectionality.html#mirroring-layout)

**Comment by youluna** [comment]
## 关于当前讨论的功能

### 出发点
我建议从业务需求出发，业务上需要什么样子的设计，再去做什么样的功能，所以最好先给下业务设计稿（没有设计稿的业务，开发者根据自己目前的数据结构，给一下想要什么样的效果示意图也可以），功能可以一步步加上去。

### Fusion现状
Fusion有个比较重要的能力就是主题配置，目前左侧的空间是固定宽度可配置的，新增新模式需要考虑当前的设计方案。目前看来新模式跟现有的设计方案是互斥的。
![image](https://user-images.githubusercontent.com/10049465/125623289-eee1ac85-5e26-40f2-b7bd-21e2cb4982e2.png)


## 关于RTL
RTL是所有Fusion组件自带的功能，开启使用是通过`<ConfigProvider rtl ></ConfigProvider>`全局开启来实现的，有text-align 也有 direction等各种属性。

**Comment by Summer-andy** [comment]
效果图其实就是我上面截的那些图, 我考虑rtl主要是担心我的pr会影响其他bu的海外业务，因为我不太清楚给Fusion写组件的时候需要考虑哪些方面，因为有些rtl似乎在ConfigProvider里面就处理了。

**Comment by Summer-andy** [comment]
left content width 这个选项貌似没有哦 ～

**Comment by Summer-andy** [comment]
目前 left content width 是 通过主题样式来控制的，但是实际业务中这个width肯定是事先不知道的，也就是说left content  width 是一个不确定的值，它取决于业务数据的返回。 请教一下这种情况怎么处理比较好？如果不居中显示的话，可以让用户传配置（width）嘛？

**Comment by Summer-andy** [comment]
感觉现有的模式 不好做交替显示呀 😩😭😢

**Comment by Summer-andy** [comment]
我觉得timeline居左或者居右显示的话，就按照原来的设计方案。交替显示的话就按照新的方案（居中显示）可以吗？

**Comment by Summer-andy** [comment]
![image](https://user-images.githubusercontent.com/30104912/125788760-5b302f79-a095-434a-a896-2c3e6caa017c.png)
![image](https://user-images.githubusercontent.com/30104912/125789179-cb3ec25f-b8e3-4d31-87e3-049fb3e7c89b.png)

目前交替显示的效果是这样的，没有入侵之前的代码。

**Comment by Summer-andy** [comment]
![image](https://user-images.githubusercontent.com/30104912/125795129-28528cd4-5c73-407c-b385-d1a7fcbe7c8e.png)
间距调整了一下

**Comment by Summer-andy** [comment]
![image](https://user-images.githubusercontent.com/30104912/125883765-b12313d4-ed93-4ab8-833a-62261059e9e2.png)
修改了一些细节

**Comment by micate** [comment]
@Summer-andy PR 先提下
