### ISSUE TITLE
[Tree]拖动非 tree 元素到 tree 元素时报错且高亮不会消失

### ISSUE THREAD

**Issue by devrsi0n** [alibaba-fusion/next#319]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.12.3

### Component
Tree

### Environment
mac 10.14.2 chrome 72.0.3626.109

### Reproduction link
复现视频已反馈锦鲤

### Steps to reproduce
拖动非 tree 元素到 tree 元素时报错且高亮不会消失

**Comment by youluna** [comment]
any progress? @myronliu347

**Comment by myronliu347** [comment]
https://github.com/alibaba-fusion/next/pull/363/commits/a247a09dd6b3dc555a2ef992426e1448e6bf9a5e

**Comment by youluna** [comment]
@myronliu347 可以看下是否可以关闭这个issue了
