### ISSUE TITLE
[Field]setError后 validatePromise会重新校验，setError相当于没有用

### ISSUE THREAD

**Issue by curry-wxj** [alibaba-fusion/next#3192]
### Component 
Field
### Feature Description
希望提供 removeError方法， 将Error控制权 给用户自己控， validatePromise时也能拿到 setError的 错误信息。

**Comment by YSMJ1994** [comment]
validatePromise 后根据 Rule 重新设置 error 是符合预期行为，如想自己控制 error，建议通过自定义 Rule 来实现。

`setError` 是独立方法，会自动触发 rerender，不应与 `validate` 同时使用
