### ISSUE TITLE
[Select]Select 和 AutoComplete 无法获取内部 input 的引用

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#3194]
### Component 
Select
### Feature Description
我们在开发中经常需要去聚焦某个 Select 或 AutoComplete，以减少用户点击，提高效率。但是 Select 和 AutoComplete 并没有直接获取 input 的 ref 的方法。

**Comment by bindoon** [comment]
ref.getInstance().foucs()
