### ISSUE TITLE
[NumberPicker]NumberPicker的props interface中缺少了hasTrigger的定义

### ISSUE THREAD

**Issue by ljx94nb** [alibaba-fusion/next#3196]
### Component 
NumberPicker

**Comment by ljx94nb** [comment]
版本号为：1.23.12

**Comment by j787701730** [comment]
有改的话,  顺便把 device 也加进去吧. 要不老是报红色波浪线

**Comment by bindoon** [comment]
https://github.com/alibaba-fusion/next/blob/master/types/number-picker/index.d.ts
