### ISSUE TITLE
[Table]Table自定义Cell中做请求，结果没有在Table中展示

### ISSUE THREAD

**Issue by zhanleibo** [alibaba-fusion/next#3202]
### Component 
Table

### Steps to reproduce
const status = (...args: any[]) => {
    const row = args[2];
    request({
      method: 'get',
      url: '/api/mi/getMarkInfoCount',
      params: { folder: row.de_folder },
    })
      .then((res) => {
        return <div>{res}</div>
      })
      .catch((err) => {
        return <div>0</div>;
      });
  };
return (
            <Table dataSource={dataSource} size="small" hasBorder={false}>
              <Table.Column title="版本" align="center" dataIndex="de_name" />
              <Table.Column title="数据集ID" align="center" dataIndex="id" />
              <Table.Column title="数据量" align="center" dataIndex="de_folder_count" />
              <Table.Column title="标注类型" align="center" dataIndex="de_mark_type_name" />
              <Table.Column title="标注状态" align="center" width={100} cell={status} />
            </Table>
)

**Comment by youluna** [comment]
TableCell是UI组件，建议在外层请求好然后塞进来。或者给cell传一个自定义的react组件，你在这个组件里面写异步逻辑
