### ISSUE TITLE
[Form]Form.Submit 提交时未强制校验数据

### ISSUE THREAD

**Issue by wangchongwei** [alibaba-fusion/next#3211]
### Component 
Form

### Steps to reproduce
Form 使用时，有FormItem开启了数据格式校验
在Sumbit也使用了 validate
Form.Submit 提交时会校验数据格式，但即使校验未通过，会有红色提示，仍会提交表单

那此时数据格式校验的意义是什么？

**Comment by bindoon** [comment]
上代码，复现demo。要不然不知道你说啥
