### ISSUE TITLE
[Slider]Slider在React.Suspense中渲染异常

### ISSUE THREAD

**Issue by csr632** [alibaba-fusion/next#3224]
### Component 
Slider

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/f8dd739b](https://riddle.alibaba-inc.com/riddles/f8dd739b)

### 问题分析

背景：React渲染Suspense的逻辑： 当Suspense还在loading的时候，它会将其内部已经加载好的子树先渲染出来，但是会对子树的根容器设置`display:none`。
> 为什么React不等到全部加载好以后再一起渲染，而是”渲染部分+隐藏“，我也不理解，但是React[就是这样实现的](https://github.com/facebook/react/search?q=hideInstance)

**当父容器被`display:none`隐藏的时候，fusion的Slider组件无法正确渲染**。具体的来说，就是[探测可用宽度的时候得到0](https://github.com/alibaba-fusion/next/blob/4d755849c621065efe59425e6eb1da2437b92c2c/src/slider/slick/mixins/helpers.js#L9)。
当React去掉父容器的`display:none`的时候，不会触发Slider组件的重新渲染，导致Slider一直以为自己的可用宽度为0，直到下次ComponentDidUpdate。

## 修复方式

使用`react-intersection-observer`:
https://codesandbox.io/s/fusion-slider-ko88m

需要加polyfill才能支持IE11。

**Comment by csr632** [comment]
同类问题： https://github.com/alibaba-fusion/next/issues/2804

**Comment by youluna** [comment]
Suspense受限于React16的版本，用的display none的实现；React18并发模式下的 Suspense 更符合直觉https://juejin.cn/post/6979480649212100622#heading-9

当然Slider还是存在问题的，就是很容易受容器宽度影响，从这个角度看需要优化。

@csr632 要不直接来提pr 😆

**Comment by YSMJ1994** [comment]
特殊场景出现的组件问题，建议使用 Slider 提供的 `resize` 方法来手动处理，组件库层面只能保证在绝大多数场景可以按预期运行，并提供开放方法来尽量满足少数场景。
