### ISSUE TITLE
主题首页默认内容意义不大且无法定制

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#3225]
### Type 
Platform

### Feature Description
https://fusion.alibaba-inc.com/75046/yuque/fusion-design-system/lo6b6p/kr9bgo?themeid=19894

作为一个主题，受众主要是前端团队成员，他们最需要的应该是，这个主题包是为什么领域设计的，如何安装和使用主题包，有问题需要找谁反馈。而不是看一大段看了半天也看不懂的长文。和 Fusion 的关联性，只要标注“Powered By Fusion Design”并链接到 Fusion 官网首页就好了。

**Comment by bindoon** [comment]
赞同，我们优化下这块

**Comment by YSMJ1994** [comment]
Stale
