### ISSUE TITLE
[Table]当在drawer有table，且 table有stickyHeader属性。stickyHeader不生效，当选中一个时，header会在界面上方，当滑到上面时，header布局错误

### ISSUE THREAD

**Issue by heihei12305** [alibaba-fusion/next#3239]
### Component 
Table

### Reproduction link 
[https://codepen.io/heihei12305/pen/NWjzoGP?editors=0010](https://codepen.io/heihei12305/pen/NWjzoGP?editors=0010)

### Steps to reproduce
下滑时未生效
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/SpGQq5kZuMzZ.png)

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/WxDAM5NMRzgp.png)

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/5UWNuI4d0wEV.png)

**Comment by heihei12305** [comment]
图片第二个图片错了![image](https://user-images.githubusercontent.com/37496285/127951092-f68bbac8-c2c7-4bbf-bd48-898d9794fee4.png)

**Comment by YSMJ1994** [comment]
在滚动容器中使用 stickyHeader 需要制定滚动容器节点
你的例子向 table 传递
```js
<Table affixProps={{container: () => document.querySelector('.next-overlay-inner > div')}}>
```
