### ISSUE TITLE
[Select]React 16.8.2 下 Select.AutoComplete 无法输入中文

### ISSUE THREAD

**Issue by liunian** [alibaba-fusion/next#324]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
latest

### Component
Select、Input

### Environment
Chrome

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/3b0bfd1a](https://riddle.alibaba-inc.com/riddles/3b0bfd1a)

### Steps to reproduce
RT

![ime](https://user-images.githubusercontent.com/646129/52854244-d6ac2600-3158-11e9-9321-da30140f9863.gif)

**Comment by youluna** [comment]
https://github.com/facebook/react/issues/14861
