### ISSUE TITLE
[Select]点击选中的选项，下拉菜单无法关闭

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#3248]
### Component 
Select

### Reproduction link 
[https://fusion.alibaba-inc.com/pc/component/select?themeid=2#basic-container](https://fusion.alibaba-inc.com/pc/component/select?themeid=2#basic-container)

### Steps to reproduce
1. 点击 Select，鼠标点击 Jack，下拉菜单关闭
2. 再次点击 Select，鼠标点击 Jack，无法关闭下拉菜单

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/gWsOdz4AMM86.png)

**Comment by guoyunhe** [comment]
对照 Ant Design，选择 Jack 之后，再次打开下拉菜单，点击 Jack，下拉菜单能够自动关闭：

https://ant.design/components/select-cn/

![image](https://user-images.githubusercontent.com/5836790/128311685-d1879c3e-cd71-4e03-842b-736341d7caf4.png)

**Comment by YSMJ1994** [comment]
已修复
