### ISSUE TITLE
[Select]【a11y】弹层定制 (popupContent) 支持 arrow 触发

### ISSUE THREAD

**Issue by flyinhigh** [alibaba-fusion/next#325]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Select

### Feature Description
目前只支持 enter 和 space 键，需要支持 down arrow 键展开，跟其它的 Select 类型一样

**Comment by bindoon** [comment]
底层依赖的是 popup 的能力，是否可以在 popup 增加自定义触发方式，比如 arrow-down @youluna

**Comment by youluna** [comment]
应该考虑让Popup开放API出来  https://github.com/alibaba-fusion/next/blob/master/src/overlay/popup.jsx#L141

考虑新增参数 https://github.com/alibaba-fusion/next/issues/478

**Comment by youluna** [comment]
功能已添加，select可以提供个demo

**Comment by huarse** [comment]
这个应该是一开始就支持的吧，方向键 下 是可以唤起选择弹层的
