### ISSUE TITLE
[DatePicker2]在@alife/theme-idc-dark主题包datepicker2和select无数据hover未适配

### ISSUE THREAD

**Issue by hjc-1997** [alibaba-fusion/next#3253]
### Component 
DatePicker2

### Reproduction link 
[https://aliark-pre.alibaba-inc.com/ark-local/web/edit/?id=1&menuId=13&building=B&moduleName=%E9%A6%96%E9%A1%B5](https://aliark-pre.alibaba-inc.com/ark-local/web/edit/?id=1&menuId=13&building=B&moduleName=%E9%A6%96%E9%A1%B5)

### Steps to reproduce
1.使用@alife/theme-idc-dark主题包，版本^0.4.2，RangePicker弹开还是白色的，以及下拉组件无数据houver的时候也是白色的

**Comment by youluna** [comment]
range picker 2 系列还没有开放配置能力，建议样式覆盖先
