### ISSUE TITLE
[Form]表单组件预览态下密码不应该显示为明码

### ISSUE THREAD

**Issue by baicoding** [alibaba-fusion/next#3260]
### Component 
Form

### Reproduction link 
[https://fusion.design/pc/component/form?themeid=2#preview-container](https://fusion.design/pc/component/form?themeid=2#preview-container)

### Steps to reproduce
在预览态下，有两个问题：
1.密码框的密码变成了明码
2.Formitem的高度发生了变化，比原来编辑态下小了，两种状态切换时会一跳一跳的。
官网示例可复现该问题
https://fusion.design/pc/component/form?themeid=2#preview-container
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/Z8GXCHkYzITS.png)

**Comment by bindoon** [comment]
1. 密码框一般不会有预览态，即使有后端返回的数据应该做处理
2. 一般不会有直接切换情况，预览态需要信息更加密集，行高小写是合理的
