### ISSUE TITLE
[Dialog]dialog在设置了height之后，footer不应该浮动，应当压缩content区域

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#3262]
### Component 
Dialog

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/1f350985](https://riddle.alibaba-inc.com/riddles/1f350985)

### Steps to reproduce
两个问题：
1. height 最好支持 string 或者 number，并且文档上最好给一些例子。比如用户传了“400”它是不会生效的，要传“400px”或者{400}
2. 当内容很长，但height比较小的时候，header/content/footer三个区域，content应当是可滚动的

**Comment by bindoon** [comment]
height 是支持 number 的。
第二个问题支持下

**Comment by bindoon** [comment]
fixed in PR #3345 , released in @alifd/next@1.25
