### ISSUE TITLE
[CascaderSelect]联级选择组件

### ISSUE THREAD

**Issue by helloljq** [alibaba-fusion/next#3269]
### Component 
CascaderSelect

### Steps to reproduce
搜索下拉选项滚动位置不符合预期；

在搜索demo页面即可复现；

先搜索比如“浙江省”，然后任意选择一个比如“临安市”，此时组件被选中的是临安市，下拉选项定位到了浙江省临安市；

然后再搜索比如“广东省”，任意选中一个比如“广州市”；被选中的数据已经是广东省广州市；

此时再打开下拉框，滚动位置还停留在 “浙江省临安市”； 预期应该已经是在“广东省广州市”了；

**Comment by YSMJ1994** [comment]
已修复
