### ISSUE TITLE
[Select]【a11y】用 arrow 键选择 option 时读屏软件没有读出 option 内容

### ISSUE THREAD

**Issue by flyinhigh** [alibaba-fusion/next#327]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Select

### Feature Description
mac + voiceover ，用上下箭头键选择 option 时，读不出来，虽然视觉上能看到是 focus 在上面了。

**Comment by bindoon** [comment]
这个没办法，因为箭头上下的时候是focus在 input 上面，要不然无法做到下拉的时候还能输入。

需要通过api onToggleHighlightItem 来获取高亮item，然后自己做读取

**Comment by flyinhigh** [comment]
> 这个没办法，因为箭头上下的时候是focus在 input 上面，要不然无法做到下拉的时候还能输入。
> 
> 需要通过api onToggleHighlightItem 来获取高亮item，然后自己做读取

可以参考下 https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html  mac + voiceover

**Comment by bindoon** [comment]
![image](https://user-images.githubusercontent.com/5189853/53098934-afda5f00-355f-11e9-9da4-878823f22c21.png)

如果不 focus 在 input 上面，这种情况我是无法方便的输入的！

**Comment by flyinhigh** [comment]
combobox 的作用是在于，在input输入的时候，下方会根据你输入的内容列出对应的选项，然后用户再去选择需要的选项，所以输入和选择，是不能同时发生的操作，输入的时候不选择，选择的时候就不需要输入。如果想再次输入，就按 esc 关掉下拉列表，或者按 enter/space 键选择一个选项之后，焦点再回到 input 中，重新输入，否则，键盘用户都不知道自己选择了哪个选项。

**Comment by bindoon** [comment]
use `<span aria-live="polite">{srReader}</span>` in the select
