### ISSUE TITLE
[Checkbox]组件对齐

### ISSUE THREAD

**Issue by Zitian770** [alibaba-fusion/next#3270]
### Component 
Checkbox

### Steps to reproduce
1、icon 和组件文字居中对齐；2、去掉文字右侧多于空白
截屏2021-08-10 下午4.45.45
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/K7XZqQ00FGtS.png)

**Comment by YSMJ1994** [comment]
目前已修复
