### ISSUE TITLE
[Form]无法校验后缀名为中文域名的邮箱地址

### ISSUE THREAD

**Issue by jiyeking** [alibaba-fusion/next#3275]
### Component 
Form

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-template-forked-t9yum?file=/src/index.js)

### Steps to reproduce
Form.Item的format为mail时，输入 `mail@test.中国` 提示校验错误。（可在重现链接中输入任意中文域名的邮箱地址即可重现）

**Comment by bindoon** [comment]
mail 的正则就没覆盖中文，可以帮忙提 PR 吗？
在 https://github.com/alibaba-fusion/validate 中

**Comment by jiyeking** [comment]
我不确定是不是符合提交的规范，然后提了一个PR，https://github.com/alibaba-fusion/validate/pull/22
