### ISSUE TITLE
[TreeSelect]Dark 模式下 Tree-Select 树选择的背景色没法配置

### ISSUE THREAD

**Issue by Zitian770** [alibaba-fusion/next#3276]
### Component 
TreeSelect

### Steps to reproduce
Dark 模式下 Tree-Select 树选择的背景色没法配置
截屏2021-08-18 上午11.18.23.png
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/i48bcS0uhyLK.png)

**Comment by YSMJ1994** [comment]
目前该问题已经修复
