### ISSUE TITLE
[Input]希望支持一下textarea文本自动换行时键入换行符

### ISSUE THREAD

**Issue by myzhuaijun** [alibaba-fusion/next#3282]
### Component 
Input
### Feature Description
textarea 标签是有wrap属性,希望能支持一下,参考MDN
https://fusion-image.oss-cn-beijing.aliyuncs.com/images/kzfpblzxkELs.png

**Comment by bindoon** [comment]
![image](https://user-images.githubusercontent.com/5189853/132637121-4dcbfec5-133b-463c-84cc-a1cf3bdad3f2.png)
wrap 属性是可以直接透传进去的。
