### ISSUE TITLE
[Nav]hover 状态加粗字体导致布局抖动

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#3293]
### Component 
Nav

### Steps to reproduce
目前 Nav Item 在鼠标悬浮的时候，会加粗字体。

首先，我们已经有背景色和字体色，甚至 active line 来标记 active 的选项，粗体显得非常不必要。

其次，加粗字体会导致如下两个问题：

1. 加粗会导致文本的高度宽度发生变化，导致视觉抖动。比如侧栏宽度抖动。在 Shell 里尤其明显。
2. 图标字体也会跟着加粗，在低分屏上，依据像素网格对齐制作的图标，会突然变糊。一些精细的细节完全丢失。

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/3qW8qzMCVWlY.png)

**Comment by Zitian770** [comment]
有意义的建议，感谢反馈，我们优化下～

**Comment by YSMJ1994** [comment]
从现在的站点默认主题来看，已修复
