### ISSUE TITLE
[Search]【a11y】search input 的 role 应该是 searchbox

### ISSUE THREAD

**Issue by flyinhigh** [alibaba-fusion/next#330]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Search

### Feature Description
```
<input role="combobox" aria-autocomplete="list" aria-disabled="false" placeholder="请输入" height="100%" autocomplete="off" value="">  
```
不应该是 combobox，某些情况下是跟 Table 一起连用，只是搜索框，这种情况下应该是 searchbox
       可以放开 role 这个属性让用户自己修改

combobox 的用法可以参考 https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html

**Comment by tao1991123** [comment]
@flyinhigh  内网联系一下  我想询问一下细节 把这个issue发到 内网群 我就知道你是哪个了

**Comment by tao1991123** [comment]
> searchbox

好像没有searchbox这种role @flyinhigh

**Comment by flyinhigh** [comment]
> @flyinhigh 内网联系一下 我想询问一下细节 把这个issue发到 内网群 我就知道你是哪个了

易敛

**Comment by flyinhigh** [comment]
> > searchbox
> 
> 好像没有searchbox这种role @flyinhigh

有的 https://www.w3.org/TR/wai-aria/#searchbox

**Comment by tao1991123** [comment]
由于Search的input其实是应用值 Select.AutoComplete,
需要 Select 支持传入role
