### ISSUE TITLE
[Dialog] Invalid prop `className` supplied to `React.Fragment`

### ISSUE THREAD

**Issue by footmess** [alibaba-fusion/next#3301]
### Component 
Dialog

### Reproduction link 
[https://github.com/footmess/test-fusion](https://github.com/footmess/test-fusion)

### Steps to reproduce
作为UI库引入后，初始化Dialog组件报错：
Warning: Invalid prop `className` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.

虽然不影响功能，但飘红的warning很刺眼

**Comment by youluna** [comment]
meet 的dialog
