### ISSUE TITLE
[Timeline]主题配置-时间轴样式错误

### ISSUE THREAD

**Issue by Mingshuang-ant** [alibaba-fusion/next#3302]
### Component 
Timeline

### Steps to reproduce
如图，这个left time text 字体大小的设置改了以后组件没有任何变化
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/HwOPMVkqjLLh.png)

**Comment by stevapple** [comment]
ping一下，这里似乎是CSS属性被内层的p标签class覆盖了
