### ISSUE TITLE
[List]主题配置List组件extra text color属性无效

### ISSUE THREAD

**Issue by Mingshuang-ant** [alibaba-fusion/next#3303]
### Component 
List

### Steps to reproduce
如图，normal list组件的extra text color配置后无效
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/GEHs4V9zRL9t.png)

**Comment by YSMJ1994** [comment]
图示区域是 content ，右侧按钮是 extra color 区域
