### ISSUE TITLE
[Icon]Icon 的 loading 在某种切换的场景会导致闪屏

### ISSUE THREAD

**Issue by alex-mm** [alibaba-fusion/next#3305]
### Component 
Icon

### Steps to reproduce
建议换种实现方式
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/qPsZM9XV66zg.png)

**Comment by youluna** [comment]
什么浏览器什么场景里？效果是什么样的，有demo吗？补充下更多信息吧

**Comment by YSMJ1994** [comment]
Stale
