### ISSUE TITLE
[Balloon]受控例子无法关闭

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#3315]
### Component 
Balloon

### Reproduction link 
[https://fusion.alibaba-inc.com/pc/component/balloon?themeid=2#onCloseClick-container](https://fusion.alibaba-inc.com/pc/component/balloon?themeid=2#onCloseClick-container)

### Steps to reproduce
这个例子 onClose 没有更改状态为 false

**Comment by youluna** [comment]
![image](https://user-images.githubusercontent.com/10049465/132437367-33f4a8ea-a17f-4389-b886-3f5a7ab424d5.png)

这个例子只是打印了onClose状态，没有改state，demo改下好了
