### ISSUE TITLE
[主题]如何实现动态切换皮肤 / [theme] how to change theme dynamically in production env

### ISSUE THREAD

**Issue by devfpy** [alibaba-fusion/next#332]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Feature Description
请问如何动态切换皮肤

**Comment by bindoon** [comment]
描述清晰些：是一个线上项目通过一个按钮切换皮肤，还是本地开发的时候想把默认皮肤换掉？

**Comment by devfpy** [comment]
线上项目通过点击按钮切换皮肤

**Comment by bindoon** [comment]
如果是通过Fusion平台配出来的，编译出来两份css。
你可以在点击按钮的时候切换css，比如可以把新的 css 挂到 link 上，再把老的link 删掉。

**Comment by devfpy** [comment]
> 如果是通过Fusion平台配出来的，编译出来两份css。
> 你可以在点击按钮的时候切换css，比如可以把新的 css 挂到 link 上，再把老的link 删掉。

FusionDesign发布出来的主题包都是scss样式变量，使用主题包时需要通过配置webpack，打包时再替换官方自带的样式变量的值。

**Comment by youluna** [comment]
@devfpy 有css样式的，在`dist`目录下，例如 https://unpkg.com/@alifd/theme-3@0.0.9/dist/

**Comment by tao1991123** [comment]
@youluna @bindoon 

动态换组件的皮肤很容易, 你们俩的回复已经可以做到, 但是 如果他自己写的css 使用了 scss variable，整体动态换肤,我们暂时还没有提供解决方案

**Comment by bindoon** [comment]
@devfpy 你可以用两个主题包打两份样式出来！ 可以需要自己改改webpack

**Comment by liuyiliuyi** [comment]
> @youluna @bindoon
> 
> 动态换组件的皮肤很容易, 你们俩的回复已经可以做到, 但是 如果他自己写的scss 使用了 scss variable，整体动态换肤,我们暂时还没有提供解决方案

@t
使用 CSS variable 来进行纯浏览器端的换肤，
