### ISSUE TITLE
[DatePicker]禁止选择之前日期，结果不能选择未来（今年）的日期

### ISSUE THREAD

**Issue by Ljiajia** [alibaba-fusion/next#3324]
### Component 
DatePicker

### Reproduction link 
[https://codepen.io/leijia/pen/ExXNGNJ?editors=0010](https://codepen.io/leijia/pen/ExXNGNJ?editors=0010)

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/YNB5Ze0LdTpw.png)

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/rL0eAtcZk6wY.png)

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/d1i2ogtfnS4z.png)

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/KtY3B18IcHSt.png)

复现步骤：
1、先选择结束日期
2、在弹出的面板上，直接点击年份
3、在看到的年份上面，直接点击左箭头（当前看到的应该是2010年-2019年）
4、再点击右箭头
5、当前看到的应该是（2020年-2029年），发现2021年不能选择了
当前期望可以选择今天以及今天往后的日期

**Comment by weinianyang** [comment]
#### disabledDate函数有第二个参数，需要用第二个参数写年月日的不同操作，正确写法如下：
```
const disabledDate = function (date, view) {
    switch (view) {
        case 'date':
            return date.valueOf() <= currentDate.valueOf();
        case 'year':
            return date.year() < currentDate.year();
        case 'month':
            return date.year() * 100 + date.month() < currentDate.year() * 100 + currentDate.month();
        default: return false;
    }
};
```
