### ISSUE TITLE
iconfont.cn 导入图标显示异常

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#3326]
### Steps to reproduce
在主题编辑模式，图标显示异常，线条粗细不均匀：

https://fusion.alibaba-inc.com/75046/design/style/icon?type=theme&themeid=19894

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/9GaDK2IR3Bie.png)

而发布后显示正常：

https://fusion.alibaba-inc.com/75046/component/icon?type=theme&themeid=19894

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/3LvUSzI2cFtL.png)

**Comment by youluna** [comment]
这个应该跟icon有关，这个问题影响比较小，有类似的问题再看

**Comment by guoyunhe** [comment]
这个感觉不是某个图标的问题，每个图标的预览效果都出现了线条粗细不准的问题：

![image](https://user-images.githubusercontent.com/5836790/138226035-2ac0969c-1e1b-4248-a351-d3150114cb60.png)
