### ISSUE TITLE
[Drawer]Drawer希望支持快捷调用

### ISSUE THREAD

**Issue by cccRaim** [alibaba-fusion/next#3330]
### Component 
Drawer
### Feature Description
Dialog是支持快捷调用show或者alert的，那么Drawer支持快捷调用应该也ok的

**Comment by youluna** [comment]
什么场景下需要快捷调用呢

**Comment by cccRaim** [comment]
> 什么场景下需要快捷调用呢

需要抽离逻辑的时候，一般Dialog的快捷调用也是这样，直接抽离逻辑到特定的util里

**Comment by bindoon** [comment]
快捷调用是小弹窗，Drawer这种全屏的一般都是按钮触发，为什么会有快捷调用诉求？

**Comment by cccRaim** [comment]
> 快捷调用是小弹窗，Drawer这种全屏的一般都是按钮触发，为什么会有快捷调用诉求？

抽离逻辑呀，不希望引入控制展示与否的额外变量，并且抽离控制逻辑到工具包里

**Comment by guoyunhe** [comment]
同求。这个和大小无关，主要是操作可能是短暂的。Dialog 不一定比 Drawer 小。

**Comment by bindoon** [comment]
will be released in 1.26
