### ISSUE TITLE
[NumberPicker]NumberPicker 设置最小值时删除有bug

### ISSUE THREAD

**Issue by huangzuizui** [alibaba-fusion/next#3331]
### Component 
NumberPicker

### Steps to reproduce
import React, { useEffect } from 'react';
import { NumberPicker } from '@alifd/next';

function NewNumberPicker(props) {
  const [value, setValue] = React.useState(10);

  console.log('value', value);
  return (
    <NumberPicker
      min={0.1}
      max={999}
      onChange={v => {
        setValue(v);
      }}
      value={value}
    />
  );
}

export default NewNumberPicker;

以上代码无法删除情况输入框

**Comment by youluna** [comment]
什么叫「无法删除情况输入框」 ？

**Comment by huangzuizui** [comment]
> 什么叫「无法删除情况输入框」 ？

这个先关掉，问题另一处提交了
