### ISSUE TITLE
[NumberPicker]当NumberPicker设置min时，清空输入框不触发onChange内容为undefined

### ISSUE THREAD

**Issue by huangzuizui** [alibaba-fusion/next#3334]
### Component 
NumberPicker

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/32896df0 ](https://riddle.alibaba-inc.com/riddles/32896df0 )

### Steps to reproduce
当NumberPicker设置min时，清空输入框不触发onChange内容为undefined。未设置min时可正常触发

**Comment by bindoon** [comment]
正常逻辑，设了min后清空就是个中间态，要等 onBlur 才触发onChange
