### ISSUE TITLE
[Tree]树形组件拖拽bug

### ISSUE THREAD

**Issue by 185172970** [alibaba-fusion/next#3335]
### Component 
Tree

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/9c8546bb](https://riddle.alibaba-inc.com/riddles/9c8546bb)

### Steps to reproduce
官网拖拽demo jsx改成dataSource渲染，直接挂了因为在低代码里使用，所以没办法用jsx

![image](https://user-images.githubusercontent.com/21350840/133015476-7977081d-f42b-4bf3-95f7-947730bf81e2.png)

**Comment by YSMJ1994** [comment]
设置 `immutable={true}` 即可，这样 tree 内部不会修改传入的 dataSource 数据，后续的更新不会因为旧数据而发生计算错误导致你的问题
