### ISSUE TITLE
[Message]Message组件无法显示图标

### ISSUE THREAD

**Issue by h5-Old-driver** [alibaba-fusion/next#3344]
### Component 
Message

### Steps to reproduce
Message.warning('连接机器失败，请重试！')
这样只有文字  没有出现warning的图标 

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/Y9WuwKDR42JY.png)

**Comment by h5-Old-driver** [comment]
其他的方式  type 好像也都不生效  不会出现图标 title和content能正常显示

**Comment by youluna** [comment]
这里icon用的是 iconfont，用的是字体的方式，可以看下控制台里是否有报错

**Comment by h5-Old-driver** [comment]
![image](https://user-images.githubusercontent.com/81205631/133869670-d152f936-b4d1-4005-a19d-c09bcbc7d854.png)
![image](https://user-images.githubusercontent.com/81205631/133869675-4c0b9e83-cc3c-4a72-9e74-5837866ade13.png)
![image](https://user-images.githubusercontent.com/81205631/133869685-b4632494-0843-47b4-8f02-fe07f3806edc.png)
如果是这种写法的话  图标就只有绿色了

**Comment by shinegz** [comment]
The reason may be that you did not import the style file. For example
// import '@alife/next/dist/next.css';
