### ISSUE TITLE
[MenuButton][QUESTION]MenuButton请问如何实现多选点击item后自动关闭

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#3361]
### Component 
MenuButton
### Feature Description
背景
- 我有个需求是多选操作
- 用户点击item后自动关闭弹窗
- 然后我不知道如何处理

尝试
- 查看相关属性，发现没有
- 试图自己去控制显示，弹窗是可以关闭了，但是遇到另外一个问题就是弹窗出现的时候，就算我点击弹窗外不会触发任何事件，导致用户点击弹窗外，我没办法关闭；还有我再次点击menuButton的时候也不会收起

需求
- MenuButton多选，用户点击item后自动关闭

**Comment by YSMJ1994** [comment]
自己通过 `visible` 和 `onVisibleChange` 属性控制显示，然后在 onSelect 里面调整 visible 为 false 即可实现你的需求。
点击弹窗外会触发 `onVisibleChange(false, 'docClick')`。
