### ISSUE TITLE
[NumberPicker]1.24.4 NumberPicker应能禁止输入字符串

### ISSUE THREAD

**Issue by crawler-django** [alibaba-fusion/next#3363]
### Component 
NumberPicker
### Feature Description
版本号1.24.4 
NumberPicker应能禁止输入字符串. 以前的是禁止输入字符串(英文字母/各种符号)

**Comment by crawler-django** [comment]
如果有需要字符串出现的需求, 建议能有一个禁止输入字符串的属性, 

**Comment by bindoon** [comment]
onBlur 的时候会自动订正的数据的，不会允许字符串onChange出来

**Comment by crawler-django** [comment]
以前有些功能逻辑 要监听onKeyDown事件, 比如按"="键, 会自动计算借贷平衡. 会把金额回填上去.

然后按'='键回填的时候, 正常的话是单纯的金额, 比如11111,  现在的话是金额 + '=', 比如11111=. 显示有点问题.
简单的demo: https://codepen.io/crawler-django/pen/abwRwMd?editors=0010
重现步骤: 在借的框里写上321, 再贷的框里按'=', 贷里就会出现321=, 是一个显示问题, onblur后是正常的.

具体功能比这复杂的多, 会有很多行借贷, 然后按=重现计算的情况.

**Comment by bindoon** [comment]
同 #3916

**Comment by xiaobebe** [comment]
😓 东南亚、欧美场景下，用户使用 "，" 进行小数点分隔
