### ISSUE TITLE
[Field][QUESTION]Field和checkbox类型怎么通过

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#3381]
### Component 
Field
### Feature Description
背景
```
       <Checkbox
            {...props.field?.init('checkbox', {
              valueName: 'checked',
            })}
          >
            abc
          </Checkbox>
```

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/UHCN5Hc3Myha.png)

需求
- 通过类型检查

**Comment by bindoon** [comment]
我们的 ts 是手动维护的，文件在 types/field ，能否帮忙 PR

**Comment by weinianyang** [comment]
valueName: 'checked'.  init 返回的结构应该是 { checked, onChange} .  理论上不应该报错的。

你再确认下 props.field?.init('checkbox', {  valueName: 'checked',   }) 返回的是啥？
