### ISSUE TITLE
[Drawer]Drawer组件的header未固定

### ISSUE THREAD

**Issue by smancang** [alibaba-fusion/next#3389]
### Component 
Drawer

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/a5ea825](https://riddle.alibaba-inc.com/riddles/a5ea825)

### Steps to reproduce
drawer组件，当内容超出一屏幕时，滚动应该固定顶部不动，现在发现，只有个关闭图标，其余部分被一起滚动走了

**Comment by bindoon** [comment]
same with #3045
