### ISSUE TITLE
[Button][QUESTION]要使用cssVar是不是必须加载一个主题包

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#3392]
### Component 
Button
### Feature Description
背景
- 我安装了 fusion/next，但不需要/希望安装主题，也不希望用到插件
- 然后我想自己实现动态修改样式(只修改一点点，不用自定义主题包)，所以需要用到cssVar变量
- 然后我发现fusion/next里variables.scss是直接用sassVar而不是cssVar
- 然后我发现主题包才有cssVar以及sassVar映射

背景
- 是否可以实现只安装fusion/next，但同时又可以调整成cssVar模式？

**Comment by bindoon** [comment]
@alifd/next@1.23.25/dist/next.var.min.css  用这个主题包样式

**Comment by xmsz** [comment]
> @alifd/next@1.23.25/dist/next.var.min.css 用这个主题包样式

可行~

之前傻了，一直再找这个包里css变量在哪定义

然后发现是在各个组件里有个variable.css有，但是又没找到哪里有引用的地方，如果手动引用就太麻烦
然后就去看了主题包，发现有聚合的文件

但是忽略了一点，css变量可以设置默认值，我的需求有默认值就行

**Comment by xmsz** [comment]
然后我发现 确实也要有css2sass这个文件，就是sass变量和css变量映射

我现在修改一个变量得更新两个2个地方 有点麻烦

总之我需要
1. 一个css变量总文件，包含所有css变量，这样我项目直接引用就行
2. 一个css2sass文件，这样只需要修改css变量就能实现需求，不用修改两个地方
