### ISSUE TITLE
[Tab][QUESTION]如何实现多步骤/多页面内容切换动画效果

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#3398]
### Component 
Tab
### Feature Description
背景
- 我们有个需求多步骤表单填写
- 然后切换步骤的时候需要实现切换的动画，类似于swiper那种

需求
- 想知道有没有可以快速实现的办法

------------

在不自己写的情况下，尝试了

Tab组件
但是Tab组件的动画只是头部动画，不是内容动画
而且TabItem是通过自身实现样式实现显示和隐藏，和swiper的transform不一样，所以感觉也不好搞

Animation组件
实现不了swiper的效果，那就简单实现动画，但是动画需要自己写，当然也可以安装animation
还是有点麻烦

Animation进阶版queueAnim
https://motion.ant.design/components/queue-anim-cn#components-queue-anim-demo-simple

需要额外插件

**Comment by bindoon** [comment]
这个和我们的 Animation 差不多呀，都能通过 Animation 实现的
