### ISSUE TITLE
[Balloon]Balloon内容如果过高的话，页面会向上跳

### ISSUE THREAD

**Issue by komaedaXnagito** [alibaba-fusion/next#3405]
### Component 
Balloon

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/7e9167a9](https://riddle.alibaba-inc.com/riddles/7e9167a9)

### Steps to reproduce
往下滚动到有Balloon的地方，随便选择一项，页面就往上跳

**Comment by youluna** [comment]
这个行为挺符合预期的呀，总要从头开始看内容吧
