### ISSUE TITLE
[Nav]SubNav 类型定义错误

### ISSUE THREAD

**Issue by mariodu** [alibaba-fusion/next#3437]
### Component 
Nav

### Reproduction link 
[https://github.com/alibaba-fusion/next/blob/master/src/nav/sub-nav.jsx#L47](https://github.com/alibaba-fusion/next/blob/master/src/nav/sub-nav.jsx#L47)

### Steps to reproduce
SubNav 继承自 Menu.SubMenu，丢失了 mode 属性的 typescript 定义

**Comment by YSMJ1994** [comment]
SubNav 是和 Nav 配置使用的，而`mode` 属性会从 Nav 处传递过来，所以 SubNav 自身不会开放 mode 属性配置。
