### ISSUE TITLE
[Message]message 的 index.d.ts 定义错误

### ISSUE THREAD

**Issue by Summer-andy** [alibaba-fusion/next#3443]
### Component 
Message

### Steps to reproduce
export default class Message extends React.Component<MessageProps, any> {
    static show(props: OpenProps): void;
    static hide(): void;
    static success(props: OpenProps): void;
    static warning(props: OpenProps): void;
    static error(props: OpenProps): void;
    static help(props: OpenProps): void;
    static loading(props: OpenProps): void;
    static notice(props: OpenProps): void;
    static config(props: OpenProps): void;
}

这是最新Message定义

然后这是官网的关闭弹窗的示例

const instance = Message.success('this is a message');
instance.close(); // 可以用 close 直接关闭弹窗

那就是  Message.success的返回值不是为void了啰？那类型定义那里是不是得改一下了？

**Comment by YSMJ1994** [comment]
以类型为准，message 有两个版本，一个没有返回值，一个有返回值，类型中返回 void 代表官方在后续版本中不会兼容有返回值的行为。
