### ISSUE TITLE
[Dialog]水平滚动条缺失

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#3446]
### Component 
Dialog

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/a7889c17](https://riddle.alibaba-inc.com/riddles/a7889c17)

### Steps to reproduce
当内容过宽时，不会显示水平滚动条。

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/7aSN9wf4N7Ms.png)

**Comment by bindoon** [comment]
fixed in @alifd/next@1.25 with api v2
