### ISSUE TITLE
[Overlay]Overlay 全屏使用 cache 第二次之后会发生闪动

### ISSUE THREAD

**Issue by zuoqi705** [alibaba-fusion/next#3451]
### Component 
Overlay

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/b48aa709](https://riddle.alibaba-inc.com/riddles/b48aa709)

**Comment by lakerswgq** [comment]
使用 shouldUpdatePosition:  ` <Overlay shouldUpdatePosition />`
