### ISSUE TITLE
[Upload]希望支持 onFileNameClick 用来干预文件名点击之后的动作

### ISSUE THREAD

**Issue by micate** [alibaba-fusion/next#3455]
### Component 
Upload
### Feature Description
现在 Upload 的 List 中，文件名是固定的 <a> 链接，我们想在点击文件名时，根据文件类型，控制是预览还是下载。

希望能增加一个类似 onFileNameClick 的 API，透传 (file, e) 参数，方便实现这种控制逻辑。

![image](https://user-images.githubusercontent.com/433481/139194338-57a1a08c-1d4c-4e9f-9b8f-199bbee7364c.png)

涉及`getTextList` 和 `getImageList` 两个实现。

**Comment by bindoon** [comment]
是不是图片和文件名的点击逻辑是一致的，我思考了下打算增加一个api   previewOnFileName=ture ，把 onPreview 加到 filename 上面。

**Comment by micate** [comment]
> 是不是图片和文件名的点击逻辑是一致的，我思考了下打算增加一个api previewOnFileName=ture ，把 onPreview 加到 filename 上面。

这样也可以的。
