### ISSUE TITLE
[Loading][QUESTION]如何实现调整Loading.Overlap.BackgroundColor/如何实现全屏无背景loading

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#3468]
### Component 
Loading
### Feature Description
背景
- 我有个需求，就是要显示一个全屏Loading盖住页面，让用户感知页面在加载
- 然后我使用Loading fullscreen，但是这样有个透明黑色的背景
- 我们希望这个背景是透明白色或者没有颜色，但是配置不了

临时办法
- 自己包一层Overlap

**Comment by YSMJ1994** [comment]
可以传递 `wrapperClassName` 给弹层顶级节点添加一个类名，然后用 css 方式覆写背景的颜色，但目前 ts 类型还未透出这些属性，后面几个迭代我们会补全 ts 类型

**Comment by eternalsky** [comment]
Loading ts 已补全
