### ISSUE TITLE
[DatePicker2]新版本宽度问题

### ISSUE THREAD

**Issue by wjw131211** [alibaba-fusion/next#3471]
### Component 
DatePicker2

### Steps to reproduce
DatePicker2组件宽度样式是否有更新修改，较旧版本引起了样式问题，之前未遇到。
最新版本：@1.24.12
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/kbJdGI4078fT.png)

旧版本测试：@1.23.25

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/sxRmqIjUnd2d.png)

**Comment by bindoon** [comment]
fixed in `@alifd/next@1.25`
