### ISSUE TITLE
[CascaderSelect]CascaderSelect怎么回显?

### ISSUE THREAD

**Issue by crawler-django** [alibaba-fusion/next#3472]
### Component 
CascaderSelect
### Feature Description
一个普通的编辑功能, 里面的cascaderSelect要把完整的数据显示出来.

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/2wO5dLST4jXI.png)
比如选择了 "客户/测试数据", 并新增了数据.

那我编辑的时候, 我怎么把"客户/测试数据"显示出来? 
我想知道这样cascaderSelect对应的value是什么? 
我存起来了它对应的value, 但是回显的时候是这样的.
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/zeLSUCOEwzAt.png)

我该传怎样的value才能把"客户/测试数据" 这样有关系的数据回显出来?

**Comment by lakerswgq** [comment]
@crawler-django 应该是你传的 value 在 dataSource 里面没有对应选项吧

**Comment by crawler-django** [comment]
那应该是我打开弹层的时候再请求的数据, 所以一开始回显是有问题的.
但是总不能没打开就请求数据吧

**Comment by crawler-django** [comment]
可以像remote select一样, 打开的时候请求数据, 回显的时候有label就行.

**Comment by lakerswgq** [comment]
弹层显示之前请求很常见，这样不用等待请求，体验更好。

目前 CascaseSelect 还不支持 value 传对象
