### ISSUE TITLE
[Dialog]弹窗(Dialog) 新增多态的默认模式

### ISSUE THREAD

**Issue by Zitian770** [alibaba-fusion/next#3486]
### Component 
Dialog
### Feature Description

需求描述：业务交互反馈存在很多多态的提示场景，目前需要业务自己一个个去配置增加了很大的成本，希望在 Fusion 维度可以直接调用弹窗的多态组件。

设计稿链接：https://done.alibaba-inc.com/file/meOpAVB6TnG5/29DjGfisKnBxJ7DA/preview?commitId=da903758bcf09743&m=CANVAS&pageId=E05E3FE1-DF91-4D4B-938A-5B3CB67E8926&aid=16FAACAE-3594-4080-A201-8E675687D76D

**Comment by bindoon** [comment]
same with #3488
