### ISSUE TITLE
[Dialog]Dialog组件在visible=true时，某些场景下没有回调onClose方法

### ISSUE THREAD

**Issue by sanshan521** [alibaba-fusion/next#3499]
### Component 
Dialog

### Steps to reproduce
Dialog组件，通过设置visible参数为false关闭Dialog时，不能触发回调onClose方法，与文档（ https://fusion.alibaba-inc.com/pc/component/dialog?spm=fusion-inc.help-inc-fusion.top-nav.d2pc.2a095ab29C0eco&themeid=2#Dialog ）中对onClose参数的描述“对话框关闭时触发的回调函数”内容不符。

**Comment by bindoon** [comment]
文档我改改，用 afterClose 吧，更加准确
