### ISSUE TITLE
D-One插件已设计过的页面可以在主题更新后随着更新吗？

### ISSUE THREAD

**Issue by charisna** [alibaba-fusion/next#3501]
### Type 
Fusion Cool

### Feature Description
如图所示，之前用 Fusion 组件拖出来的页面，如何在主题更新后批量替换为新主题的组件样式？

iShot2021-11-11 14.36.58.png
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/71eg7F6FOLuJ.png)

**Comment by bindoon** [comment]
需要点组件，右侧面板的配置修改下，重现触发下渲染

**Comment by charisna** [comment]
> 需要点组件，右侧面板的配置修改下，重现触发下渲染

好的，多谢 👌。后续是否会考虑增加选中一键替换为新样式这种功能？

**Comment by bindoon** [comment]
@miadwang 看看是否有计划？

**Comment by bindoon** [comment]
暂无批量替换计划
