### ISSUE TITLE
[Table] 横向滚动时标题和内容区不同步

### ISSUE THREAD

**Issue by iCyris** [alibaba-fusion/next#3514]
### Component 
Table

### Reproduction link 
[https://fusion.alibaba-inc.com/pc/component/table?themeid=2#basicColumns-container](https://fusion.alibaba-inc.com/pc/component/table?themeid=2#basicColumns-container)

**Comment by gezhicui** [comment]
解决了吗 我觉得这应该是组件设计问题吧 表头位置是实时计算的

**Comment by YSMJ1994** [comment]
表头与内容的滚动是通过 `scroll` 事件相互实时同步的，极端情况确实有可能短暂出现不同步的问题，这是因为表格的复杂度决定的，表头与内容必须分离设计，并不在同一个滚动容器内，目前没有规划改造原本的实现，欢迎 PR
