### ISSUE TITLE
[Rating]传入 id 属性后 onChange 会触发两次

### ISSUE THREAD

**Issue by micate** [alibaba-fusion/next#3526]
### Component 
Rating

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-template-forked-tjlff?file=/src/index.js)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/433481/142096660-ef0cf1b4-19d9-4126-a7de-c094430be0bf.png)
1. 为 Rating 增加 id 属性；
2. 点击切换分数，查看控制台，发现一次点击打印了两条日志。

**Comment by youluna** [comment]
![image](https://user-images.githubusercontent.com/10049465/142127551-ad4b1252-678a-4c4c-8432-ce260b22ba3a.png)
传入id后，生成了input。label 加了 for 后，点击 label 时会自动触发 input 的点击
