### ISSUE TITLE
[Build] css 合并的时候未删除 @charset

### ISSUE THREAD

**Issue by lakerswgq** [alibaba-fusion/next#3542]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/9381522/142595670-645e5db7-c218-4b01-8b08-297630294c13.png)
https://unpkg.alibaba-inc.com/browse/@alifd/next@1.23.25/dist/next.var.css

**Comment by lakerswgq** [comment]
![image](https://user-images.githubusercontent.com/9381522/143822484-aeafa00b-7bd3-4178-a696-c11b9ad91a97.png)

目前都设置为了设置为 utf8，4 无效的话，默认也是 utf 8

**Comment by youluna** [comment]
https://github.com/alibaba-fusion/next/blob/c5607284607da79a4a5ee62d49da9572dd40ffde/scripts/build/generate-css-entry.js

生成 index.css的时候，手动replace掉好了
