### ISSUE TITLE
[Input]Input组件默认trim是true，导致无法使用空格

### ISSUE THREAD

**Issue by wangshaoyuan** [alibaba-fusion/next#3543]
### Component 
Input

### Reproduction link 
[https://gsp.aliexpress.com/apps/siteadmin/aeproduct](https://gsp.aliexpress.com/apps/siteadmin/aeproduct)

### Steps to reproduce
页面中的Input框无法使用空格，代码地址:http://gitlab.alibaba-inc.com/intl-dada/intl-ae-product/blob/master/src/Product/MultiLanguage/index.tsx#L174

**Comment by weinianyang** [comment]
复现地址用这个：https://riddle.alibaba-inc.com/riddles/9587eb82

**Comment by lakerswgq** [comment]
Tree 支持键盘操作，space 键会触发选中。在 Input 的 onKeyDown 事件中取消冒泡即可

```jsx
<Input onKeyDown={(e) => {e.stopPropagation();}} onChange={this.change} />
```

**Comment by wangshaoyuan** [comment]
> Tree 支持键盘操作，space 键会触发选中。在 Input 的 onKeyDown 事件中取消冒泡即可
> 
> ```js
> <Input onKeyDown={(e) => {e.stopPropagation();}} onChange={this.change} />
> ```

好的，我试一下
