### ISSUE TITLE
[DatePicker]DatePicker.RangePicker起止时间显示宽度不等

### ISSUE THREAD

**Issue by ShaoFei10027** [alibaba-fusion/next#3545]
### Component 
DatePicker
### Feature Description
RangePicker组件有开始时间和结束时间，左右宽度是一样的，但是右侧（结束时间）有一个图标，这个图标占用的显示时间的区域，导致右边能够显示时间的宽度比左边短，看起来就是左边太长，右边太短。
期望右侧的图标不要占用显示时间的区域，给右侧图标单独划分一个宽度

**Comment by lakerswgq** [comment]
@ShaoFei10027 使用 DatePicker2 ，input 的宽度是一样
