### ISSUE TITLE
[Transfer]Transfer 右侧添加内容后左侧的树状结构直接跳到从头开始展示了 

### ISSUE THREAD

**Issue by zuoqi705** [alibaba-fusion/next#3551]
### Component 
Transfer

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/1b1717e0](https://riddle.alibaba-inc.com/riddles/1b1717e0)

### Steps to reproduce
[期望结果]: 滚动条位置不变，保持原来的位置，或者增加配置

**Comment by mark-ck** [comment]
这应该是 Tree 的问题，不是 Transfer 的问题，我试着加了个 useVirtual 配置就好了
![image](https://user-images.githubusercontent.com/44559440/145052073-7627706d-828e-41f6-8b74-f65c39608fe9.png)
