### ISSUE TITLE
[站点 Icon]fusion自定义站点升级基线版本，icon未同步更新

### ISSUE THREAD

**Issue by IHOD** [alibaba-fusion/next#3557]
### Component 
Icon

### Steps to reproduce
自定义主题升级基线版本1.24.x，与官网同步，但是icon未同步更新，与官网展示不同

自定义主题：
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/ayAnAUc4aENn.png)

fusion官网组件展示：
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/7tjmqDuRRqdM.png)

**Comment by sxqwaade** [comment]
+1 同样问题

**Comment by bindoon** [comment]
官网首页也是自己定制的主题，里面的 icon 也是定制的，并非元素 Icon。 所以升级和官网首页没关系！

**Comment by IHOD** [comment]
感谢解答
