### ISSUE TITLE
[Shell]顶栏 NavItem 图标和文本对不齐中线

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#3559]
### Component 
Shell

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/9a7a8f63](https://riddle.alibaba-inc.com/riddles/9a7a8f63)

### Steps to reproduce
如图，可以看到文本和图标位置明显偏上：

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/GMypn6PODSNT.png)

**Comment by YSMJ1994** [comment]
Nav组件行高与 Shell 不一致导致的，给 Nav 传递 `style={{lineHeight: '50px'}}` 即可解决
