### ISSUE TITLE
[Form]Form URL 校验导致页面挂掉

### ISSUE THREAD

**Issue by huyinglin** [alibaba-fusion/next#3561]
### Component 
Form

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/16ff43c0](https://riddle.alibaba-inc.com/riddles/16ff43c0)

### Steps to reproduce
使用 Form 中的 format="url" 时输入下面 URL 时会报错：https://item.taobao.com/item.htm?id=606535109270&ali_trackid=2:mm_12238993_19794510_110896800135:1637753061_136_624411470&union_lens=lensId:OPT@1637753056@6dcd3e84-67cc-4ee1-9dbc-00639596ecfa_606535109270@1;recoveryid:201_11.27.64.247_12983227_1637753058662;prepvid:201_11.27.64.247_12983227_1637753058662&spm=a231o.13503973.20618785.2&pvid=6dcd3e84-67cc-4ee1-9dbc-00639596ecfa&scm=1007.16016.217477.0&bxsign=tbkviNxf5b2kLFy42lYxfcooSjl4jfCk7bU52g4aDLoMBvTtXRlJVFhYZdJHDKQOOAlwjNBk91TjipSBf2/R6Y5B8O8qd/Hqs8CwaNRKD5abzg=

**Comment by lakerswgq** [comment]
![image](https://user-images.githubusercontent.com/9381522/143428740-1f4ef181-780f-4839-987d-6d5336e721f5.png)
性能问题，这个函数执行太久，页面不响应了

**Comment by lakerswgq** [comment]
alibaba-fusion/validate#23
