### ISSUE TITLE
无法升级主题的基线版本

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#3562]
### Reproduction link 
[https://fusion.alibaba-inc.com/crate/design/style/color?type=theme&themeid=35528](https://fusion.alibaba-inc.com/crate/design/style/color?type=theme&themeid=35528)

### Steps to reproduce
链接中的主题是基于 1.20 的，我想把它升级到 1.25 但是点升级按钮没有效果，发布了之后也没有效果。

**Comment by weinianyang** [comment]
![image](https://user-images.githubusercontent.com/90443688/143826431-6b6af530-82eb-4b2e-b8dc-a933f5b03631.png)
是跟这个一样的问题吗

**Comment by guoyunhe** [comment]
@weinianyang  我点了这个升级按钮，还是不能升级

**Comment by lakerswgq** [comment]
答疑群已经解决，升基线后需要重新发包

**Comment by guoyunhe** [comment]
这个还是不太直观，点升级之后没有任何提示。建议加个弹窗，告诉用户需要重新发布。

**Comment by bindoon** [comment]
> 这个还是不太直观，点升级之后没有任何提示。建议加个弹窗，告诉用户需要重新发布。

我们记录下，下次升级下平台能力

**Comment by guoyunhe** [comment]
好像还是有点问题，我今天又升级一个主题，发布了之后，基线版本还是没变。只能找 @youluna 操作，我自己操作从来没有成功过。
