### ISSUE TITLE
[Tree]数据源某个选项 key 为空时导致输入框无法获得焦点

### ISSUE THREAD

**Issue by micate** [alibaba-fusion/next#3566]
### Component 
Tree

### Reproduction link 
[https://codepen.io/micate/pen/ZEXzNKw?editors=0010](https://codepen.io/micate/pen/ZEXzNKw?editors=0010)

### Steps to reproduce
0. 数据源中的某个 key 设置为空（已设置）；
1. 光标聚焦到输入框，可以输入；
2. 点击 Tree 节点；
3. 光标聚焦到输入框，无法获得焦点。

**Comment by lakerswgq** [comment]
点击 input 的时候，触发了 Tree 的 onBlur，现在默认会把 focusKey 设置为空字符，所以当 key 也有空字符的时候，会触发 input 的 blur，现象表现为输入框无法获得焦点，下个 patch 版本修复
