### ISSUE TITLE
[Button] sass 变量 rgba 变量写法，导致生成的 next.var.css 不可用

### ISSUE THREAD

**Issue by bindoon** [alibaba-fusion/next#3584]
### Steps to reproduce

https://github.com/alibaba-fusion/next/blob/master/src/button/scss/variable.scss#L298
```css
/// bg opacity
/// @namespace statement/normal
/// @type alpha
$btn-ghost-dark-bg-opacity: 0 !default;
$btn-ghost-dark-bg-normal: rgba($btn-ghost-dark-bg, $btn-ghost-dark-bg-opacity) !default;
```
![image](https://user-images.githubusercontent.com/5189853/144529895-6b17ce26-e56e-4c39-8164-ff63c7af7e2f.png)
![image](https://user-images.githubusercontent.com/5189853/144529963-b1cd18fe-9add-46ec-9349-44736d55f922.png)

这种写法导致 
https://unpkg.com/browse/@alifd/theme-1@0.4.2/dist/next.var.css
![image](https://user-images.githubusercontent.com/5189853/144529473-2ee95e38-42a7-473f-846b-1ab8edfa4e4c.png)

浏览器无法识别 sass 的 rgba 函数

正确的用法：
https://unpkg.alibaba-inc.com/browse/@alifd/next@1.24.18/dist/next.var.css
![image](https://user-images.githubusercontent.com/5189853/144566535-61b62768-2576-491b-934b-817ac1441692.png)

**Comment by bindoon** [comment]
关联 issue #3379
可能的问题还是 $btn-ghost-dark-bg-normal 没有录入DB 跟着一起编译导致的。

**Comment by csr632** [comment]
主题平台编译sass的时候，和官方仓库编译有一些区别。

官方仓库的这一行： https://github.com/alibaba-fusion/next/blob/bed22a2bea9e7561b613b83e49c5288d4ab7d69e/scripts/build/css-var-temp-file-core.js#L30
是可以【预计算】出所有变量（包括衍生变量）的最终值的 （[计算结果](https://unpkg.com/browse/@alifd/next@1.24.18/lib/button/variable.css)），但是在平台编译主题包的时候，似乎并没有类似逻辑。
