### ISSUE TITLE
[Select]Select在多选模式下开启选项输入过滤，输入一次关键字后，希望每次能选择多个选项

### ISSUE THREAD

**Issue by CAIyb7923** [alibaba-fusion/next#3590]
### Component 
Select
### Feature Description
目前Select在设置mode="multiple"、showSearch=true、hiddenSelected=false、filterLocal=true时，每次输入关键字对datasource进行过滤后，只能选择其中一个选项，然后datasource会被重置，导致如果想选择相同关键字下的多个选项，必须输入多次。希望能在输入一次关键字后，一次可以勾选多个选项。

**Comment by lakerswgq** [comment]
> ### Component
> Select
> 
> ### Feature Description
> 目前Select在设置mode="multiple"、showSearch=true、hiddenSelected=false、filterLocal=true时，每次输入关键字对datasource进行过滤后，只能选择其中一个选项，然后datasource会被重置，导致如果想选择相同关键字下的多个选项，必须输入多次。希望能在输入一次关键字后，一次可以勾选多个选项。

目前多选模式下，每次选择会清空搜索的关键词，需要支持下不清空搜索词，就可以选多个了

**Comment by bindoon** [comment]
关键是 hiddenSelected=false 了，有这个条件的时候 弹层 会一直展开。

这里应该建议一个交互约定：只要弹层不关闭就不应该自动清除搜索，要不然数据源会突然抖动。
