### ISSUE TITLE
[Pagination]An error was reported when switching pageSize through pageSizeSelector 

### ISSUE THREAD

**Issue by nicoopy** [alibaba-fusion/next#3592]
### Component 
Pagination

### Steps to reproduce
Version: 1.23.25
An error was reported when switching pageSize through pageSizeSelector ( occasionally triggered ) ：
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/pbAacyJOfhU4.png)

**Comment by nicoopy** [comment]
My temporary solution:
Catch error by errorBoundary and manually re-render the Pagination Component.
![image](https://user-images.githubusercontent.com/32139451/144815900-106b6ca8-9852-40c8-ad93-687195bfb97d.png)

**Comment by lakerswgq** [comment]
could you provide a demo that we can reproduce this bug, from the stack trace it's more like an Overlay issue

or you can upgrade to the newest version(1.25.x) of `@alifd/next`, check if this problem still exists

**Comment by nicoopy** [comment]
hi @lakerswgq.
The Pagination Component was just normally used like this:
![image](https://user-images.githubusercontent.com/32139451/144825529-cba69250-8000-4e9a-bb34-3c330ad92694.png)
Hope to solve it in this version(1.23.x). And i will try it again in the newest version.Thanks a lot.

**Comment by nicoopy** [comment]
> could you provide a demo that we can reproduce this bug, from the stack trace it's more like an Overlay issue
> 
> or you can upgrade to the newest version(1.25.x) of `@alifd/next`, check if this problem still exists

hi @lakerswgq.
The Pagination Component was just normally used like this:
![image](https://user-images.githubusercontent.com/32139451/144825529-cba69250-8000-4e9a-bb34-3c330ad92694.png)
The error above was triggered when frequently change pageSize through the pageSizeSelector.
Hope to solve it in this version(1.23.x). And i will try it again in the newest version.Thanks a lot.

**Comment by lakerswgq** [comment]
@nicoopy you can probide an online demo using [codesandbox](https://codesandbox.io/)
if it turns out to be a bug, it'll be fixed in 1.25
