### ISSUE TITLE
定制了主题的站点gg了

### ISSUE THREAD

**Issue by kingcher** [alibaba-fusion/next#3594]
### Reproduction link 
[https://fusion.design/29131/component/box?type=theme&themeid=19954](https://fusion.design/29131/component/box?type=theme&themeid=19954)

### Steps to reproduce
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/utya3TXHiXR8.png)

**Comment by bindoon** [comment]
早上 g.alicdn 有问题，现在已经恢复了
