### ISSUE TITLE
站点进不去

### ISSUE THREAD

**Issue by zhanleibo** [alibaba-fusion/next#3597]
### Reproduction link 
[https://fusion.design/39705/setting/theme?spm=fusion-design.mysite-design-fusion.0.0.6c201388TZzaQ5](https://fusion.design/39705/setting/theme?spm=fusion-design.mysite-design-fusion.0.0.6c201388TZzaQ5)

### Steps to reproduce
进不去 一直在loading

**Comment by mark-ck** [comment]
你好，问题的原因查到了，fusion.design 目前要求必须包含一个主题，刚好你删掉了唯一的主题所以页面有报错😂，这个我们下个版本会兼容一下；
我现在手动帮你关联了一个官方的默认主题，现在站点已经可以打开了，你再试试。
