### ISSUE TITLE
[Select]Select组件开启搜索后禁用失效

### ISSUE THREAD

**Issue by Cyrilszq** [alibaba-fusion/next#3598]
### Component 
Select

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-template-forked-xqviw?file=/src/index.js)

### Steps to reproduce
在下拉框中输入 aaa，可以看到搜索到了 aaa 这个选项，此时这个选项是禁用的不可选择，但如果这时候按下回车键，下拉框会展示 value 16，这样不符合预期

**Comment by lakerswgq** [comment]
应该是一开始的时候 focusKey 在 ccc 上，搜索的时候没重置还是在 ccc 上，所以回车的时候会选中 16，`autoHighlightFirstItem ={false}` 可以临时解决

**Comment by linjunxyz** [comment]
我刚刚用组件库的最新版本调试了一下，已经没有这个问题了，你可以升级一下组件库的版本
