### ISSUE TITLE
[Select]虚拟滚动在选中值之后，再次打开一片空白

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#3600]
### Component 
Select

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/be938700](https://riddle.alibaba-inc.com/riddles/be938700)

### Steps to reproduce
1. 输入“巴西”，搜索，选中。
2. 再次点击 Select 打开，然后向下滚动。
3. 滚动到一定程度，整个下拉框变成一篇空白。

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/Q1haiiX328F0.png)

**Comment by weinianyang** [comment]
@bindoon @youluna 刚打印看到虚拟滚动每次加载出来的items是有值的，看下是不是性能的问题

**Comment by bindoon** [comment]
滚动条似乎也有问题，越滚越小
![image](https://user-images.githubusercontent.com/5189853/145174034-eef6c08d-6f32-4426-a9e5-522befcb329a.png)

**Comment by guoyunhe** [comment]
请问是哪个版本修复了这个问题？何时发布？
