### ISSUE TITLE
账号登录只能用淘宝账户

### ISSUE THREAD

**Issue by complicated2018** [alibaba-fusion/next#3620]
### Type 
Platform

### Feature Description
账号登录只能用淘宝账户，但是公司把淘宝登录给过滤禁止了

**Comment by bindoon** [comment]
目前只能支持淘宝账户

**Comment by complicated2018** [comment]
能否集成其它认证方式



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月22日(周三) 下午3:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba-fusion/next] 账号登录只能用淘宝账户 (Issue #3620)




 
目前只能支持淘宝账户
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bindoon** [comment]
暂时无此计划
