### ISSUE TITLE
[Table] 设置loading效果时，x轴滚动条会被重置回0

### ISSUE THREAD

**Issue by cwtuan** [alibaba-fusion/next#3625]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/901502b4](https://riddle.alibaba-inc.com/riddles/901502b4)

### Steps to reproduce
1. 把x轴滚动条移到中间
![image](https://user-images.githubusercontent.com/3455798/146742468-2ba3d061-ba48-4492-8295-33521accdfb9.png)

2. 按下"Load"，产生loading效果时，x轴滚动条会被重置回0。造成用户使用上不方便
![image](https://user-images.githubusercontent.com/3455798/146742519-984d1ffa-2288-4ff7-9963-9fe4d16c891f.png)

把loading属性去除，就不会出现这个问题
![image](https://user-images.githubusercontent.com/3455798/146743074-dc99e238-aeed-49bb-a1d0-95a8c44743ce.png)

**Comment by YSMJ1994** [comment]
已经修复，提供的demo已不能复现问题
