### ISSUE TITLE
[DatePicker] selected 示例被遮挡，设计态的Demo要优化下

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#3627]
### Reproduction link 
[https://fusion.alibaba-inc.com/crate/design/component/date-picker?type=theme&themeid=33544](https://fusion.alibaba-inc.com/crate/design/component/date-picker?type=theme&themeid=33544)

### Steps to reproduce
由于上方例子过长，把下方的例子遮住了，看不到效果
![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/miEQ3q8CfUyK.png)

**Comment by bindoon** [comment]
看起来是你们配的比较宽松，高度不够了。我们处理下
