### ISSUE TITLE
[Select]fusion design 的Dialog组件配合Form、Select组件有问题，升级之前是正常的

### ISSUE THREAD

**Issue by edc-hui** [alibaba-fusion/next#3630]
### Component 
Select  DatePicker2

### Steps to reproduce
Dialog组件包裹Form，FormItem包裹Select组件，当Select组件的下拉框显示出来之后，除非选中Select的选项，否则Select组件的下拉框不会消失。（此问题同样出现在DatePicker2组件上面，估计是同一类问题）

目前有问题的fusion design 版本号是1.25.9，升级fusion design之前是正常的，正常的版本号是1.24.18

**Comment by bindoon** [comment]
可以加一个api v2 来解此问题，老版本兼容的问题我们再check下

```
<Dialog v2 > <Select popupProps={{v2: true}} /></Dialog>
```

**Comment by edc-hui** [comment]
好的  谢谢

**Comment by edc-hui** [comment]
@bindoon 刚刚这边测试被Drawer组件包裹的Select 也会有相同问题。我们这边暂时退回到1.24.18版本，等fusion design处理好了  我们这边再跟随升级

**Comment by lakerswgq** [comment]
解释一下问题的原因

升级出现这个问题有两个条件：
1. react 版本 >= 17 
2. 升级到 1.25 之前的版本在` 1.23.13` (_2021-07-13_) ～ `1.24.17` (_2021-11-19_) 之间

React 17 的事件代理方式[发生了变化](https://reactjs.org/blog/2020/10/20/react-v17.html#changes-to-event-delegation)，一句话概括就是之前所有的 React 事件都会在 document 上统一代理处理，而 React 17 中这个行为改变了，变成在 React 的挂载根节点上监听。

这个改变对 Fusion Next 组件的影响是：
Overlay 组件需要判断是否有点击(这里用点击事件举例)发生在自身元素之外，来决定是否要收起弹层，这个监听是在 document 上监听原生事件。同时，`1.23.13 `之前，Overlay 对自己的 children 会做一个默认的 `stopPropagation` 操作，避免父元素也收到点击事件。
在 React 17 之前，document 上无论如何都是能拿到点击事件的，因为所有 React 事件在 document 上统一被处理，所以即使在 React 的事件回调中取消了冒泡，document 上仍然能拿到点击事件，因为这个时候原生事件已经冒泡到了 document。 这是 React 事件和 DOM 原生事件不同之处。

![image](https://user-images.githubusercontent.com/9381522/147069127-3f4d70e9-6120-422d-abdd-d15fd4a81c7d.png)

而在 React 17 中，由于代理位置“下移”了一点，所以这个时候如果指定了 `stopPropagation` 操作，事件就不会继续向上冒泡到 document，所以 Overlay 无法监听到点击，也就无法自动关闭弹层。

所以在 `1.23.13` 中，为了兼容 React 17 ，取消了 Overlay 中默认的 `stopPropagation` 操作，保证 document 上能拿到点击事件。但是这个改动造成了 Overlay 行为的不一致，父节点也会收到点击事件，一些用户在升级后反馈了这造成了一些使用场景上的问题。

所以在 `1.25` 中，为了和之前的长期行为保持一致，Overlay 的 `stopPropagation` 继续得以保留，同时提供了一个新选项 `useCapture`，使用捕获方式监听，避免被冒泡打断。这个属性并不是默认开启，所以如果之前版本在 `1.23.13` 到 `1.24.17`之间
且 React 版本大于等于 17 的用户可能会有感觉到有行为不一致。

针对这个问题目前有两种解法：
1. 使用 Overlay v2，全新的弹层组件，没有历史包袱，性能更好 (推荐)
2. 在 Overlay 上增加 `useCapture` 属性，可以使用 `ConfigProvider` 来全局配置：
```jsx
const config = {
  Overlay: {
     useCapture: true
  }
}
<ConfigProvider defaultPropsConfig={config}>
    ...
</ConfigProvider>
```

同时为了保证升级感知的一致性，在 Dialog, Drawer 等依赖 Overlay 的组件中，会默认开启 `useCapture`，预计随下个 patch 版本发布

**Comment by lakerswgq** [comment]
[问题演示](https://codesandbox.io/s/fusionzu-jian-ce-shi-forked-9ud64?file=/src/index.js)

**Comment by lakerswgq** [comment]
fixed in `1.25.10`

**Comment by wangchongwei** [comment]
升级@alifd/next到版本1.25.13出现异常
![image](https://user-images.githubusercontent.com/25812026/149060423-e78309a9-71af-472c-a1c5-3dc3a34dd408.png)
当弹窗已经关闭，但overlay视图仍然存在，导致无法点击页面

之前的@alifd/next版本为1.23.24

**Comment by edc-hui** [comment]
@lakerswgq 受教了，感谢告知底层原因
