### ISSUE TITLE
建议文档中添加node版本 >= 9.2.0

### ISSUE THREAD

**Issue by dddreee** [alibaba-fusion/next#3633]
### Type 
Platform

### Feature Description
@alifd/fusion-collector 使用的 fs-extra 是10.0版本的，里边使用 fs.realpath.native 方法在node 9.2.0添加的，我们当时的项目使用的node是8.x的，没有这个方法导致项目无法启动。所以希望能在文档中添加一个node版本的提示

**Comment by YSMJ1994** [comment]
@alifd/fusion-collector 并非由 fusion 官方提供并维护的工具库，建议找到包提供者来跟进
