### ISSUE TITLE
[Transfer]Transfer

### ISSUE THREAD

**Issue by YaWeiBoy** [alibaba-fusion/next#3636]
### Component 
Transfer组件
### Feature Description
Transfer组件interface未定义useVirtual，导致参数使用时提示错误
内容如下：：
    不能将类型“{ mode: "simple"; showSearch: true; useVirtual: true; onChange: (value: any[], data: any[], extra: any) => void; listStyle: { width: string; height: string; }; titles: Element[]; dataSource: any[]; value: any; }”分配给类型“IntrinsicAttributes & IntrinsicClassAttributes<Transfer> & Readonly<TransferProps> & Readonly<...>”。

**Comment by YSMJ1994** [comment]
> fixed in #3724
