### ISSUE TITLE
[CascaderSelect]是否支持自定义autoWidth的属性

### ISSUE THREAD

**Issue by yiescc** [alibaba-fusion/next#3637]
### Component 
CascaderSelect
### Feature Description
背景：
- 默认情况下组件的下拉选择会根据内容撑开宽度

需求：
- 是否可以像select的autoWidth的属性一样自定义

**Comment by lakerswgq** [comment]
是想要下拉弹层和输入框等宽么？

**Comment by YunMeng99** [comment]
@yiescc 有resultAutoWidth这个  先关闭处理，如需继续跟进重新开启
