### ISSUE TITLE
[Nav] 设计规范讨论： Nav 应该包含什么能力

### ISSUE THREAD

**Issue by bindoon** [alibaba-fusion/next#3646]
### Component 
Nav
### Feature Description
比如这么一张图，Nav 是完整的一行？还是仅仅中间一部分？
![image](https://user-images.githubusercontent.com/5189853/147480909-36236bd2-e55d-417b-8434-5b420c457178.png)
![image](https://user-images.githubusercontent.com/5189853/147481028-1310de43-2b0b-4cf7-8610-435fee3f8e3a.png)

如果不是完整一行，那么是否需要给 Nav 配成灰色还是透明色？

**Comment by YSMJ1994** [comment]
Stale
