### ISSUE TITLE
[Dialog]缺少dialogRender类型提示

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#3648]
### Component 
Dialog
### Feature Description
背景
- dialog现在缺少dialogRender的类型提示

**Comment by bindoon** [comment]
求提 PR

**Comment by yiescc** [comment]
> 求提 PR
我来提PR，dialogRender属性的描述应该是什么

**Comment by yiescc** [comment]
> 求提 PR

贡献指南在哪
