### ISSUE TITLE
[TimePicker2]TimePicker2 with specified format can only recognise full input

### ISSUE THREAD

**Issue by cheehonglee-lazada** [alibaba-fusion/next#3651]
### Component 
TimePicker2

### Steps to reproduce
When choosing custom format for TimePicker2,
    <TimePicker2 format="HH" />

the component won't help to select 12 when we just type "12", we will need to type in the full format "12:00:00" for TimePicker2 to recognise the time.

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/x2NQYzOX9Y2O.png)

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/ofJwUyKZpWdk.png)

**Comment by YSMJ1994** [comment]
原因：https://github.com/alibaba-fusion/next/blob/master/components/time-picker2/time-picker.jsx#L405 此处写死了 format
修复方案：根据 props.format 来格式化输入字符串
