### ISSUE TITLE
[Message]fusion 1.22.x，Message消息提示支持同时显示多个提示 

### ISSUE THREAD

**Issue by rootsli** [alibaba-fusion/next#3665]
### Component 
Message
### Feature Description
PR：当前的Message消息提示仅支持显示一个，部分场景希望Message支持显示多个消息。可以参考AntDesign的Message全局提示。

支持maxCount属性配置，最多同时显示多少个消息。

**Comment by bindoon** [comment]
已经在 @alifd/next@1.24 里面支持，可以看官网 Message 组件的 api
