### ISSUE TITLE
[TimePicker2]TimePicker2.RangePicker 组件使用有问题

### ISSUE THREAD

**Issue by incloudZhang** [alibaba-fusion/next#3678]
### Component 
TimePicker2

### Steps to reproduce
1.name赋值不上去
2.设置value或者defaultValue时第一次数据为空数组或者undefined后面再也更新不了
3.选择第一个值的时候分钟秒数设置了后第二个值只能选择比第一个值大的分支秒数

**Comment by YSMJ1994** [comment]
问题 1、2 缺乏示例，无法理解你的问题，问题 3 第二个值限制必须 >= 第一个值符合预期
