### ISSUE TITLE
[Pagination]Pagination 翻页器受控bug

### ISSUE THREAD

**Issue by Ethan997** [alibaba-fusion/next#3680]
### Component 
Pagination

### Steps to reproduce
当分页为受控组件时，动态修改current的值，页码部分没有正确显示，点击下一页却跳到末页。
场景：当url带有页码时，动态修改当前翻页器的页码，预期页码正确显示，点击下一页是当前页面加1。

![image](https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/Axqq8rbj89ed.png)

**Comment by YSMJ1994** [comment]
在当前版本没有复现你的问题，可以再看一下，如仍旧有问题，麻烦带上复现的链接
