### ISSUE TITLE
[Select]AutoComplete组件，非手动选择值的情况下，设置的值不会与下拉选项匹配

### ISSUE THREAD

**Issue by AmmiWang** [alibaba-fusion/next#3681]
### Component 
Select

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/weathered-currying-6nc76?file=/src/App.js)

### Steps to reproduce
AutoComplete组件，非手动选择值的情况下，设置的值不会与下拉选项匹配。

**Comment by bindoon** [comment]
可以用 fillProps=label 填充 label，组件api默认值在1.x里面不能直接修改

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进请重提 issue
