### ISSUE TITLE
[CascaderSelect][CascaderSelect]组件1.23.25版本搜索后不支持快捷键

### ISSUE THREAD

**Issue by RukiQ** [alibaba-fusion/next#3685]
### Component 
CascaderSelect

### Steps to reproduce
CasaderSelect组件在搜索的时候上下左右的快捷键，以及Enter快捷键都使用不了，1.18.16版本是支持的，最新的版本就不支持了，应该是组件升级导致的bug。

![image](https://user-images.githubusercontent.com/10571239/149724562-5bbdd4dc-7c70-4cc3-b009-7f0bca625f1e.png)

**Comment by lakerswgq** [comment]
这个我看了下代码3年前之后就没变过，能确认下是哪个版本是支持的吗

**Comment by RukiQ** [comment]
我写了是1.18.16，不是很确定。
![image](https://user-images.githubusercontent.com/10571239/150088778-f04d4ef6-c62e-4855-8bf9-0ff83acd0299.png)

那现在能修复下这个Bug吗？

**Comment by RukiQ** [comment]
预期行为：在搜索的时候可以支持上下左右的快捷键，以及Enter快捷键
