### ISSUE TITLE
[Slider]slider动态渲染数据

### ISSUE THREAD

**Issue by PiscesWD** [alibaba-fusion/next#3702]
### Component 
Slider
 版本:  "react": "^17.0.2",
            "@alifd/next": "^1.19.4",
          "ice.js": "^2.0.0",

不停轮训动态渲染组件, slider陷入死循环页面白屏
Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

**Comment by PiscesWD** [comment]
不停轮训动态渲染, slider陷入死循环页面白屏

**Comment by YSMJ1994** [comment]
Stale
