### ISSUE TITLE
[Dialog]Dialog v2 增加 wrapperClassName 支持

### ISSUE THREAD

**Issue by zuoqi705** [alibaba-fusion/next#3703]
### Component 
Dialog

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/d396b8ce](https://riddle.alibaba-inc.com/riddles/d396b8ce)

### Steps to reproduce
wrapperClassName 忘透传了，希望平铺支持，同时文档也更新一下

**Comment by bindoon** [comment]
v1 是通过 overlay 的能力透传的， v2 的 Dialog 没有用 overlay，需要单独支持 wrapperClassName 透传
