### ISSUE TITLE
[Tab] key类型是number，onChange却变成string

### ISSUE THREAD

**Issue by cwtuan** [alibaba-fusion/next#3720]
### Component 
Tab

### Reproduction link 
[https://codepen.io/cwtuan/pen/BamKGzm?editors=0010](https://codepen.io/cwtuan/pen/BamKGzm?editors=0010)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/3455798/152139647-acbd89e4-83ac-4049-8f52-854d16ab1abc.png)

**Comment by bindoon** [comment]
讨论下，在 React 里面key是否区分强类型，还是都是转 string 的呢？

**Comment by cwtuan** [comment]
React 里面key可以是string or number

![image](https://user-images.githubusercontent.com/3455798/153328494-9841d11c-0d47-467f-92d1-8a13c2e05fb9.png)

**Comment by YSMJ1994** [comment]
https://github.com/facebook/react/blob/main/packages/react/src/jsx/ReactJSXElement.js#L679 
React 对于 key 的处理是默认转 string
