### ISSUE TITLE
[Upload]M1芯片 chrome 浏览器无法使用 Upload 组件

### ISSUE THREAD

**Issue by datou0412** [alibaba-fusion/next#3721]
### Component 
Upload

### Reproduction link 
[https://fusion.alibaba-inc.com/pc/component/upload?themeid=40463#base-container](https://fusion.alibaba-inc.com/pc/component/upload?themeid=40463#base-container)

### Steps to reproduce
用 M1 芯片的 Mac 电脑，鼠标点击上传按钮，无法唤起文件上传的弹框

**Comment by bindoon** [comment]
M1芯片机器无法复现。是 chrome 哪个版本？

**Comment by yangweinan** [comment]
我的是M1的芯片，正常显示的，看下你的浏览器哪个版本？

**Comment by xdlrt** [comment]
最近在多个网站上都发现了类似的问题，更新 chrome 后好了，大概率是 chrome 本身的 bug 引起的。

**Comment by laixiangran** [comment]
同样的问题，chrome 版本 97.0.4692.99（正式版本） (x86_64)，不是M1芯片
