### ISSUE TITLE
[Slider]slider rerender重新初始化的问题

### ISSUE THREAD

**Issue by H5DevHoward** [alibaba-fusion/next#3722]
### Component 
Slider

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/6bf2c95f](https://riddle.alibaba-inc.com/riddles/6bf2c95f)

### Steps to reproduce
只要 onChange setSate  Slider 就会重置

**Comment by bindoon** [comment]
@H5DevHoward 我看了这个 demo 好像没问题，挺正常的。

**Comment by H5DevHoward** [comment]
@bindoon https://riddle.alibaba-inc.com/riddles/6bf2c95f 这个

**Comment by H5DevHoward** [comment]
这个bug什么时候修复呢？

**Comment by H5DevHoward** [comment]
> 

这个bug什么时候修复呢？

**Comment by H5DevHoward** [comment]
@bindoon 这个bug什么时候修复呢？
