### ISSUE TITLE
[DatePicker2] DatePicker2 WeekPicker 指定初始值错误

### ISSUE THREAD

**Issue by zuoqi705** [alibaba-fusion/next#3727]
### Component 
DatePicker2

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/983427e9](https://riddle.alibaba-inc.com/riddles/983427e9)

### Steps to reproduce
demo 里应该是 2021-52周，而不是2022-52周

**Comment by YSMJ1994** [comment]
这是 dayjs 的已知问题 https://github.com/iamkun/dayjs/issues/2274 ，官方指明应使用 gggg 代替 YYYY 来获取 weekYear，目前 DatePicker2 默认使用 YYYY-wo 作为 WeekPicker 的默认 format，计划在近期调整为 gggg-wo 为默认 format ，并增加兜底逻辑，对用户传入的 format 中的 YYYY 处理为 gggg 后再执行
