### ISSUE TITLE
Done插件的组件物料无法使用，显示主题资源加载超时

### ISSUE THREAD

**Issue by IHOD** [alibaba-fusion/next#3734]
### Steps to reproduce
Done插件版本3.2.6
提示信息：
![origin_img_v2_9c4ee9ba-5a58-4a50-b9f3-6c8ff6da4a7g](https://user-images.githubusercontent.com/16380442/153751050-33193bef-642f-4e2c-b84e-2cdbdf2a9c8c.png)

**Comment by sxqwaade** [comment]
+1   有人帮忙看下吗？ 现在功能设计急着用

**Comment by bindoon** [comment]
正在看了，资源的问题

**Comment by mark-ck** [comment]
@IHOD 
cnpm 升级导致，现已跟进修复
