### ISSUE TITLE
[Drawer]vite项目中引入fusiondesign在运行npm run build报错

### ISSUE THREAD

**Issue by csfankun** [alibaba-fusion/next#3748]
### Component 
Drawer

### Reproduction link 
[https://stackblitz.com/edit/vitejs-vite-ajpyen?file=src%2FApp.tsx&terminal=dev](https://stackblitz.com/edit/vitejs-vite-ajpyen?file=src%2FApp.tsx&terminal=dev)

### Steps to reproduce
node_modules/@alifd/next/types/drawer/index.d.ts:13:18 - error TS2430: Interface 'DrawerProps' incorrectly extends interface 'HTMLAttributesWeak'.

重现步骤：
1、打开链接等待运行正常
2、在编辑器区域新开terminal终端，运行npm run build 即可发现此报错

**Comment by csfankun** [comment]
再补充下。如果vite模式不是typescript的语法。则npm run build是能打包成功

**Comment by YSMJ1994** [comment]
tsconfig.json 里 设置  skipLibCheck: true 即可解决
