### ISSUE TITLE
[Message]弹出的message 没有固定在顶部

### ISSUE THREAD

**Issue by myronliu347** [alibaba-fusion/next#376]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Message

### Environment
mac pro

### Steps to reproduce
RT

**Comment by youluna** [comment]
可能跟这个相关 https://github.com/alibaba-fusion/next/pull/372/files/ac22b052f3e1d25200ecc5de7440da0f1c6feefc#r260103682

**Comment by myronliu347** [comment]
fixed
