### ISSUE TITLE
[DatePicker]DatePicker组件获取小时的值有误

### ISSUE THREAD

**Issue by DouLu** [alibaba-fusion/next#3765]
### Component 
DatePicker

### Reproduction link 
[https://codepen.io/pen?&editors=0010](https://codepen.io/pen?&editors=0010)

### Steps to reproduce
import { DatePicker } from '@alifd/next';

const { RangePicker } = DatePicker;
const onChange = val => {alert(val.format('YYYY-MM-DD hh:mm:ss'))};

ReactDOM.render(<div>
    
    <DatePicker format="YYYY-M-D" onChange={onChange} showTime={{ format: 'HH:mm:ss' }} />
   
</div>, mountNode);
选择时分秒，format的是12小时制，而实际选择的是24小时制

**Comment by eternalsky** [comment]
这看起来不是 DatePicker 的问题，onChange 的时候你获得的是一个 Moment 对象，如果真的 format 有问题（当然大概率不是），那就是 Moment 有问题了。
