### ISSUE TITLE
[Tab]tab组件来回切换页面时页面无响应

### ISSUE THREAD

**Issue by yang1004** [alibaba-fusion/next#3767]
### Component 
Tab
### Feature Description
使用tab组件时，初次加载时正常页面正常，切换回此页面后赋值成功但页面无响应，但去除activeKey参数正常响应

**Comment by YunMeng99** [comment]
@yang1004 能提供一个demo吗 你这个赋值是怎么实现的 问题描述不清楚先关闭处理，如需继续跟进重新开启
