### ISSUE TITLE
[Balloon]Ballon 浮窗消失后 会自动触发当前document.activeElement的focus(), 如果此时页面activeElement元素在页面顶部，会导致页面自动位移到最上面

### ISSUE THREAD

**Issue by heihei12305** [alibaba-fusion/next#3790]
### Component 
Balloon

### Reproduction link 
[https://codepen.io/heihei12305/pen/JjMdPWp?editors=0010](https://codepen.io/heihei12305/pen/JjMdPWp?editors=0010)

### Steps to reproduce
点击Tab 的 “Document” 元素，然后hover页面最下面的Ballon "bbb"， 将鼠标移开等浮窗消失后，页面会自动位移到最上面

**Comment by bindoon** [comment]
autoFocus={false}
