### ISSUE TITLE
[Dialog]支持配置有 Footer 和无 Footer 时，Body 的 padding-bottom 不同

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#3799]
### Component 
Dialog
### Feature Description
在我们的业务设计规范中，设计师要求 Body 和 Footer 内容之间有 24px 空间，在没有 Footer 的情况下，Body 内容和 Dialog 底部之间也有 24px 空间。

目前主题定制只能固定 Body 和 Footer 的 padding。

如果把 24px 加在 Body 的 padding-bottom 上，在 Body 内容滚动的时候，Footer 没有上边距会很奇怪。

![image](https://user-images.githubusercontent.com/5836790/158544051-9ddf5122-0b73-4904-9016-f38132a28af8.png)

如果 Body 的 padding-bottom 和 Footer 的 padding-top 为 12px，在内容过长滚动的时候，是看不到 Body 的 padding-bottom 的，视觉上是 12px

![image](https://user-images.githubusercontent.com/5836790/158543811-8a624dff-19eb-4469-b691-68bb77a75db0.png)

如果把 24px 加在 Footer 的 padding-bottom 上，在没有 Footer 的时候，Body 下边距就没有了。

![image](https://user-images.githubusercontent.com/5836790/158543606-071a13e3-3a01-4bd7-87ee-3658985ea31f.png)

希望能增加一个新的主题配置参数，在无 Footer 时使用不同的 Body padding-bottom：

```scss
$dialog-content-padding-bottom: 0;
$dialog-content-padding-bottom-no-footer: 24px;
```

**Comment by bindoon** [comment]
放个截图吧

**Comment by guoyunhe** [comment]
@bindoon 补充了
