### ISSUE TITLE
[Field]如何避免Field.parseName在dialog.visible=false时丢失？

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#3813]
### Component 
Field
### Feature Description
背景
https://codepen.io/xmsz/pen/qBpbEBG?editors=0010

情况有点复杂
- 我有一个form.item.name=a.b，并且开启了parseName=true
- 正常修改的时候，通过field.getValues()是正常的
- 但如果我在关闭弹窗以后，这个a.b就没了，只剩下了一级对象的值和a一个空对象

**Comment by bindoon** [comment]
把 Field 的 autoUnmount 关闭即可

**Comment by xmsz** [comment]
> 把 Field 的 autoUnmount 关闭即可

ok 明白了
