### ISSUE TITLE
[Menu] Divider 被 <> 包裹后渲染报错

### ISSUE THREAD

**Issue by micate** [alibaba-fusion/next#3825]
### Component 
Menu

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/awesome-cerf-0pxwms?file=/src/App.js:114-121)

### Steps to reproduce
见 codesandbox，Menu 中处理时没有考虑这种场景：

https://github.com/alibaba-fusion/next/blob/master/src/menu/view/menu.jsx#L116

此时 child 为数组，没有 `.type` 属性，因此没有正确透传 root 属性，导致 Divider render 时报错。

**Comment by bindoon** [comment]
![image](https://user-images.githubusercontent.com/5189853/163799109-b42db702-d5cd-4b3e-b6ba-7246b0af3074.png)
