### ISSUE TITLE
[Upload]表单受控预览模式下onPreview方法失效

### ISSUE THREAD

**Issue by mingchangran** [alibaba-fusion/next#3830]
### Component 
Upload

### Reproduction link 
[https://codepen.io/mingchangran/pen/RwxVjeR?editors=0011](https://codepen.io/mingchangran/pen/RwxVjeR?editors=0011)

### Steps to reproduce
如标题，希望在预览模式下onPreview方法能够正常执行

**Comment by bindoon** [comment]
欢迎直接提 Pull request
