### ISSUE TITLE
[Pagination]Pagination 选择PageSize时Maximum update depth exceeded

### ISSUE THREAD

**Issue by komaedaXnagito** [alibaba-fusion/next#3836]
### Component 
Pagination

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/87156d34](https://riddle.alibaba-inc.com/riddles/87156d34)

### Steps to reproduce
复现流程
1.每页显示选择100
2.滚动到页面最底端
3.每页显示选择50
4.不要滚动页面(滚动之后就没bug了)
5.再点击一下每页数量的选择按钮

**Comment by komaedaXnagito** [comment]
快6个月了，bug依然还在

**Comment by weinianyang** [comment]
1.25 v2优化了弹层逻辑。popupProps={{ v2: true }}

**Comment by weinianyang** [comment]
1.25 v2优化了弹层逻辑。popupProps={{ v2: true }}
