### ISSUE TITLE
[TimePicker2]TimePicker2.RangePicker 结合 Field  使用无法赋值

### ISSUE THREAD

**Issue by chen-chunk** [alibaba-fusion/next#3841]
### Component 
TimePicker2
### Feature Description
下面的操作无效
field.setValue("time-picker", [ dayjs(),  dayjs()]);

初始化是正常的
init("time-picker", {
      rules: [{ required: true, message: "Time Required" }],
      initValue:  [ dayjs(),  dayjs()]
})

**Comment by lakerswgq** [comment]
提供一个复现 demo

**Comment by dddreee** [comment]
> 提供一个复现 demo

https://codepen.io/dddreee/pen/KKowJpE?editors=0010

**Comment by YunMeng99** [comment]
@dddreee  您这个demo打不开了 先关闭处理，如需继续跟进重新开启
