### ISSUE TITLE
[Tree]tree 选中在 isNodeBlock 情况下无法取消选中

### ISSUE THREAD

**Issue by zuoqi705** [alibaba-fusion/next#3850]
### Component 
Tree

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/2cd90768](https://riddle.alibaba-inc.com/riddles/2cd90768)

**Comment by lakerswgq** [comment]
排查了下是 Checkbox 组件的问题

https://github.com/alibaba-fusion/next/blob/7edc87f010e3f74c9345bb5efc4924725ff185ef/src/checkbox/checkbox.jsx#L226-L237

这里用了 onChange 事件去处理状态变更，checkbox 的 onChange 事件在 foucs 状态下不会触发

https://stackoverflow.com/questions/4942437/html-checkbox-onchange-not-working
