### ISSUE TITLE
[Select]select 同时添加 width 和 addonTextAfter 属性，箭头样式异常

### ISSUE THREAD

**Issue by hellohy** [alibaba-fusion/next#3854]
### Component 
Select

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/427eaf7a](https://riddle.alibaba-inc.com/riddles/427eaf7a)
![image](https://user-images.githubusercontent.com/13514644/163128656-f1cbd2e6-7e4f-44d3-831c-86f3157500f2.png)

### Steps to reproduce
期望结果：箭头位置正常

**Comment by bindoon** [comment]
Select 不是输入框，过滤掉 addonTextAfter API
