### ISSUE TITLE
[DatePicker]DatePicker 日期选择组件选择完时间之后，自动定位到页面顶部

### ISSUE THREAD

**Issue by sendsnow** [alibaba-fusion/next#3856]
### Component 
DatePicker

### Steps to reproduce
实际结果：DatePicker 日期选择组件选择完时间之后，自动定位到页面顶部
期望结果：选择完时间之后，遮罩层不滚动

**Comment by lakerswgq** [comment]
给个复现 demo

**Comment by YSMJ1994** [comment]
Stale
