### ISSUE TITLE
[Search]Search 的尺寸问题讨论

### ISSUE THREAD

**Issue by imsobear** [alibaba-fusion/next#386]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Search

### Feature Description
- 为什么默认的高度跟 button 和 Input 之类的不一致，同等 size 的都相对较高，通过主题可以实现，但是我认为默认应该是一样高的
- 为什么  shape="simple" 会改变组件高度，这个感觉不符合 shape 的语义（当然这个也可以通过主题解决）
- 为什么没有支持 size="small"，Search 经常会跟 button 之类放在一起，如果 button 用的是 small，那 search 就很奇怪了

**Comment by youluna** [comment]
类似问题 https://github.com/alibaba-fusion/next/issues/303

目前情况（以下数值均为高度）：
Search支持large 60px、medium（40px默认）
Button支持large 40px、medium（28px 默认）、small 20px 
![image](https://user-images.githubusercontent.com/10049465/53556177-4c16ee00-3b7e-11e9-9f50-8167d5fd02d5.png)

breakchange 1.x应该不会改了，可以讨论2.x版本：
1. Search 新增small
2.Search 三种高度对应Button/Input等组件
3.shape不该变高度，只改变放大镜位置

**Comment by tao1991123** [comment]
这个问题 在内网群直接和设计师讨论比较合适

**Comment by imsobear** [comment]
卧槽已经要讨论 2.x 版本了，那不用讨论了，现在这样挺好的。。。前两点主题可以支持就好了，增加 size="small" 这个应该不是 br @youluna

**Comment by bindoon** [comment]
两个size是设计师定的，可以和设计师讨论下当初为何是这么设计的！

**Comment by youluna** [comment]
0.0   加small之后   Search 的 size还是会比Button Input整个小一圈，明天把设计师拉进群里一起聊下好了
