### ISSUE TITLE
[Dialog]Dialog, the message shortcut pop-up box cannot get the prefix of the class name replaced by the < configprovider prefix = "text -" > component

### ISSUE THREAD

**Issue by xiehuiyao** [alibaba-fusion/next#3863]
### Component 
Dialog
### Feature Description
Dialog,Message快捷弹框获取不到通过<ConfigProvider prefix="text-">组件替换的类名前缀，导致弹出框位置、样式等发生变化。
链接：https://fusion.alibaba-inc.com/feedback

**Comment by bindoon** [comment]
用 withContext 可以获取。https://riddle.alibaba-inc.com/riddles/20d487d1

**Comment by xiehuiyao** [comment]
因为系统里边几百上千的弹出框，都需要这样替换的话，成本会很大，改动的页面很多，看看能否从fusion自生解决下问题，开发这边更新版本就可以解决的这种方式

**Comment by bindoon** [comment]
你看demo，直接调用 Message.xxx 的 prefix 是换掉了的。如果你项目里面只有一次 ConfigProvider 全局配置是没问题的。
