### ISSUE TITLE
代码有问题

### ISSUE THREAD

**Issue by qiufeihong2018** [alibaba-fusion/next#3866]
### Reproduction link 
[https://fusion.alibaba-inc.com/pc/yuque/fusion-design-system/ahvubx/vbg4pt?themeid=40463](https://fusion.alibaba-inc.com/pc/yuque/fusion-design-system/ahvubx/vbg4pt?themeid=40463)

### Steps to reproduce
```
cosnt localeObj = {
    component1: {
        key1: value1,
        key2: value2
    },
    component2: {
        key1: value1,
        key2: value2
    }
}
<ConfigProvider locale={localeObj}>
```

cosnt改成const才对

**Comment by bindoon** [comment]
fixed

**Comment by bindoon** [comment]
fixed
