### ISSUE TITLE
网站样式问题

### ISSUE THREAD

**Issue by qiufeihong2018** [alibaba-fusion/next#3867]
### https://fusion.alibaba-inc.com/pc/yuque/fusion-design-system/ahvubx/ypqppc?themeid=40463
https://fusion.alibaba-inc.com/pc/yuque/fusion-design-system/ahvubx/ypqppc?themeid=40463

### Steps to reproduce

希望不要遗漏 t（@alifd/next）

<img width="902" alt="image" src="https://user-images.githubusercontent.com/36500514/164367053-8c519ea8-94e0-4e58-896d-80658cd1256d.png">

**Comment by bindoon** [comment]
fixed
