### ISSUE TITLE
内容错误

### ISSUE THREAD

**Issue by qiufeihong2018** [alibaba-fusion/next#3868]
### Reproduction link 
[https://fusion.alibaba-inc.com/pc/yuque/fusion-design-system/ahvubx/gyqrg9?themeid=40463](https://fusion.alibaba-inc.com/pc/yuque/fusion-design-system/ahvubx/gyqrg9?themeid=40463)

### Steps to reproduce
应该改成package.json

<img width="992" alt="image" src="https://user-images.githubusercontent.com/36500514/164368399-da641899-4779-467a-91e1-716880b836bb.png">

**Comment by bindoon** [comment]
fixed
