### ISSUE TITLE
[Balloon]Balloon 对空标签的兼容处理

### ISSUE THREAD

**Issue by Nanchenk** [alibaba-fusion/next#3870]
### Component 
Balloon and ToolTip

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/a55caaac](https://riddle.alibaba-inc.com/riddles/a55caaac)

### Steps to reproduce
如果 trigger 的属性传入的是 <> 空标签包住的节点，那么就不会出现气泡了，文档里写的类型是 any
![image](https://user-images.githubusercontent.com/12292427/164684436-961c917c-a769-4e10-bb61-786c8465b92f.png)

**Comment by bindoon** [comment]
什么场景下你的触发器 trigger 会不存在呢？

**Comment by Nanchenk** [comment]
> 

看上面的例子，左边的 button，只要用 <> 包裹就会不显示

**Comment by bindoon** [comment]
你的需求是一个 Balloon，跟随点击不同的地方切换位置吧，有点类似新手引导？

这个时候感觉应该用 api target，然后 动态切换 target 这个定位目标吧？

**Comment by Nanchenk** [comment]
> 你的需求是一个 Balloon，跟随点击不同的地方切换位置吧，有点类似新手引导？
> 
> 这个时候感觉应该用 api target，然后 动态切换 target 这个定位目标吧？

不是啊，只是 trigger 用了 fragment 而已，看例子 https://riddle.alibaba-inc.com/riddles/a55caaac

**Comment by bindoon** [comment]
```
const CustomButton = (props) => <><Button {...props}>click</Button></>
```
类似这样包裹一个组件，因为需要对 trigger 做点击监控，所以属性需要透传过去。
