### ISSUE TITLE
[NumberPicker]两种numberpicker用法区别

### ISSUE THREAD

**Issue by m1582006** [alibaba-fusion/next#3871]
### Component 
NumberPicker
### Feature Description
在文档中描述一下两种组件的桌面端用法区别。什么时候用哪个 还是桌面端任意二选一

**Comment by bindoon** [comment]
没明白问题，多点截图和描述

**Comment by m1582006** [comment]
因为设计规范中给出了两种不同ui的组件，想确定是什么时候选择哪个UI。希望给出使用时选择的指导
<img width="325" alt="image" src="https://user-images.githubusercontent.com/28682855/167304290-a75f440d-52c5-41f2-91b5-cdb07085ec55.png">
