### ISSUE TITLE
[Table][Table] 开启表格的单选时，如果表格经过了销毁=>显示 过程，就不能再选数据了

### ISSUE THREAD

**Issue by GroupOfStar** [alibaba-fusion/next#3873]
### Component 
Table

### Reproduction link 
[https://codepen.io/groupofstar/pen/abErjKx](https://codepen.io/groupofstar/pen/abErjKx)

### 重现步骤
1. 先选一项表格中的数据
2. 点击隐藏后，再点一遍显示出表格来
3. 再选表格中的数据时，就选不了了

![image](https://user-images.githubusercontent.com/28132535/165058144-44824ce2-4295-4e3a-8bdb-30654a3395c8.png)

### 期望结果
可以继续选择
### 实际结果
无法点击了

**Comment by eternalsky** [comment]
新版 next 已不存在此问题
