### ISSUE TITLE
[Input]Input 在 ref 引用上缺少 getInputNode 函数签名

### ISSUE THREAD

**Issue by chvin** [alibaba-fusion/next#3878]
### Component 
Input

### Reproduction link 
![image](https://user-images.githubusercontent.com/5383506/165494636-92fc521e-7c74-4334-878c-49136fb9307d.png)
![image](https://user-images.githubusercontent.com/5383506/165494652-f0727111-7893-4f52-915b-cf4f5be0f1e8.png)

### Steps to reproduce
在 TS 环境下，Input ref 引用下缺少 getInputNode 函数签名，这个是官方文档透出的 API

**Comment by bindoon** [comment]
求 PR  文件在 types/input/index.d.ts 里面
