### ISSUE TITLE
[Select]Select传入popupProps={{triggerType: 'focus'}}，下拉选中后未自动失焦，再次点击输入框无法唤出下拉菜单

### ISSUE THREAD

**Issue by air-eienniutau** [alibaba-fusion/next#3884]
### Component 
Select

### Reproduction link 
[https://codepen.io/air_wataru/pen/ExQjBoV?editors=0010](https://codepen.io/air_wataru/pen/ExQjBoV?editors=0010)

### Steps to reproduce
Select传入popupProps={{triggerType: 'focus'}}，下拉选中后未自动失焦，再次点击输入框无法唤出下拉菜单，需要手动点击页面其它位置使输入框失焦，才能进行二次选择

**Comment by bindoon** [comment]
既然有点击行为，建议 popupProps={{triggerType: ['focus', 'click]}} 两种行为都设上
