### ISSUE TITLE
[Dialog]Dialog开启v2后通过样式表设置padding失效

### ISSUE THREAD

**Issue by yanqianyu** [alibaba-fusion/next#3885]
### Component 
Dialog

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/83ba83ed](https://riddle.alibaba-inc.com/riddles/83ba83ed)

### Steps to reproduce
Dialog的v2版本通过样式表设置dialog-body的padding为0无效，关闭v2设置成功。

**Comment by bindoon** [comment]
v2 结构不一样，建议查找下样式再设置

**Comment by bowei-jbw** [comment]
Duplicate of #3892
