### ISSUE TITLE
[Shell]使用CLI创建 TypeScript   Fusion Design的项目，将导航栏和左侧菜单栏固定后，强刷（Ctrl  F5）,有一定几率 next-shell-sub-main 生成的样式margin-left值错误，导致内容不在可视区域显示！

### ISSUE THREAD

**Issue by waittingbar** [alibaba-fusion/next#3887]
### Component 
Shell

### Reproduction link 
[https://oss.lkjlx.cn/project_.zip](https://oss.lkjlx.cn/project_.zip)

### Steps to reproduce
Shell 布局在使用了固定头部和菜单栏后，windows电脑 强刷（Ctrl F5）会有一定几率出现，内容区dom的margin-left值计算错误而导致页面空白。
复现在线地址：http://162.14.70.90:8080/menu2
劳烦看下这个bug是怎么出现的，目前对项目上线有一点影响，非常感谢！
邮箱：928864229@qq.com

**Comment by waittingbar** [comment]
// Shell使用代码

<ConfigProvider device={device}>
      <Shell
        style={{
          minHeight: '100vh',
        }}
        type="brand"
        fixedHeader
      >
        <Shell.Branding>
          <Logo
            image="https://img.alicdn.com/tfs/TB1.ZBecq67gK0jSZFHXXa9jVXa-904-826.png"
            text="Logo"
          />
        </Shell.Branding>
        <Shell.Navigation
          direction="hoz"
          style={{
            marginRight: 10,
          }}
        />
        <Shell.Action />
        <Shell.Navigation fixed>
          <PageNav />
        </Shell.Navigation>

        <Shell.Content>{children}</Shell.Content>
        <Shell.Footer>
          <Footer />
        </Shell.Footer>
      </Shell>
    </ConfigProvider>

**Comment by waittingbar** [comment]
![image](https://user-images.githubusercontent.com/3805567/167576226-53ca15e1-97a6-4626-a489-388f4c6a2481.png)

**Comment by YSMJ1994** [comment]
我们正在整理一些遗留的 bug，现在这个问题还在吗?
