### ISSUE TITLE
设计预览中的“构建一套最佳模式库”最下面的“产品单元/Product Unit“描述文字，把list错打成了lsit

### ISSUE THREAD

**Issue by loooogan** [alibaba-fusion/next#389]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.13.2

### Component
VirtualList

### Environment
Mac、Chrome、

### Reproduction link
[https://fusion.design/design/doc/15](https://fusion.design/design/doc/15)

### Steps to reproduce
https://fusion.design/design/doc/15 最底部的 “产品单元/Product Unit”下面的描述，把list错打成了lsit

**Comment by youluna** [comment]
fixed, thanks
