### ISSUE TITLE
[Select]Select 清除项和清空操作不一致的 2 个问题

### ISSUE THREAD

**Issue by cytle** [alibaba-fusion/next#3896]
### Component 
Select

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/7c755ca7](https://riddle.alibaba-inc.com/riddles/7c755ca7)

### Steps to reproduce

当前表现：
![image](https://user-images.githubusercontent.com/5120505/168056386-9990729e-648c-49fe-ae33-d8f61d2b3ad9.png)

期望表现：

1. 通过清除项或清空清除，没选中项后，value 为 统一的 [](空数组)
2. 通过清除项或清空清除，没选中项后，hover 输入框都不再出现清空 icon

**Comment by bindoon** [comment]
交互层面可以先改为一致。

不过现在大清空是 undefined，小清空是 []。涉及到类型的变化，当前不能直接改掉，可能会给业务带来 BR
