### ISSUE TITLE
[Transfer]Transfer 搜索关键字全选后，不能取消全选

### ISSUE THREAD

**Issue by cytle** [alibaba-fusion/next#3902]
### Component 
Transfer

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/7f58ca58](https://riddle.alibaba-inc.com/riddles/7f58ca58)

### Steps to reproduce
Transfer 使用带有 Disabled 项的数据源，在搜索关键字全选后，不能取消全选。

![image](https://user-images.githubusercontent.com/5120505/168717377-0ef06e78-7140-48b8-8d44-7faa387edf52.png)

**Comment by YunMeng99** [comment]
官网目前是支持的  先关闭处理，如需继续跟进重新开启
