### ISSUE TITLE
[Dropdown]Dropdown组件的Child为FC时，下拉菜单交互异常

### ISSUE THREAD

**Issue by inarol** [alibaba-fusion/next#3905]
### Component 
Dropdown

### Reproduction link 
[https://codepen.io/linjinying/full/yLvMLKY](https://codepen.io/linjinying/full/yLvMLKY)

### Steps to reproduce
Dropdown组件的Child为FC时，鼠标指针移到菜单后，会自动隐藏菜单。

**Comment by bindoon** [comment]
![image](https://user-images.githubusercontent.com/5189853/169257236-f57688f5-1f45-46d4-a0b1-b44b1a6963f8.png)
props 要透传给 Menu

**Comment by cpxGithub** [comment]
这种设计很不合理吧，为什么需要使用者还显示的传递props，而且需要这么使用为什么又不在文档中描述。
