### ISSUE TITLE
[Field]数组的结构化解析 如何才能不中断input的输入

### ISSUE THREAD

**Issue by yiescc** [alibaba-fusion/next#3915]
### Component 
Field
### Feature Description
- 表现：使用Field.useField并开启结构化解析parseName，使用input作为值的输入，但是在输入的过程中input会被中断。
- 示例代码：https://fzc3hy.csb.app/
-  问题：如何使用才能保留结构化解析的功能，又不中断input的正常输入

**Comment by YunMeng99** [comment]
示例代码这边无法显示 先关闭处理，如需继续跟进重新开启
