### ISSUE TITLE
[Select]0.x

### ISSUE THREAD

**Issue by 1321667290** [alibaba-fusion/next#392]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Select

### Environment
win7，360browser 10.0 

### Reproduction link
[https://alibaba.github.io/ice/0.x/component/select](https://alibaba.github.io/ice/0.x/component/select)

### Steps to reproduce
select多选框，再次点击已选项会去除该选项，但是该选项的√还在

**Comment by youluna** [comment]
0.x问题提到内网gitlab（内网用户）或者反馈给ice团队（外网用户）
