### ISSUE TITLE
[DatePicker2] RangePicker 设置 format 后选择不了时间

### ISSUE THREAD

**Issue by zuoqi705** [alibaba-fusion/next#3924]
### Component 
DatePicker

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/a30b1c1e](https://riddle.alibaba-inc.com/riddles/a30b1c1e)

**Comment by linjunxyz** [comment]
是因为’MMM,DD,YYYY‘这种日期格式我们不支持展示，format设置成支持的格式是可以选择时间的，比如’YYYY/MM/DD‘
