### ISSUE TITLE
[Dialog]dialog组件 里面套用table 会有更新问题

### ISSUE THREAD

**Issue by Tankpt** [alibaba-fusion/next#3925]
### Component 
Dialog

### Steps to reproduce
https://links.alipay.com/app/room/5fdb179ccd068c058047fb6d/search/1653895799280/?kw=dialog%20cache&from=out&hotWord=INPUT&detailType=conversation&detailId=6078fa0e0f030d050e5a7ab6

这个问题使用cache 原因是啥，然后我理解是不是个内部短期无法解决的bug。

文档里面从没看到相关的标注。使用的人。重复采坑。

**Comment by YSMJ1994** [comment]
现在这个问题无法复现了，麻烦再 check 一下吧

**Comment by YSMJ1994** [comment]
Stale
