### ISSUE TITLE
[Checkbox] Checkbox的value类型，应该包含boolean

### ISSUE THREAD

**Issue by cwtuan** [alibaba-fusion/next#3931]
### Component 
Checkbox

### Steps to reproduce
Checkbox定义文件有问题
![image](https://user-images.githubusercontent.com/3455798/171183218-6cfd2519-0e05-4925-bf09-cc982505ccfa.png)

Checkbox的value类型，应该包含boolean

目前ts定义不支持boolean：
![image](https://user-images.githubusercontent.com/3455798/171183118-c7a3b951-6cc7-4c15-a257-e79e66828bc6.png)

在[types](https://github.com/alibaba-fusion/next/blob/master/types/checkbox/index.d.ts#L111)定义成了：
![image](https://user-images.githubusercontent.com/3455798/171182599-8ef7fde7-bb9a-4e16-ba9e-f1c49f72d4c7.png)

**Comment by youluna** [comment]
你的场景下用checked是不是更合适？

checkbox设计上是想把value 和 checked 分开
- 比如签署协议场景，用checked更合适，https://fusion.design/pc/component/form?themeid=2#base-container
![image](https://user-images.githubusercontent.com/10049465/171324473-59e624dd-b342-4e93-822b-28f388624056.png)

- 比如多选场景用value获得一个数组的结果，https://fusion.design/pc/component/form?themeid=2#mix-container
![image](https://user-images.githubusercontent.com/10049465/171324453-1ee0d670-3ecb-45f2-a454-b2f8a66eccfb.png)

**Comment by cwtuan** [comment]
一个form底下，有多个item，我都用field来管理，如果只有checkbox要单独管理，那不太合理。

而且目前组件行为是支持的boolean，只是ts报错，把ts定义文件改下就好了。行为不变
