### ISSUE TITLE
[Search]onChange does not follow Select.AutoComplete

### ISSUE THREAD

**Issue by justnewbee** [alibaba-fusion/next#394]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.13.2

### Component
Search

### Environment
any

### Reproduction link
[n/a](n/a)

### Steps to reproduce
Select.AutoComplete onChange will accept 3 parameters `onChange(value, source, item)`
Search says it inherits Select.AutoComplete's interface
However, onChange in Search only takes 1 parameter that is value

**Comment by youluna** [comment]
any progress?
