### ISSUE TITLE
[Table]当同时使用表格分组和锁列 表格给你异常

### ISSUE THREAD

**Issue by fanzih** [alibaba-fusion/next#3940]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/3d78eb3b](https://riddle.alibaba-inc.com/riddles/3d78eb3b)

### Steps to reproduce
当同时使用表格分组和锁列的时候, 锁列的内容 没有挡住下面的内容, 然后滚动之后, 表头也没有同步

**Comment by YSMJ1994** [comment]
Same as #4396 , fixed at 1.26.35
