### ISSUE TITLE
[Icon]iconfont

### ISSUE THREAD

**Issue by leehomeok** [alibaba-fusion/next#3942]
### Type 
Platform Theme
### Component 
Icon
### Feature Description
在Iconfont挂了的情况下想要替换icon ,能否考虑可以直接上传单个icon,
或者使用其他类似Iconfont的站点，比如iconpark（虽然不太可能）

**Comment by YSMJ1994** [comment]
目前暂未有计划支持其它方式上传 icon ，现在 iconfont 已经比较稳定了
