### ISSUE TITLE
Title Error on "Web无障碍开发漫游指南"

### ISSUE THREAD

**Issue by Lionad-Morotar** [alibaba-fusion/next#3956]
### Reproduction link 
[https://alibaba-fusion.github.io/next/](https://alibaba-fusion.github.io/next/)

### Steps to reproduce
Page title error, "<title>Introduction · fuson gitbook</title>"，maybe "<title>Introduction · fusion gitbook</title>"?

![image](https://user-images.githubusercontent.com/26913795/173893851-a470a653-7a14-4658-88aa-6d208b46c70c.png)

**Comment by bindoon** [comment]
求 PR， 在 https://github.com/alibaba-fusion/next/tree/gh-pages   gh-pages 分支
