### ISSUE TITLE
[Icon]主题配置fusion图标库无法导入iconfont图标资源

### ISSUE THREAD

**Issue by sxqwaade** [alibaba-fusion/next#3957]
### Component 
Icon

### Steps to reproduce
主题配置，icon配置，导入iconfont图标，接口返回500，导入失败

**Comment by sxqwaade** [comment]
![image](https://user-images.githubusercontent.com/7403258/174007931-33d7f1e5-179b-462f-b051-dc69100f40f5.png)

**Comment by MarshalShan** [comment]
遇到了相同的问题，提交时提示：”Iconfont close.“

**Comment by YSMJ1994** [comment]
Fixed
