### ISSUE TITLE
[Tab]Tab选项卡组件超出时滑动功能工作不正常

### ISSUE THREAD

**Issue by kevinat** [alibaba-fusion/next#3978]
### Component 
Tab

### Reproduction link 
[https://fusion.design/pc/component/tab?themeid=2#excessMode-container](https://fusion.design/pc/component/tab?themeid=2#excessMode-container)

### Steps to reproduce
1. 只能往右侧滑动;
2. excessMode="dropdown"时，下拉选中的tab没有定位到；
3. excessMode=slide时，箭头状态不同步;

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进请重提 issue
