### ISSUE TITLE
[TreeSelect]树形控件开启preserveNonExistentValue后 先设置个treeData中不存在的字符串 ，再切换其它值 无法切换

### ISSUE THREAD

**Issue by love999262** [alibaba-fusion/next#3982]
### Component 
TreeSelect

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/726c7d0](https://riddle.alibaba-inc.com/riddles/726c7d0)

**Comment by love999262** [comment]
@bindoon

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进请重提 issue
