### ISSUE TITLE
[TreeSelect]开启「勾选」和「可搜索」，搜索关键字后选择一次结果，会退出搜索状态，现希望保留

### ISSUE THREAD

**Issue by HytonightYX** [alibaba-fusion/next#3985]
### Component 
TreeSelect

### Reproduction link 
[https://o2.alibaba-inc.com/sandbox/ide?id=234](https://o2.alibaba-inc.com/sandbox/ide?id=234)

### Steps to reproduce
开启「勾选」和「可搜索」，搜索关键字后选择一次结果，会退出搜索状态，如何实现「搜索后要勾选多个」的需求，使用 searchValue 不生效

**Comment by lakerswgq** [comment]
supported in 1.26.0-beta.6
