### ISSUE TITLE
[Search]官网搜索结果跳转问题

### ISSUE THREAD

**Issue by Linn508** [alibaba-fusion/next#3991]
### Component 
Search

### Reproduction link 
[直接搜索即可复现](直接搜索即可复现)

### Steps to reproduce
在官网页面搜索组件，经常会跳转到首页，不是搜索结果页。
搜索后显示链接：https://fusion.alibaba-inc.com/dsm/pc/component/field?themeid=40463&tabActiveKey=component

**Comment by bindoon** [comment]
刚刚看了下好像是好的
