### ISSUE TITLE
[NumberPicker]NumberPicker组件不支持warning state

### ISSUE THREAD

**Issue by littuoMuXin** [alibaba-fusion/next#3993]
### Component 
NumberPicker

### Steps to reproduce
NumberPicker源码片段：
<Input
                    {...others}
                    aria-valuemax={max !== Infinity ? max : undefined}
                    aria-valuemin={min !== -Infinity ? min : undefined}
                    state={state === 'error' ? 'error' : null}
                    onBlur={this.onBlur.bind(this)}
                    onFocus={this.onFocus.bind(this)}
                    onKeyDown={this.onKeyDown.bind(this)}
                    autoFocus={autoFocus}
                    readOnly={!editable}
                    value={this.renderValue()}
                    disabled={disabled}
                    size={size}
                    onChange={this.onChange.bind(this)}
                    ref={this.saveInputRef.bind(this)}
                    label={label}
                    innerAfter={innerAfter}
                    extra={extra}
                    addonBefore={addonBefore}
                    addonAfter={addonAfter}
                />

**Comment by bindoon** [comment]
NumberPicker 在交互不能出现提示icon类的信息，所以待icon的比如 success、warning 都去掉了

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进请重提 issue
