### ISSUE TITLE
[Icon]项目相对路径打包（publicPath：./）后，本地静态打开html，icon无法显示

### ISSUE THREAD

**Issue by CX330-jiuxi** [alibaba-fusion/next#3995]
### Component 
Icon

### Reproduction link 
[https://github.com/CX330-jiuxi/vite-build-error.git](https://github.com/CX330-jiuxi/vite-build-error.git)

### Steps to reproduce
demo 环境：pnpm：7.x
重现步骤：pnpm install，pnpm build，本地打开/client/demo/build/index.html

**Comment by bindoon** [comment]
icon 引入了cdn资源，需要下载到本地
