### ISSUE TITLE
[Icon]fusion打包后icon资源为什么通过请求获取

### ISSUE THREAD

**Issue by CX330-jiuxi** [alibaba-fusion/next#3997]
### Component 
Icon
### Feature Description
打包后发现，icon图标都是通过网络加载，导致如果通过file://协议打开页面，无法加载icon
![image](https://user-images.githubusercontent.com/51979013/179191917-0609cd64-af4d-4cec-8344-6cbc480dc314.png)

**Comment by bindoon** [comment]
icon资源一直都在cdn上面，如果期望离线使用需要自己下载到本地！

**Comment by CX330-jiuxi** [comment]
@bindoon 嗯，已经解决了
