### ISSUE TITLE
[Form]启用 responsive 后 label 和 input 水平线对不齐

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#3999]
### Component 
Form

### Reproduction link 
[https://o2.alibaba-inc.com/sandbox/ide?id=241](https://o2.alibaba-inc.com/sandbox/ide?id=241)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/5836790/179472813-5f08d29e-5cbd-4b64-864d-e78162623c53.png)

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进请重提 issue

**Comment by YunMeng99** [comment]
@guoyunhe 这个bug会继续跟进 昨天看错了 是有点对不齐

**Comment by YSMJ1994** [comment]
经排查，是 responsive 模式下 label 对齐使用了与普通模式不一样的方式，且该实现方式欠缺考虑（依赖下级 label 高度为其 font-size值），调整为 line-height = element-height 后即可恢复

**Comment by eternalsky** [comment]
已修复，见 https://o2.alibaba-inc.com/sandbox/ide?id=689
