### ISSUE TITLE
[NumberPicker]设置大于0的精度后，中文输入法输入小数点第一次无法输入，输入数字后再次输入小数点可以输入

### ISSUE THREAD

**Issue by mytrip** [alibaba-fusion/next#400]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.13.2

### Component
NumberPicker

### Environment
所有，中文输入法

### Reproduction link
[http://fusion-demo.alibaba-inc.com/demos/next/number-picker](http://fusion-demo.alibaba-inc.com/demos/next/number-picker)

### Steps to reproduce
http://fusion-demo.alibaba-inc.com/demos/next/number-picker   官网demo，精度demo，中文输入法情况下输入小数点如上标题所示问题

**Comment by youluna** [comment]
https://github.com/alibaba-fusion/next/pull/401
