### ISSUE TITLE
自定义主题导入Icon报错 422

### ISSUE THREAD

**Issue by caoxuccc** [alibaba-fusion/next#4003]
### Steps to reproduce
自定义配置主题导入iconfont失败，报错422

![image](https://user-images.githubusercontent.com/51979013/179911854-da70b018-c1c9-4bec-a71b-9fd064dd508c.png)

**Comment by bindoon** [comment]
外网 iconfont 还没回复

**Comment by lakerswgq** [comment]
iconfont 外网服务仍有问题，重新找 iconfont 的人确认了一下预计在 11 月恢复

**Comment by caoyi5225** [comment]
请问这个问题有什么进展吗

**Comment by jurieo** [comment]
请问这个问题有什么进展吗

**Comment by CX330-jiuxi** [comment]
下载下来吧

**Comment by lakerswgq** [comment]
外网 iconfont 仍然有问题

**Comment by YSMJ1994** [comment]
已修复
