### ISSUE TITLE
[Input][QUESTION]如何优雅的手动修改Input的value

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#4008]
### Component 
Input
### Feature Description
背景
- 我们有个需求就是手动给已有的input中追加一些内容

```
<Form field={field} ref={ref}>
  <Form.Item>
    <Input/>
  </Form.Item>
</Form>
```

然后做法有
- 调用field修改值，但是因为实际这个组件离field太远了，不好操作，所以放弃
- ref.value = 'xxx' ，虽然dom修改了，但只要再点击input框还是变回了原来的值。
- ref.value = 'xxx'，然后 input.dispatchEvent(new CustomEvent('change'));，和上面一样没有效果

需求
- 如何优雅实现

**Comment by bindoon** [comment]
如果不用 field，就用最原生的方法，自己受控

**Comment by xmsz** [comment]
> 如果不用 field，就用最原生的方法，自己受控

好 那我需要上报哪个事件 form才能收到最新值更新

**Comment by xmsz** [comment]
然后还有一个情况 我有一个场景是用field.setValue，但是设置后原先require的校验仍然存在
请问如何在设置后重新自动校验一次？

**Comment by xxih** [comment]
> ### Component
> Input
> 
> ### Feature Description
> 背景
> 
> * 我们有个需求就是手动给已有的input中追加一些内容
> 
> ```
> <Form field={field} ref={ref}>
>   <Form.Item>
>     <Input/>
>   </Form.Item>
> </Form>
> ```
> 
> 然后做法有
> 
> * 调用field修改值，但是因为实际这个组件离field太远了，不好操作，所以放弃
> * ref.value = 'xxx' ，虽然dom修改了，但只要再点击input框还是变回了原来的值。
> * ref.value = 'xxx'，然后 input.dispatchEvent(new CustomEvent('change'));，和上面一样没有效果
> 
> 需求
> 
> * 如何优雅实现

发布订阅模式合适
在距离较远的组件中发布事件，在能拿到 field 的组件中订阅该事件并做响应
