### ISSUE TITLE
[Balloon]v2版本Balloon不支持alignEdge

### ISSUE THREAD

**Issue by stitchXxx** [alibaba-fusion/next#4011]
### Component 
Balloon
### Feature Description
v2版本Balloon无法设置alignEdge自动调整肩头对齐位置

**Comment by bindoon** [comment]
默认就是自动的呀，给个demo看看。

**Comment by stitchXxx** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lakerswgq** [comment]
@stitchXxx 空了麻烦提供个 demo，长期不回复的 issue 会被清理的

**Comment by stitchXxx** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
