### ISSUE TITLE
[DatePicker2]日期组件本地化问题

### ISSUE THREAD

**Issue by hongxingshi** [alibaba-fusion/next#4013]
### Component 
DatePicker2

### 复现
[https://codepen.io/hong-xing-shi/pen/QWmMGZJ?editors=0010](https://codepen.io/hong-xing-shi/pen/QWmMGZJ?editors=0010)

### 问题

![image](https://user-images.githubusercontent.com/4546918/180723710-92302ada-a9dd-4df4-b8ed-5a1c076153b4.png)

浮层里的本地化文案应该是英文的

**Comment by lakerswgq** [comment]
https://riddle.alibaba-inc.com/riddles/ed350c5
