### ISSUE TITLE
[Balloon]trigger 设置 Button 并设置 disabled，hover 气泡问题

### ISSUE THREAD

**Issue by acrens** [alibaba-fusion/next#402]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Balloon

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/5da23441](https://riddle.alibaba-inc.com/riddles/5da23441)

### Steps to reproduce
问题：

给 trigger 属性设置 Button，并给 Button 设置 disabled，此时 hover 气泡出现，移动鼠标气泡并不消失，0.x、1.x 均存在以上问题

**Comment by youluna** [comment]
重复 issue 关注https://github.com/alibaba-fusion/next/issues/308
