### ISSUE TITLE
[Upload]upload的accept API详见文档地址挂了（target="_blank"打开）

### ISSUE THREAD

**Issue by weinianyang** [alibaba-fusion/next#4020]
### Component 
Upload

### Reproduction link 
[https://fusion.design/pc/component/upload?themeid=2#Upload](https://fusion.design/pc/component/upload?themeid=2#Upload)

**Comment by weinianyang** [comment]
![image](https://user-images.githubusercontent.com/90443688/181222297-c80e2880-8287-4a7b-b5d7-15a77f39a401.png)

**Comment by lakerswgq** [comment]
链接改成默认new tab打开吧
