### ISSUE TITLE
[Loading]在tsx中使用组件会报错

### ISSUE THREAD

**Issue by LYB-FY** [alibaba-fusion/next#4025]
### Component 
Loading

### Steps to reproduce
在tsx中使用组件会报错：   “Loading”不能用作 JSX 组件。
  其实例类型 "Loading" 不是有效的 JSX 元素。
    在这些类型中，"render()" 返回的类型不兼容。
      不能将类型“React.ReactNode”分配给类型“import("C:/linkcld/das-rm/das-rm/web/node_modules/@types/react-router/node_modules/@types/react/index").ReactNode”。
        不能将类型“{}”分配给类型“ReactNode”。ts(2786)

**Comment by lakerswgq** [comment]
<img width="870" alt="image" src="https://user-images.githubusercontent.com/9381522/186564454-43de6a49-ce75-4c5e-949a-af23f1b515b0.png">

Loading 是一个 React.Componennt，可以在 ts 项目中使用，你的问题需要提供复现 demo

**Comment by LYB-FY** [comment]
也不是报错跑不了，就是在ts中这个组件名会报红。比如说下边这种情况，是我这什么配置没有做吗？我飞冰官网yarn create ice <projectName&gt;初始化的项目也会出现这个问题。
然后还有两个问题：
1、用vite和ice.js构建的项目，使用图片会报错

2、在build.json里把vite改为false之后跑不起来




以上问题都在附件的demo里能复现，复现使用图片报错的问题需要把vite构建模式打开




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba-fusion/next"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月25日(星期四) 中午11:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba-fusion/next] [Loading]在tsx中使用组件会报错 (Issue #4025)





 

 
Loading 是一个 React.Componennt，可以在 ts 项目中使用，你的问题需要提供复现 demo

**Comment by lakerswgq** [comment]
没看到你的 demo，后两个问题是 ice 的问题，可以找 ice 仓库提 issue 问一下
