### ISSUE TITLE
[Field]表单提交时候，在已经配置过help的表单项，手动 setError不生效

### ISSUE THREAD

**Issue by desirepaths** [alibaba-fusion/next#4029]
### Component 
Field

### Reproduction link 
[https://o2.alibaba-inc.com/sandbox/ide?id=248](https://o2.alibaba-inc.com/sandbox/ide?id=248)

### Steps to reproduce
表单提交时候，在已经配置过help的表单项，手动 setError不生效。期望setError生效

**Comment by bindoon** [comment]
help 是表示错误受控，你可以 getError 取出来给 help
