### ISSUE TITLE
[Table]expandedRowIndent 在只有 1 行数据时导致展开异常

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#4035]
### Component 
Table

### Reproduction link 
[https://o2.alibaba-inc.com/sandbox/ide?id=250](https://o2.alibaba-inc.com/sandbox/ide?id=250)

### Steps to reproduce
在只有一行数据时，`expandedRowIndent={[0]}` 会导致 `colspan=“NaN”` 进而导致展开内容宽度异常：
![image](https://user-images.githubusercontent.com/5836790/182561345-3a5c85a7-097b-4f05-9081-6782101d4dda.png)

**Comment by bindoon** [comment]
expandedRowIndent 额外渲染行的缩进,  是个二维数组(eg:[1,1]) 分别表示左右两边的缩进。这个需要严格遵守
