### ISSUE TITLE
[Table][Table]:开启useVirtual并设置maxBodyHeight，滚动时表格的最后一行会一直滚动到表格中间

### ISSUE THREAD

**Issue by CAIyb7923** [alibaba-fusion/next#4043]
### Component 
Table

### Steps to reproduce
重现步骤：1、Table设置useVirtual和fixedHeader为true，设置maxBodyHeight；
2、向下滚动表格内容；
期望结果：滚动到最后一行时，最后一行应该贴于表格下边框；
实际结果：最后一行仍可以继续向上移动，导致最后一行与表格下边框之间留有空白；
![image](https://user-images.githubusercontent.com/21198694/183616646-43905796-9220-41d5-93f9-e9f8e2291a0f.png)

**Comment by lakerswgq** [comment]
能补充一下 demo 吗，方便复现，会优先处理

**Comment by YunMeng99** [comment]
长时间不活动，如需继续跟踪请补充复现方法 reope
