### ISSUE TITLE
[TreeSelect]missing select props export

### ISSUE THREAD

**Issue by callmeYe** [alibaba-fusion/next#4044]
### Component 
TreeSelect

### Steps to reproduce
I find that I can pass the Tree prop (fillProps) to Treeselect，and it works.  But I get an ts error that the property does not exist.

**Comment by lakerswgq** [comment]
TreeSelect Inherited props from Tree so you can use `fillProps` on TreeSelect. 
The TS definition maybe outdated & PR welcome

**Comment by lakerswgq** [comment]
close via https://github.com/weinianyang/next/commit/db53876b39c2c7ea524f9fe8a924f646fb0e45f3
