### ISSUE TITLE
[Search]回车提交如果已在dataSource里为什么会触发两次onSearch

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#4049]
### Component 
Search
### Feature Description
背景
```

  <Search
          onSearch={(value) => {
            console.log('search');
          }}
          dataSource={[{labe:"a", value:"a"}]}
        />
```

用户输入a，然后回车，会触发两次onSearch
触发条件是必须满足value存在于datasource

如果用户输入后，手动点击提交 => 正常
如果用户输入value，但不存在与datasource，回车提交 => 正常

需求
- 为什么会触发两次
- 如何避免触发两次
- 额外 autoHighlightFirstItem 类型不存在

**Comment by lakerswgq** [comment]
<img width="970" alt="image" src="https://user-images.githubusercontent.com/9381522/189792304-ad408588-2986-4788-820e-49780dde65d5.png">
只看到一次 onSearch，你升级到最新版本试试

**Comment by xmsz** [comment]
> Search

https://codepen.io/xmsz/pen/wvjzyym

我少打了 需要配合`autoHighlightFirstItem={false}`复现

**Comment by lakerswgq** [comment]
第一次是输入框回车触发的，第二次是高亮元素触发的
