### ISSUE TITLE
物料区块同步至doneclient插件问题

### ISSUE THREAD

**Issue by sxqwaade** [alibaba-fusion/next#4055]
### Reproduction link 
[https://fusion.design/34341/template/1378](https://fusion.design/34341/template/1378)

### Steps to reproduce
自行开发区块已在物料库中，但是doneclient插件内区块物料中心没有显示，需要添加其他什么操作吗？急需帮助

**Comment by lakerswgq** [comment]
这个是低代码资产，低代码资产在外网版插件上是不展示的
