### ISSUE TITLE
[Balloon]Balloon 建议 trigger 作为children，可以极大的减少代码量

### ISSUE THREAD

**Issue by bindoon** [alibaba-fusion/next#4059]
### Component 
Balloon
### Feature Description
如下遇到条件判断的时候 trigger Button 要写两遍。
![image](https://user-images.githubusercontent.com/5189853/186057660-7edd0efa-4c6f-4b97-af30-55533562a3ae.png)

```
<Balloon.Tooltip
    overlay={<span>请联系平台管理员添加</span>}
    visible={!grant}
>
    <Button disabled type="primary">
            <Icon type="add" />
             新增
    </Button>
</Balloon.Tooltip>
```

**Comment by YSMJ1994** [comment]
给Balloon传递 visible = false 同样可以实现只写一次trigger的需求，非必要情况api的break chang暂时不考虑采纳哈
