### ISSUE TITLE
[Balloon] trigger是组件时，hover就无法触发提示

### ISSUE THREAD

**Issue by cwtuan** [alibaba-fusion/next#4061]
### Component 
Balloon

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/75539a5d](https://riddle.alibaba-inc.com/riddles/75539a5d)
![image](https://user-images.githubusercontent.com/3455798/186106643-7a1e7fa0-2cf7-4b68-906b-842e33260d78.png)

### Steps to reproduce
- Hover到1111(span)，能展示提示（正确行为）
![image](https://user-images.githubusercontent.com/3455798/186106117-c5f8e39f-2881-494c-97c3-c57ee86b231a.png)

- Hover到2222（组件），却不能展示提示 （不正确行为）

![image](https://user-images.githubusercontent.com/3455798/186106491-893c2082-6199-411e-8cc7-f4d950818043.png)

**Comment by bindoon** [comment]
透传 props 到 span  `<span {...props}>`

**Comment by cwtuan** [comment]
MyComp可能是外部组件，不是我们能控制的

**Comment by bindoon** [comment]
> MyComp可能是外部组件，不是我们能控制的

Balloon 其实是要给 trigger 写 onClick 事件的，所以trigger 需要支持 onClick onMouseOver 等事件。

如果业务觉得做不到，可以自己包个 div 在组件上面吧

**Comment by cwtuan** [comment]
OK，我先包一层
