### ISSUE TITLE
[Switch]Switch在 Form.Item 中时调整size无用，永远都是medium的大小

### ISSUE THREAD

**Issue by bokufawishasu** [alibaba-fusion/next#4064]
### Component 
Switch

### Reproduction link 
[https://codepen.io/sherrywanna/pen/qBEEJqB](https://codepen.io/sherrywanna/pen/qBEEJqB)

**Comment by lakerswgq** [comment]
<img width="995" alt="image" src="https://user-images.githubusercontent.com/9381522/187344146-fc4c59b8-aad5-4a38-8642-722c4968f622.png">
直接在 FormItem 上指定 size
