### ISSUE TITLE
[Table]使用“可展开”功能时，父Table的lock会让子Table的对应列“压”在底层，无法显示

### ISSUE THREAD

**Issue by zangguojun** [alibaba-fusion/next#4067]
### Component 
Table

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-template-forked-ch6nh0?file=/src/index.js)

### Steps to reproduce
1、设置lock（left或者right）
2、将maxWidth使lock生效
如下图：
![image](https://user-images.githubusercontent.com/49148972/187060021-72ea1720-5ecf-4d88-b92d-e193adb8e1e6.png)

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进请重提 issue
