### ISSUE TITLE
[Table]Table组件在生产环境column为undefined时会报错 TypeError: Cannot read properties of undefined (reading '__normalized')

### ISSUE THREAD

**Issue by standjojo** [alibaba-fusion/next#4070]
### Component 
Table

### Steps to reproduce
Table组件在生产环境column为undefined时会报错
TypeError: Cannot read properties of undefined (reading '__normalized')
产生原因：columns是接口返回计算的，所以在接口返回前为undefined，在开发环境不会有问题，但是在生产环境会报错

**Comment by YSMJ1994** [comment]
这个需要传入合法的columns属性，越过类型定义传入非法的column导致报错在预期范围内。
另外columns = undefined的情况确实会导致报错，你可以在你的pr中调整一下，保证最小改动

**Comment by YSMJ1994** [comment]
Resolved at https://www.npmjs.com/package/@alifd/next/v/1.26.27
