### ISSUE TITLE
[Select]select 组件的 onRemove 事件会触发 onChange 事件

### ISSUE THREAD

**Issue by stefan-ysh** [alibaba-fusion/next#4071]
### Component 
Select
### Feature Description
如：我选择选项（onChange）是为了增加，onRemove 事件是为了删除，但是我现在 onRemove 也会触发 onChange ，造成业务流混乱，希望能改善此功能，或者提供相关设置，谢谢

**Comment by lakerswgq** [comment]
onChange 含义不是增加触发，是任何修改的时候都要触发。你如果要区分是 add 还是 remove ，比较一下 onChange 的 value 参数和目前的 value 就行了，我看了下其他的组件库的 select 也没有额外区分这两个情况.
