### ISSUE TITLE
[Table]table columns={undefined} or columns=[undefined] 报错

### ISSUE THREAD

**Issue by weinianyang** [alibaba-fusion/next#4074]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/f1faedde](https://riddle.alibaba-inc.com/riddles/f1faedde)

**Comment by lakerswgq** [comment]
这个传值就不规范，也不符合 props 类型，没必要做额外的兼容逻辑，传值的规范需要业务方去保证，基础组件库不需要做太多，这种兼容逻辑容易增加维护成本
