### ISSUE TITLE
[Dialog]弹层显示时背景遮罩层会闪烁

### ISSUE THREAD

**Issue by songxiangyu223** [alibaba-fusion/next#4078]
### Component 
Dialog

### Steps to reproduce
官网的demo可以复现这个问题

**Comment by lakerswgq** [comment]
我去试了下没感受到，能说一下是哪个 demo 么，最好能录个屏

**Comment by songxiangyu223** [comment]
在fireFox浏览器下，点击

**Comment by songxiangyu223** [comment]
在firefox浏览器下，点击快捷调用的warning可以复现。
