### ISSUE TITLE
[DatePicker2]Fork 之后的 next代码，执行npm run test 之后， date-picker2组件的测试用例报错

### ISSUE THREAD

**Issue by edc-hui** [alibaba-fusion/next#4086]
### Component 
DatePicker2

### Steps to reproduce
问题：
Fork next代码之后，什么都没改，执行npm run test之后， date-picker2组件的测试用例报错，报错的测试文件代码处，我看测试用例代码是2021年9月24提交的。不知道为什么突然会报错。

报错截图：

![image](https://user-images.githubusercontent.com/33356467/188051047-2c25f951-c5c4-450a-8a19-d63a2f00c60f.png)

测试用例代码处：

![image](https://user-images.githubusercontent.com/33356467/188051117-7a36f254-8e7c-4ec3-96a7-dd24bbe4cc09.png)

**Comment by edc-hui** [comment]
@youluna 我看是您这边提交的，方便指导下怎么处理这个问题么？

**Comment by edc-hui** [comment]
@youluna 我看测试用例代码是您这边当初写的，方便指导下怎么处理这个问题么？

**Comment by lakerswgq** [comment]
之前这种 delay 写法比较 hack，有时会过不了，多跑几次就 ok 了
