### ISSUE TITLE
[Notification]Notification中api ICON 定义类型与实际node_module中的不符

### ISSUE THREAD

**Issue by yuzhiheng0924** [alibaba-fusion/next#4087]
### Component 
Notification

![image](https://user-images.githubusercontent.com/110157626/188053996-dbc1aa53-e040-4dcd-9f6c-d99732c050c5.png)
![image](https://user-images.githubusercontent.com/110157626/188054089-a458f047-c380-4aaa-a103-1724ffed6927.png)

### Steps to reproduce
Notification文档中的icon定义类型为ReactNode，但实际ts定义类型中的Icon为string类型，导致用户无法扩展消息提醒的icon按钮。

**Comment by lakerswgq** [comment]
ts 类型没问题，文档写的有问题，这里只能 string
