### ISSUE TITLE
[Table]table锁列出现滚动条，遮挡dialog

### ISSUE THREAD

**Issue by 185172970** [alibaba-fusion/next#409]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Table

### Environment
macOS chrome 72.0.3626.119

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/6287dfbe](https://riddle.alibaba-inc.com/riddles/6287dfbe)

### Steps to reproduce
table锁列出现滚动条不消失的情况，遮挡dialog

**Comment by youluna** [comment]
难以定位原因 hold

**Comment by youluna** [comment]
看起来与浏览器相关
