### ISSUE TITLE
[DatePicker2]rangepicker值相同时，切换mode显示方式不改变

### ISSUE THREAD

**Issue by DayDreamZero** [alibaba-fusion/next#4090]
### Component 
DatePicker2

### Reproduction link 
[https://code.alibaba-inc.com/xijue.ly/tab-and-rangepicker](https://code.alibaba-inc.com/xijue.ly/tab-and-rangepicker)

**Comment by kyokaxin** [comment]
@DayDreamZero 你好，请给出详细的复现步骤和相关截图说明一下

**Comment by YSMJ1994** [comment]
Resolved at https://www.npmjs.com/package/@alifd/next/v/1.26.27
