### ISSUE TITLE
[Select]经常在 Select 里面看到 Tag 展示不全

### ISSUE THREAD

**Issue by bindoon** [alibaba-fusion/next#4093]
### Component 
Select

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/fc2c0257](https://riddle.alibaba-inc.com/riddles/fc2c0257)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/5189853/188765788-ec0072fe-005f-4c64-afca-7f07c159431d.png)

原因：外层 div 利用了文字的长度去控制宽度，内层的 span 利用了自身的宽度-24px 去限制最大高度，必然空间不够。

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进请重提 issue
