### ISSUE TITLE
[Menu]fusion多个组件使用string来指定ref,建议优化createRef来指定

### ISSUE THREAD

**Issue by weinianyang** [alibaba-fusion/next#4097]
### Component 
Menu
### Feature Description
 fusion的subMenu菜单代码中使用string来指定ref = ‘subMenu’ 。页面导航中使用preact加快加载速度，preact不支持string指定ref。建议升级，使用createRef来指定ref

**Comment by lu-tianyu** [comment]
follow this issue

**Comment by lakerswgq** [comment]
@lu-tianyu 没搜到 string ref，都是 callback ref，能说明下具体是什么地方么

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进请重提 issue
