### ISSUE TITLE
[Table]Table组件合并时，如果改变了CellProps的返回值，样式会出现错误

### ISSUE THREAD

**Issue by komaedaXnagito** [alibaba-fusion/next#4106]
### Component 
Table

### Reproduction link 
[https://o2.alibaba-inc.com/sandbox/ide?id=274](https://o2.alibaba-inc.com/sandbox/ide?id=274)

### Steps to reproduce
点击改变CellProps按钮，可以看到单元格合并后的样式存在问题
![image](https://user-images.githubusercontent.com/26919146/190403320-a271d1c4-94e3-47e3-8d7b-f8f920414a4f.png)

**Comment by YSMJ1994** [comment]
Fixed at 1.27.2
