### ISSUE TITLE
[Drawer]Drawer.show的定位不在页面上

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#4108]
### Component 
Drawer

### Reproduction link 
[https://github.com/xmsz/2022091701](https://github.com/xmsz/2022091701)

### Steps to reproduce
<img width="1891" alt="image" src="https://user-images.githubusercontent.com/5879146/190842134-c08359fb-3386-448a-9ae3-02496b617155.png">

**Comment by xmsz** [comment]
还有show类型类没有 content
` 对象文字可以只指定已知属性，并且“content”不在类型“DrawerProps”中。ts(2345) `

**Comment by bindoon** [comment]
css 不是 1.26 最新版本吧

**Comment by xmsz** [comment]
> css 不是 1.26 最新版本吧

确实好像是主题基线问题，我之前操作

- 主题管理，升级了1.26.x
- 更改了变量，发布
- 刷新，发现又变回了1.25.x 

我刚重新升级 可以了
