### ISSUE TITLE
[Select]Select组件对Preview态样式等属性不可控

### ISSUE THREAD

**Issue by jbts6** [alibaba-fusion/next#4111]
### Component 
Select
### Feature Description
希望能对isPreview下Select弹出的预览框可控，如传入className等。
目前的问题是，Select的values数量过多的话(300 )，isPreview下的显示Ballon会过长且无法滚动

**Comment by lakerswgq** [comment]
没明白，弹出的预览框指的是什么

**Comment by jbts6** [comment]
> 没明白，弹出的预览框指的是什么

我是从hippo-design里点反馈进来的，提错地方了
