### ISSUE TITLE
[Select]Select组件由编辑态变为预览态，显示内容发生改变

### ISSUE THREAD

**Issue by siyou** [alibaba-fusion/next#4116]
### Component 
Select

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-select-nuk7jp)

### Steps to reproduce
只是改变Select的isPreview属性的值，不希望显示内容发生变化

**Comment by lakerswgq** [comment]
这个 pr 多选的时候会有问题，用 `fillProps` 不要用 `valueRender`
