### ISSUE TITLE
[Table]Table.groupHeader如何去除"React does not recognize the `tableEl` prop on a DOM element"提示

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#4118]
### Component 
Table
### Feature Description
背景
- https://codesandbox.io/s/nifty-currying-1cupjm?file=/src/App.tsx
<img width="462" alt="image" src="https://user-images.githubusercontent.com/5879146/191448732-00552488-84fd-4e2e-8102-7d65479380e1.png">

正常Table没有这个提示，但是分组table就会提示这个，虽然不影响使用，但是每次打开都提示很不友好

需求
- 如何去除这个提示

**Comment by lakerswgq** [comment]
应该是把这个属性透传给 dom 了
