### ISSUE TITLE
[DatePicker2]DatePicker的RangePicker组件不支持antd  的DatePicker组件onCalendarChange函数，这样没法灵活控制可选择的时间范围

### ISSUE THREAD

**Issue by sunhannie** [alibaba-fusion/next#4119]
### Component 
DatePicker2
### Feature Description
希望有这种函数，灵活控制可选择的时间范围

**Comment by lakerswgq** [comment]
可以再详细说下你的场景

**Comment by sunhannie** [comment]
类似于这种场景 ：https://blog.csdn.net/qq_35976676/article/details/116500480
也就是可以通过选择一个时间点，再通过时间段（比如只能选择一个月）控制能选择的第二个时间点

**Comment by sunhannie** [comment]
不解决问题吗？

**Comment by lakerswgq** [comment]
描述你的真实需求绝对是有必要的。如果你需要根据还未生效的值去确定禁用区间，你的 disabledDate 怎么写，是你自己再维护一个 state 去表示当前选择指，还是入参也需要改

**Comment by lakerswgq** [comment]
duplicate of #4135
