### ISSUE TITLE
[Select]下拉选项报错导致页面白屏bug

### ISSUE THREAD

**Issue by Liting1** [alibaba-fusion/next#4124]
### Component 
Select，CascaderSelect

组件库版本为：1.25.48

### Steps to reproduce
只要是带有下拉选项的组件都有概率触发死循环白屏bug
此bug为偶现bug,并不能百分比复现，一下是触发报错是的控制台截图，

个人认为是这个下拉框内容在出现时定位位置时出现了问题

![image](https://user-images.githubusercontent.com/33544236/192933736-ee989373-df79-43d9-9580-6ea6569973c7.png)
![image](https://user-images.githubusercontent.com/33544236/192933778-f48eab34-d28f-4c75-ad19-ae52a00a3d0d.png)

**Comment by lakerswgq** [comment]
这个是重复渲染死循环了，如果是受控用法的话，估计是你的状态管理有问题。要定位 bug 得提供复现 demo
