### ISSUE TITLE
[Input]TextArea 使用 isPreview，如果 value 为 null 的话会报错

### ISSUE THREAD

**Issue by yyz945947732** [alibaba-fusion/next#4127]
### Component 
TextArea

### Steps to reproduce
https://github.com/alibaba-fusion/next/blob/build/1.26.2/src/input/textarea.jsx#L274

这里没判断 value 是空的情况，导致直接报错了。求帮忙改下，挺急的。

**Comment by yyz945947732** [comment]
https://github.com/alibaba-fusion/next/issues/2189

看到之前也提过这个 BUG，但是改动跟问题好像没关系 issue 就关掉了。

**Comment by yyz945947732** [comment]
https://github.com/alibaba-fusion/next/blob/master/src/input/textarea.jsx#L94

构造函数这里是不是少判断了 `null` 的情况，看

https://github.com/alibaba-fusion/next/blob/master/src/input/base.jsx#L145

`getDerivedStateFromProps ` 生命周期里有判断，但有时候不会走这里。

**Comment by lakerswgq** [comment]
判空需要加强下
