### ISSUE TITLE
[Table]table前后两列锁定后，中间列无法设置最小宽度， 期望当table较宽时能自适应撑开，较窄时可出现横向滚动条

### ISSUE THREAD

**Issue by zengyumei** [alibaba-fusion/next#4133]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/3ff5056f](https://riddle.alibaba-inc.com/riddles/3ff5056f)

### Steps to reproduce
1. table中对最左和最右列进行锁列了，给定了width。中间的列希望它宽度自适应，且能手动配置最小宽度， 否则随着列变多，中间列的宽度会不断被压缩，导致列内容发生重叠。
2. 使用者想给中间列设置最小宽度，不生效。

**Comment by lakerswgq** [comment]
研发小蜜已回复

**Comment by lakerswgq** [comment]
小蜜已回复
