### ISSUE TITLE
[Collapse]collapse封装一层后无法打开

### ISSUE THREAD

**Issue by weinianyang** [alibaba-fusion/next#4147]
### Component 
Collapse

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/21be7fb](https://riddle.alibaba-inc.com/riddles/21be7fb)

**Comment by lakerswgq** [comment]
看了下目前确实只有 Panel 直接作为 children 的时候才会注册事件

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进请重提 issue
