### ISSUE TITLE
[Message]Message组件在没有关闭按钮的时候，右侧间距应该缩紧

### ISSUE THREAD

**Issue by azhang1987** [alibaba-fusion/next#4152]
### Component 
Message
### Feature Description
当前message组件可选择 是否使用关闭按钮，在选择不要关闭按钮的情况下，右侧的间距仍然保留了按钮的位置，造成距离过大。应该在不使用关闭按钮的情况下，去除按钮的位置。

<img width="740" alt="截屏2022-10-20 20 11 02" src="https://user-images.githubusercontent.com/95275219/196944918-7c4eab07-4db2-415a-be96-6135d9770ac8.png">

**Comment by lakerswgq** [comment]
看了下 Message 是 block ，和关闭 icon 没啥关系
