### ISSUE TITLE
[Table]Table组件的Small & Medium尺寸下，字体的大小不应该联动

### ISSUE THREAD

**Issue by azhang1987** [alibaba-fusion/next#4153]
### Component 
Table
### Feature Description
当前Table组件下，包含List，组件的Small 以及 Medium尺寸配置字体大小是联动的，不应该联动，应允许单独配置

**Comment by lakerswgq** [comment]
这个首先得设计给下默认值

**Comment by azhang1987** [comment]
medium尺寸默认使用body-2（14px)
small组件默认使用body-1 (12px)
