### ISSUE TITLE
[Dialog]如何给Dialog v2的next-overlay-inner next-dialog-wrapper增加样式？

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#4155]
### Component 
Dialog
### Feature Description
我们有个需求是
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/5879146/197093542-fa5b6368-516f-40c6-a80f-3ab6ceca85d1.png">
弹出一个弹窗，但是弹窗后面还是可以点击

可是我们不知道怎么实现比较好

暂时想到的是给next-overlay-inner next-dialog-wrapper增加pointer-events: none来实现，但是并没有任何api可以操作

**Comment by xmsz** [comment]
可以设置wrapperClassName 这个在文档里有 但是实际类型没有
<img width="737" alt="image" src="https://user-images.githubusercontent.com/5879146/197098703-4f547250-e0c9-462d-a4e1-d5944f6c35c7.png">

**Comment by lakerswgq** [comment]
可以帮补充一下 d.ts 🤝
