### ISSUE TITLE
[Icon]建议字体文件改成 https，现在 xswitch 代理到本地后 iconfont 无法显示

### ISSUE THREAD

**Issue by tudou527** [alibaba-fusion/next#4156]
### Component 
Icon
### Feature Description

![image](https://user-images.githubusercontent.com/1134658/197099297-86b1d03d-bfe4-4dd8-accb-f88d3c2bfdaa.png)

**Comment by lakerswgq** [comment]
字体文件因该是没指定协议的
<img width="806" alt="image" src="https://user-images.githubusercontent.com/9381522/197708090-8af671c0-7565-46dd-9271-3d251d5ca0f6.png">
会保持和页面协议一致
