### ISSUE TITLE
[Select]Select单/多选模式是否可以支持自动创建item

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#4158]
### Component 
Select
### Feature Description

背景
- 我们有个下拉框可以选择角色名称
<img width="604" alt="image" src="https://user-images.githubusercontent.com/5879146/197322690-c31155db-65fa-47d4-9f8d-eeab4243873a.png">
- 角色名称允许用户自己创建
- 我们希望可以在用户输入的时候，如果没有，则自动进行创建，这样操作更加的快速。就是和mode=tag时一样的效果

其他产品

antDesign，没有这个功能，但是有类似的Demo
<img width="431" alt="image" src="https://user-images.githubusercontent.com/5879146/197322796-84e6f8d7-8f38-4aaf-b23e-118d4c71bfbb.png">
蛮奇葩的，不想要

arcoDesign，有这个allowCreate这个属性，符合需求
<img width="469" alt="image" src="https://user-images.githubusercontent.com/5879146/197322819-f113a8bf-c084-4f24-93dd-399fbafc7774.png">

**Comment by lakerswgq** [comment]
这个目前没有原生的支持，取决于你们的交互，通过定制弹层可以达到 ant-design 类似的效果。如果你们想要类似 arco 那样的，select 是支持渲染 dataSource 里面不存在的 value 的，但是这个需要你们自己去做 setValue

**Comment by YSMJ1994** [comment]
Stale
