### ISSUE TITLE
[Form]Field[parseName=true]不同方式操作array，获取的值不同

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#4159]
### Component 
Field
### Feature Description

```
const List = ConfigProvider.config(({ value }) => {
  console.log('组件内', JSON.stringify(value));
  return <div />;
});

  const field = Field.useField({
    values: {
      list: [
        {
          text: '1',
        },
      ],
    },
    parseName: true,
    onChange: () => {
      console.log('实际值', JSON.stringify(field2.getValue('list')));
    },
  });
   <Form field={field}>
        <Form.Item name="list">
          <List />
        </Form.Item>
        <Form.Item name="list[0].text">
          <Input />
        </Form.Item>
      </Form>



```

输入值1234

预期输出
```
组件内 [{"text":"1234"}]
实际值 [{"text":"1234"}]
```

但实际
```
组件内 [{"text":"1"}]
实际值 [{"text":"1234"}]
```

List组件的值和实际的值不是同一个

而且如果我在List组件里onChange实际上是有效的，就是不知道为什么value拿到的确实另外一个值

我的业务场景
<img width="557" alt="image" src="https://user-images.githubusercontent.com/5879146/197331288-747d5a51-703e-40e2-9b36-2e00ff3c4b70.png">
- 涉及list里元素的增删改查
- 元素里的change直接修改list，很方便

- 而我把list也作为Form的自定义元素是为了更好的操作value
因为最开始的时候，我的List组件的value是通过field.getValue("list")传入，但是这样感觉很奇怪，估计性能也不好。
还有一个问题，当我变更的时候调用field.setValue("list",[...])，但是这个时候并不会触发页面重渲染，这时候页面什么变化都没有，需要随便输入一些值触发重渲染才行，很不符合预期。

需求
- 如何解决List组件拿到的value不是预期的
- 有没有更好的方法解决这样的需求

**Comment by lakerswgq** [comment]
没太看明白，你的例子完整吗，1234 这个值没看到任何来源。能给个在线 demo 吗

**Comment by xmsz** [comment]
> 没太看明白，你的例子完整吗，1234 这个值没看到任何来源。能给个在线 demo 吗

Demo: https://codepen.io/xmsz/pen/LYrYZwq

- 输入框输入内容
- 查看console可以看到List里拿到的value一直是初始值没有变化
- 而field里实际上有变化

**Comment by YSMJ1994** [comment]
Fixed at @alifd/field@1.6.4
