### ISSUE TITLE
[Slider]Slider 多次异步数据渲染

### ISSUE THREAD

**Issue by Kyiren-zhr** [alibaba-fusion/next#4162]
### Component 
Slider

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/54110056](https://riddle.alibaba-inc.com/riddles/54110056)

### Steps to reproduce
slider 多次请求的数据整合后渲染，children节点数量错误，节点可以全部渲染，但计算的节点总数仍是第一次返回数据数量，导致不能切换至最后

**Comment by lakerswgq** [comment]
预计明天发版修复
