### ISSUE TITLE
[Tree]Tree 如何自定义子节点显示， 能弄个demo吗？（右边加上  【新增、删除、编辑、复制】等功能）

### ISSUE THREAD

**Issue by huangapple** [alibaba-fusion/next#4164]
### Component 
Tree
### Feature Description
我的需求是在树的右边加上  【新增、删除、编辑、复制】等功能， 目前物料市场有找到一个还算合适的组件。
https://unpkg.com/@aligov/tree@1.1.5/build/index.html
但是他这个跟原本的Tree好像有点兼容问题， 如 showLine 等无法支持。draggable后样式也有点怪怪的。

能否官方在tree组件上支持一下， 或者联系一下@aligov/tree的作者麻烦他出个新版本。

或者给个demo, 目前看好像是在原本tree组件的Tree.node的  label上做文章吗？

**Comment by lakerswgq** [comment]
用 `labelRender` 可以自定义子节点展示

**Comment by huangapple** [comment]
有 https://unpkg.com/@aligov/tree@1.1.5/build/index.html 这个库的源码地址吗？官方没有demo， 想看一下他那边怎么写的。
npm包里的是编译后的， 不好看懂。
@lakerswgq
