### ISSUE TITLE
[Select][AutoComplete] Can not show label but emit value when trigger onChange event at the same time

### ISSUE THREAD

**Issue by foxpsd** [alibaba-fusion/next#4165]
### Component 
Select
### Feature Description
if fillProps set to 'value'，then the input shows the 「value」of dataSource (that is not what i want.)
if fillProps set to ‘label’，then the input shows the 「label」correctly, but onChange event handler emit the 「label」too.  (that is not what i want.)
It seems like what the input shows, the 「value」prop of AutoComplete, and the emit value in onChange event handler, are bound. (bad)
Can AutoComplete show the 「label」of dataSource， but store the 「value」of dataSource，and emit the 「value」in onChange event handler as well？

**Comment by lakerswgq** [comment]
AutoComplete is actualy Input,so what input shows is what you get.
For your case, you can get both label and value in `onChange` as third parameter
