### ISSUE TITLE
[Form]有没有好的方法解决Form.Item嵌套会出现两条requiredMessage

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#4170]
### Component 
Form
### Feature Description
DEMO: https://codepen.io/xmsz/pen/PoaZjom

<img width="968" alt="image" src="https://user-images.githubusercontent.com/5879146/199198055-c638b94b-f122-4e91-89ae-442f8c4e7135.png">

临时解决办法。多加一层div。有点.. 有没有其他办法
```
<Form.Item>
  <div>
    <Form.Item required>
    </Form.Item>
  </div>
</Form.Item>
```

**Comment by lakerswgq** [comment]
你是用了两个 FormItem，去掉一个就行

**Comment by xmsz** [comment]
> 你这为什么 FormItem 嵌套使用

和https://fusion.design/pc/component/form?themeid=2#nest-container一样需求，就是第一层Form.Item只是为了显示label和样式，里面的Form.Item才会操作到value

**Comment by lakerswgq** [comment]
直接嵌套感觉基本没有这种场景，目前不考虑支持。官网这个例子是为了布局，类似这样的 case 都不会是直接嵌套
