### ISSUE TITLE
[CascaderSelect]新增需求：希望cascadeSelect单选时也能选到中间节点

### ISSUE THREAD

**Issue by asheng303** [alibaba-fusion/next#4174]
### Component 
CascaderSelect
### Feature Description
目前cascadeSelect单选时只能选到叶子节点，希望cascadeSelect单选时也能选到中间节点，可以让hover展开时，点击中间节点触发onChange，目前是不会触发的。

import { CascaderSelect } from '@alifd/next';

class Demo extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            data: []
        };
    }

    componentDidMount() {
        fetch('https://os.alipayobjects.com/rmsportal/ODDwqcDFTLAguOvWEolX.json')
            .then(response => response.json())
            .then(data => {
                this.setState({ data });
            })
            .catch(e => console.log(e));
    }

    handleChange = (value, data, extra) => {
        console.log(value, data, extra);
    }

    render() {
        return <CascaderSelect dataSource={this.state.data} onChange={this.handleChange} expandTriggerType={'hover'}/>;
    }
}

ReactDOM.render(<Demo />, mountNode);

**Comment by lakerswgq** [comment]
非叶节点只在多选模式下有效，选中父节点即代表子节点是被选中的

**Comment by asheng303** [comment]
但这个需求也很合理，在表格筛选的时候，要先选了第一个select才能选第二个select，第二个select是单选，根据当前条件进行表格搜索，这样的实现目前只能通过select实现级联选择，为什么不能直接让cascader select实现呢，我看antdesign里他们的级联选择期单选模式就提供了changeonSelect方法来指定点击即选中------------------ 原始邮件 ------------------发件人: 尘弦 ***@***.***>发送时间: 2022年11月11日 15:59收件人: alibaba-fusion/next ***@***.***>抄送: asheng303 ***@***.***>, Author ***@***.***>主题: 回复：[alibaba-fusion/next][CascaderSelect]新增需求：希望cascadeSelect单选时也能选到中间节点 (Issue #4174)
