### ISSUE TITLE
[TreeSelect]TreeSelect组件在搜索交互中没有完全实现异步加载

### ISSUE THREAD

**Issue by PTLEI** [alibaba-fusion/next#4176]
### Component 
TreeSelect

### Steps to reproduce
TreeSelect组件在关键词搜索的时候会默认将搜索结果的子集展开，因为是直接修改state -> props值变更 -> 触发expanded，所以未触发Tree组件的expand事件 -> 未触发 loadData的异步加载

**Comment by PTLEI** [comment]
是否能有props/其他事件感知这个expanded的触发

**Comment by lakerswgq** [comment]
感觉搜索时直接触发异步加载的行为比较复杂，可能会出现一直加载一直搜索，这个更适合去做自定义搜索

**Comment by PTLEI** [comment]
> 感觉搜索时直接触发异步加载的行为比较复杂，可能会出现一直加载一直搜索，这个更适合去做自定义搜索

有试过使用TreeSelect做自定义搜索，但发现渲染popup内容又是个问题，不能去修改dataSource引发重绘，那样又造成了其他怪异的问题；最后就仿源码做了一个简版的，在搜索的时候去除展开搜索结果子集的逻辑；
个人也觉得这样可能更符合产品逻辑，”没有被加载过的节点不必在程序里默认展开“

**Comment by lakerswgq** [comment]
为什么不能修改 dataSource 去 re-render，我想的是 dataSource 是父组件的 state，修改 dataSource 就会让父组件 re-render，这样 TreeSelect 也会用最新的 dataSource 去做 re-render

**Comment by PTLEI** [comment]
> 为什么不能修改 dataSource 去 re-render，我想的是 dataSource 是父组件的 state，修改 dataSource 就会让父组件 re-render，这样 TreeSelect 也会用最新的 dataSource 去做 re-render

是的，当时的实现方式是类似的，但这样修改之后我这边发现随着dataSource的突变TreeSelect触发 re-render的同时，其value值也会发生突变，页面现象就是已经选择的选项值丢失了；猜测是选项值的dataSource丢失了，所有value也会突变，后续没有继续深入下去

**Comment by lakerswgq** [comment]
如果场景需要可以用 preserveNonExistentValue 去继续保留 value
