### ISSUE TITLE
[Search]能否支持composition和透传inputProps

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#4177]
### Component 
Search
### Feature Description
需求一
- 设置input的属性

需求二
- 支持composition/补全类型
- Select组件也想要支持和补全类型

其实是支持的，但是提示类型不存在

**Comment by lakerswgq** [comment]
没太看懂，composition 指的什么

设置什么属性提示不存在

**Comment by xmsz** [comment]
第一个需求： Search组件能否新增一个 `inputProps` 属性，我可以自己控制`search`里的`input`属性

第二个需求：search/select/input 这些组件都缺少`composition`这个类型提示，文档里也没有，但实际上是支持的

**Comment by lakerswgq** [comment]
文档和ts都没有，你是怎么用的。。

**Comment by xmsz** [comment]
> 文档和ts都没有，你是怎么用的。。

input有composition的问的那个，但是没有类型提示
另外两个文档没有，类型提示也没有，但是源码里都是直接...props传递给input.complete，所以理论是支持的

**Comment by lakerswgq** [comment]
1: 现在 search 应该是直接透传给 Input 的，你的意思是统一 input 属性的配置入口吗。现在理论上你可以传 Input 的 props 给 Search
2. 可能是 extends 有问题，我们确认下
