### ISSUE TITLE
[Overlay]triggerType支持contextmenu

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#4179]
### Component 
Overlay
### Feature Description
背景
- 右键显示菜单

现在虽然有Menu.Create实现，但是限制了内容是Menu。希望triggerType能支持contextMenu/右键

**Comment by lakerswgq** [comment]
右键浏览器有默认行为，对绝大部分交互场景都不合适

**Comment by lakerswgq** [comment]
你这种用 visible 自己去受控控制吧，自己监听一下右键事件
