### ISSUE TITLE
[CascaderSelect]CascaderSelect搜索后next-cascader-inner不自适应更新width

### ISSUE THREAD

**Issue by weinianyang** [alibaba-fusion/next#4180]
### Component 
CascaderSelect

### Reproduction link 
[https://done.alibaba-inc.com/dsm/pc/components/detail/cascaderselect?themeid=2&tabActiveKey=component#search-container](https://done.alibaba-inc.com/dsm/pc/components/detail/cascaderselect?themeid=2&tabActiveKey=component#search-container)

### Steps to reproduce
next-cascader-inner 的 width 之前是随着点击层级不一样，设置的值不一样的，但是搜索后清空，再点击就不自适应更新width了

**Comment by lakerswgq** [comment]
width 属性确实是没有了，这个偏实现层，对你们有什么影响么，我测试了下感知不到有什么区别

**Comment by lakerswgq** [comment]
钉钉沟通过，还是需要一个能复现的 demo，不然既没法确定问题原因，也没法确定是否修复

**Comment by eternalsky** [comment]
width 属性没有这个是很好复现的，https://done.alibaba-inc.com/dsm/pc/components/detail/cascaderselect?themeid=2&tabActiveKey=component#search-container 只要先进入到搜索状态，再退格删除返回到选择状态，就可以看到对 inner 的 width 的修改不生效了。我们的样式不正常正式因为 width 没有造成的，只要可以修复到 width 一直有效，那么我们这个问题就是修复了。

**Comment by YSMJ1994** [comment]
Fixed at 1.26.28
