### ISSUE TITLE
网站的一些链接有误需要更新

### ISSUE THREAD

**Issue by huarse** [alibaba-fusion/next#4181]
### Reproduction link 
[https://fusion.alibaba-inc.com/dsm/pc/yuque/fusion-design-system/ahvubx/xorf09#l5UL1](https://fusion.alibaba-inc.com/dsm/pc/yuque/fusion-design-system/ahvubx/xorf09#l5UL1)

### Steps to reproduce
1. “大流量生产环境 ” 中附上的 def lib 链接应该直接跳转到 https://work.def.alibaba-inc.com/lib/alifd__next ，而不是 lib 首页，因为使用者并不知道要搜索 alifd__next，现在 搜索 @alifd/next 或 next 都是搜索不到的

2. 讨论组中的钉钉群二维码已经过期，建议及时更新

**Comment by weinianyang** [comment]
done
