### ISSUE TITLE
[Balloon][QUESTION]Balloon的箭头为什么还是用before实现

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#4186]
### Component 
Balloon
### Feature Description
背景
- 使用Balloon，然后希望是半透明颜色
- 但是没办法实现，因为Ballon的箭头是用before写的，会叠加到内容区域
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/5879146/201835134-3561e482-78a4-452f-a883-d82cc88cbdb5.png">
和https://github.com/alibaba-fusion/next/pull/2403 这个是一样的需求
- 而Balloon.Tooltip是正常的。但由于需要关闭按钮，所以没办法用Tooltip

需求
- 为什么Balloon的箭头不是和Tooltip一样通过div裁剪实现，还是用before

**Comment by lakerswgq** [comment]
你们现在怎么去做半透明的

**Comment by YSMJ1994** [comment]
需求：参考 Tooltip对于 arrow的实现 https://github.com/alibaba-fusion/next/pull/2403，调整Balloon的arrow，使半透明弹窗与arrow不会发生颜色重叠

**Comment by YSMJ1994** [comment]
Improved at 1.26.34, demo: https://riddle.alibaba-inc.com/riddles/745a99b4
