### ISSUE TITLE
[Slider]Slider组件连续切换问题

### ISSUE THREAD

**Issue by kororinto** [alibaba-fusion/next#4195]
### Component 
Slider

### Steps to reproduce
<Slider
              className="w-[330px] h-full"
              draggable={false}
              arrows={false}
              autoplay
              speed={500}
              triggerType="hover"
              dotsRender={(index, current) => (
                <div
                  className="w-[40px] h-[4px] rounded-[2px] opacity-30 bg-blank"
                  style={current === index ? { opacity: 1 } : {}}
                />
              )}
            >
              {[1, 2, 3].map((item) => (
                <div key={item} className="bg-[pink] !h-[464px] text-blank">
                  {item}
                </div>
              ))}
            </Slider>
// 连续切换时受节流阀影响导致体验很差

**Comment by lakerswgq** [comment]
能加一个能跑的在线 demo 么，排查效率高一点
