### ISSUE TITLE
[Overlay]部分弹层组件是否可以默认 followTrigger 

### ISSUE THREAD

**Issue by lakerswgq** [alibaba-fusion/next#4200]
### Component 
Overlay
### Feature Description
经常有业务反馈弹层滚动的问题，目前 Overlay 的 followTrigger 默认不会开启。对于 Dialog 场景，挂在到 body 确实比较适合；但是对于 select 类型的组件，是否可以默认开启 followTrigger？

**Comment by lakerswgq** [comment]
### 哪些组件适合默认开启 followTrigger
- Select
- 

### Pros
- 



### Cons
-

**Comment by akirakai** [comment]
### 哪些组件适合默认开启 followTrigger
- Select
- DatePicker
- TimePicker
- RangePicker
- CascaderSelect
- Tooltip

### Pros
- 上述组件的弹层有个特点，它不像Dialog那样会阻塞用户的操作，而只是一种辅助，辅助的信息需要跟随主体滚动


### Cons
- 跟随滚动是想要的效果，但按照目前的实现方式，会把弹层放到target父容器的内部，而不是放到body上，如果父容器设置了overflow: hidden，会导致弹框显示不全

建议这些组件默认开启followTrigger，并且把container设置为距离当前组件最近的可滚动容器，问题在于，这个容器需要为非static定位，否则弹层的absolute定位会寻找外层的非static容器，大概率还是找到了body

**Comment by baicoding** [comment]
可否同步考虑Drawer抽屉组件，能够在指定的DOM上进行渲染。

**Comment by YSMJ1994** [comment]
计划在 2.0 版本重构 overlay 的实现，始终将弹层内容渲染至 body，并使之能够始终跟随 trigger 节点，参考 [floating-ui autoUpdate](https://floating-ui.com/docs/autoUpdate#animationframe)
