### ISSUE TITLE
[CascaderSelect]级联选择组件选项定位混乱

### ISSUE THREAD

**Issue by liujiede** [alibaba-fusion/next#4201]
### Component 
CascaderSelect

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-template-forked-mybon0)

### Steps to reproduce
fusion 级联选择在DataSource为结构化格式时，不能正确区分层级
见demo中：选择印度尼西亚
比如 ： 印度尼西亚的value 和 美国的某个州的 value相同，出现反显混乱问题（但实际上有结构化）

**Comment by lakerswgq** [comment]
value 不能相同

**Comment by liujiede** [comment]
不是同级别 value 重复，比如国际地区：某个国家下的某个城市和「其他国家」的编码是可能重复。
如果组件区分层级是可以避免的，测试了一下 antd 是没有问题的，next 是否考虑支持下？
测试地址：https://dx3qsm.csb.app/

**Comment by liujiede** [comment]
> value 不能相同

不是同级别 value 重复，比如国际地区：某个国家下的某个城市和「其他国家」的编码是可能重复。
如果组件区分层级是可以避免的，测试了一下 antd 是没有问题的，next 是否考虑支持下？
测试地址：https://dx3qsm.csb.app/
