### ISSUE TITLE
[Dialog]support ssr please

### ISSUE THREAD

**Issue by smat0096** [alibaba-fusion/next#4205]
### Component 
Dialog

### Steps to reproduce
document is undefined in ssr env, at overlay.js used such code: 
useListener(document, 'mousedown', clickEvent, false, !!(visible && overlayRef.current && (canCloseByOutSideClick || hasMask && canCloseByMask)));

**Comment by eternalsky** [comment]
the code above is written in didMount lifeCycle, and will not affect ssr. but we review the whole code of Dialog, and  fix all problems which will result in error in ssr.
