### ISSUE TITLE
主题包无法获取最新版本

### ISSUE THREAD

**Issue by kororinto** [alibaba-fusion/next#4207]
### Steps to reproduce
执行：npm i @alifd/theme-22420，提示No matching version found for @alifd/theme-22420@latest.
执行：npm i @alifd/theme-22420@1.0.1，提示No matching version found for @alifd/theme-22420@1.0.1.
但在npm中能看到最新版本是1.0.1
npm包链接地址：https://www.npmjs.com/package/@alifd/theme-22420/v/1.0.1

**Comment by lakerswgq** [comment]
包已经发布了，安装不上是 npm 的问题，检查一下是不是用的内网仓库还没有同步过来
