### ISSUE TITLE
[Select]配置popupContent后，点击tag会清空所有value

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#4214]
### Component 
Select
### Feature Description
DEMO: https://codepen.io/xmsz/pen/WNKNrwY

部分代码
```
   <Select mode="multiple"  value={['10001',10002]} onChange={handleChange}  popupContent={<div>2</div>} />
```

- 只要设置了popupContent
- 点击任意tag的关闭按钮，onChange里的value就是[]

**Comment by linjunxyz** [comment]
你没有加dataSource属性吧，我试了点击tag，onChange里面是有值的
![image](https://user-images.githubusercontent.com/44048690/217698858-f0b0be4b-6c7e-4f54-9aa7-5c6c0a72dec0.png)

**Comment by xmsz** [comment]
> 你没有加dataSource属性吧，我试了点击tag，onChange里面是有值的 ![image](https://user-images.githubusercontent.com/44048690/217698858-f0b0be4b-6c7e-4f54-9aa7-5c6c0a72dec0.png)

ok 我看一下
