### ISSUE TITLE
[Select]select默认值回显问题

### ISSUE THREAD

**Issue by 245570565** [alibaba-fusion/next#4215]
### Component 
Select
### Feature Description
组件再封装  defaultValue回显问题，在本地运行时可以默认请求并回显，再次搜索并更改dataSource原默认值显示正常，组件引入项目中运行也可以正常请求并回显默认数据，但是再次搜索更改dataSource时defaultValue显示异常，只显示value值label消失了

**Comment by lakerswgq** [comment]
是因为 value 在 dataSource 里面没有对应选项了吧，检查一下。还有问题的话提供一个 demo

**Comment by 245570565** [comment]
不过我已经知道原因了哈哈哈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 尘弦 ***@***.***&gt;
发送时间: 2022年12月20日 10:10
收件人: alibaba-fusion/next ***@***.***&gt;
抄送: 245570565 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [alibaba-fusion/next] [Select]select默认值回显问题 (Issue #4215)

**Comment by lakerswgq** [comment]
什么原因，分享一下看看
