### ISSUE TITLE
[Field]Field的ts定义中缺失options属性

### ISSUE THREAD

**Issue by callmeYe** [alibaba-fusion/next#4221]
### Component 
Field

### Reproduction link 
[https://github.com/alibaba-fusion/field/blob/ed3f555c6b48a1cdb5782b9e7b2667402d5557b8/src/index.js#L44](https://github.com/alibaba-fusion/field/blob/ed3f555c6b48a1cdb5782b9e7b2667402d5557b8/src/index.js#L44)

<img width="779" alt="image" src="https://user-images.githubusercontent.com/15107776/209299631-1dab3ed4-8574-430d-b069-fca39ecf0fff.png">

### Steps to reproduce
Field原始代码中是存在this.options的，但是工程中使用Field时调用this.field.options.onChange会提示field没有options属性

**Comment by lakerswgq** [comment]
this.options 是内部实现，不要依赖这种写法
![image](https://user-images.githubusercontent.com/9381522/209495388-ab847e3d-75d6-4d74-b855-5d7221e1824a.png)
监听变化用文档推荐的写法

**Comment by callmeYe** [comment]
恰恰就是因为单独setValue会脱离监听
<img width="926" alt="image" src="https://user-images.githubusercontent.com/15107776/209497621-42522d42-7150-409b-b9da-5a94e92051ab.png">
