### ISSUE TITLE
[Balloon]Balloon和弹窗问题

### ISSUE THREAD

**Issue by SteveCGC** [alibaba-fusion/next#4223]
### Component 
Balloon

### Steps to reproduce
Balloon浮层中有一个按钮，点击浮层中的按钮，弹出Dialog,随便点击Dialog中的内容，Balloon浮层消失，希望Balloon浮层不消失

**Comment by lakerswgq** [comment]
看你的用法了，所有的弹层元素在点击外部元素的时候默认都会消失。
对于你的场景
1. 可以给 Ballon 加 safeNode 或者 safeId 去标识点击元素
2. 直接用 visible 去自己判断显隐逻辑
3. 通过 popupContainer 讲 Dialog 挂载到 Balloon 内部
可以看下文档各个用法的示例
