### ISSUE TITLE
[Button]按钮组件显示问题

### ISSUE THREAD

**Issue by lebifeng** [alibaba-fusion/next#4225]
### Component 
Button

### Steps to reproduce
```html
<Button text warning type="primary">测试</Button>
```
上述代码仍显示蓝色字体, 需要显示警告色

![image](https://user-images.githubusercontent.com/47881345/209922123-9817a008-de84-4fa7-978c-2ca80a9d7a5e.png)

text 和 warning 的css优先级是否设置错误?

**Comment by lakerswgq** [comment]
你用了文本按钮，文本按钮也有自己的样式，你是两种需要一起用？

**Comment by lebifeng** [comment]
我需要警告色的文本按钮, 这种在设计规范里吗? @lakerswgq

**Comment by lakerswgq** [comment]
目前没有，目前文本按钮和警告没法混着使用，他们样式也是互斥的
