### ISSUE TITLE
[Icon]icon组件中type中含有ic的所有icon都无法渲染

### ISSUE THREAD

**Issue by fufu11111** [alibaba-fusion/next#4228]
### Component 
Icon

### Reproduction link 
[https://codepen.io/pen?&editors=0010](https://codepen.io/pen?&editors=0010)

### Steps to reproduce
打开即可查看无法渲染的问题

**Comment by lakerswgq** [comment]
试了几次都没打开，看能不能换个链接。
我们自己的主题也有很多含 ic 的 icon 不存在这个问题，你看下是不是主题文件加载错了，可以把字体文件下载下来看看有没有这个 Icon

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进请重提 issue
