### ISSUE TITLE
[Table]columns是动态值，rowSelection动态设置为undefined时会报错

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#4229]
### Component 
Table
### Feature Description
DEMO:https://codesandbox.io/s/fusion-next-template-forked-k3bgzr?file=/src/index.js:479-486

步骤
1. 点击「切换多选」按钮

代码
```
import React, { useMemo, useState } from "react";
import ReactDOM from "react-dom";

import { Button, Table } from "@alifd/next";

import "./styles.css";

function App() {
  const columns = useMemo(() => [], []);
  const [selectedRowOpen, setSelectedRowOpen] = useState(true);

  return (
    <div className="App">
      <Button
        onClick={() => {
          setSelectedRowOpen((prev) => !prev);
        }}
      >
        切换多选
      </Button>
      <Table
        columns={columns}
        dataSource={[{ id: 1 }, { id: 2 }]}
        rowSelection={selectedRowOpen ? {} : undefined}
      />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

```

错误
```
TypeError
Cannot read properties of undefined (reading 'mode')
    at SelectionTable._this.renderSelectionHeader (https://k3bgzr.csb.app/node_modules/
alifd/next/es/table/selection.js:74:349
    at Cell.render (https://k3bgzr.csb.app/node_modules/
alifd/next/es/table/base/cell.js:58:17
```

**Comment by linjunxyz** [comment]
组件里定义了rowSelection的类型就是object的，所以不能改成undefined

**Comment by xmsz** [comment]
> 组件里定义了rowSelection的类型就是object的，所以不能改成undefined

嗯 我想要切换『开启选中』的话，要如何设置

我原来的想法是想，关闭时，设置undefined，但是会保存。而如果关闭时，设置{}，则还是有选择项

**Comment by linjunxyz** [comment]
> https://codesandbox.io/s/fusion-next-template-forked-k3bgzr?file=/src/index.js:479-486

可以通过设置 rowSelection.selectedRowKeys 属性实现，比如： `rowSelection={selectedRowOpen ? {} : { selectedRowKeys: [] }}`

**Comment by linjunxyz** [comment]
> > 组件里定义了rowSelection的类型就是object的，所以不能改成undefined
> 
> 嗯 我想要切换『开启选中』的话，要如何设置
> 
> 我原来的想法是想，关闭时，设置undefined，但是会保存。而如果关闭时，设置{}，则还是有选择项

可以通过设置 rowSelection.selectedRowKeys 属性实现，比如： `rowSelection={selectedRowOpen ? {} : { selectedRowKeys: [] }}`

**Comment by xmsz** [comment]
> 可以通过设置 rowSelection.selectedRowKeys 属性实现，比如： `rowSelection={selectedRowOpen ? {} : { selectedRowKeys: [] }}`

这样设置后chekbox还在，没有消失

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进请重提 issue
