### ISSUE TITLE
[Field]field无法取得在list里的checkbox默认值

### ISSUE THREAD

**Issue by cwtuan** [alibaba-fusion/next#4230]
### Component 
Field

### Reproduction link 
https://riddle.alibaba-inc.com/riddles/2346c356

### Steps to reproduce
1. 点击最后一个"add"
![image](https://user-images.githubusercontent.com/3455798/212459724-e09f0f7d-a117-400f-ad25-9039d92bff4f.png)

2. 预期应该能立刻取得最新的值，但是却没有

3. 点其force update ![image](https://user-images.githubusercontent.com/3455798/212459779-9f49225e-e27e-4e36-8c3e-df24ecda7b1f.png) 按钮，才能取得最新值

**Comment by linjunxyz** [comment]
导致这个问题的原因是field的init方法不会导致组件重渲染，如果init方法导致组件重渲染的话，是会引起一些性能问题的。推荐你改一下代码的写法，比如在添加方法的时候，手动指定checkbox属性的值

**Comment by cwtuan** [comment]
> 导致这个问题的原因是field的init方法不会导致组件重渲染，如果init方法导致组件重渲染的话，是会引起一些性能问题的。推荐你改一下代码的写法，比如在添加方法的时候，手动指定checkbox属性的值

这个说法似乎无法解释：新增一笔数据，为什么input能取到值，checkbox却取不到。

**Comment by linjunxyz** [comment]
> > 导致这个问题的原因是field的init方法不会导致组件重渲染，如果init方法导致组件重渲染的话，是会引起一些性能问题的。推荐你改一下代码的写法，比如在添加方法的时候，手动指定checkbox属性的值
> 
> 这个说法似乎无法解释：新增一笔数据，为什么input能取到值，checkbox却取不到。

你的addItem方法里面，如果这么写`this.field.addArrayValue('name', index, { id: this.idx, checkbox: true });`，你会发现你的input取不到值了，但是checkbox有值，就是你在添加数据的时候，要指定初始值才行

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进请重提 issue
