### ISSUE TITLE
[Table]固定表格列的宽度显示不正常，在调整页面宽度之后设置正常

### ISSUE THREAD

**Issue by topwood** [alibaba-fusion/next#4239]
### Component 
Table

### Reproduction link 
[https://o2.alibaba-inc.com/sandbox/ide?id=339](https://o2.alibaba-inc.com/sandbox/ide?id=339)

### Steps to reproduce
固定表格列的宽度显示不正常，在调整页面宽度之后设置正常。打开上面页面，观察到最后一个固定列的表头高度跟其他没有对齐，在拉动中间的间隔调调整右侧宽度时，高度重新自动调整成正常状态

**Comment by weinianyang** [comment]
锁列推荐：Table.StickyLock
