### ISSUE TITLE
[Balloon]Checkbox disable状态下，外面包tooltip的时候无法正常关闭

### ISSUE THREAD

**Issue by topwood** [alibaba-fusion/next#4242]
### Component 
Balloon

### Reproduction link 
[https://o2.alibaba-inc.com/sandbox/ide?id=340](https://o2.alibaba-inc.com/sandbox/ide?id=340)

### Steps to reproduce
鼠标放到checkbox上，会有内容提示，鼠标从checkbox移开，提示不会消失

**Comment by topwood** [comment]
会的，鼠标放到checkbox出现tooltip之后，从不是tooltip的方向移除，就可以复现了

**Comment by YSMJ1994** [comment]
> 会的，鼠标放到checkbox出现tooltip之后，从不是tooltip的方向移除，就可以复现了

麻烦检查一下这个问题还存在吗，我在你的复现链接中按照你说的步骤并没有出现这个问题

**Comment by topwood** [comment]
> > 会的，鼠标放到checkbox出现tooltip之后，从不是tooltip的方向移除，就可以复现了
> 
> 麻烦检查一下这个问题还存在吗，我在你的复现链接中按照你说的步骤并没有出现这个问题

看起来是好了
