### ISSUE TITLE
[Field]Fusion Field超过500个字段表单输入不流畅

### ISSUE THREAD

**Issue by weinianyang** [alibaba-fusion/next#4243]
### Component 
Field
### Feature Description
解决的思路: 
1.减少非必要的 re-render，之后看下页面性能数据,看下耗时的点在哪里
2. 组件props.onChage的时候做优化
复现：https://riddle.alibaba-inc.com/riddles/dd149db7

**Comment by linjunxyz** [comment]
建议改一下代码的写法 在input组件的onBlur事件去更改数据 就不会卡了
`
import { Button, Input, Table, Field } from "@alifd/next";

class Demo extends React.Component {
  constructor(props) {
    super(props);

    this.idx = 3;

    this.field = new Field(this, {
      parseName: true,
      values: {
        name: new Array(500).fill(0).map((i, index) => {
          return { id: index, input: i };
        }),
      },
    });
  }

  getValues = () => {
    const values = this.field.getValues();
    console.log(values);
  };

  addItem(index) {
    ++this.idx;
    this.field.addArrayValue("name", index, { id: this.idx, input: this.idx });
  }

  removeItem(index) {
    this.field.deleteArrayValue("name", index);
  }

  input = (value, index) => {
    return (
      <Input
        defaultValue={this.field.init(`name.${index}.input`).value}
        onBlur={(e) => {
          this.field.setValue(`name.${index}.input`, e.target.value);
        }}
      />
    );
  };
  op = (value, index) => {
    return (
      <span>
        <Button type="primary" onClick={this.addItem.bind(this, index + 1)}>
          add
        </Button>
        <Button warning onClick={this.removeItem.bind(this, index)} style={{ marginLeft: 4 }}>
          delete
        </Button>
      </span>
    );
  };

  render() {
    const dataSource = this.field.getValue("name");
    return (
      <div>
        <Table dataSource={dataSource}>
          <Table.Column title="id" dataIndex="id" />
          <Table.Column title="input" dataIndex="id" cell={this.input} />
          <Table.Column title="operation" cell={this.op} width={150} />
        </Table>
        <pre style={{ marginTop: 8 }}>{JSON.stringify(dataSource, null, 2)}</pre>
      </div>
    );
  }
}

ReactDOM.render(<Demo />, mountNode);

`

**Comment by linjunxyz** [comment]
是因为组件大量不必要的重渲染导致的卡顿 改一下代码的写法就可以解决
```
import { Button, Input, Table, Field } from "@alifd/next";

class Demo extends React.Component {
  constructor(props) {
    super(props);

    this.idx = 3;

    this.field = new Field(this, {
      parseName: true,
      values: {
        name: new Array(500).fill(0).map((i, index) => {
          return { id: index, input: i };
        }),
      },
    });
  }

  getValues = () => {
    const values = this.field.getValues();
    console.log(values);
  };

  addItem(index) {
    ++this.idx;
    this.field.addArrayValue("name", index, { id: this.idx, input: this.idx });
  }

  removeItem(index) {
    this.field.deleteArrayValue("name", index);
  }

  input = (value, index) => {
    return (
      <Input
        defaultValue={this.field.init(`name.${index}.input`).value}
        onBlur={(e) => {
          this.field.setValue(`name.${index}.input`, e.target.value);
        }}
      />
    );
  };
  op = (value, index) => {
    return (
      <span>
        <Button type="primary" onClick={this.addItem.bind(this, index + 1)}>
          add
        </Button>
        <Button warning onClick={this.removeItem.bind(this, index)} style={{ marginLeft: 4 }}>
          delete
        </Button>
      </span>
    );
  };

  render() {
    const dataSource = this.field.getValue("name");
    return (
      <div>
        <Table dataSource={dataSource}>
          <Table.Column title="id" dataIndex="id" />
          <Table.Column title="input" dataIndex="id" cell={this.input} />
          <Table.Column title="operation" cell={this.op} width={150} />
        </Table>
        <pre style={{ marginTop: 8 }}>{JSON.stringify(dataSource, null, 2)}</pre>
      </div>
    );
  }
}

ReactDOM.render(<Demo />, mountNode);
```

**Comment by xmsz** [comment]
> 

有改动前代码吗 我想看看问题

**Comment by lakerswgq** [comment]
demo 有更新

**Comment by xmsz** [comment]
> demo 有更新

在哪可以看 [https://riddle.alibaba-inc.com](https://riddle.alibaba-inc.com/riddles/dd149db7)这个内网的我看不了
