### ISSUE TITLE
[Select]value值为`[]`时，提示 Failed prop type: Invalid prop `focusedKey` supplied to `Config(Menu)`, expected one of type [string, number, object]

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#4245]
### Component 
Select

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-template-forked-jr6dj1?file=/src/index.js)

### Steps to reproduce
背景
- 多选的情况下，value是数组
- 但是这个时候会提示 Failed prop type: Invalid prop `focusedKey` supplied to `Config(Menu)`, expected one of type [string, number, object].
- 因为这里并没有接受array

**Comment by xmsz** [comment]
还有一个相关的表现
DEMO: https://codesandbox.io/s/fusion-next-template-forked-mq2ykv?file=/src/index.js

那就是设置popupContent、value=[]、 mode='multiple'以后，会出现


```
Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at span
    at span
```
的错误

**Comment by linjunxyz** [comment]
多选的话，设置mode的值为multiple就不报错了，比如`<Select mode="multiple" value={[]} />`
