### ISSUE TITLE
[Select]设置popupContent、value=[]、 mode='multiple'会出现Each child in a list should have a unique "key" prop错误

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#4247]
### Component 
Select

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](DEMO: https://codesandbox.io/s/fusion-next-template-forked-mq2ykv?file=/src/index.js)

### Steps to reproduce
背景
- 设置popupContent、value={[]}、 mode='multiple'以后，会出现

Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at span
    at span
的错误

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进请重提 issue
