### ISSUE TITLE
[Icon]icon无法导入自定义图标，链接打不开

### ISSUE THREAD

**Issue by jurieo** [alibaba-fusion/next#4253]
### Component 
Icon

### Steps to reproduce
主题配置-icon-导入图标，点击后，上面教程的链接有错误，无法打开。“打开图标库”的链接地址是 https://undefined/dsm/undefined/design/icons 。另外，fusion官网的社区群的钉钉二维码过期了，GitHub上的社区群地址也过期了，无法加入社区群。
<img width="747" alt="image" src="https://user-images.githubusercontent.com/18009286/219867931-cda99a62-1c06-4caa-8805-e21da6869695.png">

**Comment by weinianyang** [comment]
外网群聊二维码更新了
出于集团信息安全及合规要求，导入图标换了实现方式。因外网没有DSM概念，导致暂时无法导入图标。产品正在处理，后续优化

**Comment by jurieo** [comment]
新的二维码可以打开了，但加入的时候提示 系统繁忙。
另外一个问题，我在低代码引擎的github提了一个issue，群里作者说这是fusion的bug，他们一般不处理fusion的bug，麻烦你们看看。感谢。
[issue在这里](https://github.com/alibaba/lowcode-engine/issues/1608)
![image](https://user-images.githubusercontent.com/18009286/220222129-18f09e3d-e7cd-424f-bd09-d8f644905853.png)

**Comment by lakerswgq** [comment]
我自己试了下没问题，你再试试看

**Comment by stevapple** [comment]
请问该问题是否有排期，如果短期内无法解决的话如何workaround

**Comment by weinianyang** [comment]
> 请问该问题是否有排期，如果短期内无法解决的问题如何解决

集团信息安全要求，之前的导入方式不允许了。外网没有DSM，外网短期这个导入icon的功能考虑下掉了。导入图标的话建议将站点迁移至内网导入

**Comment by jurieo** [comment]
在主题配置系统如何配置--icon-font-path的地址呢？

**Comment by AndyJinSS** [comment]
请问功能什么时候上线？

**Comment by weinianyang** [comment]
> 请问功能什么时候上线？

外网因信息安全要求，不能导入图标了。内网站点可以，在内网创建设计系统站点就可以
![image](https://user-images.githubusercontent.com/90443688/226531795-c0488c31-42aa-41d2-bf5b-9ba86bd40e6c.png)

**Comment by weinianyang** [comment]
没有其他途径，只能内网导入图标
![image](https://user-images.githubusercontent.com/90443688/226531961-9a7f7137-9d71-42d0-9fa8-37246b926868.png)

**Comment by stevapple** [comment]
@weinianyang 能否和 ice 团队合作，在 [`@ice/plugin-fusion`](https://github.com/alibaba/ice/blob/master/packages/plugin-fusion) 中加入导入 SVG 图标的能力？

**Comment by weinianyang** [comment]
> @weinianyang 能否和飞冰团队合作，在 [`@ice/plugin-fusion`](https://github.com/alibaba/ice/blob/master/packages/plugin-fusion) 中加入导入 SVG 图标的能力？ 这样应该不存在合规问题，也可以解决 icejs 用户的自定义图标需求。

@lakerswgq 看下这个
