### ISSUE TITLE
[Table]高级表格，编辑数据列的数据字段，增加操作列的事件，打印输出当前列数据，预览，打印当前数据列的 数据字段错误。

### ISSUE THREAD

**Issue by jurieo** [alibaba-fusion/next#4256]
### Component 
Table

### Steps to reproduce
我在低代码引擎的github提了一个issue，有详细的说明和复现步骤。群里作者说这是fusion的bug，麻烦你们看看。感谢。
[issue在这里](https://github.com/alibaba/lowcode-engine/issues/1608)

**Comment by lakerswgq** [comment]
如果确定是 fusion 的 bug，说清楚是什么原因导致的，用 fusion table 提供一个复现 demo，提供低代码引擎的复现步骤不好排查

**Comment by jurieo** [comment]
> 如果确定是 fusion 的 bug，说清楚是什么原因导致的，用 fusion table 提供一个复现 demo，提供低代码引擎的复现步骤不好排查

这是在lowcode的物料fusion-ui中发现的。 fusion table不能直接编辑表格列属性，无法复现呐。在lowcode官网的demo中很容易就复现了。
