### ISSUE TITLE
[DatePicker2]DatePicker2组件，当开启showtime 且 format="DD/MM/YYYY HH:mm:ss" 组件不可用，无法选择日期

### ISSUE THREAD

**Issue by Vincent697** [alibaba-fusion/next#4258]
### Component 
DatePicker2

### Reproduction link 
[https://o2.alibaba-inc.com/sandbox/ide?id=345](https://o2.alibaba-inc.com/sandbox/ide?id=345)

### Steps to reproduce
DatePicker2组件，当开启showtime 且 format="DD/MM/YYYY HH:mm:ss" 组件不可用，无法选择日期

**Comment by weinianyang** [comment]
isPreview无法选择日期？isPreview是预览态，本身就是不能选择
![image](https://user-images.githubusercontent.com/90443688/220509602-92ea869d-2f33-4d4d-b613-aaf4930a9481.png)

**Comment by weinianyang** [comment]
![image](https://user-images.githubusercontent.com/90443688/220509815-dfc103de-8ab8-4e14-92d6-8cbf8f701191.png)

**Comment by Vincent697** [comment]
> isPreview无法选择日期？isPreview是预览态，本身就是不能选择 ![image](https://user-images.githubusercontent.com/90443688/220509602-92ea869d-2f33-4d4d-b613-aaf4930a9481.png)

不是预览态，可以直接看下面这个例子：
https://o2.alibaba-inc.com/sandbox/ide?id=346

![image](https://user-images.githubusercontent.com/8027665/220812927-f429f7e0-cab1-43cc-b377-385227ba3086.png)

**Comment by Vincent697** [comment]
@weinianyang

**Comment by YSMJ1994** [comment]
这个问题貌似现在不能复现了，麻烦你再看一下呢

**Comment by YSMJ1994** [comment]
Stale
