### ISSUE TITLE
babel-runtime-jsx-style-transform已停止维护且存在安全风险

### ISSUE THREAD

**Issue by stevapple** [alibaba-fusion/next#4270]
### Steps to reproduce
https://github.com/Yurisa/babel-runtime-jsx-style-transform
该仓库最新提交为2年前，npm audit提示多项安全风险且无法自动修复

**Comment by lakerswgq** [comment]
没看到这个包，npm list 看下谁引入的

**Comment by stevapple** [comment]
```
  └─┬ @alifd/next@1.26.14
    └─┬ @alifd/meet-react@2.8.5
      └── babel-runtime-jsx-style-transform@1.0.2
```

**Comment by stevapple** [comment]
@lakerswgq

**Comment by stevapple** [comment]
Ping

**Comment by YSMJ1994** [comment]
next组件通过 peerDependencies 声明依赖 @alifd/meet-react 组件库，是在 mobile 场景使用 next 的必要条件，meet-react 组件库运行时依赖了babel-runtime-jsx-style-transform，目前暂时没有规划将之替换或移除。
不过考虑到高版本 npm 对于 peerDependencies 的默认安装处理报出的问题，我们将在下个版本中移除 peerDependencies 里的 @alifd/meet-react。

**Comment by YSMJ1994** [comment]
经过排查，是 babel-runtime-jsx-style-transform 错误的依赖了 mocha@8 导致的风险信息，我们准备 fock 这个仓库，调整一下依赖，并调整meet 组件库的相关实现，考虑到变更内容较多，延期至下次迭代再发布

**Comment by YSMJ1994** [comment]
Fixed at @alifd/meet-react@2.9.9
