### ISSUE TITLE
[Input]firefox下开启composition后无法输入中文

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#4276]
### Component 
Input

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-template-forked-c3vcpr?file=/src/index.js)

### Steps to reproduce
开启了composition在Firefox下无法输入中文，chrome和safari没有问题

**Comment by weinianyang** [comment]
![image](https://user-images.githubusercontent.com/90443688/225277568-070b29de-0620-4c71-a18b-08cee7e935a0.png)
![image](https://user-images.githubusercontent.com/90443688/225277704-60226904-9319-4576-8ed5-4de11422477a.png)

**Comment by weinianyang** [comment]
@lakerswgq @xmsz 刚下载个Firefox，用起来没问题呀
