### ISSUE TITLE
[Theme] Fusion主题包variables.js文件umd化

### ISSUE THREAD

**Issue by lintao-lintao** [alibaba-fusion/next#428]
### Feature Description
当前主题包 例如:  https://unpkg.com/@alifd/theme-1@0.0.12/ 里面的 variables.js写法只兼容 nodejs 标准

期望能umd化 在其他环境中或者浏览器中直接可用

**Comment by youluna** [comment]
现在有什么真实的使用场景需要umd格式的么？如果是阿里同学可内网细聊

**Comment by youluna** [comment]
close due to inactive
