### ISSUE TITLE
[DatePicker]DatePicker 错误使用 moment 第二个参数导致序列化问题

### ISSUE THREAD

**Issue by bojoyzhou** [alibaba-fusion/next#4282]
### Component 
DatePicker

### Steps to reproduce
表单DatePicker 的 value 在经过 JSON.stringify 之后再 parse 回去，回传给 DatePicker 少了 8 小时。

以下两种结果有差异
moment('2023-02-28T16:00:00.000Z', 'YYYY-MM-DD').format('YYYY-MM-DD')
'2023-02-28'
moment('2023-02-28T16:00:00.000Z').format('YYYY-MM-DD')
'2023-03-01'

DatePicker 的 value 是 moment 对象，stringify 之后变为 '2023-02-28T16:00:00.000Z'， 该值在传给 DatePicker 的时候（showTime=false），next 内部实现为第一种方式，导致后面的 时间和时区数据都丢掉了。原来 3 月 1 日的时间变成了 2 月 28，少了一天。

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进请重提 issue
