### ISSUE TITLE
[Tab]选中最左侧tab时，tab的内容被遮挡

### ISSUE THREAD

**Issue by liaomin555** [alibaba-fusion/next#429]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.13.5

### Component
Tab

### Environment
官网的demo就能复现

### Reproduction link
[http://riddle.alibaba-inc.com/riddles/1cfc4f05](http://riddle.alibaba-inc.com/riddles/1cfc4f05)

### Steps to reproduce
选中最左侧tab时，tab的内容被遮挡

**Comment by guanpu** [comment]
这个issue和 https://github.com/alibaba-fusion/next/issues/226 是互相矛盾的，如果自动移动部分可见的tab到可见区域也会出现bug： http://fusion-image.oss-cn-beijing.aliyuncs.com/test/bug.mov 我打算暴露"scrollToTab"给开发者，由开发自己决定Tab的行为。

**Comment by guanpu** [comment]
Fixed at #464 , closing this.
