### ISSUE TITLE
[Tag]fusion-mobile Tag 组件，主题期望能支持 Tag.Selectable 的背景色，边框，字体等配置 

### ISSUE THREAD

**Issue by hi-otto** [alibaba-fusion/next#4291]
### Component 
Tag
### Feature Description
fusion-mobile，Tag组件有很多css变量，但是主题的配置里，Tag.Selectable 的背景色、边框、字体、字体颜色，都不支持配置。 希望能增加一下主题配置项

**Comment by YSMJ1994** [comment]
mobile 尚未开源，麻烦移步至内部 [TB 项目](https://teambition.alibaba-inc.com/project/64ba3389a70cfbacd38f41b8/projectinfoapp)提交需求，这里就先关闭了
