### ISSUE TITLE
[Slider]fade动效切换的情况下，向左切换动效闪烁

### ISSUE THREAD

**Issue by pinkdoremi** [alibaba-fusion/next#4292]
### Component 
Slider

### Reproduction link 
[https://fusion.alibaba-inc.com/dsm/pc/components/detail/slider?themeid=40463&tabActiveKey=component#fade-container](https://fusion.alibaba-inc.com/dsm/pc/components/detail/slider?themeid=40463&tabActiveKey=component#fade-container)

### Steps to reproduce
fade切换的情况
官网文档就能复现，向左切换和向右切换动效有差异。向右切换过渡平滑，但是向左切换会闪烁一下。

**Comment by YSMJ1994** [comment]
Resolved at https://www.npmjs.com/package/@alifd/next/v/1.26.27
