### ISSUE TITLE
[Checkbox]值应该支持boolean

### ISSUE THREAD

**Issue by cwtuan** [alibaba-fusion/next#4295]
### Component 
Checkbox的值只支持string | number，应该要能支持boolean
（实际行为是支持的，就是ts会报错）

![image](https://user-images.githubusercontent.com/3455798/225533098-df4564ef-63c7-4284-bd73-a5186defd4c8.png)

Checkbox代码：https://github.com/alibaba-fusion/next/blob/master/src/checkbox/checkbox.jsx#L80

### Steps to reproduce
```jsx
<Checkbox
    {...init('agree', 
         valueName: 'checked',
    })}
>同意</Checkbox>
```

**Comment by weinianyang** [comment]
bool只有true/false不符合value的预期
@lakerswgq 看下是checkbox的value ts类型，是否要增加bool

**Comment by linjunxyz** [comment]
这个之前有提过了吧 链接：https://github.com/alibaba-fusion/next/issues/3931

**Comment by weinianyang** [comment]
![image](https://user-images.githubusercontent.com/90443688/227831682-92e97def-757c-40c4-9e5d-afb0d4bff3fc.png)

**Comment by cwtuan** [comment]
一个form底下，有多个item，我都用field来管理，如果只有checkbox要单独管理，那不太合理。

而且目前组件行为是支持的boolean，只是ts报错，把ts定义文件改下就好了。行为不变
