### ISSUE TITLE
[Field]Field 使用setValue 设置表单值不生效

### ISSUE THREAD

**Issue by Liting1** [alibaba-fusion/next#4301]
### Component 
Field

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-template-forked-qrb4wh?file=/src/index.js)

### Steps to reproduce
如上链接所示

**Comment by Liting1** [comment]
![image](https://user-images.githubusercontent.com/33544236/227474457-db64803a-75ee-4c0a-a469-334e8d0f5b5b.png)

**Comment by linjunxyz** [comment]
因为init方法只会在组件第一次初始化的时候被赋值，这里建议使用field的getValue方法去获取数据

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进请重提 issue

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进请重提 issue

**Comment by YunMeng99** [comment]
因长期不活跃关闭，如需继续跟进请重提 issue
