### ISSUE TITLE
[Slider]slider纵向位置问题

### ISSUE THREAD

**Issue by zwwill** [alibaba-fusion/next#4302]
### Component 
Slider

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/b37a97f3](https://riddle.alibaba-inc.com/riddles/b37a97f3)

### Steps to reproduce
自动高度，位置对齐

**Comment by lakerswgq** [comment]
再补充些描述吧

**Comment by zwwill** [comment]
![image](https://user-images.githubusercontent.com/20720117/228412350-624f6e37-0412-4bcd-9826-ff45e5d900a9.png)

**Comment by YSMJ1994** [comment]
Resolved at https://www.npmjs.com/package/@alifd/next/v/1.26.27
