### ISSUE TITLE
[List]全局样式导致 <ol> 和 <ul> 项目符号无法展示

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#4305]
### Component 
List

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-template-forked-giklu0?file=/src/index.js)

### Steps to reproduce
引入 Fusion Design 的 CSS 之后，使用 `<ol>` 和 `<ul>` 无法展示左侧的数字序号或者圆点。感觉很不合理，一些第三方库会受影响，只能手动写样式修复。

**Comment by weinianyang** [comment]
没有限制手动写ol,ul的样式
![image](https://user-images.githubusercontent.com/90443688/228756584-4eb175cf-6e8f-4b81-b4c2-daed8c098d51.png)

检查下是不是本地环境reset了ul,ol 样式

**Comment by guoyunhe** [comment]
@weinianyang 请看 Fusion Design 源码中的这个地方：

https://github.com/alibaba-fusion/next/blob/master/src/core/base/_reset.scss#L9

**Comment by lakerswgq** [comment]
很多框架都会有类似 reset.css 的处理，用于处理浏览器的默认样式，浏览器的默认样式一般比较丑而且不用浏览器之间也会有差异，所以通过这种方式去让所有浏览器表现统一。
你引入的这个三方库如果只用浏览器默认样式，没法保证在所有浏览器中表现一致，而且浏览器默认的列表样式和大部分设计系统的风格都是很违和粗糙的，不建议依赖这种样式，fusion 本身也提供了 List

**Comment by guoyunhe** [comment]
@lakerswgq 在很多情况下，HTML 内容是由各种 CMS 平台提供的，无法调用 Fusion Design 的组件，也没有 class，这种情况下，ol/ul 和 p/div 完全区分不出来，确实导致了业务上的问题。我横向比较了各种 Design System, 其 ol/ul 都是有列表符号的，但是 Fusion Design 没有，感觉非常不合理。解决浏览器之间差异的方式有很多种，但是直接去掉列表符号完全改变了它的 HTML 语义，就像 strong 不加粗一样。
