### ISSUE TITLE
[Cascader]cascader defaultvalue不生效

### ISSUE THREAD

**Issue by pinkdoremi** [alibaba-fusion/next#4311]
### Component 
Cascader

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/35872768](https://riddle.alibaba-inc.com/riddles/35872768)

### Steps to reproduce
如题，demo可以复现。
复选模式下，defaultvalue设置不生效

**Comment by lakerswgq** [comment]
defaultValue 只会在最开始初始化一次，这时 dataSource 还是空，后续 props 变化目前只针对 value 做了处理，如果你数据是异步的，先用 value 吧
