### ISSUE TITLE
[Badge]编译时，部分组件类型定义报错，阻塞编译

### ISSUE THREAD

**Issue by djknight1** [alibaba-fusion/next#4313]
### Component 
Badge

### Steps to reproduce
使用以下三个依赖
"@types/react": "^16.9.0"
"react": "^16.9.0"
"@alifd/next": "^1.23.10"

**Comment by viko16** [comment]
排查出来是 [`@types/react 16.14.37`](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/3f5d20608d31363487694535189ef64569043ff9) 给 `HTMLAttributes`  增加了 `content?: string` 属性

与 Badge 上定义的 `content?: React.ReactNode` 冲突，官方看看要怎么处理下？

**Comment by lakerswgq** [comment]
![image](https://user-images.githubusercontent.com/9381522/232363470-561e9c51-cf23-4245-8da5-46f664edf5bb.png)
