### ISSUE TITLE
[Switch]Switch 组件 loading 无 ts 提示

### ISSUE THREAD

**Issue by Silence-dream** [alibaba-fusion/next#4323]
### Component 
Switch

### Steps to reproduce
Switch 组件的 loading API 是生效的但是在对应的 ts 文件中没有声明
<img width="580" alt="image" src="https://user-images.githubusercontent.com/42824008/233816239-cc5b70a5-e005-40c0-90d9-7b1504dd66f7.png">

**Comment by Silence-dream** [comment]
我将创建一个 pr 进行修复,可以分配给我吗?

**Comment by bindoon** [comment]
可以直接提PR 

> 我将创建一个 pr 进行修复,可以分配给我吗?
