### ISSUE TITLE
[Tab]Tab key定义为数字，但是onChange却变成string

### ISSUE THREAD

**Issue by cwtuan** [alibaba-fusion/next#4326]
### Component 
Tab

### Reproduction link 
https://riddle.alibaba-inc.com/riddles/5a969422

```jsx
import { Tab } from '@alifd/next';

ReactDOM.render(
  <Tab onChange={(v) => console.log('onchange', v, typeof v)}>
    <Tab.Item title="1" key={1}>1</Tab.Item>
    <Tab.Item title="2" key={2}>2</Tab.Item>
  </Tab>
  , mountNode);

```
### Steps to reproduce
![image](https://user-images.githubusercontent.com/3455798/233828026-e7dd2b78-5dcf-44ae-be3a-787fabfaf522.png)

建议1：key定义为数字，onChange就返回数字，保持类型的一致性。否则后续要拿这个值去做全等于比较，就会出现不相等问题
建议2：或者key强制必须为string，那么ts类型定义，就改成`key:string`而不是`key:string | number`

**Comment by linjunxyz** [comment]
主要这个改动是向前不兼容的

**Comment by jbts6** [comment]
https://github.com/alibaba-fusion/next/pull/4120
