### ISSUE TITLE
[TimePicker2]Form下TimePicker2，在error时红色border被覆盖

### ISSUE THREAD

**Issue by shiki-gm** [alibaba-fusion/next#4328]
### Component 
TimePicker2

### Steps to reproduce
/src/time-picker2/main.scss 第50行，为什么有一句border:none， 导致error状态下的红色border被覆盖

**Comment by lakerswgq** [comment]
@linjunxyz 帮看一下，是有这个问题，看下是不是之前改动什么影响到了

**Comment by linjunxyz** [comment]
> 

应该不是之前改动影响到的 这行代码是20个月以前写的了
