### ISSUE TITLE
[Table]虚拟表格在react18中使用createrender快速滚动时出现闪烁空白

### ISSUE THREAD

**Issue by shijunfeng** [alibaba-fusion/next#4331]
### Component 
Table

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cold-sea-2jt1zv)

### Steps to reproduce
虚拟表格在react18中使用createrender快速滚动时出现闪烁空白，入口文件以如下方式则没有问题：
import ReactDOM from 'react-dom';
import Test from './App';

ReactDOM.render(<Test />, document.getElementById('root'));

**Comment by lakerswgq** [comment]
我自己试了下 6 倍 cpu 降速才能感觉到，你的机器配置是什么样的

**Comment by shijunfeng** [comment]
> 我自己试了下 6 倍 cpu 降速才能感觉到，你的机器配置是什么样的

![image](https://github.com/alibaba-fusion/next/assets/17823594/ebb84fac-3d2e-485c-b535-f8aa000ae22f)

**Comment by shijunfeng** [comment]
> 我自己试了下 6 倍 cpu 降速才能感觉到，你的机器配置是什么样的

如果是我机器配置垃圾，那改成ReactDOM.rende 就可以提升6倍CPU的性能。显然不太可能

**Comment by shijunfeng** [comment]
> 我自己试了下 6 倍 cpu 降速才能感觉到，你的机器配置是什么样的

请修改示例代码中的index.js文件，将内容修改为如下代码，拖拽右侧滚动轴观察两种代码的效果差异。
import ReactDOM from 'react-dom';
import App from "./App";
ReactDOM.render(<App />, document.getElementById ('root'));

**Comment by shijunfeng** [comment]
![image](https://github.com/alibaba-fusion/next/assets/17823594/4745da08-9251-4841-83c8-eaf12f41b4c7)
index.js文件中改成这种写法就不会出现闪烁空白的情况
