### ISSUE TITLE
[Dialog] 在 Dialog v1 中 this.overlay 可能为空，但是没有做处理

### ISSUE THREAD

**Issue by HuColin** [alibaba-fusion/next#4333]
### Component 
Dialog

### Steps to reproduce
收到报错 'Cannot read properties of null (reading 'getInstance')'，定位到 '/src/dialog/dialog.jsx' 中 'getInner' 和 'getInnerNode' 函数没有判断 this.overlay 是否为空直接调用导致报错

**Comment by lakerswgq** [comment]
推荐直接升级 v2 ，这个问题之后会提高下健壮性

**Comment by YSMJ1994** [comment]
@HuColin 你好，可以提供复现场景（[codesandbox](https://codesandbox.io/s/kmy7zjr7l3) 或 [codepen](https://codepen.io/pen?&editors=0010)）和复现步骤么

**Comment by HuColin** [comment]
就是日常使用的时候，JS 异常监控收到了这个告警 'Cannot read properties of null (reading 'getInstance')' 翻查源码的时候发现这里没有对 this.overlay 进行空值判断。不太清楚用户的使用场景（比如是否使用了一些插件导致 overlay 丢失），也不确定这里出现 this.overlay 是 null 的情况是否符合预期。不过我想既然有这样的报错，是否应该判断一下

**Comment by YSMJ1994** [comment]
> 就是日常使用的时候，JS 异常监控收到了这个告警 'Cannot read properties of null (reading 'getInstance')' 翻查源码的时候发现这里没有对 this.overlay 进行空值判断。不太清楚用户的使用场景（比如是否使用了一些插件导致 overlay 丢失），也不确定这里出现 this.overlay 是 null 的情况是否符合预期。不过我想既然有这样的报错，是否应该判断一下

好的，我们优化一下代码，确保所有this.overlay的下级执行都在其存在的情况下~

**Comment by YSMJ1994** [comment]
> 就是日常使用的时候，JS 异常监控收到了这个告警 'Cannot read properties of null (reading 'getInstance')' 翻查源码的时候发现这里没有对 this.overlay 进行空值判断。不太清楚用户的使用场景（比如是否使用了一些插件导致 overlay 丢失），也不确定这里出现 this.overlay 是 null 的情况是否符合预期。不过我想既然有这样的报错，是否应该判断一下

好的，我们优化一下代码，确保所有this.overlay的下级执行都在其存在的情况下~

**Comment by YSMJ1994** [comment]
Resolved at https://www.npmjs.com/package/@alifd/next/v/1.26.27
