### ISSUE TITLE
[Input]多行文本输入希望支持清空操作

### ISSUE THREAD

**Issue by lakerswgq** [alibaba-fusion/next#4334]
### Component 
Input
### Feature Description

![image](https://user-images.githubusercontent.com/9381522/236757988-ddf47fd3-c7e8-40da-bec5-214188a89aa5.png)

**Comment by bindoon** [comment]
hasClear 在右上角会出清除按钮

**Comment by lakerswgq** [comment]
> hasClear 在右上角会出清除按钮

这里反馈的是 textarea 没支持
