### ISSUE TITLE
[Select]Select本地过滤能力失效

### ISSUE THREAD

**Issue by IHOD** [alibaba-fusion/next#4341]
### Component 
Select

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-template-forked-s6qzdb?file=/src/index.js:726-733)

### Steps to reproduce
Select组件传入带children的数据源并将showDataSourceChildren设置为false时，本地过滤会失效。

**Comment by lakerswgq** [comment]
@linjunxyz 帮看下

**Comment by linjunxyz** [comment]
我看了一下 没什么问题呀 本地过滤也是生效的
![image](https://github.com/alibaba-fusion/next/assets/44048690/8466687b-49f3-45ad-8e37-8ec329f09b74)
