### ISSUE TITLE
[Tab]关于单词拼写错误的问题

### ISSUE THREAD

**Issue by chengdongqing** [alibaba-fusion/next#4348]
### Component 
Tab

### Reproduction link 
[https://fusion.design/pc/component/tab?themeid=2#closable-container](https://fusion.design/pc/component/tab?themeid=2#closable-container)

### Steps to reproduce
Tab.Item 组件的“是否可关闭”属性单词写错了，现在是closeable，应该是closable

**Comment by lakerswgq** [comment]
这两个拼写都是可以的
