### ISSUE TITLE
[Table]table表格 

### ISSUE THREAD

**Issue by fanyahu** [alibaba-fusion/next#4354]
### Component 
Table

### Reproduction link 
[const onChange = function(...args) {     console.log(...args);   },   dataSource = () => {     const result = [];     for (let i = 0; i < 5; i  ) {       result.push({         title: {           name: `Quotation for 1PCS Nano ${3   i}.0 controller compatible`         },         id: 100306660940   i,         time: 2000   i       });     }     return result;   },   render = (value, index, record) => {     return <a href={`#${index}`}>Remove({record.id})</a>;   },   rowSelection = {     onChange: onChange,     getProps: record => {       return {         disabled: record.id === 100306660942       };     }   };  class App extends React.Component {   constructor(...args) {     super(...args);     this.state = {       widths: {         time: 300,         [`title.name`]: 300       }     };     this.onResizeChange = (dataIndex, value) => {       const { widths } = this.state;       widths[dataIndex] = widths[dataIndex]   value;       this.setState({         widths       });     };   }   render() {     const { widths } = this.state;     const time = widths.time;     const name = widths[`title.name`];      return (       <Table         dataSource={dataSource()}         rowSelection={rowSelection}         onResizeChange={this.onResizeChange}       >         <Table.Column lock title="Id" dataIndex="id" width={100} />         <Table.Column           title="Title"           dataIndex={"title.name"}           asyncResizable           width={name}         />         <Table.Column           title="Time"           dataIndex="time"           asyncResizable           width={time}         />         <Table.Column  asyncResizable lock='right'cell={render} width={200} />       </Table>     );   } }  ReactDOM.render(<App />, mountNode);](const onChange = function(...args) {     console.log(...args);   },   dataSource = () => {     const result = [];     for (let i = 0; i < 5; i  ) {       result.push({         title: {           name: `Quotation for 1PCS Nano ${3   i}.0 controller compatible`         },         id: 100306660940   i,         time: 2000   i       });     }     return result;   },   render = (value, index, record) => {     return <a href={`#${index}`}>Remove({record.id})</a>;   },   rowSelection = {     onChange: onChange,     getProps: record => {       return {         disabled: record.id === 100306660942       };     }   };  class App extends React.Component {   constructor(...args) {     super(...args);     this.state = {       widths: {         time: 300,         [`title.name`]: 300       }     };     this.onResizeChange = (dataIndex, value) => {       const { widths } = this.state;       widths[dataIndex] = widths[dataIndex]   value;       this.setState({         widths       });     };   }   render() {     const { widths } = this.state;     const time = widths.time;     const name = widths[`title.name`];      return (       <Table         dataSource={dataSource()}         rowSelection={rowSelection}         onResizeChange={this.onResizeChange}       >         <Table.Column lock title="Id" dataIndex="id" width={100} />         <Table.Column           title="Title"           dataIndex={"title.name"}           asyncResizable           width={name}         />         <Table.Column           title="Time"           dataIndex="time"           asyncResizable           width={time}         />         <Table.Column  asyncResizable lock='right'cell={render} width={200} />       </Table>     );   } }  ReactDOM.render(<App />, mountNode);)

### Steps to reproduce
使用火狐浏览器 组件表格table组件 <Table.Column  asyncResizable lock='right'cell={render} width={200} />代码里面 asyncResizable 和lock一起使用 出现横向滚动条拖拽到最右端后，拖拽不回去

**Comment by lakerswgq** [comment]
这个看着 demo 不完整，给个在线 demo 吧
