### ISSUE TITLE
[Upload]开放reUpload事件，和remove一样可单独设置，比如想单独设按钮实现重新上传图片功能

### ISSUE THREAD

**Issue by coder-txh** [alibaba-fusion/next#4358]
### Component 
Upload
### Feature Description
其次可以开放reUpload事件，和remove一样可单独设置，比如想单独设按钮实现重新上传图片功能，比如上传图片之后，在组件之外设置按钮实现重新上传文件功能

**Comment by lakerswgq** [comment]
duplicate of #4357
