### ISSUE TITLE
[Dialog]弹窗设置v2属性为true的情况下，再设置hasMask等于false，此时弹窗后面的内容无法选中

### ISSUE THREAD

**Issue by am0622** [alibaba-fusion/next#4366]
### Component 
Dialog

### Steps to reproduce
步骤：弹窗设置v2属性为true的情况下，再设置hasMask等于false，此时弹窗后面的内容无法选中。删除v2属性的话，可拖拽的功能失效了。
期望结果：既可拖拽，也可复制弹窗后面的内容。
实际效果：两个属性不能同时生效。

**Comment by lakerswgq** [comment]
能给个 demo 么，提高排查效率

**Comment by am0622** [comment]
你好！
&nbsp; &nbsp; &nbsp;我想实现弹窗既可拖拽又可以关掉遮罩复制后面的文字的功能，但是现在发现可拖拽的功能必须在弹窗为v2的时候才可实现，然后关掉遮罩可选中弹窗后面内容的功能又必须得在弹窗版本不为v2的时候才可实现，所以比较冲突。这个是可拖拽弹窗的在线编辑地址：https://codepen.io/aomin/pen/LYXYObY?editors=0010，麻烦帮忙看看~
&nbsp;


敖敏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月7日(星期三) 中午11:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba-fusion/next] [Dialog]弹窗设置v2属性为true的情况下，再设置hasMask等于false，此时弹窗后面的内容无法选中 (Issue #4366)





 
能给个 demo 么，提高排查效率

**Comment by lakerswgq** [comment]
私聊已解决，需要点击穿透，css 可解
