### ISSUE TITLE
[Field]「Field」rules传入的正则常量会被添加一个validator参数，导致rc-from使用同一个参数时报错

### ISSUE THREAD

**Issue by 17863136957** [alibaba-fusion/next#4367]
### Component 
Field

### Steps to reproduce
// 校验规则常量
export const MORE_THAN_2_ERROR = {
  pattern: MORE_THAN_2,
  message: intl('common.tip.2_char_required'),
}

// Field业务使用
<Input
    maxLength={256}
    hasLimitHint
    multiple
    data-spm-id="create-cloud-service-desc-input"
    {...init('Description', {
     rules: [
     MORE_THAN_2_ERROR,
     CREATE_CEN_DESC_XREGEXP_ERROR,
      ],
      })}
 />
执行validate()之后，
MORE_THAN_2_ERROR 多了一个validator参数；
导致rc-form再使用MORE_THAN_2_ERROR时认为validator是业务侧自定义的，从而导致报错；

rules作为props不应该直接修改原有的值；

**Comment by lakerswgq** [comment]
@young858968202 这个帮评估一下改成不修改入参的工作量和兼容性

**Comment by YSMJ1994** [comment]
Resolved at https://www.npmjs.com/package/@alifd/next/v/1.26.27
