### ISSUE TITLE
[Dialog]Dailog 组件快捷调用后 onCancel 中使用 Promise 返回后，Loading 状态加在了 okProps 里

### ISSUE THREAD

**Issue by HuColin** [alibaba-fusion/next#4368]
### Component 
Dialog

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-template-forked-gd9yw9)

**Comment by lakerswgq** [comment]
改入参确实是不好的设计
