### ISSUE TITLE
[Field]field监管isPreiview或者可以设置基础传递属性

### ISSUE THREAD

**Issue by xmsz** [alibaba-fusion/next#4372]
### Component 
Field
### Feature Description
背景
- 使用field
- 有isPreview切换

现在
- isPreview得给每个组件自己手动加上`<Input {...field.init("name")} isPreview={isPreivew}/>`
- 有点麻烦

希望
- field可以填写isPreview，并自动传入组件props

**Comment by lakerswgq** [comment]
这个和 field 没什么关系，组件本身是有预览态的，这个不应该 field 去控制，目前 field 的 API 不做这样的拓展
