### ISSUE TITLE
[Input]Input maxLength 长度，需要区分中文、英文

### ISSUE THREAD

**Issue by progkonglei** [alibaba-fusion/next#4375]
### Component 
Input
### Feature Description
function getCharLength(str) {
  let length = 0;
  for (let i = 0; i < str.length; i  ) {
    const code = str.charCodeAt(i);
    if (code >= 0 && code <= 128) {
      length  = 1; // 英文字符长度为1
    } else {
      length  = 2; // 中文字符长度为2
    }
  }
  return length;
}

**Comment by linjunxyz** [comment]
这个maxLength是input标签原生的属性，并不支持自定义计算字符长度的方法
