### ISSUE TITLE
[Select]select组件dataSource使用Object作为value

### ISSUE THREAD

**Issue by ccctw-ma** [alibaba-fusion/next#4376]
### Component 
Select

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-template-forked-xh4wdf)

### Steps to reproduce
dataSource={[
          {
            label: "1",
            value: { a: 1 }
          },
          {
            label: "2",
            value: { a: 2 }
          },
          {
            label: "3",
            value: { a: 3 }
          }
        ]} 呈现的效果确只有一个可选项

**Comment by lakerswgq** [comment]
你的需求比较类似 useDetailValue ，但是 dateSource 里面不能这么写，value 可以是对象
