### ISSUE TITLE
[Icon]无法自定义Icon

### ISSUE THREAD

**Issue by ZRR641182473** [alibaba-fusion/next#4381]
### Type 
Platform Theme
### Component 
Icon
### Feature Description
Icon如何添加图表，没有找到对应的入口，钉钉群显示过期

**Comment by lakerswgq** [comment]
https://fusion.design/help.html/fusion-intro 你看的是这个群么

**Comment by lakerswgq** [comment]
我确认了下，目前 iconfont 外网服务挂了很久了，所以 fusion 外网版本也屏蔽掉了这个入口，暂时没有恢复时间

**Comment by lakerswgq** [comment]
#4003
