### ISSUE TITLE
[Button]button 组件的 iconSize 设置之后，icon的margin-right失效

### ISSUE THREAD

**Issue by BubbleLeaf** [alibaba-fusion/next#4383]
### Component 
Button

### Reproduction link 
[https://fusion.design/pc/component/button?themeid=2#icon-container](https://fusion.design/pc/component/button?themeid=2#icon-container)

### Steps to reproduce
button 组件的 iconSize 设置之后，icon的margin-right失效，经过查看之后是button中<i>本该有的 ‘next-btn-icon’类没有了

**Comment by lakerswgq** [comment]
@therePan 帮看下这个
