### ISSUE TITLE
[Overlay] discussion of focus

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#439]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Overlay

### What happen
Popup and Overlay are basic components,  a **_flash_** occurs when:
- `triggerType="focus"`
- `autoFocus={true}`
- children has focusable element(`<button>` `<a>`with href)

1. Focus on the`trigger element`,  and an Overlay shows.
2. Then due to autoFocus is true, the focusable element on Overlay's children will be focused  [overlay.jsx#L549](https://github.com/alibaba-fusion/next/blob/master/src/overlay/overlay.jsx#L549). 
3. Right now, the `window.activeElement` is not `trigger element`, which causes Overlay to close.
4. After close Overlay, the trigger take back the focus due to [overlay.jsx#L557](https://github.com/alibaba-fusion/next/blob/master/src/overlay/overlay.jsx#L557). Then back step 1.

This is what happend during the loop.

### Possible solutions
1. Is that possiable to set `safeNode` or  something else to keep the Overlay open when `window.activeElement` is not `trigger element` any more. 
> 3. Right now, the `window.activeElement` is not `trigger element`, which causes Overlay to close.
This will fundamentally solve the problem.

2. Make sure the two don't appear at the same time:
- `triggerType="focus"`
- `autoFocus={true}`

  This is a restriction on users, I don't think it's the best way to solve this problem. 

### My suggestion
I strongly recommend the first possible solutions. Besides, I even don't think we should only auto focus on `focusable element` [util/focus.js#L65](https://github.com/alibaba-fusion/next/blob/master/src/util/focus.js#L65)     [util/focus.js#L36](https://github.com/alibaba-fusion/next/blob/master/src/util/focus.js#L36)  when  overlay shows.

   > children has focusable element(`<button>` `<a>`with href)

  In line 551, focusNodeList[0] should be focused even its a `<div>` [overlay.jsx#L551](https://github.com/alibaba-fusion/next/blob/master/src/overlay/overlay.jsx#L551)

This need change to, what's your opinion guys?

### Resource
 `unfocusable element` and `focusable element`: https://bitsofco.de/how-and-when-to-use-the-tabindex-attribute/

 How to focus on an `unfocusable element`: https://github.com/alibaba-fusion/materials/blob/master/scaffolds/next-single-page-a11y/src/components/skip-to/index.jsx#L17

#423

**Comment by jdkahn** [comment]
If we allow `triggerType=focus` with `autoFocus` we will always have a loop where dismissing the popup will cause focus to go back to the trigger, which will cause the popup to appear again. The suggested Solution 1 does not solve this issue.

**Comment by jdkahn** [comment]
@youluna Following up from our conversation. 

- I believe we should prevent `triggerType=focus` with `autoFocus=true`. If a use tries to do this we can throw a deprecation warning and should change `triggerType=click`. 
- We should also add `aria-live=passive` to the element with `role=tooltip` so that its contents are read. And to place the close button after the contents so it is read after.

Do you agree?

**Comment by youluna** [comment]
Agree!
I have done 2. in https://github.com/alibaba-fusion/next/pull/477. The first one may need Overlay change
