### ISSUE TITLE
[Slider]点击最后一个卡片会回滚到第一个卡片

### ISSUE THREAD

**Issue by jun599** [alibaba-fusion/next#4392]
### Component 
Slider

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/730ee131](https://riddle.alibaba-inc.com/riddles/730ee131)

### Steps to reproduce
1、点击右箭头，展示出第6个卡片 
2、点击第6个卡片
3、卡片列表会回滚到第一个卡片 
期望：停留在未点击前的位置，不要滚动到第1个卡片

**Comment by linjunxyz** [comment]
目前组件库的最新版本已经修复

**Comment by YunMeng99** [comment]
setState时候页面会重新渲染 可以使用activeIndex属性变成受控的

**Comment by YunMeng99** [comment]
先关闭处理 如需继续跟进重新开启
