### ISSUE TITLE
[Upload]Upload组件itemRender 无效

### ISSUE THREAD

**Issue by wangzhongtang** [alibaba-fusion/next#4402]
### Component 
Upload

### Reproduction link 
[https://codepen.io/wzt8023/pen/xxQvRjq?editors=0010](https://codepen.io/wzt8023/pen/xxQvRjq?editors=0010)

### Steps to reproduce
Upload.Card 可以正常使用itemRender方法，但是Upload无效

![image](https://github.com/alibaba-fusion/next/assets/19568155/6ef169ae-f278-4c34-946f-77c1ad6123eb)

**Comment by kyokaxin** [comment]
itemRender参数目前只支持卡片渲染，后续会开发支持列表项渲染

**Comment by YSMJ1994** [comment]
@wangzhongtang 你好，Upload的设计就是展示文件列表，如果需要自定义文件名渲染方式，可以使用fileNameRender属性。Upload.Card的设计目的就是满足文件列表的完全自定义渲染的需求，所以不是itemRender在Upload上不支持，而是就是设计如此
