### ISSUE TITLE
[Input]input框 type=number，在ios 16.x，不能输入小数点，输入小数点 光标会移动到最前边

### ISSUE THREAD

**Issue by cxw2014** [alibaba-fusion/next#4407]
### Component 
Input

### Steps to reproduce
input框 type=number，在ios 16.x，不能输入小数点，输入小数点 光标会移动到最前边

**Comment by YunMeng99** [comment]
麻烦提到https://teambition-ei.alibaba-inc.com/collect/form/10248361a04e2132a81e000j这个链接里面吧 这个是属于meet 的问题  @cxw2014
