### ISSUE TITLE
[TreeSelect]能否定制menuProps或者popupContent

### ISSUE THREAD

**Issue by xmsz-stu** [alibaba-fusion/next#4409]
### Component 
TreeSelect
### Feature Description
背景，我想要实现自定义的内容，像select的一样
<img width="269" alt="image" src="https://github.com/alibaba-fusion/next/assets/139225486/5d2f2d06-c6ee-41c9-81bc-cbb667ae49b4">

但是treeSelect没有也不能透传menuProps，popupContent也被使用了

**Comment by eternalsky** [comment]
要实现哪些自定义内容，TreeNode 是开放传入的，里面可以传任何你想传的东西

**Comment by xmsz-stu** [comment]
> 要实现哪些自定义内容，TreeNode 是开放传入的，里面可以传任何你想传的东西

比如menuProps 
好像没有透传 https://github.com/alibaba-fusion/next/blob/261a6d4437a7a1a2cc12a64c855544bd86bbd346/src/tree-select/tree-select.jsx#L971

**Comment by eternalsky** [comment]
能说下你具体的定制场景是什么样吗？

**Comment by xmsz-stu** [comment]
> 能说下你具体的定制场景是什么样吗？

比如想加一个搜索框可以选择器和搜索框
<img width="551" alt="image" src="https://github.com/alibaba-fusion/next/assets/139225486/33a1dab3-6779-4df2-8038-d3dd657996f0">

**Comment by eternalsky** [comment]
ok，了解了，我看一下是否可以开放 menuProps 配置

**Comment by YSMJ1994** [comment]
@xmsz-stu 你好，TreeSelect组件之所以不开放menuProps，是因为popup内容不是menu，而是一个tree，若是要对下拉内容做自定义，更适合直接使用select组件

**Comment by YSMJ1994** [comment]
Stale
