### ISSUE TITLE
[Select]无取消全选功能、多选内容过长无清除按钮

### ISSUE THREAD

**Issue by acrens** [alibaba-fusion/next#441]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.13.5

### Component
Select

### Environment
组件最新版本

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/8dd9a11c](https://riddle.alibaba-inc.com/riddles/8dd9a11c)

### Steps to reproduce
如题，项目紧急

**Comment by youluna** [comment]
Changes to Tag component required @jdkahn

**Comment by youluna** [comment]
取消全选功能是个feature， 参考 https://github.com/alibaba-fusion/next/issues/287

**Comment by youluna** [comment]
https://github.com/alibaba-fusion/next/pull/443
