### ISSUE TITLE
【Field】将field作为props传递给子组件，同时子组件用mobx-react-lite的observer 方法包裹时，子组件onChange不生效

### ISSUE THREAD

**Issue by chi-gao** [alibaba-fusion/next#4411]
### 背景
父组件创建field实例， 然后将field作为props传递给子组件， 同时引入`Mobx`作为状态管理， 因此子组件需要使用`observer`包裹，以响应 mobx store的变化。

### 现象
子组件中的表单项，`onChange`时Field中的对应值变化了，但是表单本身值没有变化，应该是`setState`未生效。如下图：
![image](https://github.com/alibaba-fusion/next/assets/24784430/f8e6029b-d405-4aba-9860-df08a19f3ef6)
 

### 复现地址
https://stackblitz.com/edit/stackblitz-starters-mvmzph?file=src%2FApp.tsx

#### 步骤
直接切换下拉框的选项即可。

### 预期结果
正确响应onChange事件。

**Comment by eternalsky** [comment]
field 的 onChange 在你的 demo 里我看已经生效了，是你的子组件没有重新渲染去拿到最新的 field 值

**Comment by chi-gao** [comment]
> 

是的， 正常情况（没有使用observer）时，应该是 onChange的时候同时触发子组件的重新渲染。 但使用了observer之后， 重新渲染好像不生效了。

所以请教一下，在使用mobx的场景下， 应如何确保子组件的正常渲染？

**Comment by eternalsky** [comment]
跟 mobx 没关系，你这里没有 mobx 也不会自动渲染。Child，因为 field 拿到的是 Select，他只会让 Select 重新渲染，但是 Select 拿到的 props 是 Child 传给他的，但是 Child 并没有重新渲染。

**Comment by eternalsky** [comment]
本质是你 field 传入方式不对，你应该是让 Child 去接收 field.init 出来的属性，而不是里面的 Select

**Comment by eternalsky** [comment]
我们无法 100% 控制子组件是否渲染，只能让 field 本身 attach 的组件进行重新渲染。比如你说的 props 变化触发子组件渲染，这只是因为你的子组件会对这个 props 变化产生重新渲染的行为，但不代表所有的子组件都是这样处理的。因为部门不知道子组件的shouldComponentUpdate 是怎样写的。

**Comment by chi-gao** [comment]
> 我们无法 100% 控制子组件是否渲染，只能让 field 本身 attach 的组件进行重新渲染。比如你说的 props 变化触发子组件渲染，这只是因为你的子组件会对这个 props 变化产生重新渲染的行为，但不代表所有的子组件都是这样处理的。因为部门不知道子组件的shouldComponentUpdate 是怎样写的。

是的，所以传递field实例本身可能不是一个好的实践。我这个例子我感觉正确的写法应该是：每个子组件包含自己的field，子组件利用value+onChange可以作为一个自定义的手控组件受父组件的控制
