### ISSUE TITLE
[Card]Card组件国际化无效

### ISSUE THREAD

**Issue by zdgzdgzdg** [alibaba-fusion/next#4418]
### Component 
Card

### Reproduction link 
[https://codepen.io/zdgzdgzdg/pen/wvRGdZK?editors=0010](https://codepen.io/zdgzdgzdg/pen/wvRGdZK?editors=0010)

### Steps to reproduce
First look at the next source code, you can use locale internationalization in the Card component CollapseContent subcomponent, and then as follows, it does not work,We've also tried using locale internationalization in card, or header, or Content, and it didn't work

**Comment by eternalsky** [comment]
if you want use Card SubComponent With Card，you shuould set Card props free true.
![Uploading 截屏2023-08-31 下午2.36.07.png…]()

**Comment by eternalsky** [comment]
here is a demo modified from yours. https://codepen.io/eternalsky/pen/BavKgeZ

**Comment by zdgzdgzdg** [comment]
ok. thanks
