### ISSUE TITLE
[Icon]icon库里的icon怎么上传都失败，不是icon的问题，也不是名字或者icon重复的问题，也不是权限的问题

### ISSUE THREAD

**Issue by 198li** [alibaba-fusion/next#4422]
### Component 
Icon

### Steps to reproduce
icon库里的icon怎么上传都失败，而且之前上传成功过，因为在平台上的icon不能重新命名，我要重新命名我只能把平台上的icon下载下来重新命名，再把之前库里重复的icon删掉，再上传，就现实失败。不是icon的问题，也不是名字或者icon重复的问题，也不是权限的问题，试了很多很多次就是不行。现在前端要开发又依赖这个icon，很急。

**Comment by eternalsky** [comment]
已在答疑解决中
