### ISSUE TITLE
[Tree]Tree组件折叠父节点，里面的子节点也想直接折叠起来

### ISSUE THREAD

**Issue by Ljiajia** [alibaba-fusion/next#4431]
### Component 
Tree
### Feature Description
Demo：https://codepen.io/leijia/pen/JjwEXzR?editors=0010
不使用autoExpandParent属性，折叠父级，把当前父级下面的子集都折叠起来
（目前点击最外面的父级折叠，子集展开的id，始终存在state上面）

**Comment by kyokaxin** [comment]
暂不支持折叠父级节点时自动折叠子集，可以手动在onExpand中设置精细化的调整

**Comment by YSMJ1994** [comment]
Stale
