### ISSUE TITLE
[Balloon]Balloon组件和Balloon.Tooltip组件的类型和暴露api对齐

### ISSUE THREAD

**Issue by caozhong1996** [alibaba-fusion/next#4433]
### Component 
Balloon
### Feature Description
我注意到Balloon.Tooltip的props ts类型和Balloon的props ts类型是完全分开声明的，例如在为Balloon.Tooltip传入type属性时，会提示type类型未定义，但忽略ts报错，实际是会生效的。
1. 将Balloon.Tooltip的props类型改为继承Balloon的props类型实现应该会更好
2. Balloon 暴露了一些api，但 Balloon.Tooltip 没有。例如 onVisibleChange，但实际上Balloon.Tooltip也应该要有。

总结：Balloon.Tooltip和Balloon的：props ts 类型声明和暴露的 api 需要对齐

**Comment by YunMeng99** [comment]
Balloon.Tooltip传入type属性你是怎么生效的 官网没有复现 你是自己加了什么样式吗

**Comment by caozhong1996** [comment]
> Balloon.Tooltip传入type属性你是怎么生效的 官网没有复现 你是自己加了什么样式吗

嗯，样式是我看错了，不过是否也可以考虑是否对齐？我的大体意思是这两者没必要这么割裂。

**Comment by YunMeng99** [comment]
Tooltip是简化的Balloon, 它只支持Balloon.Tooltip 文档中那几个属性
