### ISSUE TITLE
[Field]支持是否已修改状态

### ISSUE THREAD

**Issue by xmsz-stu** [alibaba-fusion/next#4434]
### Component 
Field
### Feature Description
背景
- 筛选功能里，会有「重置」按钮，希望表单有操作后才出现，布局需求
- 筛选功能里，会有「提交」按钮，希望表单有操作后才高亮，功能需求

都依赖表单是否有操作的状态

现在我是通过onChange useState来处理，希望可以直接集成在field里

**Comment by eternalsky** [comment]
你的意思是在 Form 中做判断吧，单纯 FIeld 只是一个表单字段，怎么知道和控制他外面的按钮呢~

**Comment by xmsz-stu** [comment]
> 你的意思是在 Form 中做判断吧，单纯 FIeld 只是一个表单字段，怎么知道和控制他外面的按钮呢~

我想要field能返回「是否有修改」，然后我根据这个状态再控制外部按钮

**Comment by eternalsky** [comment]
> > 你的意思是在 Form 中做判断吧，单纯 FIeld 只是一个表单字段，怎么知道和控制他外面的按钮呢~
> 
> 我想要field能返回「是否有修改」，然后我根据这个状态再控制外部按钮

你的意思我大概理解了，但 field 不是已经有 onChange 向外通知是否已修改？还是说，你希望，比如 1->2->2 这样的行为有个回调，第一次给你 已修改，第二次再给你一个未修改这样的标？

**Comment by xmsz-stu** [comment]
> > > 你的意思是在 Form 中做判断吧，单纯 FIeld 只是一个表单字段，怎么知道和控制他外面的按钮呢~
> > 
> > 
> > 我想要field能返回「是否有修改」，然后我根据这个状态再控制外部按钮
> 
> 你的意思我大概理解了，但 field 不是已经有 onChange 向外通知是否已修改？还是说，你希望，比如 1->2->1 这样的行为有个回调，第一次给你 已修改，第二次再给你一个未修改这样的标？

嗯，这个回调我也想要，然后如果这个状态直接是储存在field更好
比如，`field.isHasModify`  这种

**Comment by eternalsky** [comment]
> > > > 你的意思是在 Form 中做判断吧，单纯 FIeld 只是一个表单字段，怎么知道和控制他外面的按钮呢~
> > > 
> > > 
> > > 我想要field能返回「是否有修改」，然后我根据这个状态再控制外部按钮
> > 
> > 
> > 你的意思我大概理解了，但 field 不是已经有 onChange 向外通知是否已修改？还是说，你希望，比如 1->2->1 这样的行为有个回调，第一次给你 已修改，第二次再给你一个未修改这样的标？
> 
> 嗯，这个回调我也想要，然后如果这个状态直接是储存在field更好 比如，`field.isHasModify` 这种

如果是 field 上的属性的话，好像起不到你要的通知的效果，那你在什么时候去调用呢~ onChange 的时候？

**Comment by xmsz-stu** [comment]
> > > > > 你的意思是在 Form 中做判断吧，单纯 FIeld 只是一个表单字段，怎么知道和控制他外面的按钮呢~
> > > > 
> > > > 
> > > > 我想要field能返回「是否有修改」，然后我根据这个状态再控制外部按钮
> > > 
> > > 
> > > 你的意思我大概理解了，但 field 不是已经有 onChange 向外通知是否已修改？还是说，你希望，比如 1->2->1 这样的行为有个回调，第一次给你 已修改，第二次再给你一个未修改这样的标？
> > 
> > 
> > 嗯，这个回调我也想要，然后如果这个状态直接是储存在field更好 比如，`field.isHasModify` 这种
> 
> 如果是 field 上的属性的话，好像起不到你要的通知的效果，那你在什么时候去调用呢~ onChange 的时候？

但onChange里就行

**Comment by eternalsky** [comment]
这里涉及到一个基准线的问题，如何决定哪个点是修改，比如初始化的时候 field 中存在一个值，后续 setValue 是否算作修改？

**Comment by YSMJ1994** [comment]
Stale
