### ISSUE TITLE
[Input]Input.Password 的onClear事件无效

### ISSUE THREAD

**Issue by zdgzdgzdg** [alibaba-fusion/next#4438]
### Component 
Input

### Reproduction link 
[https://codepen.io/zdgzdgzdg/pen/jOXwXNJ?editors=0010](https://codepen.io/zdgzdgzdg/pen/jOXwXNJ?editors=0010)

### Steps to reproduce
Input.Password组件的onClear事件无效

**Comment by kyokaxin** [comment]
@zdgzdgzdg 看到官网上并没有提供这个onClear函数，想问是在哪里看到的
