### ISSUE TITLE
[Animate]类型错误导致项目代码一直报错

### ISSUE THREAD

**Issue by yyz945947732** [alibaba-fusion/next#4439]
### Component 
Animate

### Steps to reproduce
`component` 属性的类型有问题，现在传标签名会报类型错误。
<img width="296" alt="image" src="https://github.com/alibaba-fusion/next/assets/47586954/aa8b51ef-9baa-4b28-9fa0-c6d21b808f9d">

https://github.com/alibaba-fusion/next/pull/4412

**Comment by YunMeng99** [comment]
官网未复现 能否给一个复现的demo

**Comment by eternalsky** [comment]
> 官网未复现 能否给一个复现的demo

这个我来处理吧~ 作者已经提了 pr，在对接中。

**Comment by eternalsky** [comment]
close by https://github.com/alibaba-fusion/next/pull/4412
