### ISSUE TITLE
组件库文档

### ISSUE THREAD

**Issue by 875908494** [alibaba-fusion/next#4443]
### Component 
Affix
### Feature Description
能否将现有文档改造一下，一是组件文档代码展示不够清晰，参考ant-design就可以，而且有个疑问为什么现在组件文档的代码还是使用的class，为什么不是hooks写法，这样让react16.8后学习的人使用起来非常不友好

**Comment by eternalsky** [comment]
整体改为 hooks 确实是一个优化点，我们已经将其作为一个优化方向后续会落实下来。

**Comment by eternalsky** [comment]
https://github.com/alibaba-fusion/next/discussions/4421 我们发起了一个讨论，请大家来投票决定接下来优化的优先级，hooks 也在其中，有兴趣可以参加一下~

**Comment by YSMJ1994** [comment]
目前我们正在进行基于1.x版本的组件库技术升级，包含文档优化相关内容，欢迎PR，另外我们将在 2.x 版本全面优化文档与拥抱高版本 react，敬请期待。

> https://github.com/alibaba-fusion/next/wiki/Tech-upgrade
