### ISSUE TITLE
【NumberPicker】stringMode场景，最大值和最小值初始化逻辑有误

### ISSUE THREAD

**Issue by CoCoManYY** [alibaba-fusion/next#4444]
### Component 
NumberPicker

### Reproduction link 
[无需](无需)

### Steps to reproduce
https://github.com/alibaba-fusion/next/blob/master/src/number-picker/number-picker.jsx#L223

应该为 -Infinity

**Comment by YSMJ1994** [comment]
Resolved at https://www.npmjs.com/package/@alifd/next/v/1.26.27
