### ISSUE TITLE
[Table]table组件在调用onResizeChange时报错

### ISSUE THREAD

**Issue by shiwofeiwo** [alibaba-fusion/next#4448]
### Component 
Table

### Steps to reproduce
在调用onResizeChange时控制台报错
n.props.cellDomRef.getBoundingClientRect is not a function

fusionDesign版本1.26

**Comment by eternalsky** [comment]
请提供一下复现 demo？

**Comment by shiwofeiwo** [comment]
在lowcode engine中的可以吗
![image](https://github.com/alibaba-fusion/next/assets/105789907/6a947d8b-b33d-4d7f-a176-4895677304d3)
![image](https://github.com/alibaba-fusion/next/assets/105789907/4836c417-5827-45e7-ad16-d72e07a984e1)

**Comment by eternalsky** [comment]
这样会无谓增加问题的复杂度，最好是以最小 demo 提供给我们。可以使用我们 demo 下提供的 codePen 链接。https://fusion.design/pc/component/table?themeid=2

**Comment by eternalsky** [comment]
可以从上面的链接中复制 demo 代码，在 codePen 或者 codesandbox 中给到我们 demo

**Comment by eternalsky** [comment]
你如类似这种，https://codepen.io/eternalsky/pen/JjwMWPz?editors=0010

**Comment by shiwofeiwo** [comment]
demo中没有问题，可能不是组件库的原因，麻烦close这个issue吧
