### ISSUE TITLE
[Calendar2]celendar2组件问题

### ISSUE THREAD

**Issue by zhoup07** [alibaba-fusion/next#4449]
### Component 
Calendar2

### Steps to reproduce
Celendar2组件年月下拉框change事件无法被监听到

**Comment by YSMJ1994** [comment]
组件onChange事件的设计是在组件值发生变化时触发，年月下拉框的变更不属于组件值变化，你可以使用onPanelChange事件来监听到变化

**Comment by YSMJ1994** [comment]
不知道有没有能够解决你的问题，我们即将关闭这个issue啦
