### ISSUE TITLE
[Table]开启虚拟滚动后表格回显异常

### ISSUE THREAD

**Issue by callmeYe** [alibaba-fusion/next#4453]
### Component 
Table

### Steps to reproduce
import { Table, Field, Button } from '@alifd/next';
import React, { useState, useEffect } from 'react'
import ReactDOM from 'react-dom'

const dataSource = () => {
    const result = [];
    for (let i = 0; i < 5; i  ) {
        result.push({
            title: {name: `Quotation for 1PCS Nano ${3   i}.0 controller compatible`},
            id: 100306660940   i,
            time: 2000   i
        });
    }
    return result;
};
const render = (value, index, record) => {
    return <a href="javascript:;">Remove({record.id})</a>;
};

export default function Demo() {
  const field = Field.useField();
  const { init } = field;
  const [step,setStep]= useState(1);

  useEffect(() => {
    field.setValue('ds', dataSource());
    field.setValue('myinput2', 'my input text2');
    
  }, [])
  
  return (
    <div>
      <Button onClick={()=>{setStep(1);}}>setStep 1</Button>
      
      <Button onClick={()=>{setStep(2);}}>setStep 2</Button>

      <div
      style={{display: step===1 ? 'block':'none'}}
      >current step1
      </div>

{
  // step===2 &&
  <div
      style={{display: step===2 ? 'block':'none'}}
      >
       current step2
        <Table useVirtual dataSource={field.getValue('ds')}>
    <Table.Column title="Id" htmlTitle="Unique Id" dataIndex="id"/>
    <Table.Column title="Title" dataIndex="title.name" />
    <Table.Column title="Time" dataIndex="time"/>
    <Table.Column cell={render}/>
</Table>
    </div>
}
      
    </div>
  );
}

ReactDOM.render(<Demo />, document.getElementById("root"))

**Comment by eternalsky** [comment]
异常表现是什么？

**Comment by callmeYe** [comment]
异常表现是数据无法回显

**Comment by YSMJ1994** [comment]
> 异常表现是数据无法回显

你好，麻烦提供最小复现demo和复现路径（ [codesandbox](https://codesandbox.io/s/kmy7zjr7l3) 或 [codepen](https://codepen.io/pen?&editors=0010) ）以便我们理解并排查问题

**Comment by callmeYe** [comment]
最小复现代码已经给出

**Comment by YSMJ1994** [comment]
> 最小复现代码已经给出

你给得代码粘贴出来都是语法错误...

**Comment by callmeYe** [comment]
https://riddle.alibaba-inc.com/riddles/8c3c0c8f

**Comment by YSMJ1994** [comment]
@callmeYe 排查到问题是开启虚拟滚动后，会检测容器的尺寸进行滚动计算，你的demo初始状态为display： none，导致无法获取到容器尺寸，后续的状态变更也没有触发table props变化进入了缓存逻辑，导致计算过程没有再次执行。
这种情况建议你通过 step 值来动态渲染table节点，而非通过 display 隐藏，或者step更新时给table 传递一个不一样的key来让其重载

**Comment by YSMJ1994** [comment]
Stale
