### ISSUE TITLE
[TreeSelect]TreeSelect单选希望支持全路径展示

### ISSUE THREAD

**Issue by Mr-TNF** [alibaba-fusion/next#4464]
### Component 
TreeSelect

**Comment by eternalsky** [comment]
可以考虑开放 valueRender @YSMJ1994

**Comment by YSMJ1994** [comment]
@eternalsky 现在的TreeSelect就是支持开放支持所有Select属性的，看起来用户的诉求是想完整显示value全路径这个功能内置到组件内，可以通过一个参数控制是否开启

**Comment by eternalsky** [comment]
> @eternalsky 现在的TreeSelect就是支持开放支持所有Select属性的，看起来用户的诉求是想完整显示value全路径这个功能内置到组件内，可以通过一个参数控制是否开启

目前好像不是的，虽然他可以传 others，但是会经过一个剪裁，只有 TreeSelect 支持的 props 才会透传下去

**Comment by YSMJ1994** [comment]
> > @eternalsky 现在的TreeSelect就是支持开放支持所有Select属性的，看起来用户的诉求是想完整显示value全路径这个功能内置到组件内，可以通过一个参数控制是否开启
> 
> 目前好像不是的，虽然他可以传 others，但是会经过一个剪裁，只有 TreeSelect 支持的 props 才会透传下去

看目前的代码，裁剪的是TreeSelect私有的属性，我尝试了一下，现在是传所有Select属性都是可以生效的

**Comment by eternalsky** [comment]
ok，那这个通过 valueRender 就可以完成了 @Mr-TNF

**Comment by Mr-TNF** [comment]
> ok，那这个通过 valueRender 就可以完成了 @Mr-TNF

但是说明文档里并没有valueRender这个props，而且我是希望在结果那展示全路径

**Comment by eternalsky** [comment]
> > ok，那这个通过 valueRender 就可以完成了 @Mr-TNF
> 
> 但是说明文档里并没有valueRender这个props，而且我是希望在结果那展示全路径

valueRender 就是展示在结果那里的，文档的话我们后续可以优化一下

**Comment by YSMJ1994** [comment]
> > ok，那这个通过 valueRender 就可以完成了 @Mr-TNF
> 
> 但是说明文档里并没有valueRender这个props，而且我是希望在结果那展示全路径

我们讨论了下这个需求的合理性，树形下拉的选择框展示全路径确实是一个合理的业务诉求，考虑到改动的普适性，我们决定在下一个release添加TreeSelect自己的valueRender属性，区别于Select的是，它将会有两个参数，类似
```
function valueRender(item: any, itemPaths: any[]): React.ReactNode
```

**Comment by YSMJ1994** [comment]
Resolved at https://www.npmjs.com/package/@alifd/next/v/1.26.27
