### ISSUE TITLE
[Tree]tree组件对接接口数据时，默认展开全部节点和默认展开部分节点失效

### ISSUE THREAD

**Issue by uiiu** [alibaba-fusion/next#4466]
### Component 
Tree

### Steps to reproduce
1、tree组件
2、对接接口数据时，默认展开全部节点和默认展开部分节点失效

**Comment by eternalsky** [comment]
没太理解，能否提供 demo 辅助说明一下。

**Comment by Azariasa** [comment]
问题复现步骤：
1、设置默认值，并将默认展开设置为true
2、点击按钮或者其他更改数据源的值
3、新赋予的值含有子节点，但是节点没有展开

`
const data1 = [
  {
    label: "Component",
    key: "1",
    children: [
      {
        label: "Form",
        key: "2",
        selectable: false,
        children: [
          {
            label: "Input",
            key: "4"
          },
          {
            label: "Select",
            key: "5",
            disabled: true
          }
        ]
      },
      {
        label: "Display",
        key: "3",
        children: [
          {
            label: "Table",
            key: "6"
          }
        ]
      }
    ]
  }
];

class Demo extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      selectedKeys: [],
      multiple: false,
      data: data1
    };
    this.handleSelect = this.handleSelect.bind(this);
    this.handleCheck = this.handleCheck.bind(this);
    this.handleData = this.handleData.bind(this);
  }

  handleSelect(keys, info) {
    console.log(keys, info);

    this.setState({
      selectedKeys: keys
    });
  }

  handleCheck() {
    this.setState({
      multiple: !this.state.multiple,
      selectedKeys: []
    });
  }
  handleData(flag){
    if(flag){
      this.setState({
      data: [
        {
          label:'0-0',
          key: '0-0',
          children:[
            {
              label:'0-0-0',
              key: '0-0-0'
            },
            {
              label:'0-0-1',
              key: '0-0-1'
            }
          ]
        }
      ]
    })
    }else{
     this.setState({
     data: date1
     })
    }
  }

  render() {
    const { multiple, selectedKeys, data } = this.state;

    return (
      <div className="control-select-demo">
        <label className="multiple-check">
          <Checkbox checked={multiple} onChange={this.handleCheck} />
          <span className="multiple-text">多选</span>
        </label>
         <label className="multiple-check">
          <Checkbox checked={false} onChange={() =>{this.handleData(true)}} />
          <span className="multiple-text">设置数据</span>
        </label>
        <Tree
          defaultExpandAll
          multiple={multiple}
          selectedKeys={selectedKeys}
          onSelect={this.handleSelect}
          dataSource={data}
        />
      </div>
    );
  }
}

ReactDOM.render(<Demo />, mountNode);
`

**Comment by Azariasa** [comment]
@eternalsky

**Comment by Azariasa** [comment]
有没有什么属性，可用设置展开顶级节点时，将所有的子节点都展开，包括折叠的子节点，要不然数据量大的话，使用expandedKeys数据处理这块就比较麻烦

**Comment by Azariasa** [comment]
有没有什么属性，可用设置展开顶级节点时，将所有的子节点都展开，包括折叠的子节点，要不然数据量大的话，使用expandedKeys数据处理这块就比较麻烦

**Comment by YSMJ1994** [comment]
> 有没有什么属性，可用设置展开顶级节点时，将所有的子节点都展开，包括折叠的子节点，要不然数据量大的话，使用expandedKeys数据处理这块就比较麻烦

你好，这种场景我们没有预设配置提供，你的场景不具有普适性，最好还是手动控制来解决。
