### ISSUE TITLE
[Menu]选中时没有选中态

### ISSUE THREAD

**Issue by YunMeng99** [alibaba-fusion/next#4468]
### Component 
Menu
### Feature Description
![image](https://github.com/alibaba-fusion/next/assets/141202126/47246d7b-d3c3-4cc4-aa25-8e3111630aef)
选中的没有背景样式 官网就能复现
https://links.alibaba-inc.com/support/conversation/65279d59a130ed077c2f4456/

**Comment by eternalsky** [comment]
@YunMeng99 还是在 issue 里把需求写明确吧，另外 label 也打好，这样后续才比较能看懂。大家也不需要再去把聊天记录读一遍。
