### ISSUE TITLE
[Overlay]Select 组件在「表格组件锁列的情况」下使用时，popupProps 使用 v2   autoAdjust 时，判断 trigger 不可见时弹层没有消失， z-index 层级也不太对

### ISSUE THREAD

**Issue by HuColin** [alibaba-fusion/next#4481]
### Component 
Overlay

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/condescending-gates-x8jmmf?file=/src/App.js)

### Steps to reproduce
期望 Trigger 元素不可见时，弹层隐藏

**Comment by YSMJ1994** [comment]
![image](https://github.com/alibaba-fusion/next/assets/18289306/69d66128-5cb9-469d-b856-c1e836525d61)
@HuColin 不在可视区域内就执行隐藏弹层这个不是广泛适用的交互方式，如果需要可以业务自己实现；z-index的问题我们会在下一个迭代里修复，感谢你的反馈~

**Comment by HuColin** [comment]
我将 Demo 中的 Select 的弹出形式改成了 v2 的模式
Select 弹层隐藏好像是 overlay.popup v2 中 autoAdjust 的能力，目前似乎是判断有问题
正常情况下，trigger 被隐藏的时候 overlay 的 DOM 会被加上一个 diaplay: none 的样式
<img width="1467" alt="image" src="https://github.com/alibaba-fusion/next/assets/16102181/92049e8d-3dc1-402d-afb0-6ed12953a92d">

**Comment by HuColin** [comment]
因该是 @alifd/overlay 这个包里面 `getPlacements` 方法判断超出滚动区域的逻辑有问题
https://codesandbox.io/s/condescending-gates-x8jmmf?file=/src/App.js
可以看一下 Demo1 和 Demo2 的弹层消失的逻辑
具体是因为 https://github.com/alibaba-fusion/overlay/blob/6cd329d384b7290d2d3a5e6508526419757efba9/src/placement.ts#L391-L405 中循环计算了 target 和滚动容器的关系，虽然 target 已经不在内层的滚动容器的可视区域内了，但是还在外层滚动容器的”可视区域“内，因此前面的 diaplay: none 属性被覆盖了
