### ISSUE TITLE
[Table]分组表格表头不跟随表格内容左右滚动的问题

### ISSUE THREAD

**Issue by mimimamahaoduozi** [alibaba-fusion/next#4490]
### Component 
Table

### Steps to reproduce
【分组表格】列宽过大出现滚动情况时，滚动下方内容表头不跟随滚动

**Comment by YSMJ1994** [comment]
@mimimamahaoduozi 你好，可以给一个复现demo吗，在这里 https://codesandbox.io/s/fusion-design-demo-rpr46k
