### ISSUE TITLE
[Upload]upload组件上传文件后的文件列表可以关掉吗？

### ISSUE THREAD

**Issue by owenchen1004** [alibaba-fusion/next#4496]
### Component 
Upload
### Feature Description
upload组件上传文件后，会弹出文件列表，可以不显示这个列表吗？

**Comment by YSMJ1994** [comment]
暂时没有开放参数可以隐藏列表，如果是自定义程度较高的场景，我们建议使用Upload.Card来实现。如果实在不行，可以考虑使用css样式覆盖隐藏list。

**Comment by eternalsky** [comment]
既要上传又不显示上传文件列表的场景是什么样的呢

**Comment by YSMJ1994** [comment]
> 既要上传又不显示上传文件列表的场景是什么样的呢

猜想是自定义程度较高且不需要我们内置的列表展示的场景，比如用上传trigger区域来反馈已上传状态， like：传前是一个按钮，点击上传后，展示一个已上传的按钮
