### ISSUE TITLE
[DatePicker]datepicker组件showTime属性传值问题

### ISSUE THREAD

**Issue by zdgzdgzdg** [alibaba-fusion/next#4498]
### Component 
DatePicker

### Steps to reproduce
场景：datepicker组件的showTime属性可以传timepicker的属性，且查阅timepicker的props的使用之后发现defaultValue可以传moment 对象或时间字符串
![图片](https://github.com/alibaba-fusion/next/assets/100658615/3b896ac2-39be-4673-852b-877262974f40)
使用：
传moment对象时正常：
![图片](https://github.com/alibaba-fusion/next/assets/100658615/4e0217be-722f-4232-95b6-e9178d950ca1)
传字符串时异常：
![图片](https://github.com/alibaba-fusion/next/assets/100658615/ac87abc3-dab8-4510-ae71-43f13afd2063)
format要的是 时 : 秒，但是表现的是  时 : 分
经过实验，当showTime使用defaultValue时传moment对象时正常，传时间字符串时异常，只有HH，HH：mm，或者HH：mm：ss正常，其他形式比如mm：ss，HH：ss 等等形式表现皆异常

**Comment by YSMJ1994** [comment]
你好，调整time的format是不通过props.format，而是showTime.format，详见 https://fusion.design/pc/component/date-picker?themeid=2#showTime-container
