### ISSUE TITLE
[Select]onChange时希望将选择的是哪项item带出来，特别多选的时候

### ISSUE THREAD

**Issue by soulcm** [alibaba-fusion/next#451]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Select

### Feature Description
现在onChange有第3个参数，但多选的时候是数组，是所有已选择的items，希望提供操作的是哪项item的参数（勾选或取消勾选的item）

**Comment by myronliu347** [comment]
请问是哪种场景下需要给出操作的item呢 ？

**Comment by huarse** [comment]
可以在 dataSource 的 value 不中传一个字符串而是一个对象，对象的 toString 是一个 value 值，例如：

```
class Emp {
  constructor(id, name) {
    this.id = id;
    this.name = name;
  }
  
  toString() {
    return this.id;
  }
  
  valueOf() {
    return this.id;
  }
}

const dataSource = [
  { label: '张三', value: new Emp(10001, '张三') },
  { label: '李四', value: new Emp(10002, '李四') },
];

ReactDOM.render(<Select showSearch dataSource={dataSource} />, mountNode);
```

这样在最终拿到的 value 其实就是一个 Emp 实例，里面包含了想要的各种信息

**Comment by soulcm** [comment]
> 请问是哪种场景下需要给出操作的item呢 ？

是之前组件多选时全选功能不完善无法取消全选时想要的功能，暂且用不着了
