### ISSUE TITLE
[Calendar]自己配置的主题样式，日历语言修改不生效

### ISSUE THREAD

**Issue by TomLilione** [alibaba-fusion/next#4516]
### Component 
Calendar

### Steps to reproduce
自己配置的样式，在设置语言为中文时不生效

<img width="311" alt="截屏2023-11-08 16 26 00" src="https://github.com/alibaba-fusion/next/assets/47802577/46bde855-29f6-4611-96ca-fa85a166c68c">

**Comment by YSMJ1994** [comment]
可以参考一下官方文档关于日期格式化相关的内容 https://fusion.design/pc/doc/component/107?themeid=2
