### ISSUE TITLE
[Form]如何让我的第三方组件（类似input）被form item管理

### ISSUE THREAD

**Issue by shiwofeiwo** [alibaba-fusion/next#4521]
### Component 
Form
### Feature Description
我现在有一个第三方组件（类似input），当我将这个组件放到form item中，在提交表单时，我无法获取到这个组件中的value

复现demo
https://codepen.io/shiwofeiwo/pen/poGwVXV

**Comment by BruceHong666** [comment]
`
class Demo extends React.Component {
    field = new Field(this);    // 实例创建

    onClick = ()=>{
        console.log(this.field.getValue('name'));
    }
    render() {
        const init = this.field.init;

        // 注意：initValue只会在组件第一次初始化的时候被赋值，如果你是异步赋值请用setValue
        return <div>
            <Input {...init('name',{initValue:'first value'})} />
            <button onClick={this.onClick}>获取数据</button>
        </div>
    }
}
`

**Comment by BruceHong666** [comment]
```
class Demo extends React.Component {
    field = new Field(this);    // 实例创建

    onClick = ()=>{
        console.log(this.field.getValue('name'));
    }
    render() {
        const init = this.field.init;

        // 注意：initValue只会在组件第一次初始化的时候被赋值，如果你是异步赋值请用setValue
        return <div>
            <Input {...init('name',{initValue:'first value'})} />
            <button onClick={this.onClick}>获取数据</button>
        </div>
    }
}
```

**Comment by YSMJ1994** [comment]
自定义组件需要支持 value、onChange 这两个属性

**Comment by shiwofeiwo** [comment]
> 自定义组件需要支持 value、onChange 这两个属性 参考： https://fusion.design/pc/component/field?themeid=2#custom-container

解决了，感谢解答
