### ISSUE TITLE
[Field]Field 表单辅助工具设置值不生效 bug

### ISSUE THREAD

**Issue by Liting1** [alibaba-fusion/next#4525]
注：@alifd/next 包 version 1.26.31  有问题，
 以前的旧版本包就没有 例如 1.26.18 版本就是正常的

### Component 
Field 

```
import React from "react";
import { Form, Field, Button, Input } from '@alifd/next';
const FormTest = () => {
  const filed = Field.useField({
    parseName: true, autoUnmount: false, values: {
      one: [],
      two: { code: '33' }
    }
  });
  const clickHandle = () => {
    filed.setValues({
      one: [
        [{ b: { name: 'zhangsan', age: 27 } }],
      ], two: { code: '555' }
    })
  }
  const clickHandle2 = () => {
    // debugger;
    filed.setValues({
      one: [
        [{ b: null }], // 设置数据的值失败
      ],
      two: '' // 设置数据失败
    })
  }
  console.log(filed.getValues());

  return <div>
    <Form field={filed}>
      <Form.Item label="one-1">
        <Input type="text" {...filed.init(`one.0.0.b.name`)} />
      </Form.Item>
      <Form.Item label="one-2">
        <Input type="text" {...filed.init(`one.0.0.b.age`)} />
      </Form.Item>
      <Form.Item label="one-3">
        <Input type="text" {...filed.init(`two.code`)} />
      </Form.Item>
      <Button onClick={clickHandle}>按钮 1</Button>
      <Button onClick={clickHandle2}>按钮 2</Button>
    </Form>
  </div>
}
export default FormTest;
```
**以上代码就能复现 先点按钮1 ， 再点按钮2 就能看到**

@YSMJ1994  我目测原因出在 @alifd/field 这个包的这个地方
![image](https://github.com/alibaba-fusion/next/assets/33544236/d77bf3f6-1461-4a1e-af3a-02d3101f6cb8)

**Comment by Liting1** [comment]
![image](https://github.com/alibaba-fusion/next/assets/33544236/0013a8b7-2088-4a79-8a5c-7feb02a864a3)
点击按钮1 时正常设置值，点击按钮2的时候设置值就没有生效

**Comment by YSMJ1994** [comment]
按照目前的 parseName=true 对于setValues的设计 ( shallow merge and keep old field values )，你这个情况是符合预期的，清空数据可以使用 reset() 方法

**Comment by Liting1** [comment]
@YSMJ1994  但是旧版本是可以这么设置的, 这样不是会出现很多问题吗

**Comment by YSMJ1994** [comment]
> @YSMJ1994 但是旧版本是可以这么设置的, 这样不是会出现很多问题吗

近期的版本确实是有不一致的问题，我看一下

**Comment by YSMJ1994** [comment]
@Liting1 排查到的问题是以前的逻辑针对非undefined值会直接使用新的值来替换，你设置的 null 和 "" 正好符合了这个规则，所以覆盖了原有field的值，最近一次改动调整了这块逻辑，通过hasIn判断就走进了错误的逻辑。
已经了解到了这个问题，我们将在下一个迭代中修复这个问题，感谢你的反馈。

**Comment by YSMJ1994** [comment]
Replay demo: https://riddle.alibaba-inc.com/riddles/aa564e4b

**Comment by YSMJ1994** [comment]
Fixed at  [@alifd/field@1.6.7](https://github.com/alibaba-fusion/field/releases/tag/v1.6.7)
