### ISSUE TITLE
[Overlay] Why stopPropagation in onClick?

### ISSUE THREAD

**Issue by FringeY** [alibaba-fusion/next#4526]
here [https://github.com/alibaba-fusion/next/blob/dcd19d78bac8f132dd24e7c88463a6da330180b9/src/overlay/overlay.jsx#L216](https://github.com/alibaba-fusion/next/blob/dcd19d78bac8f132dd24e7c88463a6da330180b9/src/overlay/overlay.jsx#L216)

**Comment by YSMJ1994** [comment]
seems because of this https://github.com/alibaba-fusion/next/pull/3714

**Comment by FringeY** [comment]
It causes onClick not firing outside, is it expected?

**Comment by YSMJ1994** [comment]
Click outside will hide the overlay, so... it is expected.
