### ISSUE TITLE
[Tree]tree受控时，在子节点选中状态下，父节点及爷节点无法折叠

### ISSUE THREAD

**Issue by woiweb** [alibaba-fusion/next#4529]
### Component 
Tree

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/167822e9](https://riddle.alibaba-inc.com/riddles/167822e9)

**Comment by YSMJ1994** [comment]
api使用的问题，已私聊解决，计划在 tree 组件添加一个受控模式的demo补充说明一下
