### ISSUE TITLE
[Slider]Slider onChange 钩子中用 setState 后，会导致轮播失效。

### ISSUE THREAD

**Issue by hxuena** [alibaba-fusion/next#4533]
### Component 
Slider

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/44e5f670](https://riddle.alibaba-inc.com/riddles/44e5f670)

### Steps to reproduce
Slider onChange 钩子中用 setState 后，轮播失效。具体表现如：有 4张卡片，从1 -> 2，正常；从2->3，在切到3后，会立马切回 1.

**Comment by YSMJ1994** [comment]
Fixed at  [1.26.34](https://github.com/alibaba-fusion/next/releases/tag/build%2F1.26.34)
