### ISSUE TITLE
[Table]拖拽表格没办法展示行

### ISSUE THREAD

**Issue by ming001** [alibaba-fusion/next#4542]
### Component 
Table

### Reproduction link 
[https://o2.alibaba-inc.com/sandbox/ide?id=578](https://o2.alibaba-inc.com/sandbox/ide?id=578)

### Steps to reproduce
实现表格拖拽后，点击行元素，没办法展开

**Comment by ming001** [comment]
https://github.com/alibaba-fusion/next/issues/4489
问题被关闭了，这个bug是他的延伸

**Comment by YSMJ1994** [comment]
拖拽表格的实现自定义了Row，而expandRow是需要Row来实现的，参考：https://github.com/alibaba-fusion/next/blob/master/src/table/expanded.jsx#L295
内置实现： https://github.com/alibaba-fusion/next/blob/master/src/table/expanded/row.jsx#L134
