### ISSUE TITLE
[Drawer]drawer、dialog组件在html设置zoom的情况下位置不准确

### ISSUE THREAD

**Issue by zhtzjz** [alibaba-fusion/next#4548]
[### Component 
Drawer

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/3f8f790c](https://riddle.alibaba-inc.com/riddles/3f8f790c)

### Steps to reproduce

](https://riddle.alibaba-inc.com/riddles/3f8f790c)

**Comment by YSMJ1994** [comment]
v2版本已解决，v1版本的 overlay 逻辑我们排期解决一下

**Comment by YSMJ1994** [comment]
@zhtzjz 调研了一下，目前v1版本的弹层组件的实现使用了绝对定位调整top、left的方式，无法处理zoom，scale等情况，我们规划在下一个大版本中（2.x）重构弹层组件的实现机制。
目前你可以先使用 v2版本暂时解决这个问题。

**Comment by YSMJ1994** [comment]
Will fix at 2.x

**Comment by YSMJ1994** [comment]
Same as #3845
