### ISSUE TITLE
[Tree]可能的样式污染

### ISSUE THREAD

**Issue by andylili21** [alibaba-fusion/next#4549]
### Component 
Tree

### Reproduction link 
[https://codepen.io/andylili21/pen/WNPgRVv?editors=0110](https://codepen.io/andylili21/pen/WNPgRVv?editors=0110)

### Steps to reproduce
icon覆盖tree样式可能是出现bug

**Comment by YSMJ1994** [comment]
demo里你的预期是什么呢

**Comment by andylili21** [comment]
> demo里你的预期是什么呢

![image](https://github.com/alibaba-fusion/next/assets/101868030/c3abbb0a-f134-4642-b54b-c7fe7e4808dc)
想让icon之间的间隔小一些 ，右边的节点的选中状态样式完整（demo的中样式不完整）

**Comment by YSMJ1994** [comment]
调整外层容器的margin即可

**Comment by andylili21** [comment]
> 调整外层容器的margin即可

tree外面的容器嘛还是..
