### ISSUE TITLE
[Overlay]upside down when there is no enough space

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#462]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.13.x

### Component
Overlay

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/c9bbba3e](https://riddle.alibaba-inc.com/riddles/c9bbba3e)

![image](https://user-images.githubusercontent.com/10049465/54346144-894fa580-467f-11e9-8464-d27bb4e77a57.png)

**Comment by jdkahn** [comment]
resolved in https://github.com/alibaba-fusion/next/pull/463
