### ISSUE TITLE
[Drawer]drawer设置了遮罩但没有遮罩

### ISSUE THREAD

**Issue by xiestrikerzj** [alibaba-fusion/next#4634]
### Component 
Drawer

### Reproduction link 
[https://pre-insight.tmall.com/manager/nos/tmic-insight/newSurvey?hideLayout=true&projectId=1343680&surveyId=203968](https://pre-insight.tmall.com/manager/nos/tmic-insight/newSurvey?hideLayout=true&projectId=1343680&surveyId=203968)

### Steps to reproduce
点击右侧“整卷答题逻辑”设置

**Comment by YSMJ1994** [comment]
你好，麻烦提供下最小复现场景，不要使用业务demo

**Comment by YSMJ1994** [comment]
Stale
