### ISSUE TITLE
[TimePicker2]TimerPicker.RangePicker预览模式下会报错

### ISSUE THREAD

**Issue by xmsz-stu** [alibaba-fusion/next#4638]
### Component 
TimePicker2

### Steps to reproduce
    <TimePicker2.RangePicker isPreview/>
会报错`value.format is undefined`

还有缺少isPreview和renderPreview类型提示

**Comment by YSMJ1994** [comment]
排查到确实有这样的问题，我们规划在本期迭代解决这个问题，非常感谢你的反馈
