### ISSUE TITLE
[Tree]Tree的dataSource如果有type字段，就会有样式问题

### ISSUE THREAD

**Issue by cwtuan** [alibaba-fusion/next#4644]
### Component 
Tree

### Reproduction link 
https://codepen.io/cwtuan/pen/MWLRjOL?editors=0010

### Steps to reproduce
![image](https://github.com/alibaba-fusion/next/assets/3455798/d492e1b6-601a-4ccc-a1bf-ea7706549e69)

**Comment by YSMJ1994** [comment]
dataSource item中多余的属性会传递给 tree node 内的 <li></li> 节点，图示的表现正是  <li type="1"></li> 的结果，所以是符合预期的行为，建议调整数据

**Comment by YSMJ1994** [comment]
欢迎 PR，建议在 dataSouce 类型定义中添加 @remarks 注释说明即可
