### ISSUE TITLE
主题发布失败

### ISSUE THREAD

**Issue by caoyi5225** [alibaba-fusion/next#4647]
### Steps to reproduce
在主题配置/发布与历史页，点击“确认发布”按钮，发布失败。hover fail标签的信息如下：
Command failed: NODE_ENV=development /home/admin/fusion-theme/target/fusion-theme/node_modules/node/bin/node /home/admin/fusion-theme/target/fusion-theme/node_modules/_npm@6.14.18@npm/bin/npm-cli.js publish --access=public --userconfig=/home/admin/fusion-theme/target/fusion-theme/config/npmrc --registry="https://registry.npmjs.org/"
npm notice
npm notice ? @alifd/theme-20832@0.6.13
npm notice === Tarball Contents ===
npm notice 52.3kB icons.var.css
npm notice 396.0kB dist/next-1.css
npm notice 425.3kB dist/next-2.css
npm notice 400.3kB dist/next-noreset-1.css
npm notice 411.7kB dist/next-noreset-2.css
npm notice 811.8kB dist/next-noreset.css
npm notice 302.9kB dist/next-noreset.min-1.css
npm notice 329.1kB dist/next-noreset.min-2.css
npm notice 631.8kB dist/next-noreset.min.css
npm notice 532.1kB dist/next-noreset.var-1.css
npm notice 644.6kB dist/next-noreset.var-2.css
npm notice 1.2MB dist/next-noreset.var.css
npm notice 401.0kB dist/next-noreset.var.min-1.css
npm notice 534.0kB dist/next-noreset.var.min-2.css
npm notice 934.7kB dist/next-noreset.var.min.css
npm notice 821.0kB dist/next.css
npm notice 296.3kB dist/next.min-1.css
npm notice 339.0kB dist/next.min-2.css
npm notice 635.1kB dist/next.min.css
npm notice 517.7kB dist/next.var-1.css
npm notice 669.8kB dist/next.var-2.css
npm notice 1.2MB dist/next.var.css
npm notice 389.3kB dist/next.var.min-1.css
npm notice 549.9kB dist/next.var.min-2.css
npm notice 939.0kB dist/next.var.min.css
npm notice 220.8kB variables.css
npm notice 82.0kB design-token.js
npm notice 55B index.js
npm notice 3.0MB dist/next.js
npm notice 978.0kB dist/next.min.js
npm notice 42.3kB variables.js
npm notice 1.2kB package.json
npm notice 118.1kB variables.less
npm notice 227B README.md
npm notice 49.3kB icons.scss
npm notice 159B index-noreset.scss
npm notice 103B index-noreset.var.scss
npm notice 128B index.scss
npm notice 95B index.var.scss
npm notice 118.1kB variables.scss
npm notice 455.0kB variables.scss2css.scss
npm notice === Tarball Details ===
npm notice name: @alifd/theme-20832
npm notice version: 0.6.13
npm notice package size: 2.3 MB
npm notice unpacked size: 19.4 MB
npm notice shasum: a83fdaa3e1b1cb7c777c22a41cfd0ad076215c42
npm notice integrity: sha512-5qIlLUGxRBGOG[...] KOYq4mKulWAA==
npm notice total files: 41
npm notice
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/@alifd%2ftheme-20832 failed, reason: connect ETIMEDOUT 104.16.27.34:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly. See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR! /home/admin/.npm/_logs/2023-12-12T06_30_57_475Z-debug.log

**Comment by eternalsky** [comment]
应该和上周 npm 国内链接情况不好有关，可以再试一下。

**Comment by caoyi5225** [comment]
> 应该和上周 npm 国内链接情况不好有关，可以再试一下。

已经可以了，感谢回复～
