### ISSUE TITLE
[Form]关于form组件的format

### ISSUE THREAD

**Issue by shiwofeiwo** [alibaba-fusion/next#4652]
### Component 
Form
### Feature Description
想问一下form是如何对format['number', 'tel', 'url', 'email']的值进行校验的，是正则表达式吗，如果是的话，能否看一下具体的正则

**Comment by YSMJ1994** [comment]
https://github.com/alibaba-fusion/validate/blob/master/src/rules/format.js

**Comment by shiwofeiwo** [comment]
> https://github.com/alibaba-fusion/validate/blob/master/src/rules/format.js

好的，感谢
