### ISSUE TITLE
[DatePicker2]datepicker没有国际化

### ISSUE THREAD

**Issue by fancyzhe** [alibaba-fusion/next#4654]
### Component 
DatePicker2

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/f5831a5](https://riddle.alibaba-inc.com/riddles/f5831a5)

### Steps to reproduce
浮窗里面内容没有国际化

**Comment by YSMJ1994** [comment]
DatePicker2 采用 dayjs 作为底层库，所以面板内的国际化需要引入 dayjs 对应语言包，参考文档：
https://fusion.design/pc/component/date-picker-2?themeid=2#%E5%9B%BD%E9%99%85%E5%8C%96

**Comment by YSMJ1994** [comment]
Stale
