### ISSUE TITLE
[Balloon]Balloon V2 ，样式配置的无border，但依然显示了border

### ISSUE THREAD

**Issue by xianglgd** [alibaba-fusion/next#4656]
### Component 
Balloon

### Steps to reproduce
@alife/theme-102368

bug图片
https://img.alicdn.com/imgextra/i3/O1CN01kyBwcb1CsnAbBXcCZ_!!6000000000137-2-tps-1024-806.png

**Comment by YSMJ1994** [comment]
Fixed at #4186
