### ISSUE TITLE
[TimePicker2]TimePicker2 focus 状态不对。且样式配置里也找不到该组件

### ISSUE THREAD

**Issue by xianglgd** [alibaba-fusion/next#4657]
### Component 
TimePicker2

### Steps to reproduce
主题:  @alife/theme-102368

bug图片
https://img.alicdn.com/imgextra/i4/O1CN01g3tTFO1s49EpJUVum_!!6000000005712-2-tps-1023-538.png

https://img.alicdn.com/imgextra/i4/O1CN01tarqpW1cs2WvZ31jJ_!!6000000003655-0-tps-439-132.jpg

**Comment by seven-lh** [comment]
你好 方便的话可以提供一下最小复现的demo： riddle 或者 codepen 等，方便快速排查问题。不清楚怎么操作看 https://yuque.antfin-inc.com/youlu.zgy/keysmp/bd3wq1#ULiIb
