### ISSUE TITLE
[Upload]Upload.Card实例没有selectFiles方法，Upload确是有的

### ISSUE THREAD

**Issue by laixiangran** [alibaba-fusion/next#4663]
### Component 
Upload

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/5e421a41](https://riddle.alibaba-inc.com/riddles/5e421a41)

### Steps to reproduce
我现在要实现类似粘贴上传的功能，根据你们写的例子使用uploaderRef.selectFiles方法实现选择文件，但我发现Upload.Card没有uploaderRef.selectFiles这个方法，Upload组件是有的，是不是API有遗漏

**Comment by YSMJ1994** [comment]
card在原有的Upload基础上封装了一层，可以通过 cardRef.uploaderRef获得里面的upload实例

**Comment by laixiangran** [comment]
@YSMJ1994 好的，我试试看，谢谢

**Comment by YSMJ1994** [comment]
Stale
