### ISSUE TITLE
[DatePicker2]DatePicker2.RangePicker在Form.Item里使用，样式宽度不是分配的宽度,DatePicker2.RangePicker的宽度溢出了

### ISSUE THREAD

**Issue by wangsweet** [alibaba-fusion/next#4676]
### Component 
DatePicker2

### Reproduction link 
[https://codepen.io/wangshuang/pen/gOEbXWm?editors=0010](https://codepen.io/wangshuang/pen/gOEbXWm?editors=0010)

### Steps to reproduce
DatePicker2.RangePicker在Form.Item里使用，如果容器宽度较小时，样式宽度不是分配的宽度,DatePicker2.RangePicker的宽度溢出了

**Comment by YSMJ1994** [comment]
RangePicker会计算一个最小宽度，取决于由内部的input的 html size 属性，而 input 的 html size 属性是根据日期的 format 计算而来的，所以过于狭窄的空间是无法完整展示日期组件的内容的。
建议切换交互方案来解决，或者通过 css 强制给 input 设置一个宽度

**Comment by YSMJ1994** [comment]
Stale
