### ISSUE TITLE
[DatePicker2]1.27.0 导致大量 Vite 应用白屏

### ISSUE THREAD

**Issue by guoyunhe** [alibaba-fusion/next#4694]
### Component 
DatePicker2

### Steps to reproduce
1.27.0 导致大量 Vite 构建的应用白屏，锁 ～1.26.0 版本可恢复正常。错误定位到文件 https://github.com/alibaba-fusion/next/blob/master/components/util/date.ts

```js
import * as advancedFormat from 'dayjs/plugin/advancedFormat';
```

这个导入与 [dayjs 官方用法](https://github.com/iamkun/dayjs?tab=readme-ov-file#plugin)不同：

```js
import advancedFormat from 'dayjs/plugin/advancedFormat' // load on demand
```

可能导致了导入的插件错误（Vite 和 Webpack 对 `import * as` 的处理是不同的，Webpack 更加宽容，而 Vite 则更加严格）。

**Comment by eternalsky** [comment]
其实 import * 的用法感觉更对一些，因为 commonjs 只有 module.exports 输出，正确来讲是没有 default  的，import advancedFormat from 'dayjs/plugin/advancedFormat' 与实际表意不符，这里是 esbuild 在处理 esm import cjs 时处理的不正确导致的，当前的话我们会先做一版回复原有的逻辑来兼容。后续大版本升级时会给出更好的解决方案。

**Comment by YSMJ1994** [comment]
@guoyunhe Fixed at 1.27.1, try again.
