### ISSUE TITLE
[Upload]Upload组件类型为card时，itemRender失效

### ISSUE THREAD

**Issue by kulelikule** [alibaba-fusion/next#4721]
### Component 
Upload

### Steps to reproduce
现象：Upload组件类型为card时，itemRender失效
排查原因：List组件没有传入itemRender属性，如下图
![image](https://github.com/alibaba-fusion/next/assets/5518809/51d79c69-73e3-4951-9e55-aa0a46a7f01b)

**Comment by YSMJ1994** [comment]
Same as #3098
