### ISSUE TITLE
[Overlay]Overlay v2 版本中使用Select点击子弹窗可能导致父弹窗消失

### ISSUE THREAD

**Issue by qiuxiadongyu** [alibaba-fusion/next#4724]
### Component 
Overlay

### Steps to reproduce
因为Select中选项面板弹层还是next-overlay-wrapper而不是next-overlay-wrapper v2，导致Overlay v2 版本中使用Select组件，点击选项面板时会导致父弹窗Overlay v2消失

![issue](https://github.com/alibaba-fusion/next/assets/63301184/bbcd4041-864f-4f32-a745-19354321a10f)

**Comment by YSMJ1994** [comment]
你是在浮层中放了个 Select，然后点击 Select 的下拉框导致 外层的浮层消失了吗

**Comment by qiuxiadongyu** [comment]
嗯，我在Popup v2中放置个子组件，子组件中包含Select，在点击Select的选项时Popup关闭了
![1705633434210](https://github.com/alibaba-fusion/next/assets/63301184/c730c5ba-454c-4d14-a9b6-add539b6f0a0)
![1705633520166](https://github.com/alibaba-fusion/next/assets/63301184/cf3fc613-bac9-44f7-bd36-99f3f00a382b)

**Comment by YSMJ1994** [comment]
方法1：给 Select配置 followTrigger
方法2：给 Popup 配置 safeNode ，指向 Select 的下拉弹层（safeNode={() => selectPopupContentEl}）

**Comment by qiuxiadongyu** [comment]
解决了，谢谢大佬
