### ISSUE TITLE
[Loading]Loading组件的ts问题

### ISSUE THREAD

**Issue by lilithyang2018** [alibaba-fusion/next#4725]
### Component 
Loading

### Steps to reproduce
1.27.2版本的@alifd/next/types/loading/index.d.ts文件中没有默认导出Loading这个class，导致引用了Loading组件的项目在ts build的时候会有以下错误提示
Public property 'Loading' of exported class has or is using name 'Loading' from external module

这个问题在1.26.37版本是不存在的

**Comment by eternalsky** [comment]
没有发现类似问题（刚在几个项目中也尝试 build 没有发现问题），Loading 这个 class 从逻辑上来讲，是不应该被导出的，默认导出的应该被 ConfigProvider.config 包裹之后的，请提供一下会出现此问题的 demo。

**Comment by lilithyang2018** [comment]
> 没有发现类似问题（刚在几个项目中也尝试 build 没有发现问题），Loading 这个 class 从逻辑上来讲，是不应该被导出的，默认导出的应该被 ConfigProvider.config 包裹之后的，请提供一下会出现此问题的 demo。

地址在这里
https://codesandbox.io/p/devbox/build-test-with-loading-djqgyz

可以确定的是1.26.37没有这个问题

**Comment by YSMJ1994** [comment]
> > 没有发现类似问题（刚在几个项目中也尝试 build 没有发现问题），Loading 这个 class 从逻辑上来讲，是不应该被导出的，默认导出的应该被 ConfigProvider.config 包裹之后的，请提供一下会出现此问题的 demo。
> 
> 地址在这里 https://codesandbox.io/p/devbox/build-test-with-loading-djqgyz
> 
> 可以确定的是1.26.37没有这个问题

@lilithyang2018 以前的类型是不准确的，组件的 Ref 类型请使用 React.ComponentRef<typeof Loading> 获取

**Comment by lilithyang2018** [comment]
了解
