### ISSUE TITLE
[Overlay]@alifd/next弹出层overly 死循环问题

### ISSUE THREAD

**Issue by JeremyCaoYu** [alibaba-fusion/next#4740]
### Component 
Overlay

### Reproduction link 
[申通内部系统 无法对外展示](申通内部系统 无法对外展示)

### Steps to reproduce
overly组件 calls setState inside componentWillUpdate or componentDidUpdate.导致select等相关组件选择时报错，影响线上使用

**Comment by JeremyCaoYu** [comment]
1.27.4版本开始出现的问题 就这几天

**Comment by yehuozhili** [comment]
同样的问题，已经回退了

**Comment by Maconzhang** [comment]
确实有问题，我的case是dialog中select一选中就触发导致页面白屏。
无法提供复现链接，是在用户电脑上出现，目测存在兼容性问题。已经通过回滚lock版本修复，目测所有继承overlay 的组件在handleposition的函数中有异常。
异常堆栈图：
![image](https://github.com/alibaba-fusion/next/assets/20869112/5e9235df-b8dc-4561-a31a-5b8c4b3ab6a9)

**Comment by JeremyCaoYu** [comment]
回退吧 已经生产事故了 我现在lock到1.26.x

**Comment by YSMJ1994** [comment]
latest tag 已指向 1.27.2
