### ISSUE TITLE
[TreeSelect]TreeSelect组件选中效果异常

### ISSUE THREAD

**Issue by mengyibo** [alibaba-fusion/next#4743]
### Component 
TreeSelect

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/14a215ad](https://riddle.alibaba-inc.com/riddles/14a215ad)

### Steps to reproduce
searchValue为空时，应该重置选中效果
重现步骤：
1、搜索过滤一下，任何选项都不选，展开到了搜索的数据；
2、删除searchKey，之前展开的还在展开

**Comment by YSMJ1994** [comment]
你的需求是否是在 输入 searchValue 时记录当前的展开节点，清空 searchValue 时恢复上一次展开的节点？

**Comment by mengyibo** [comment]
是的，数据源是远程搜索取到的，输入 searchValue 展开到叶子节点，清空 searchValue 时恢复到初始化的状态
