### ISSUE TITLE
[Cascader]Cascader在开启useVirtual后样式异常

### ISSUE THREAD

**Issue by shiwofeiwo** [alibaba-fusion/next#4749]
https://github.com/alibaba-fusion/next/assets/105789907/f86c508e-24b0-4ef5-9ebc-0f1f6cda69bb

### Component 
Cascader

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/src69y?file=%2Fsrc%2FApp.jsx%3A2%2C40)

### Steps to reproduce
来回切换第一列数据时，第二列数据会出现在第一列的下方而不是右侧

**Comment by Yuchaocheng** [comment]
是的，启用useVirtual后动态加载的item宽度超过了首次渲染时的列宽，就会导致该列掉下来。目前建议的解决方案是增加listStyle属性固定列宽
