### ISSUE TITLE
[Select]Select组件重复的option value导致的BUG

### ISSUE THREAD

**Issue by huarse** [alibaba-fusion/next#475]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.13.9

### Component
Select

### Environment
chrome last version

### Description

Select 组件的 dataSource 如果有相同 value 的 item，会导致下次 dataSource 更新后，还会保留一个之前重复的 item，且无法选择，会报错

![image](https://user-images.githubusercontent.com/3724927/54657614-16be4a00-4b05-11e9-9b78-ccc19c9044c5.png)

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/2c2251e7](https://riddle.alibaba-inc.com/riddles/2c2251e7)

### Steps to reproduce
dataSource 修改后，应该正常更新

**Comment by bindoon** [comment]
https://riddle.alibaba-inc.com/riddles/de71916  @youluna  menu的bug，有重复key的时候引起的

**Comment by youluna** [comment]
menu的更改已于1.13.10上线 @bindoon @huarse 看下这个问题是不是已经解决了

**Comment by bindoon** [comment]
fixed.
