### ISSUE TITLE
[TimePicker2]TimePicker2.RangePicker引入之后值为undefined

### ISSUE THREAD

**Issue by Azariasa** [alibaba-fusion/next#4764]
### Component 
TimePicker2

### Steps to reproduce
目前使用的fusion组件库版本为1.26.37
引入组件TimePicker2，使用时间区间组件时，提示 TimePicker2.RangePicker 值为undefined

引入方式为：
![image](https://github.com/alibaba-fusion/next/assets/5989227/bb1bae7a-36ac-4fb6-bb68-1b8462fee4a3)

**Comment by YSMJ1994** [comment]
未能复现你的问题 [Riddle Demo](https://riddle.alibaba-inc.com/riddles/9f59f82b)，可能是你的项目工程问题导致的
