### ISSUE TITLE
[DatePicker2]DatePicker 使用 trigger 自定义后，第二次选择的时间响应区不对

### ISSUE THREAD

**Issue by fenglshyun** [alibaba-fusion/next#4767]
### Component 
DatePicker2

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/fusion-next-template-forked-xmhhw7?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltdqtdfo00063b6kfv32oqdg%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltdqtdfo00023b6kdvese4wb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltdqtdfo00033b6kgzpyqolp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltdqtdfo00053b6kk052bx38%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltdqtdfo00023b6kdvese4wb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltdqtdfo00013b6khl33jc72%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522id%2522%253A%2522cltdqtdfo00023b6kdvese4wb%2522%252C%2522activeTabId%2522%253A%2522cltdqtdfo00013b6khl33jc72%2522%257D%252C%2522cltdqtdfo00053b6kk052bx38%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltdqtdfo00043b6kidu8lx04%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltdqtdfo00053b6kk052bx38%2522%252C%2522activeTabId%2522%253A%2522cltdqtdfo00043b6kidu8lx04%2522%257D%252C%2522cltdqtdfo00033b6kgzpyqolp%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltdqtdfo00033b6kgzpyqolp%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce
如标题和 codesandbox，我使用 trigger 自定义了一个组件，第一次选择时间的时候，起始时间和结束时间都响应正常，但是第二次选择时间的时候，第一个选择的时间反而是先选中的结束时间，再返回到起始时间，前后逻辑不一致。

**Comment by fenglshyun** [comment]
上面的 codeSandbox 如果打不开的话，请使用 https://codesandbox.io/p/sandbox/fusion-next-template-forked-xmhhw7?file=%2Fsrc%2Findex.js

**Comment by eternalsky** [comment]
这是因为 RangePicker 的 trigger 实际是有两个热区，begin 的热区是先选 begin，再选 end，而 end 的热区是先选 end，再选 begin。因为第一次选择后，已经进入选 end 的阶段，所以再次打开就只能是先 end 再 begin 了。而且 trigger 这里，目前没有传入 inputProps，也无法去像内置 trigger 一样，对接 onInputTypeChange，所以这里目前确实还无解。

通过优化的解决方案就是传入 inputProps  这样就可以对接 onInputTypeChange，实现这个效果。

**Comment by fenglshyun** [comment]
第一次选择完 end 之后，理论上响应区已经不再停留到 end 了。再次打开为啥没有走再从 begin 选择的逻辑

**Comment by eternalsky** [comment]
inputType 的变化是由 PanelChange 或者 triggerFocus 导致的，选择 end 后，这两个情况都不会触发，因此仍然停留在 end。正常内置 trigger 的话，在下次点击时必然命中某个热区 focus，切换到正确的 inputType 来。

这里我会提交一个 pr，让自定义 trigger 和内置 trigger 一样也可以拿到 inputProps，这样就可以模拟内置 trigger 的行为。
