### ISSUE TITLE
[TreeSelect]文档api归类非常不友好

### ISSUE THREAD

**Issue by AyawYuTing** [alibaba-fusion/next#4776]
### Component 
TreeSelect
### Feature Description
单选与多选 栏下：
代码例子绑定的onselect事件它自己也没定义过，组件api内也找不到onSelect事件说明。
![Uploading image.png…]()

全部组件都有的情况：组件属性归类不友好，事件和其他属性乱序排列，完全没有规律，找事件配置要反复翻。
![Uploading image.png…]()

**Comment by eternalsky** [comment]
图片裂了，看看是不是要重传一下
