### ISSUE TITLE
[Overlay]popup can show when press arrow key down

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#478]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Overlay

### Feature Description
triggerType="click" means the popup can show when you "click" "keyboard-space" "keyboard-enter" the trigger.

Wish to add prop of keyboard keycode, so that users can set the exact key they want. For example, arrow-down trigger the popup in Select

**Comment by jdkahn** [comment]
Resolved in https://github.com/alibaba-fusion/next/pull/499
