### ISSUE TITLE
[Calendar]shape为panel且showOtherMonth为false时，点击显示可跳转的month/year后，但是点击却无法跳转

### ISSUE THREAD

**Issue by shiwofeiwo** [alibaba-fusion/next#4782]
https://github.com/alibaba-fusion/next/assets/105789907/056e8dad-d69b-4663-95c7-c9b75818b990

### Component 
Calendar

### Reproduction link 
[https://codepen.io/zdgzdgzdg/pen/JjxovzY?editors=0010](https://codepen.io/zdgzdgzdg/pen/JjxovzY?editors=0010)

### Steps to reproduce
shape为panel，showOtherMonth为false后，点击其他year/month无法跳转是预期的行为吗

**Comment by Yuchaocheng** [comment]
showOtherMonth为false后，点击其他year/month无法跳转是预期行为。目前的问题是头部的前进后退以及模式切换依然可点击，这个算是bug需要解决
