### ISSUE TITLE
[Step]Step 组件需要控制 title content 宽度的能力

### ISSUE THREAD

**Issue by jz-wen** [alibaba-fusion/next#4785]
### Component 
Step
### Feature Description
Fusion是否有可能支持业务线调整Step的Title body With能力的接口。目前只能在DONE统一设置，但这个宽度对不同使用的业务/产品是不能符合预期的，需要业务线自己调整宽度。

**Comment by eternalsky** [comment]
如群聊沟通，Fusion 的组件样式细节，通过配置主题来完成。如果业务觉得某个主包不合适，可以建立一个新包，调整宽度。两个主题之间可以是继承关系。如果不希望建立新包，可以通过 className 来手动修改组件细节。
