### ISSUE TITLE
[DatePicker2]DatePicker2英文翻译不符合国际化规范

### ISSUE THREAD

**Issue by leaveLi** [alibaba-fusion/next#4788]
### Component 
DatePicker2

### Steps to reproduce
https://aliyuque.antfin.com/qiongji.lk/bz2s7u/lgrqydsohx23b836?singleDoc# 《DatePicker2英文翻译不符合国际化规范》

**Comment by eternalsky** [comment]
这个国际化规范的出处是哪里？

**Comment by eternalsky** [comment]
Calendar 的 locale 里没有在英文下设置 monthBeforeYear 为 true

**Comment by leaveLi** [comment]
> Calendar 的 locale 里没有在英文下设置 monthBeforeYear 为 true

除了这个问题，日期展示也未做翻译，有修复计划吗？

**Comment by eternalsky** [comment]
> > Calendar 的 locale 里没有在英文下设置 monthBeforeYear 为 true
> 
> 除了这个问题，日期展示也未做翻译，有修复计划吗？

可以另外提交 issue，如果合理，我们都是会排期修复的。
