### ISSUE TITLE
[DatePicker2]DatePicker2无法输入空格来输入时间

### ISSUE THREAD

**Issue by YunMeng99** [alibaba-fusion/next#4790]
### Component 
DatePicker2

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/63974a99](https://riddle.alibaba-inc.com/riddles/63974a99)

**Comment by wangw11056** [comment]
![Image](https://github.com/alibaba-fusion/next/assets/60127908/fb430b92-9b10-4dd5-abc9-ab33a296edb2)

我尝试通过一些 DatePicker2 props的配置，可以解决无法输入空格的问题



![Image](https://github.com/alibaba-fusion/next/assets/60127908/453ffc7d-2279-4e34-9530-2725672bba82)
