### ISSUE TITLE
[Tab]tab超出滑动的按钮被extra的内容遮盖住而无法操作

### ISSUE THREAD

**Issue by neoimale** [alibaba-fusion/next#481]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Tab

### Environment
xxx

### Reproduction link
[xxx](xxx)

### Steps to reproduce
tab超出滑动的按钮被extra的内容遮盖住而无法操作

**Comment by guanpu** [comment]
这个issue和 https://github.com/alibaba-fusion/next/issues/269 是重复的，我们已经在文档里加了标注
![image](https://user-images.githubusercontent.com/5867109/55157785-40781080-5198-11e9-81e2-23a2e753a0e9.png) 告知用户这两个功能无法同时使用。
这两个都用了tab-bar最右侧的部分，从设计上来说是互相冲突的特性，但因为都有很多的使用场景所以保留。组件本身不支持同时使用，但是用户可以很轻易地通过navStyle把tab-bar缩短一点为extra的内容腾地方，[DEMO地址](https://codesandbox.io/s/2vzln895jp)

**Comment by guanpu** [comment]
![image](https://user-images.githubusercontent.com/5867109/55158287-808bc300-5199-11e9-9acb-37b3ea0917df.png)
