### ISSUE TITLE
[NumberPicker]在iPad上数值组件单击无法导出键盘

### ISSUE THREAD

**Issue by xinghong12138** [alibaba-fusion/next#4812]
### Component 
NumberPicker

### Reproduction link 
[https://alifd.alicdn.com/demos-pages/@alifd/next/NumberPicker@1.25.51/@alifd/theme-2@0.4.4/index.zh-cn.html](https://alifd.alicdn.com/demos-pages/@alifd/next/NumberPicker@1.25.51/@alifd/theme-2@0.4.4/index.zh-cn.html)

### Steps to reproduce
在iPad上数值组件单击无法导出键盘，需要点击俩次才能导出键盘

**Comment by YSMJ1994** [comment]
ios 设备针对 touch 行为的问题，元素拥有 hover 样式的情况，第一次点击触发 hover，第二次才触发 click 和 focus 导致的。
解决方案：
组件使用媒体查询 `@media(hover:hover)` 添加 hover 样式

> https://drafts.csswg.org/mediaqueries/#hover

**Comment by eternalsky** [comment]
https://css-tricks.com/annoying-mobile-double-tap-link-issue/

**Comment by eternalsky** [comment]
仔细看了一下 number-picker 的设计，在 tablet 或者 phone 等用手指操作的场景，其实是出现 hover 出点击按钮的交互的。而应该强制为 normal 模式，按钮放在外侧（因为点击按钮太小，手指交互的场合不好点击），目前只在 device=phone 的时候有这个强制限定 type 的逻辑，后续应该加入 device=tablet 时也加入这个限定逻辑。
