### ISSUE TITLE
[List]dataSource的属性无法透传到renderItem

### ISSUE THREAD

**Issue by owenchen1004** [alibaba-fusion/next#4816]
### Component 
List

### Steps to reproduce
使用官方demo中的代码，

<img width="169" alt="image" src="https://github.com/alibaba-fusion/next/assets/56390399/11767137-fe2b-4a9a-b97d-6dcb5431475b">

<img width="221" alt="image" src="https://github.com/alibaba-fusion/next/assets/56390399/b45f8974-0242-4ef4-8b2c-8d8d713541a1">

<img width="440" alt="image" src="https://github.com/alibaba-fusion/next/assets/56390399/1c314a6f-e905-45bd-b12b-d7807e7efb75">

item无法获取到data的type，始终是unknown，所以item.list的获取会报错

**Comment by eternalsky** [comment]
item 确实是 unknown 的，因为 dataSource 是用户传入进来的，List 并没有限制 List 具体有哪些 key。实际是什么样的类型，只有用户自己知道，因此这里也是只能是用户自己指定类型。
