### ISSUE TITLE
[Table]使用 lock 时，表头 sort 行为异常

### ISSUE THREAD

**Issue by std4453** [alibaba-fusion/next#4821]
### Component 
Table

### Reproduction link 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/fusion-next-template-forked-89w4w7)

### Steps to reproduce
使用 Table 组件时，如果 columns 包含 lock: left 以及 sortable: true，排序行为异
常。

- 点击按钮不会清除非锁列表头的排序，反之亦然

如果同时还会在表格上切换 loading: true，则排序按钮不会展示为蓝色，不符合预期。

初步排查到是因为生成锁列的 Table 的时候没有传入 Table 自己的 sort state。

**Comment by eternalsky** [comment]
可以试一下 StickyLock

**Comment by std4453** [comment]
@eternalsky 非 StickyLock 的表格 bug 目前是不修复了吗？

**Comment by eternalsky** [comment]
> @eternalsky 非 StickyLock 的表格 bug 目前是不修复了吗？

如果 Sticky 就可以解决，为什么非要寻求非 Sticky 的修复呢~ Sticky 本来就是更新的方案，原方案没有直接替换为 Sticky 是为了考虑边界情况的兼容。
