### ISSUE TITLE
[Form]form还要使用field管理，反人类操作

### ISSUE THREAD

**Issue by ming001** [alibaba-fusion/next#4823]
### Component 
Form

**Comment by eternalsky** [comment]
antd 也是类似的方式来管理的，因为表单值的操作很多，包括设置、重置、校验等等，不通过一个对象实例来管理感觉也没有更简单的办法。如果你有，可以提 RFC，我们可以考虑支持。如果你只是为了赋值，也可以使用 Form 的 value 属性，你不传入 value 的时候，Form 内部自己也会初始化 Field，可以通过 saveField 回调拿到这个内部自己初始化的。

**Comment by lxzy-yun** [comment]
建议使用formily2.0

**Comment by eternalsky** [comment]
> 建议使用formily2.0

formily 也要初始化 form 实例，在这个 issue 讨论的范围内没有看到有什么不同。

**Comment by ming001** [comment]
我想使用的场景很简单，给表格一个初始值，用户填写信息后，提交给接口，这么简单的动作，还要再初始化一个field，太复杂了

**Comment by eternalsky** [comment]
> 我想使用的场景很简单，给表单一个初始值，用户填写信息后，提交给接口，这么简单的动作，还要再初始化一个field，太复杂了

看上面的第一条回复，可以不用初始化 field。
