### ISSUE TITLE
[Select]Select组件怎么覆盖无障碍操作

### ISSUE THREAD

**Issue by Lu9911** [alibaba-fusion/next#4842]
### Component 
Select
### Feature Description
使用Select组件时，想通过按下enter键触发一些其他操作，但多选时按下enter会更改其内容

**Comment by eternalsky** [comment]
先描述一下你的业务场景，看看是否合理？
所有的内置键盘操作都是默认执行的，属于交互体验的一部分，理论上不能被覆盖。
