### ISSUE TITLE
[Tree]【Tree】组件如何实现点击加载更多

### ISSUE THREAD

**Issue by chi-gao** [alibaba-fusion/next#4844]
### Component 
Tree
### Feature Description
对于目录树大数据量数据加载，要同时使用异步加载和分页加载，比如第一次默认加载100条，后续通过点击“加载更多”继续加载更多数据。目前问题有两个：
1. 如何在树节点中渲染加载更多按钮？
2. 点击“加载更多”触发父节点的loading效果；
3. 是否有类似场景的demo？
期待大佬的回复

**Comment by eternalsky** [comment]
TreeNode 并不限制具体里面渲染的内容，你可以单独找一个 treeNode 去渲染”加载更多“。触发父节点 loading 目前没什么办法，但一般加载更多是原地 loading，没必要触发父节点 loading。

**Comment by chi-gao** [comment]
收到收到，感谢[送花]
