### ISSUE TITLE
[Message]Message组件样式问题(icon和文字没有对齐)

### ISSUE THREAD

**Issue by weifengHuang** [alibaba-fusion/next#4846]
### Component 
Message

### Reproduction link 
https://fusion.design/pc/component/message?themeid=2

### Steps to reproduce
从第一个demo就能看到，icon和后面的文字在高度上没有居中对齐

**Comment by luolin-ck** [comment]
此问题已在https://github.com/alibaba-fusion/next/pull/4636上修复，
相关issue标题： [Message]没有标题时，图标与文字没有垂直对齐 #3910 
相关issue地址： https://github.com/alibaba-fusion/next/issues/3910

**Comment by luolin-ck** [comment]
已经在 1.27.x 版本中解决。请升级至相应版本体验。
