### ISSUE TITLE
随便点了下官网示例就有bug。。。

### ISSUE THREAD

**Issue by tmzdy888** [alibaba-fusion/next#4883]
### Reproduction link 
[https://fusion.design/pc/component/virtual-list?themeid=2](https://fusion.design/pc/component/virtual-list?themeid=2)

### Steps to reproduce
就是滚动，拖滚动条就复现了，edge浏览器

![screenshot20240710](https://github.com/alibaba-fusion/next/assets/27399806/921767fb-670d-4dcb-988c-bbfa9f38aabf)

**Comment by eternalsky** [comment]
之前的 demo 比较陈旧，最近更新到了最新版，现在的版本还有这个问题吗
