### ISSUE TITLE
[Icon]页面icon白屏

### ISSUE THREAD

**Issue by zahngying** [alibaba-fusion/next#4889]
### Component 
Icon

### Reproduction link 
[https://fusion.design/pc/component/icon?themeid=2](https://fusion.design/pc/component/icon?themeid=2)

### Steps to reproduce
官网看不到icon信息，白屏啦 点击展示代码也没效果

**Comment by eternalsky** [comment]
正在解决中，临时可以先看这个，https://mc.fusion.design/demos/comp_groups/@alifd/next@1.26.x/icon?theme=@alifd/theme-1@1.0.0&bgColor=%23ffffff

**Comment by eternalsky** [comment]
已解决
