### ISSUE TITLE
[Upload]图片上传组件只读状态添加文件下载功能

### ISSUE THREAD

**Issue by linianchuan** [alibaba-fusion/next#4894]
### Component 
Upload
### Feature Description
新功能需求：图片上传组件在只读状态下提供文件下载功能
使用场景：在管理侧用户有时因业务须对凭证类图片进行收集，需在只读状态下提供下载功能

**Comment by eternalsky** [comment]
上传组件支持 itemRender，可以自定义加入下载功能。如需继续跟进，比如 itemRender 不支持你的场景，可以细化 issue 描述，并附带复现链接。
