### ISSUE TITLE
[DatePicker2]Input DatePicker is not work correctly with "enter"

### ISSUE THREAD

**Issue by vuquangthinh** [alibaba-fusion/next#4896]
### Component 
DatePicker2

### Reproduction link 
[https://gist.github.com/vuquangthinh/f7e9918a426e97989145b277160331c1](https://gist.github.com/vuquangthinh/f7e9918a426e97989145b277160331c1)

### Steps to reproduce
I write above of code, 
Type "12/02/2023". as expect (format DD/MM/YYYY)
Press enter to update
Expect: close datepicker modal and keep value input: 12/02/2023
Actual: it convert to 02/12/2023

**Comment by eternalsky** [comment]
复现 demo：https://codesandbox.io/p/sandbox/fusion-yan-zheng-forked-jv5tyy?file=%2Fsrc%2Findex.js%3A17%2C24
