### ISSUE TITLE
Tree 组件【实现搜索】部分Demo代码报错

### ISSUE THREAD

**Issue by CoderSerio** [alibaba-fusion/next#4899]
### Reproduction link 
[https://fusion.design/pc/component/tree?themeid=2#searchTree-container](https://fusion.design/pc/component/tree?themeid=2#searchTree-container)

### Steps to reproduce
复现步骤：
1. 打开重现链接即可
现象：
1. 预览demo没有正常加载，而是展示了报错信息：
SyntaxError: Unexpected token (94:29)
90 :         expandedKeys: [...matchedKeys],
91 :         autoExpandParent: true,
92 :       },
93 :       () => {
94 :         this.treeRef.current?.getInstance?.().scrollFilterNodeIntoView();

**Comment by eternalsky** [comment]
之前 demo 没更新，现在应该好了
