### ISSUE TITLE
[Tree]checkBox取消选中后样式异常

### ISSUE THREAD

**Issue by lllcccwww** [alibaba-fusion/next#4907]
### Component 
Tree

### Reproduction link 
[https://fusion.design/pc/component/tree?themeid=2](https://fusion.design/pc/component/tree?themeid=2)

### Steps to reproduce
官网中例如Table、Tree有使用到checkBox的组件都有此类问题。问题复现：先选中一个checkbox，然后再取消，checkbox会带有hover时的样式，只有点击其他位置后，背景色才会去除。
![image](https://github.com/user-attachments/assets/720db1e5-cce6-4b93-8a8a-973851013722)

**Comment by eternalsky** [comment]
这不是 hover 样式，而是 focus 样式

**Comment by lllcccwww** [comment]
> 这不是 hover 样式，而是 focus 样式

哦哦。那当取消选中后，focus 样式也应该要取消掉吧

**Comment by eternalsky** [comment]
> > 这不是 hover 样式，而是 focus 样式
> 
> 哦哦。那当取消选中后，focus 样式也应该要取消掉吧

focus 是聚焦状态，肯定是失焦时才会取消。你只是反选并没有失焦，考虑一下用键盘的人。
