### ISSUE TITLE
[Dropdown]Dropdown中嵌套Menu及SubMenu时，点击SubMenu触发关闭

### ISSUE THREAD

**Issue by DanmoSAMA** [alibaba-fusion/next#4911]
### Component 
Dropdown & Menu

### Reproduction link 
[https://codepen.io/Danmoits/pen/jOjYELa?editors=0010](https://codepen.io/Danmoits/pen/jOjYELa?editors=0010)

### Steps to reproduce
一步一步点开Dropdown和Menu，点击步骤：Hello->1->2，点了2以后，期望可以显示3，但是现在的情况是，会显示一下3，然后整个Dropdown就关闭了。
找雪帝看了一下，她提出了一种不会导致Dropdown关闭的解决方案，但是并不能做到横向展开。

防止Demo的链接点不开，这里提供一下代码，复制到空白页面中即可运行。
```ts
import { Menu, Dropdown } from '@alifd/next';

const { SubMenu, Item, PopupItem } = Menu;

ReactDOM.render(
  <div style={{ width: 400, height: 200, backgroundColor: '#bfa' }}>
    <Dropdown followTrigger align="bl tl" trigger={<div>Hello</div>}>
      <Menu mode="popup">
        <SubMenu label="1">
          <PopupItem label="2" triggerType="click">
            3
          </PopupItem>
        </SubMenu>
      </Menu>
    </Dropdown>
  </div>
, mountNode);
```

**Comment by eternalsky** [comment]
这是因为浮出来的 subMenu 和 item 不是渲染在 dropdown 里的，dropdown 不知道这些元素点击后不应该关闭。可以给 dropdown 设置 safeNode 来告知。如下方 demo 
https://codepen.io/eternalsky/pen/PorQXvz?editors=0010

**Comment by DanmoSAMA** [comment]
已解决，谢谢
