### ISSUE TITLE
[Type]NumberPicker和Form.Item的placeholder类型没有

### ISSUE THREAD

**Issue by xmsz-stu** [alibaba-fusion/next#4922]
### Component 
NumberPicker/Form.Item
### Feature Description
placeholder类型的类型没有了

**Comment by xmsz-stu** [comment]
还有Affix
<img width="732" alt="image" src="https://github.com/user-attachments/assets/08556a26-f31f-4847-8cd0-0b048f69c4cb">

**Comment by eternalsky** [comment]
Affix 这个问题确认了，近期会发版修复。NumberPIcker 新版确认是有 placeholder 的，请提供复现链接。Form.Item 不记得有 placeholder 这个属性。

**Comment by xmsz-stu** [comment]
> Affix 试了一下没有 children 不存在的问题。NumberPIcker 新版确认是有 placeholder 的，以上两者请提供复现链接。Form.Item 不记得有 placeholder 这个属性。

Affix估计是react18下有问题
NumberPickerplaceholder有实现，但是类型没了

**Comment by eternalsky** [comment]
> > Affix 试了一下没有 children 不存在的问题。NumberPIcker 新版确认是有 placeholder 的，以上两者请提供复现链接。Form.Item 不记得有 placeholder 这个属性。
> 
> Affix估计是react18下有问题 NumberPickerplaceholder有实现，但是类型没了

类型也是有的

**Comment by eternalsky** [comment]
> > Affix 试了一下没有 children 不存在的问题。NumberPIcker 新版确认是有 placeholder 的，以上两者请提供复现链接。Form.Item 不记得有 placeholder 这个属性。
> 
> Affix估计是react18下有问题 NumberPickerplaceholder有实现，但是类型没了

Affix 的问题请提供复现 demo
