### ISSUE TITLE
[Table]Table 表格组件支持展开的 Expand 行锁列渲染

### ISSUE THREAD

**Issue by ggeyyuangc** [alibaba-fusion/next#4940]
### Component 
Table
### Feature Description
Table 表格组件主数据行的最右侧 Column 锁列，需要支持其展开的额外渲染行也最右侧 Column 锁列，并和主行同步滑动展示，现在额外渲染行最右侧 Column 锁列后，会被遮挡无法显示出来。
可复现问题的codepen：https://codepen.io/shibie/pen/vYqgZdp
![image](https://github.com/user-attachments/assets/d7032ad9-e983-4e30-8652-79010a4e1564)

**Comment by eternalsky** [comment]
可以使用 StickyLock 看下是不是想要的效果

**Comment by ggeyyuangc** [comment]
也试过StickyLock，并不符合期望...用了StickyLock后主表格和扩展表格就没有联动了，StickyLock似乎支持额外渲染行不太友好
![image](https://github.com/user-attachments/assets/3463e7ab-a84a-4a7f-a1da-fbc4ecb24140)

**Comment by lessonli** [comment]
一直没有解决呀

**Comment by lessonli** [comment]
这个还修复吗
