### ISSUE TITLE
[Select]Select开启useVirtual后value返回值不正确

### ISSUE THREAD

**Issue by xmsz-stu** [alibaba-fusion/next#4942]
### Component 
Select

### Steps to reproduce
https://fusion.design/pc/component/select?themeid=2#virtualSelect-container

<img width="192" alt="image" src="https://github.com/user-attachments/assets/7d055fc1-9b73-4fc1-a860-5f4a40dd5d49">

**Comment by eternalsky** [comment]
fix in 1.27.26
