### ISSUE TITLE
[Select]select 开启无限滚动useVirtual属性，选值出现严重的bug

### ISSUE THREAD

**Issue by 1119879311** [alibaba-fusion/next#4951]
### Component 
Select

### Reproduction link 
[https://fusion.design/pc/component/select?themeid=2#virtualSelect-container](https://fusion.design/pc/component/select?themeid=2#virtualSelect-container)

### Steps to reproduce
根据官方文档示例，使用useVirtual 属性开启大数据无限滚动
进行选择值的选择，select 输入框出现错误值，额外加多 “.$” 的字符
属于严重bug 
另外吐槽一下，这个组件库超级难用，而且性能差，bug 也非常多

**Comment by eternalsky** [comment]
这个问题在 9 月 20 日的版本里已经修复了。详见 changelog
