### ISSUE TITLE
[DatePicker2]日期组件outputFormat 参数无效，没有日期返回对应格式的数据，还是返回了日期对象

### ISSUE THREAD

**Issue by 1119879311** [alibaba-fusion/next#4952]
### Component 
DatePicker2

### Reproduction link 
[https://fusion.design/pc/component/date-picker-2?themeid=2#selectRangeDates-container](https://fusion.design/pc/component/date-picker-2?themeid=2#selectRangeDates-container)

### Steps to reproduce
根据官方文档示例，并没有示例，使用outputFormat  属性，并没有生效，还是返回了日期对象dayjs
这里吐槽一下，很多属性api 没有使用示例，太坑了，建议以修复bug 和文档维护为主吧

**Comment by eternalsky** [comment]
你给的这个复现链接里并没有使用 outputFormat，无法确认你的问题。我自己试了一下，是会返回指定的 outputFormat 的。
<img width="610" alt="截屏2024-10-12 17 48 50" src="https://github.com/user-attachments/assets/ba022751-566e-4621-ab58-b0e98c49b13f">
不可能每个 api 都提供一个示例，有些示例是结合了多个 api 的，有的 api 是一眼就能懂的，也不一定会单独提供。
