### ISSUE TITLE
[Search]search组件添加popupContent属性后输入框无法敲空格了

### ISSUE THREAD

**Issue by smancang** [alibaba-fusion/next#500]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.13.9

### Component
Search

### Environment
mac chrome

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/a974cf2f](https://riddle.alibaba-inc.com/riddles/a974cf2f)

### Steps to reproduce
search组件添加popupContent属性后输入框无法敲空格了

**Comment by tao1991123** [comment]
`<Select.AutoComplete popupContent={<div />}/> `
也会有这个问题 需要@bindoon 帮忙看看
