### ISSUE TITLE
[Table]Table组件自定义表头单元格props

### ISSUE THREAD

**Issue by fanwww** [alibaba-fusion/next#5005]
### Component 
Table
### Feature Description
类似于设置表格内容单元格样式的cellProps,有没有headerCellProps属性,用来设置表头某一个单元格props,包括支持级联表头单元格设置

**Comment by zyliang96** [comment]
现在Table.Column 是支持透传属性的，className、style、一些事件的注册的，对于的问题中的级联表头单元格设置是怎样的效果能说明一下吗？最好有一个直观的例子

**Comment by fanwww** [comment]
> 现在Table.Column 是支持透传属性的，className、style、一些事件的注册的，对于的问题中的级联表头单元格设置是怎样的效果能说明一下吗？最好有一个直观的例子

在hansontable配置了级联表头的颜色
![image](https://github.com/user-attachments/assets/3735caca-1643-4611-95be-b64999233df8)
想要在table组件回显
![image](https://github.com/user-attachments/assets/1b5b16f8-e86c-470a-9199-13b08168d4bb)


之前试了在Table.ColumnGroup直接设置style无效,现在采用的方案是在title属性上设置
![image](https://github.com/user-attachments/assets/6b57feb6-92fc-4f80-9125-669359e9acca)

**Comment by fanwww** [comment]
> 现在Table.Column 是支持透传属性的，className、style、一些事件的注册的，对于的问题中的级联表头单元格设置是怎样的效果能说明一下吗？最好有一个直观的例子

刚才试了一下 是支持style穿透的,估计是之前只找了headerCellProps方法,没有尝试用style属性穿透

**Comment by zyliang96** [comment]
我在官网的1.27.x的版本上试了一下，Table.ColumnGroup 直接设置style 是生效的，你使用的版本是多少呢？

**Comment by fanwww** [comment]
> 我在官网的1.27.x的版本上试了一下，Table.ColumnGroup 直接设置style 是生效的，你使用的版本是多少呢？

version: "1.26.4"
![image](https://github.com/user-attachments/assets/22224059-ec8c-47df-8e9e-8d37fd35479d)

**Comment by zyliang96** [comment]
1.26.4我本地试了也没有问题，你再确定一下你本地的代码吧

**Comment by fanwww** [comment]
> 1.26.4我本地试了也没有问题，你再确定一下你本地的代码吧

好，那我就把这个议题关掉了
