### ISSUE TITLE
[Nav]【Nav】nav组件中的SubNav属性noIcon和selectable没办法同时存在

### ISSUE THREAD

**Issue by Super-Rz** [alibaba-fusion/next#5006]
### Component 
Nav

### Steps to reproduce
SubNav当selectable为true时， noIcon设置无效

**Comment by zyliang96** [comment]
在官网上试了一下没有复现，麻烦提供一下复现信息

**Comment by Super-Rz** [comment]
![image](https://github.com/user-attachments/assets/78fa0dfb-1a9f-4175-a78b-50c8b45555ca)
使用官网demo，修改以下代码，主要增加了selectable和noIcon
 <SubNav key="sub-nav-1"label="Sub Nav 1" selectable noIcon>
      <Item key="1">Item 1</Item>
  </SubNav>

**Comment by Super-Rz** [comment]
![Uploading 截屏2024-12-31 15.50.57.png…]()

**Comment by Super-Rz** [comment]
![截屏2024-12-31 15 50 57](https://github.com/user-attachments/assets/ec90aff2-0f4b-4d1a-92ea-a1ea207eb304)

**Comment by zyliang96** [comment]
Nav 的 mode 为 popup 并且 triggerType 为 click的情况下，是SubNav 默认带icon的，因为如果不带Icon，在交互上同一个click事件会同时出发选中和展示这种是不合理的
