### ISSUE TITLE
[Select]建议新增一个 triggerRender 之类的方法

### ISSUE THREAD

**Issue by huarse** [alibaba-fusion/next#512]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Select

### Feature Description
- 需求：mode="multiple" 的时候，选择多个后 input 会被撑得很长，希望能够自定义里面值的显示，比如 AAA,BBB... 或者 AAA,BBB 等 10 项

- `Overlay` 可以自定义显示的弹层，但是不能自定义多选时 trigger 的表现 （valueRender是改 input 里面的值的显示）

**Comment by huarse** [comment]
最终的实现效果可以参考：

http://riddle.alibaba-inc.com/riddles/d8d15b43

**Comment by bindoon** [comment]
![image](https://user-images.githubusercontent.com/5189853/56578212-a45af100-65ff-11e9-81e5-4ae6e2f27af2.png)

目前在实现这个feature，是否满足你的述求呢？

**Comment by bindoon** [comment]
feature 已经实现，应该满足你的需求，不再额外增加api了
