### ISSUE TITLE
[Progress]Progress支持进度条宽度自定义，轨道背景颜色自定义

### ISSUE THREAD

**Issue by AliSnowaroma** [alibaba-fusion/next#529]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Progress

### Feature Description
环形进度自定义

**Comment by jdkahn** [comment]
Is it sufficient to have 3 sizes of circle progress bar width? These would be small, medium, and large

**Comment by jdkahn** [comment]
@AliSnowaroma Are you expecting to control the size using the theme configuration or is small, medium, large react properties enough?

**Comment by AliSnowaroma** [comment]
这是来自QQ邮箱的自动回复邮件。您好，邮件已收到，谢谢
