### ISSUE TITLE
[Transfer]窄屏下样式会出问题

### ISSUE THREAD

**Issue by janryWang** [alibaba-fusion/next#530]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

![image](https://user-images.githubusercontent.com/4060976/55318679-e7fd8780-54a5-11e9-8f32-ce50c496303a.png)

### Component
Transfer

### Environment
mac

### Reproduction link
[暂无](暂无)

### Steps to reproduce
系统屏幕窄的时候会出现区块下移

**Comment by mark-ck** [comment]
这个问题先暂时关闭了哈，推荐通过跨端方案来解决
