### ISSUE TITLE
[Range]如果Range在next-medium这个class内部会造成样式问题

### ISSUE THREAD

**Issue by janryWang** [alibaba-fusion/next#531]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

![image](https://user-images.githubusercontent.com/4060976/55319348-424b1800-54a7-11e9-9915-49b24c564e99.png)

### Component
Range

### Environment
mac

### Reproduction link
[暂无](暂无)

### Steps to reproduce
样式贴边

**Comment by guanpu** [comment]
I think it is fixed at https://github.com/alibaba-fusion/next/pull/505 and has been released, would you try with latest version?

**Comment by janryWang** [comment]
I found it already fixed. thx
