### ISSUE TITLE
[Select]搜索框内还没输入搜索词时，希望不要出现下拉框

### ISSUE THREAD

**Issue by kreja** [alibaba-fusion/next#535]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Select

### Feature Description
http://riddle.alibaba-inc.com/riddles/96eacad0 

这是来自官网的 demo，目前鼠标 focus 到输入框中，就会出现下拉框显示“无选项”。此时还没有输入任何关键词，希望不出现下拉框。
      
![image](https://user-images.githubusercontent.com/7478555/55381028-98c26000-5554-11e9-84ff-1e826d47bef4.png)

**Comment by bindoon** [comment]
新增api:  hidePopupNoOption
