### ISSUE TITLE
[Table]Disable select all checkbox

### ISSUE THREAD

**Issue by cwtuan** [alibaba-fusion/next#537]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Table

### Feature Description

Need a api to make the select-all checkbox disabled.

![image](https://user-images.githubusercontent.com/3455798/55392229-71c45800-556d-11e9-816b-828e392bd81a.png)

**Comment by youluna** [comment]
see #313
