### ISSUE TITLE
[Dialog]Alert dialog top padding does not match Dialog top padding

### ISSUE THREAD

**Issue by jdkahn** [alibaba-fusion/next#538]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.13.10

### Component
Dialog

### Environment
Chrome Version 73.0.3683.86

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/d44808f7](https://riddle.alibaba-inc.com/riddles/d44808f7)

### Steps to reproduce
Actual: 
Padding on top of Dialog.alert and Dialog.confirm components between top of the dialog and the Alert title does not match the padding for Dialog.show or when using Dialog component directly. 

Expect:
Top padding for all Dialog types should be consistent.

**Comment by youluna** [comment]
https://github.com/alibaba-fusion/next/pull/560
