### ISSUE TITLE
[Upload]beforeUpload 不能完全进行校验

### ISSUE THREAD

**Issue by abnerlinan** [alibaba-fusion/next#545]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Upload

### Feature Description
1.希望 beforeUpload 入参添加 files, 用于校验上传文件是否超出 limit 限制

**Comment by tao1991123** [comment]
暂不支持, 目前 upload的api参数已经够多 
校验limit的能力可以通过其他方式实现
