### ISSUE TITLE
[Select]autocomplete 默认值无效 & select 和 autocomplete 覆盖问题

### ISSUE THREAD

**Issue by ifibercc** [alibaba-fusion/next#558]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.13.12

### Component
Select

### Environment
chrome

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/591d7896](https://riddle.alibaba-inc.com/riddles/591d7896)

### Steps to reproduce
1. autocomplete next 默认给了"off"属性, 该值并不能关闭autocomplete, https://developer.mozilla.org/zh-CN/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
2. 如果在启用了showSearch的select中, autocomplete会覆盖掉 select 的 option, 开发时不注意很难模拟用户情况

**Comment by ifibercc** [comment]
update reproduction link and screenshot
 https://riddle.alibaba-inc.com/riddles/207a79bb
![image](https://user-images.githubusercontent.com/13199426/55778950-e0a63180-5ad6-11e9-9efa-d963d1fae1b0.png)

**Comment by Heluwe** [comment]
Select组件中可以直接使用原生input的autoComplete属性进行设置，参考 [MDN](https://developer.mozilla.org/zh-CN/docs/Web/Security/Securing_your_site/Turning_off_form_autocompleti)
，对于设置为"off"不生效的情况，采取对autoComplete值随机填充的方式禁用。
对于用户账号密码的自动填充，通过前一种方式可能无效，提供一个解决方法，对于用户名、密码字段初始设为readOnly，可以阻止浏览器的自动填充，聚焦后移除该属性。
