### ISSUE TITLE
[Table] 虚拟滚动不同高的行展示会有空隙

### ISSUE THREAD

**Issue by kreja** [alibaba-fusion/next#574]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Table

### Environment
chrome

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/7a35fd87](https://riddle.alibaba-inc.com/riddles/7a35fd87)

### Steps to reproduce
如果一开始就渲染出不同行高的话是没问题的，但是数据变化后才变成不同行高，底部就会有空隙。
![image](https://user-images.githubusercontent.com/7478555/56021271-970a5080-5d3b-11e9-86d7-d127eef2a965.png)

**Comment by weinianyang** [comment]
新版时alifd，没复现问题。建议使用alifd
