### ISSUE TITLE
[Select]下拉框多选时样式增强

### ISSUE THREAD

**Issue by soulcm** [alibaba-fusion/next#576]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Select

### Feature Description

![image](https://user-images.githubusercontent.com/5706155/56112179-d8456f00-5f8c-11e9-9de0-7a205f9b9c16.png)

下拉框多选时，若选择项太多，框的高度会被撑高，在表单或搜索项等排版上会很难看，能否在这块样式上统一进行些优化，CascaderSelect/TreeSelect同样有这个问题

**Comment by soulcm** [comment]
![image](https://user-images.githubusercontent.com/5706155/58391328-0926c280-8068-11e9-871d-45ff0d3da58e.png)
这个是0.x上我们用样式自己hack了的形式，可以参考下

**Comment by youluna** [comment]
补充：期望 TreeSelect和CascaderSelect 同样需要支持

**Comment by bindoon** [comment]
初步思考：<Select mode=multiple 模式下  />  增加 api `nowrap`，实现超出的元素隐藏能力
