### ISSUE TITLE
[Table]表格固定列（锁列）的设置项能否改为不用设置固定列宽

### ISSUE THREAD

**Issue by Z3FisherX** [alibaba-fusion/next#582]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Table

### Feature Description
现有Table组件使用固定列功能时需要指定每一列的列宽，对于有些数据不能很好的展示，能否改为设置表格总体的宽度或者滑动的宽度
有些场景下固定列宽并不适合表格需要展示的数据

**Comment by youluna** [comment]
指定每列的列宽是锁列的必要条件。

没有列宽的限制table会按照浏览器默认渲染行为在横向上自动撑开均匀分布。
