### ISSUE TITLE
[Button]please provide away to get button without any style

### ISSUE THREAD

**Issue by justnewbee** [alibaba-fusion/next#585]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Button

### Feature Description
button has style, yet more importantly, it has behavior

and in some cases, it is behavior we care about, and want to style it our own way

if we have to do style overwriting, we need to deal with css priority (which is very fragile if a new version has changed it)

so please provide a way to do so

for example, type="naked" and a button that has no predefined style at all

----

Button 不仅具有样式，更具有行为

很多场景，我们只希望用 button 的行为，而样式我们自己来定，如果用了带样式的 button 就需要各种样式覆盖，各钟优先级考虑，非常难受

希望提供 type="naked" 配置，让我可以得到「裸」的组件，不具有任何

**Comment by myronliu347** [comment]
这样的情况 原生的button标签更加适合你,
关于样式覆盖的问题，首先设计师先在fusion站点上配置一套主题，前端直接使用该主题即可，这样就不需要覆盖样式了。

**Comment by yanwii** [comment]
遇到同样的问题，全局配置了主题，为什么Button自己的main.scss优先级更高？是我打开方式有问题吗
