### ISSUE TITLE
[Tab]tab组件官网一个效果问题和shape="capsule"的切换抖动问题

### ISSUE THREAD

**Issue by shaojun427** [alibaba-fusion/next#586]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.13.13

### Component
Tab

### Environment
chrome 73.0.3683.103

### Reproduction link
[https://fusion.design/component/basic/tab](https://fusion.design/component/basic/tab)

### Steps to reproduce
1、官网demo默认有一个transform: translate3d(20px, 0px, 0px);tab点击切换的时候会有缩进的效果
2、shape="capsule"的时候切换会有抖动

**Comment by guanpu** [comment]
For issue1: it's related with animation, and you can find draft fix here: https://github.com/guanpu/next/commit/baaf590696b4c4d71349b56f03b7d2fb9a4f4eff
issue 2: fixed at https://github.com/alibaba-fusion/next/pull/578

**Comment by guanpu** [comment]
> 什么时候可以修复呢，目前我用的是1.14.0版本
已合并，今晚会发

**Comment by guanpu** [comment]
已发布，关闭此issue
