### ISSUE TITLE
[MenuButton]customize icon

### ISSUE THREAD

**Issue by justnewbee** [alibaba-fusion/next#587]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
MenuButton

### Feature Description
1. i need to customize the icon to something else
2. when label is not there, the icon shall not have a left margin

**Comment by myronliu347** [comment]
First use customize icon & style should be in fusion.design, You can create a theme to set icon or label left margin.
Of course, you can override css to change style or icon
