### ISSUE TITLE
[Message]能增加notification组件吗

### ISSUE THREAD

**Issue by dieslrae** [alibaba-fusion/next#601]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Message

### Feature Description
目前的需求需要notification组件,请问能新增notification组件吗

**Comment by myronliu347** [comment]
目前message能够应付所有消息提示上的功能，请问对notifcation的功能有啥需求

**Comment by dieslrae** [comment]
> 目前message能够应付所有消息提示上的功能，请问对notifcation的功能有啥需求

跟antd的notification一样,可以再左上或者左下弹出,然一个比较大的内容展示,多个都列出来

**Comment by myronliu347** [comment]
Fixed  1.18.3
