### ISSUE TITLE
[Overlay]make it work on ipad (support touch events)

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#606]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Overlay

### Feature Description
triggerType click should work on ipad/iphone
Overlay does not dismiss on document body click

**Comment by jdkahn** [comment]
Resolved By https://github.com/alibaba-fusion/next/pull/607
