### ISSUE TITLE
[Button]button shall support component div and span

### ISSUE THREAD

**Issue by justnewbee** [alibaba-fusion/next#611]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Button

### Feature Description
`<a> cannot contain <a>`
`<button> cannot contain <button>`

and sometimes, considering a11y, we need to put a 'button' inside an `<a>` or` <button>`
that is when we need to use component: span
it is practically ok now, however, a proptype error is yield..

hope to put div and span in component oneOf list

**Comment by myronliu347** [comment]
Button support a11y ,If you use `a` , you can set role="button", I don`t  know why need to put a `button`
