### ISSUE TITLE
[Input]Input.TextArea 的 cutString 在特殊情况下失效

### ISSUE THREAD

**Issue by Cyrilszq** [alibaba-fusion/next#620]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.14.1

### Component
Input

### Environment
mac/chrome/mac自带输入法

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/new](https://riddle.alibaba-inc.com/riddles/new)

### Steps to reproduce
使用 Input.TextArea 并设置了 maxLength = 10，当使用中文输入法时，输入超出 10 个字符时不要按空格，而是让 Input.TextArea 失焦，此时在输入法中的文字可以成功显示在输入框内。这种特殊情况在使用 Input 时不会触发。

**Comment by Cyrilszq** [comment]
发现是 React 的问题，和组件无关。

**Comment by Cyrilszq** [comment]
复现gif: 
![bug](https://user-images.githubusercontent.com/17585588/56946121-d8806580-6b5b-11e9-8840-e372f2384809.gif)

react 中的 maxLength 配合 value 使用时，行为和原生浏览器不太一致：https://codepen.io/cyrilszq-the-bold/pen/ZZZdVY

是否考虑使用 composition event 在组件层面修复这个问题？

**Comment by youluna** [comment]
@Cyrilszq it's by design.
组件的input maxLength不会修改、切割用户输入的字符串，只是提醒。

如果切割的需求，你可以通过受控，在业务层面处理哈，如果还有问题可以新开一个issue讨论
