### ISSUE TITLE
开发环境热更新的时候缺少某些控件的css

### ISSUE THREAD

**Issue by gooddaddy** [alibaba-fusion/next#626]
import {Icon,Progress} from '@alifd/next';
//import '@alifd/next/lib/progress/style'  //如果不加这行，调试运行起来没有进度条没有样色

**Comment by youluna** [comment]
可以参考下文档：
https://github.com/alibaba-fusion/next/blob/master/README.zh-cn.md#-%E5%BC%95%E5%85%A5 
https://github.com/alibaba-fusion/next/blob/master/site/zh-cn/theme.md
