### ISSUE TITLE
importing @alifd/next/index.scss through scss-loader makes output size very large (~10MB)

### ISSUE THREAD

**Issue by shinima** [alibaba-fusion/next#629]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.14.2

### Environment
win10, chrome 74, scss-loader@7.1.0

### Reproduction link
[https://github.com/shinima/fusion-next-sample](https://github.com/shinima/fusion-next-sample)

### Steps to reproduce

- clone https://github.com/shinima/fusion-next-sample
- cd into the created directory by clone
- run `yarn install` to install deps
- run `yarn profile` and see webpack output in http://127.0.0.1:8888/

### Actual Behavior

1. run `yarn profile` **with** `import '@alifd/next/index.scss'`  in `src/main.tsx`
![image](https://user-images.githubusercontent.com/5550931/57198047-0bce5480-6fa1-11e9-8afc-25cd4905a1ad.png)

2. run `yarn profile` **without** `import '@alifd/next/index.scss'`  in `src/main.tsx` (you need to modify mian.tsx to re-produce this case)
![image](https://user-images.githubusercontent.com/5550931/57198016-aed29e80-6fa0-11e9-9158-e935eed42150.png)

3. If I use `fast-sass-loader` instead of `scss-loader`, the output size is normal. (you need to install fast-sass-loader and modify webpack config to re-produce this case)
![image](https://user-images.githubusercontent.com/5550931/57198106-91520480-6fa1-11e9-891c-0cc7bfaea00b.png)

### Expected Behavior

Output size is normal (parsed size ~600K) regardless of using sass-loader or fast-sass-loader.

PS：https://fusion.design/feedback 不太好用，里面的输入框太小了

**Comment by youluna** [comment]
感谢反馈🙏 使用sass-loader体积大的原因是webpack不会对重复引入的scss文件进行去重，使用fast-sass-loader可以解决Fusion Next重复引用的问题，需要改下文档

**Comment by shinima** [comment]
嗯，还请更新一下文档。如果直接使用 sass-loader 引入的话，输出会很大，导致开发时浏览器变得很卡。
