### ISSUE TITLE
[VirtualList]virtual-list使用了Object.values方法

### ISSUE THREAD

**Issue by javaxiu** [alibaba-fusion/next#637]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.14.2

### Component
VirtualList

### Environment
webview

### Reproduction link
[https://github.com/alibaba-fusion/next/blob/master/src/virtual-list/virtual-list.jsx#L363](https://github.com/alibaba-fusion/next/blob/master/src/virtual-list/virtual-list.jsx#L363)

### Steps to reproduce
Object.values 是较新的一个api，IE全系不支持，Chrome部分不支持，webkit/webview部分不支持，希望能换个api

**Comment by youluna** [comment]
组件发布借助babel-runtime进行编译，在任何浏览器下都应该是支持的。

你遇到了VirtualList不可用的问题么，如果有的话可以详细描述性问题是什么

**Comment by javaxiu** [comment]
`import { VirtualList } from '@alifd/next';`
我是这样引用的，但是在一些低版本浏览器报错了，定位到的原因是这里用了Object.values，babel没处理node_module库

**Comment by youluna** [comment]
babel-runtime没有编译到Object.values，需要添加plugin。目前通过改成Object.keys().map()解决问题
