### ISSUE TITLE
[Tag]Group not exported in index.d.ts

### ISSUE THREAD

**Issue by justnewbee** [alibaba-fusion/next#640]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

<img width="429" alt="image" src="https://user-images.githubusercontent.com/2276086/57421608-0db54380-723f-11e9-81ab-382fb1201964.png">

<img width="876" alt="image" src="https://user-images.githubusercontent.com/2276086/57421632-2291d700-723f-11e9-88e6-9a89299bc2a5.png">

<img width="715" alt="image" src="https://user-images.githubusercontent.com/2276086/57421658-2f162f80-723f-11e9-95c1-08ab6c3059c5.png">

### Component
Tag

### Environment
any

### Reproduction link
[none](none)

### Steps to reproduce
no need

**Comment by jdkahn** [comment]
@justnewbee Does the code compile?

**Comment by youluna** [comment]
@jdkahn I think I know how to fix the issue, let me handle this

**Comment by justnewbee** [comment]
> I think there is no need to export `Tag.Group` since it's really really simple

simple?! it is not even a reason enough...

ts is WAY too important to ignore

now i have to do `const TagGroup = (Tag as any).Group;` if u do NOT port it in type, how can i use it in ts?

**Comment by justnewbee** [comment]
> @justnewbee Does the code compile? Can you show how you are importing the `Tag` component?

code cannot compile due to type issue

**Comment by justnewbee** [comment]
seems like it has been fixed anyways

<img width="608" alt="image" src="https://user-images.githubusercontent.com/2276086/90858961-d201a700-e3b9-11ea-8f0b-9db1dcfd5b7c.png">

**Comment by youluna** [comment]
TagGroup是有必要的，19年处理这个issue的时候认为TagGroup是0.x遗留待废弃的API，后面实际上是用的到的，所以加上了
