### ISSUE TITLE
[Table]ab一起使用多个table吸顶效果的时候，会出现header消失的情况

### ISSUE THREAD

**Issue by 185172970** [alibaba-fusion/next#642]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.14.2

### Component
Table

### Environment
macOS 10.13.6 chrome 73.0.3683.103

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/650c5fe7?mode=jsx](https://riddle.alibaba-inc.com/riddles/650c5fe7?mode=jsx)

### Steps to reproduce
首先打开点击tab的第二个选项，滚动出现吸顶效果，然后返回第一个tab，里面的table header已经消失

**Comment by 185172970** [comment]
.next-tabs-tabpane.active {
    display: block;
    visibility:visible;
    height: 100%;
  }
  .next-tabs-tabpane {
    display: block;
    visibility: hidden;
    height: 0;
  }
这样可以暂时解决

**Comment by youluna** [comment]
`Table` 的fixed header功能使用了`Affix`组件，在`Tab`的切换过程中没有触发`Affix`的unmount事件，导致，对同一区域的事件监听一直存在，导致获取的header宽高都为0，一定要滚动后才会出现header。

@guanpu 看下tab的隐藏能否从display: none换成上面 @185172970 写的样式呢

**Comment by guanpu** [comment]
如果是因为没有触发内容区域的unmount导致的话,可以设置tab的 unmountInactiveTabs属性为true解决. 刚在你的riddle里测试过了有效

**Comment by guanpu** [comment]
![image](https://user-images.githubusercontent.com/5867109/58926062-5f88b500-877c-11e9-9e8f-1b0eede7ad68.png)
@185172970

**Comment by 185172970** [comment]
好
