### ISSUE TITLE
[Table]开启锁列的功能后，浏览器会报这 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. 警告

### ISSUE THREAD

**Issue by SihengWang** [alibaba-fusion/next#644]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.14.2

### Component
Table

### Environment
Chrome浏览器Version 74.0.3729.131 (Official Build) (64-bit)

### Reproduction link
[https://fusion.design/component/basic/table](https://fusion.design/component/basic/table)

### Steps to reproduce
@alife/next-table 版本 1.1.3
开启锁列功能，在表格里滚动

**Comment by youluna** [comment]
在高版本chrome会出现这个报警，不会影响用户使用
