### ISSUE TITLE
[Icon]How to disable an icon?

### ISSUE THREAD

**Issue by hussaintamboli** [alibaba-fusion/next#649]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Icon

### Feature Description
I can't find a property to disable the icon. I tried "disabled" property but it doesn't work.

**Comment by youluna** [comment]
Thank you for your feedback!
`Icon` is a decoration, maybe it's better to use with `Button` if you want to make it clickable :
```
<Button text><Icon type="success" /></Button>
<Button disabled text><Icon type="success" /></Button>
```
see https://codepen.io/anon/pen/PvNqrm

**Comment by hussaintamboli** [comment]
Actually I am using it with `Baloon` like

`<Balloon
          trigger={formIcon}
          triggerType="hover"
          closable={false}
          align="tl"
        >
              Copy item
        </Balloon>`

**formIcon:**
`const formIcon = <Icon type="form" size="small" onClick={() => this.copyItem(itemId)} />;`

**Comment by youluna** [comment]
`Icon` doesn't have a disable state, `Button` do. I think this will work
```jsx
const formIcon = <Button onClick={() => this.copyItem(itemId)}><Icon type="form" size="small" /></Button>;
```

**Comment by hussaintamboli** [comment]
Button works but it changes the css style. Let me find a way to fix that.
