### ISSUE TITLE
[Dialog]How to change "confirm" and "cancel" button texts on the dialog

### ISSUE THREAD

**Issue by hussaintamboli** [alibaba-fusion/next#650]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Dialog

### Feature Description
Need a way to customize button texts

**Comment by youluna** [comment]
try this:
```jsx
<Dialog locale={{ok:'my ok', cancel: 'my cancel', close: 'my close'}}>
````
@jdkahn maybe we can add a demo about how to customize button texts

**Comment by hussaintamboli** [comment]
I am using `Dialog.confirm(...)`. Sorry I didn't mention that before.

**Comment by jdkahn** [comment]
Another solution is to set the children props for the buttons.
`<Dialog okProps={{children: 'my ok'}} cancelProps={{children: 'my cancel'}}>`

This might be a little more text, but it think it is clearer because its not overriding correct locale text.
