### ISSUE TITLE
[Form]建议表单form增加可读属性

### ISSUE THREAD

**Issue by AndyZjy** [alibaba-fusion/next#658]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Form

### Feature Description
目前表单只有禁用属性（disabled），但是实际应用中很多情况下需要使用只读属性（readOnly），建议增加form表单增加只读属性

**Comment by jdkahn** [comment]
@AndyZjy You can use the `readOnly` property on the `Input` component.

`<Input readOnly name="readOnlyInput" value="myValue/>`

Does this solve your issue?

**Comment by AndyZjy** [comment]
form表单内部的只读属性建议没有边框和聚焦，而不是禁用或者只是不能输入

**Comment by jdkahn** [comment]
From the HTML spec

> The difference between _disabled_ and _readonly_ is that read-only controls are still focusable, so the user can still select the text and interact with it, whereas disabled controls are entirely non-interactive. Only text controls can be made read-only.

If the text is going to be submitted, even though it cannot be changed, it should be selectable through keyboard navigation. The focus state is to indicate that it is selected. I think its a good idea to include in the label that it is read-only. If you do not wish to have the user see the input I would suggest making the input hidden.

**Comment by AndyZjy** [comment]
Thank you.

**Comment by bindoon** [comment]
@AndyZjy 你有相关只读态的设计稿吗？

**Comment by AndyZjy** [comment]
交互效果跟p标签差不多，只是颜色有些不同而已
