### ISSUE TITLE
[Select]Option上的自定义参数被过滤掉了

### ISSUE THREAD

**Issue by garygao12580** [alibaba-fusion/next#686]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.14.4

### Component
Select

### Environment
mac os

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/11d4ae60](https://riddle.alibaba-inc.com/riddles/11d4ae60)

### Steps to reproduce
我们的需求要根据自定义参数，根据itemRender返回不同的渲染。发现，dataSource模式是好的，可以传递自定义参数，但是Option上的参数会被过滤掉。
希望能后尽快修改这个逻辑。

**Comment by Heluwe** [comment]
Use data-extra, for example: https://riddle.alibaba-inc.com/riddles/23578a3d.
