### ISSUE TITLE
[SplitButton]SplitButton can't support popup follow trigger

### ISSUE THREAD

**Issue by guanpu** [alibaba-fusion/next#690]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.14.4

### Component
SplitButton

### Environment
any

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/a0eb659a](https://riddle.alibaba-inc.com/riddles/a0eb659a)

### Steps to reproduce
just use `popupProps={{followTrigger: true}}` to splitButton it will report error.
if workaround with `popupProps={{container: i=>i}}` it will work, but there's style issue.

**Comment by youluna** [comment]
1.15.1 fixed, and you can use `<SplitButton followTrigger>` now
