### ISSUE TITLE
[MenuButton]组件结合typescript使用时会报错

### ISSUE THREAD

**Issue by justb** [alibaba-fusion/next#705]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.14.5

### Component
MenuButton

### Reproduction link
[ ]( )

### Steps to reproduce
传入text属性时报错，Property 'text' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<MenuButton> & Readonly<MenuButtonProps> & Readonly<{ children?: ReactNode; }>

![image](https://user-images.githubusercontent.com/22002343/58240456-95419d00-7d7d-11e9-9f35-f0c3788bd917.png)

**Comment by myronliu347** [comment]
fixed in 1.15.x
