### ISSUE TITLE
[DatePicker]日期选择器 value 传值，行为不符合预期

### ISSUE THREAD

**Issue by liuyiliuyi** [alibaba-fusion/next#709]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.14.6

### Component
DatePicker

### Environment
Chrome 73

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hardcore-tesla-pykwh)

### Steps to reproduce
正确的应为 2019-05-12，而不是 2019-05-11。
@icedesign/base 的 DatePicker 行为是正常的，为 2019-05-12。

**Comment by myronliu347** [comment]
目前解析moment的方式是根据date-picker format 属性（默认： YYYY-MM-DD）, 而demo中使用了时区，导致出错， 建议这中情况，在组件外层完成解析日期操作，更改组件format属性带上时区配置
