### ISSUE TITLE
[Table]sortable & isTree cannot use together

### ISSUE THREAD

**Issue by Sheldon-Yin** [alibaba-fusion/next#732]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.15.1

### Component
Table

### Environment
Mac Chrome

### Reproduction link
[https://codepen.io/anon/pen/BeVJxQ?&editable=true&editors=0010](https://codepen.io/anon/pen/BeVJxQ?&editable=true&editors=0010)

### Steps to reproduce
the api of table isTree & sortable cannot be with together, when set isTree to Table, the sortable cannot work!

**Comment by youluna** [comment]
fixed
