### ISSUE TITLE
[Select&Overlay] 鼠标滑动全选体验问题

### ISSUE THREAD

**Issue by acrens** [alibaba-fusion/next#742]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.15.1

### Component
Select

### Environment
所有

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/fecb8a05](https://riddle.alibaba-inc.com/riddles/fecb8a05)

### Steps to reproduce
版本：0.x、1.x 均有一样体验问题

操作流程：输入搜索内容，鼠标滑动全选（鼠标滑动出 select 和 dropdown 范围），此处出现下拉搜索框自动关闭

期望：滑动全选，不会自动关闭下拉框，目前业务中使用 0.x，0.x 体验升级优先最好

**Comment by bindoon** [comment]
没看懂怎么操作的
- ”鼠标滑动全选“ 这是个啥操作，为啥滑动还能全选
- ”（鼠标滑动出 select 和 dropdown 范围）“  又滑出去了，到底选了没有？

**Comment by youluna** [comment]
![select](https://user-images.githubusercontent.com/10049465/59813348-af9e7480-9343-11e9-8833-96792dfa72e4.gif)
@bindoon 用户在select的input区域复制内容时，鼠标动作是按下->拖动->松开，如果松开时鼠标仍在input区域内是正常的，但是一旦松开时鼠标不在input区域（在弹层区域或页面其他地方），选中就不会生效

**Comment by bindoon** [comment]
了解了，是在区域外放开了，弹窗相应了自动关闭事件！

**Comment by bindoon** [comment]
这个感觉应该是 overlay 的问题，

在区域外，如果是放开鼠标不要触发 onVisibleChange ？点击才应该触发

**Comment by bindoon** [comment]
will be fixed in @alifd/overlay

**Comment by bindoon** [comment]
fixed in `@alifd/next@1.25` with api `popupProps={{v2:true}}`
