### ISSUE TITLE
[Field]当init不存在校验规则时，setError应该可被field.validate获取

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#747]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Field

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/5c04a5](https://riddle.alibaba-inc.com/riddles/5c04a5)

### Steps to reproduce
目前只能hack, 在validate之前getErrors然后setErrors,再合并validate的err
```jsx
const { validate, getValues, getErrors } = this.field;
const customError = getErrors();
   validate((err) => {
      const val = getValues();
      const errors = {};
      for (const i in customError) {
        if (customError[i]) {
          errors[i] = customError[i];
          this.setError(i, customError[i]);
        }
      }
      // 合并自定义errors
      err = { ...err, ...errors };
      if (!err) {
        handleSubVal(val);
        callBack(val);
      }
    });
```

**Comment by bindoon** [comment]
that's make sense. add api like `keepErrorsWhenNoRule` ?

**Comment by jdkahn** [comment]
@bindoon We don't need an api change for this since this will be the default behavior
