### ISSUE TITLE
[Timeline]timeline组件的中文Readme和英文Readme不一致

### ISSUE THREAD

**Issue by csr632** [alibaba-fusion/next#748]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.15.2

### Component
Timeline

### Environment
any

### Reproduction link
[https://github.com/alibaba-fusion/next/blob/master/docs/timeline/index.md](https://github.com/alibaba-fusion/next/blob/master/docs/timeline/index.md)

### Steps to reproduce
下面这两个Readme的API描述不一致
https://github.com/alibaba-fusion/next/blob/master/docs/timeline/index.md

https://github.com/alibaba-fusion/next/blob/master/docs/timeline/index.en-us.md

**Comment by youluna** [comment]
多谢反馈，可以在这里看文档 https://fusion.design/component/basic/timeline
