### ISSUE TITLE
[Balloon]能否设置一个通用的最大高度

### ISSUE THREAD

**Issue by AndyZjy** [alibaba-fusion/next#760]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Balloon

### Feature Description
建议给Balloon组件设置一个最大高度，因为当气泡图内部内容超过一屏时，当前页面会突然多出来滚动条，能否让其Balloon组件内部滚动，而不是当前整个浏览器滚动

**Comment by youluna** [comment]
你可以通过<Balloon style={{}}> 添加最大高度，就组件层面来说，最大高度没有必要
