### ISSUE TITLE
[Select]能否新增一个 maxSelectedCount 的属性

### ISSUE THREAD

**Issue by flyinhigh** [alibaba-fusion/next#770]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Select

### Feature Description
对选择做个数限制的配置，比如说，总共有 10 个选项，但是一次最多选 5 个

**Comment by Heluwe** [comment]
可以在onChange的时候通过value.length < 5判断value是否需要改变
