### ISSUE TITLE
[Select]Select 中的 Base 缺少 key prop

### ISSUE THREAD

**Issue by yibn2008** [alibaba-fusion/next#771]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.15.4

### Component
Select

### Environment
chrome

### Reproduction link
[nop](nop)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/4136679/58962248-61369500-87dd-11e9-8259-a5e6a0218c92.png)

见图, 用最简单的 <Select dataSource={data} /> 方式就可以复现, codepan 打不开, 就不给具体案例了

---

**Comment by bindoon** [comment]
复现不了呀，至少代码片段也得给个吧！

**Comment by yibn2008** [comment]
@bindoon 直接内网钉钉吧

**Comment by yibn2008** [comment]
```
import React from 'react@16';
import ReactDOM from 'react-dom@16';
import { Select, Form } from '@alife/next@1.x';

function Demo() {
  const dataSource = [
    { label: "test-just-space (测试产品)", value: 4 },
    { label: "just_test (测试)", value: 14 },
    { label: "b2b-sc (b2b-sc)", value: 16 },
    { label: "abc-group (asdfasdf)", value: 49 },
    { label: "assets-group (默认 assets 组)", value: 51 }
  ];

  return (
    <Form>
      <Form.Item label="xx">
        <Select name="xxx" dataSource={dataSource} />
      </Form.Item>
    </Form>
  );
}

ReactDOM.render(<Demo/>, mountNode);

```
