### ISSUE TITLE
[NumberPicker] reset should not only support `undefined`  but also `null`

### ISSUE THREAD

**Issue by yaniswang** [alibaba-fusion/next#780]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
NumberPicker

### Environment
Chrome 75

### Reproduction link
[https://codepen.io/yaniswang/pen/PrwjGG](https://codepen.io/yaniswang/pen/PrwjGG)

### Steps to reproduce
目前Form组件的初始值是`undefined`，这个值无法序列化进行传输，序列化时会自动删除。
如果是数组里有`undefined`，则会强行转成`null`。

例如： 

`[1, undefined, 2]`，
数据到数据库后，就变成：
`[1, null, 2]`

如果将null直接赋给NumberPicker，目前是直接忽略的。
如果field复用场景下，就会导致显示的值还是旧值，因为`null`值被NumberPicker直接忽略了。

这个ISSUE，希望讨论3个问题：

1. 初始值应该用`undefined`还是用`null`？
2. 如果初始值是`undefined`，如何解决序列化传输问题？
3. NumberPicker组件是否应该兼容`null`？

**Comment by yaniswang** [comment]
引用下阮一峰的关于undefined和null的分享和讨论：http://www.ruanyifeng.com/blog/2014/03/undefined-vs-null.html

**Comment by bindoon** [comment]
1. 每个组件都有自己的value 类型(bool/array/number/object) ，限制为一种类型后再接收其他类型值会warning.  NumberPicker 如果限定了整数(number) 那么 他能接收 number 和 undefined 值，但是 null 应该会有warning。不能期望组件去写 PropTypes.oneOfType([bool, object])

2. null 可以确定是一种值，应该被部分组件支持。那也应该有些组件不支持，比如 input 是string类型空值就是 "" 而不应该是null

**Comment by yaniswang** [comment]
`<Select ><Option value={null} >选项1</Option> <Option value={{key: 'care'}} >选项1</Option></Select>`
这种组件值应该设计不合理，应该是这样：

`<Select ><Option value={{key:0}} >选项1</Option> <Option value={{key: 'care'}} >选项1</Option></Select>`

在一个控件的值正常范围内，应该格式都一致，不应该一个是key-value的，另一个却是null。

而且相信这样的另类设计应该是非常小众的。不能因为个别小众的非标准设计，而坏了所有人合理的设计选择。

**Comment by yaniswang** [comment]
null是json结构中可支持的数据类型中唯一的选择用来当无值。

我也认为form表单产出的数据结构应该是适合序列化，适合数据传输的，并且数据传输是稳定不变的。

不能getValues数据序列后，再重新反序列化setValues，我们的组件就无法支持了。

**Comment by bindoon** [comment]
https://riddle.alibaba-inc.com/riddles/4e7f0069

因为规范是undefined，所以在parseName 并且通过 [1, undefined, 2] 设置数据的时候，field getIn 函数无法判断是 key 不存在导致的 undefined 还是数据 = undefined。
![image](https://user-images.githubusercontent.com/5189853/59401319-e5d07700-8dcc-11e9-8188-9cf2930c1ccc.png)

**Comment by bindoon** [comment]
```
JSON.stringify([undefined])
```

"[null]"

**Comment by bindoon** [comment]
supported null in PR #782
