### ISSUE TITLE
[Field] need a api to work with getValueFromEvent to reverse value to Component

### ISSUE THREAD

**Issue by bindoon** [alibaba-fusion/next#781]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Field

### Feature Description

now we can use `getValueFromEvent` to change return value

```
<Switch {...init('name', { getValueFromEvent: (value) => return value === true? 1:0})}/>
```
but switch did support value=1
```
<Switch value={1} />
```
so result is rename `getValueFromEvent` to `beforeGetValue` ,and add new api `beforeSetValue`

```
<Switch {...init('name', { 
beforeGetValue: (value) => {return value === true? 1:0},
beforeSetValue: (value) => {return value===1? true: false}
})}/>
```

**Comment by imsobear** [comment]
beforeGetValue/beforeSetValue VS formatGetValue/formatSetValue

**Comment by jdkahn** [comment]
How about `getValueFormatter` and `setValueFormatter`?

**Comment by bindoon** [comment]
+ @alifd/field@1.4.1
