### ISSUE TITLE
[Field]cant use getValues while setValues before init with parseName=true

### ISSUE THREAD

**Issue by bindoon** [alibaba-fusion/next#792]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Field

### Environment
all

### Steps to reproduce
```
class Main extends React.Component {
  constructor(props) {
    super(props);
    this.field = new Field(this, {parseName: true});
    this.field.setValues({a:1});
  }
  render() {
    this.field.getValues(); // should be {a:1} but actually get {}
    return <div>
    {this.state.show ? <input {...init('a')} />: null}
    </div>
  }
}
```

**Comment by bindoon** [comment]
we do this with react-hooks issues.  i think we should cache values directly for getValues/getValue/setValue/setValues

**Comment by jdkahn** [comment]
Can you clarify the use case for this? In the above example, the values should be set in the Field constructor. If the value is being set via api call then it would be called after `ComponentDidMount` so the `init` would already be called. As I understand it, Field cannot support react-hooks at the moment.

**Comment by bindoon** [comment]
@jdkahn just want to save values, ant `init` may be not called at first render
```
  render() {
    this.field.getValues(); // should be {a:1} but actually get {}
    return <div>
    {this.state.show ? <input {...init('a')} />: null}   // while show=true init(a) will be called
    </div>
  }
```

**Comment by jdkahn** [comment]
@bindoon 

1. I cannot see a reasonable case where `setValues` is called before `init` (see my above comment). For it to work with `parseName` it would have to just store the entire object passed in a new field attribute, which I feel is adding unnecessary complexity if we don't have a clear use case. 

1. If calling `getValues` before inputs are first rendered, then values could be assigned on Field construction. As of now, we iterate through field names, which will return nothing. This is an easy fix to return `initValue` as default value.
