### ISSUE TITLE
[Platform]英文拼写错了吧 massage处应该是message

### ISSUE THREAD

**Issue by spume123** [alibaba-fusion/next#799]
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Environment
谷歌

### Reproduction link
[https://fusion.design/design/doc/13](https://fusion.design/design/doc/13)

### Steps to reproduce
something...

**Comment by youluna** [comment]
感谢反馈， fixed
