### ISSUE TITLE
[Select]多选模式下搜索导致下拉内容滚动条回到初始位置

### ISSUE THREAD

**Issue by zhuscat** [alibaba-fusion/next#801]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.15.6

### Component
Select

### Environment
macOS 10.14 (18A391) Google Chrome 74.0.3729.169

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fusion-next-template-6rx7o)

### Steps to reproduce
1. 首先点击多选框，在输入框中输入关键词（如 1），然后删掉搜索的关键词
2. 将下拉框往下滚动，随便选择一个选项
3. 下拉框滚动条自动跳到最上面

PS：如果一开始不搜索，直接点击选择，则不会出现上述 BUG

**Comment by bindoon** [comment]
因为搜索后会把 hightLight 设置会第一个item，所以menu渲染会自动滚动到 hightLight 的元素上面！
