### ISSUE TITLE
[Overlay]Cannot pass functional react components as children

### ISSUE THREAD

**Issue by jdkahn** [alibaba-fusion/next#810]
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Overlay

### Environment
Chrome

### Reproduction link
[https://codepen.io/anon/pen/mZRvwZ](https://codepen.io/anon/pen/mZRvwZ)

### Steps to reproduce
Click on the overlay toggle
- Functional components cannot have refs attached

**Comment by youluna** [comment]
1.15.11 fixed
