### ISSUE TITLE
[Tab]Tab 支持添加功能

### ISSUE THREAD

**Issue by zhuscat** [alibaba-fusion/next#828]
### Component 
Tab
### Feature Description
希望能够支持类似浏览器这样的一个添加功能

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/i3rNAqCDMi8J.png)

**Comment by youluna** [comment]
有个差不多的，通过`extra`属性[自定义tab右侧](https://fusion.design/component/basic/tab#%E9%99%84%E5%8A%A0%E9%A2%9D%E5%A4%96%E5%86%85%E5%AE%B9 )的内容
![image](https://user-images.githubusercontent.com/10049465/61027226-3517c080-a3e8-11e9-8bf3-9b88f6151802.png)
再参考[这个demo](https://fusion.design/component/basic/tab#%E5%8F%AF%E5%85%B3%E9%97%AD%E9%80%89%E9%A1%B9%E5%8D%A1)加上新增tab功能
![image](https://user-images.githubusercontent.com/10049465/61027366-8c1d9580-a3e8-11e9-8261-208c350e2c0f.png)

**Comment by zhuscat** [comment]
@youluna 可能交互上想要`+`号跟在 tab 后面，目前我只能把最后一个 tab 作为「添加新tab」的按钮，比较繁琐。
