### ISSUE TITLE
[DatePicker]DatePicker.RangePicker 能否增加最长区间选项

### ISSUE THREAD

**Issue by csbun** [alibaba-fusion/next#829]
### Component 
DatePicker
### Feature Description
例如：时间区间选择，很多时候需要限制用户最长只能选择 1年或 1个月等场景。
的确通过 disabledDate 可以解决这个问题，但还是希望有木有更便捷的方法？

**Comment by jerryyxu** [comment]
见：https://github.com/alibaba-fusion/next/issues/1675

**Comment by csbun** [comment]
> 见：#1675

@jerryyxu 这个预设的 range 似乎不是我所需要的功能。
我的业务场景是 「最长不超过」某个时间段，例如一个 xx 预定系统，为了让更多人都能定到，限制每次预定不能超过 7 天，那用户的可选范围则为 1-7 天。
