### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by sanseo** [alibaba-fusion/next#831]
### Component 
Input

### Reproduction link 
[无](无)

### Steps to reproduce
./node_modules/_@alifd_next@1.15.9@@alifd/next/es/icon/main.scss
Module build failed:ModuleBUildError:Module build failed:Syntax Error
(14:4) Unknown word 
.#{$icon-prefix}{
  display:inline-block
}

**Comment by bindoon** [comment]
请补充下步骤环境，以上报错是正常的 scss 语法

**Comment by youluna** [comment]
$icon-prefix的定义在`core/index-noreset.scss`中，看起来是自定义工程编译漏掉了东西
