### ISSUE TITLE
[Table]添加 sticky column，当浏览器横向滚动时，这些列始终固定在某个位置

### ISSUE THREAD

**Issue by ling1900** [alibaba-fusion/next#840]
### Component 
Table
### Feature Description
就像已有的 sticky header 功能一样，当浏览器竖直滚动时，表头始终固定在某个位置。同理，希望有 sticky column 的功能，当浏览器横向滚动时，这些列始终固定在某个位置。sticky Column 与 lock Column 的区别，就像 sticky header 与 fixed header 的区别。

**Comment by youluna** [comment]
有这样的业务场景的交互图吗，想像不到sticky Column 的使用场景。

按照习惯来说，页面的宽度一般是固定的，而页面的长度可以是无限的，sticky header 扩大了视区， fixed header限定了table高度，这两个是存在差异且被认可的。

**Comment by ling1900** [comment]
表格可以设置列宽，或者拖拽调整列宽，所以表格可能会变得很宽直到浏览器出现横向滚动条（不是表格自己出现滚动条），这时浏览器横向滚动时，就希望有些列固定在某个位置。

**Comment by youluna** [comment]
交互上可以往锁列靠拢，sticky column的需求暂不考虑

**Comment by ling1900** [comment]
https://github.com/alibaba-fusion/next/issues/808
[Table]table flex布局下锁列失效
