### ISSUE TITLE
[Pagination]分页器特定场景下报错，导致组件崩溃，详细见riddle代码片段

### ISSUE THREAD

**Issue by CarltonXiang** [alibaba-fusion/next#842]
### Component 
Pagination

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/800ecf99?mode=jsx](https://riddle.alibaba-inc.com/riddles/800ecf99?mode=jsx)

### Steps to reproduce
详细见riddle代码片段

**Comment by myronliu347** [comment]
fixed in 1.16.0
