### ISSUE TITLE
[Overlay]Pagination Crashes if no bottom padding

### ISSUE THREAD

**Issue by jdkahn** [alibaba-fusion/next#853]
### Component 
Overlay

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/8cd75d4b?mode=css](https://riddle.alibaba-inc.com/riddles/8cd75d4b?mode=css)

### Steps to reproduce
1 - click on the page size dropdown and change value to 10
2 - click on page size dropdown again and page will crash

The issue does not occur if the pagination has a bottom padding value, which is commented out in the riddle

**Comment by youluna** [comment]
fixed in 1.16.0

**Comment by youluna** [comment]
https://riddle.alibaba-inc.com/riddles/f34ada8b
