### ISSUE TITLE
[Tree]Tree组件支持拉平的数据源

### ISSUE THREAD

**Issue by garygao12580** [alibaba-fusion/next#854]
### Component 
Tree
### Feature Description
希望Tree的dataSource可以支持拉平的数据源，
如： [{id: 1, pId: 0, name: 'aaa'},{id: 2, pId: 1, name: 'aaa'} ]
否则对于原本就是拉平的数据源，需要调用方转换成chidlren格式。
方案请参考：https://npm.alibaba-inc.com/package/@aximario/json-tree

**Comment by myronliu347** [comment]
这个方案不会支持，dataSource 希望还是保持一个特定的格式
