### ISSUE TITLE
多主题配置后调用window.__changeTheme__('@alifd/theme-ice-green');后报错

### ISSUE THREAD

**Issue by JerryWoo** [alibaba-fusion/next#856]
### Steps to reproduce
多主题配置后调用window.__changeTheme__('@alifd/theme-ice-green');后报错如下，是不是还要添加什么依赖：
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/KDaTGlr4BNIg.png)

**Comment by imsobear** [comment]
https://github.com/alibaba/ice/issues/2359
