### ISSUE TITLE
[尝试编译]编译出错啦(yarn install)

### ISSUE THREAD

**Issue by Alvazz** [alibaba-fusion/next#867]
### Component 
Affix

### Steps to reproduce
3333.png
![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/Z3TLBDCnNOf1.png)

clone了next的代码，想本地编译一下，在yarn install的时候，报了这个错误

**Comment by mark-ck** [comment]
需要在 nodejs 版本是 8 的环境下构建
