### ISSUE TITLE
[Nav]希望nav组件支持非iconOnly的情况下也可以隐藏右边的箭头

### ISSUE THREAD

**Issue by JulienBrks** [alibaba-fusion/next#871]
### Component 
Nav
### Feature Description
目前iconOnly为false的情况下，hasArrow配置为false没有效果。

希望增加支持iconOnly为false的情况下也可以配置hasArrow为false，如下视觉稿

![image](https://user-images.githubusercontent.com/2757198/61019649-86ff1d00-a3cd-11e9-8208-e976b973bd32.png)

**Comment by youluna** [comment]
这个交互经评审，认为没有通用性，可以用style来hack，组件上不提供api哈
