### ISSUE TITLE
官网文档Form组件API的Form.Item中validateState属性说明写错了

### ISSUE THREAD

**Issue by Slartbartfast1** [alibaba-fusion/next#889]
### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/PqtUGHYZykmf.png)
https://fusion.design/component/basic/form#demo-api

**原文：**
可选值:
'error'(成功)
'success'(失败)
'loading'(校验中)
**应该改成：**
可选值:
'error'(失败)
'success'(成功)
'loading'(校验中)

**Comment by youluna** [comment]
thanks, it would be better if you create a pull request 😄

**Comment by youluna** [comment]
fixed
