### ISSUE TITLE
[Table]固定列table设置单元格不换行样式后，内容过长的固定列单元格导致样式bug

### ISSUE THREAD

**Issue by haoqi0818** [alibaba-fusion/next#890]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/3542ec12](https://riddle.alibaba-inc.com/riddles/3542ec12)

**Comment by youluna** [comment]
![image](https://user-images.githubusercontent.com/10049465/96669688-49d75800-1390-11eb-8e63-4fe924f745ac.png)

升级到1.21.x，使用Table.StickyLock，亲测完美解决
