### ISSUE TITLE
[Upload]Dragger如果是受控模式，拖拽上传后不会触发onChange和onSuccess

### ISSUE THREAD

**Issue by garygao12580** [alibaba-fusion/next#908]
### Component 
Upload

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/6cbd7c2e](https://riddle.alibaba-inc.com/riddles/6cbd7c2e)

### Steps to reproduce
如Riddle链接，拖拽上传和点击图标上传的行为不一致，拖拽上传后不会触发onChange和onSuccess

**Comment by bindoon** [comment]
issue same with #923  and fixed in PR #928
