### ISSUE TITLE
[Upload]dragger under controlled cant get value

### ISSUE THREAD

**Issue by bindoon** [alibaba-fusion/next#923]
### Component 
Upload

### Steps to reproduce

1. drag file , release mouse,
2. Upload.jsx: will call onSelect and save fileList length=1
2. dragger.jsx: call onDrop, but because onChange not called.  value=[]
3. Upload.jsx: componentWillReceiveProps called.  should check isUploading to ignore value=[]

**Comment by youluna** [comment]
is this related to https://github.com/alibaba-fusion/next/issues/908 ?
