### ISSUE TITLE
[Dialog]Fullscreen dialog cannot close by mask click

### ISSUE THREAD

**Issue by jdkahn** [alibaba-fusion/next#927]
### Component 
Dialog

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/142a0581](https://riddle.alibaba-inc.com/riddles/142a0581)

### Steps to reproduce
create a dialog with isFullScreen=true and hasMask=true
click on the mask and it does not close the dialog

**Comment by youluna** [comment]
https://riddle.alibaba-inc.com/riddles/3db24b41
`Dialog` with `isFullScreen` `animation`, animation in failed

**Comment by jdkahn** [comment]
@youluna Fixed fullscreen animation issue. Please review
