### ISSUE TITLE
[Form]TimePicker、DatePicker、NumberPicker没有Name字段，使用Form表单时会报错

### ISSUE THREAD

**Issue by luhc228** [alibaba-fusion/next#937]
### Component 
TimePicker

[飞冰官网组件链接](https://ice.work/component/form#%E8%A1%A8%E5%8D%95%E7%BB%84%E5%90%88)

**Comment by youluna** [comment]
贴的链接是`<Form>`组件关于Form.Item一个参数validateState的用法，这是一个纯UI展示，没有结合任何判断。
![image](https://user-images.githubusercontent.com/10049465/62105134-195f5600-b2d4-11e9-94b6-6ad6efcc0f8d.png)
Field组件与Form组件有深度结合，可以通过field自动校验状态

**Comment by luhc228** [comment]
下面是官网的例子：
```
    <Form>
              <FormItem
                    label="TimePicker:"
                    required
               >
                    <TimePicker name="time" />
                </FormItem>
    </Form>
```
但是上面的TimePicker这个组件是没有name这个属性的，DatePicker组件也是一样没有的。
所以是否需要考虑加进去呢？

**Comment by bindoon** [comment]
我明白意思了，是说组件不一定有 `name` 这个属性。ts 会报错warning吧

**Comment by luhc228** [comment]
> 我明白意思了，是说组件不一定有 `name` 这个属性。ts 会报错warning吧

嗯嗯，是的

**Comment by bindoon** [comment]
暂时无法解决，除非把 name 从 组件挪到 FormItem 上面，先 hold 思考下解决方案

**Comment by youluna** [comment]
@bindoon any update？

**Comment by bindoon** [comment]
TODO: 2.x Form解决方案里面吧 name从 组件上面挪到 FormItem 上面。
