### ISSUE TITLE
[Dialog]need a static method adjustPosition

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#941]
### Component 
Dialog

### Reproduction link 
[https://codepen.io/anon/pen/XvRRXY](https://codepen.io/anon/pen/XvRRXY)

### Steps to reproduce
1. click 'open dialog'
2. click 'Documentation'
3. scroll, you can't click the button

![image](https://user-images.githubusercontent.com/10049465/62178429-9db8e400-b37b-11e9-82cd-be821dc59b19.png)

**Comment by youluna** [comment]
问题在于，Tab组件的高度变化，无法被Dialog获知，在Tab切换的过程中，Dialog没有render，因此出现上述情况。

在这种父元素无法主动获知子元素的改变，但子元素的改变会影响父元素功能的情况下，组件层面该如何处理？

### 可能的思路
1. Dialog等增加api 暴露resize事件（参考Slider，Slider在与Tab组件一起使用的时候会遇到高度塌陷的问题，因此Slider增加了静态方法，通过用户主动调用解决此问题）
2. 用户直接触发this.forceUpdate()

**Comment by bindoon** [comment]
Field 在dialog里面使用也会遇到这个问题，一起考虑下

**Comment by youluna** [comment]
@bindoon 你说的Field与Dialog的问题是 this指向改变，引起的field校验不生效问题吧？这个issue讨论的是父组件何时、如何rerender，不是同一类问题

**Comment by myronliu347** [comment]
如果 content 的内容可以自动伸缩，那么整个dialog 容器需要支持 overflow: auto , 参考 element-ui dialog

**Comment by youluna** [comment]
你的意思是说用样式设计上的css的方式来catch这种异常

Dialog现在是position: fixed，并且Dialog没有高度限制，完全由内容区域撑开， overflow: auto 不生效，有其他css catch的方式么 https://codepen.io/anon/pen/XvRRXY

**Comment by bindoon** [comment]
fixed in PR #3345 , released in @alifd/next@1.25
