### ISSUE TITLE
[Dialog]已经设置了overlayProps={{  disableScroll: false }}，但dialog显示时页面仍不能滚动

### ISSUE THREAD

**Issue by Alex-xd** [alibaba-fusion/next#954]
### Component 
Dialog

### Reproduction link 
[https://codepen.io/anon/pen/RXZeYX?&editable=true&editors=0010#anon-login](https://codepen.io/anon/pen/RXZeYX?&editable=true&editors=0010#anon-login)

### Steps to reproduce
dialog显示时，页面不能滚动。设置了overlayProps={{  disableScroll: false }}无效

**Comment by youluna** [comment]
在Dialog的模式下，禁用页面滚动是必要的，什么情况会让页面滚动呢？

**Comment by Alex-xd** [comment]
> 在Dialog的模式下，禁用页面滚动是必要的，什么情况会需要让页面滚动呢？

关闭了mask，弹窗在屏幕的右上角出现，弹窗里的内容是一个反馈问卷，所以这种场景下弹窗阻塞了页面的正常滚动就有问题啦。但是我不用弹窗的话，就只能自己用Overlay去封装一个一摸一样的弹窗.. @youluna
