### ISSUE TITLE
fusion.design 同步物料 build 目录文件缺失

### ISSUE THREAD

**Issue by imsobear** [alibaba-fusion/next#968]
目前看起来只同步了 index.js index.css index.html 三个文件，有的构建器构建出来的文件比较多，比如 CRA：

![image](https://user-images.githubusercontent.com/2505411/62513955-3b1a8900-b850-11e9-8df1-ef5cc77062f9.png)

**Comment by youluna** [comment]
现在直接用的unpkg资源解决问题，先close
