### ISSUE TITLE
[Form]values 属性，应当先拷贝再修改，而不是直接引用修改

### ISSUE THREAD

**Issue by jasonintju** [alibaba-fusion/next#969]
### Component 
Form
### Feature Description
使用三方状态管理库时，从store取出的值是不能直接改变的，需要通过action去改变值。当把取出的值赋值给Form，onChange时会报错，因为Form直接改变了values。理想的做法是Form拿到values之后，做一次拷贝再使用，而不是直接引用。

**Comment by bindoon** [comment]
1.16 以上field改过，用了浅拷贝。请确认下最新版本是否也有这个问题？

**Comment by bindoon** [comment]
升级到 1.16 即可
