### ISSUE TITLE
[Select]select 点清除的时候没有触发 onSearchClear

### ISSUE THREAD

**Issue by kreja** [alibaba-fusion/next#979]
### Component 
Select

### Reproduction link 
[http://riddle.alibaba-inc.com/riddles/ef32940](http://riddle.alibaba-inc.com/riddles/ef32940)

### Steps to reproduce
select 点清除的时候没有触发 onSearchClear，也没有其他回调可以用了，业务需要清空的时候触发模糊搜索

**Comment by bindoon** [comment]
点清除按钮的时候是value变了，应该触发onChange，搜索值并没有变，不应该触发onSearchClear！

**Comment by bindoon** [comment]
```
const onChange = function (value, type) {
  if( type === 'clear' ) {}
};
```
you can use like this!
