### ISSUE TITLE
[Message]Message内容区域多行情况下看起来很挤

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#980]
### Component 
Message
### Feature Description
Message更多情况下是简单内容，比如提示网络错误这种。

在多行情况下，Message内容区域font-size与line-height一样，导致这个时候起来很挤，两个方案讨论下哪个合适
1. 直接去掉line-height  https://github.com/alibaba-fusion/next/blob/master/src/message/scss/mixin.scss#L40
2. 拆分变量，line-height font-size分开配置
![image](https://user-images.githubusercontent.com/10049465/62625280-7784dc80-b957-11e9-9793-281840122d84.png)

**Comment by youluna** [comment]
@myronliu347 关注下

**Comment by myronliu347** [comment]
fixed
