### ISSUE TITLE
[Table]table如果锁列的列有合并单元格操作，样式会出问题

### ISSUE THREAD

**Issue by DophinL** [alibaba-fusion/next#981]
### Component 
Table

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/6b69cb7b](https://riddle.alibaba-inc.com/riddles/6b69cb7b)

### Steps to reproduce
https://riddle.alibaba-inc.com/riddles/6b69cb7b

**Comment by youluna** [comment]
已解决，版本1.19+
