### ISSUE TITLE
[Input]onchange() event.target return icon instead of the input when click hasClear 

### ISSUE THREAD

**Issue by tuanzhang7** [alibaba-fusion/next#984]
### Component 
Input

### Reproduction link 
[https://codepen.io/tuanzhang7/pen/LwdOgm?editors=0010](https://codepen.io/tuanzhang7/pen/LwdOgm?editors=0010)

### Steps to reproduce
click x button

**Comment by bindoon** [comment]
I don't think we could do that. when click icon to clear.  event is not on input.
