### ISSUE TITLE
[NumberPicker]NumberPicker样式bug

### ISSUE THREAD

**Issue by AndyZjy** [alibaba-fusion/next#994]
### Component 
NumberPicker

### Steps to reproduce

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/Ki7DUZZAJ3Bn.png)
组件引入就是这个样式

**Comment by AndyZjy** [comment]
右方的加减功能按钮展示问题

**Comment by youluna** [comment]
组件版本 与 主题包基准版本 不匹配导致的，建议固定组件版本至~1.15.x或升级主题包基准版至1.16.x

**Comment by AndyZjy** [comment]
> 组件版本 与 主题包基准版本 不匹配导致的，建议固定组件版本至~1.15.x或升级主题包基准版至1.16.x

本地"@alifd/next": "^1.16.6",

**Comment by youluna** [comment]
那就升级下主题包基准版本
![image](https://user-images.githubusercontent.com/10049465/62848652-25550a00-bd0f-11e9-9126-e939e2b19c32.png)
